/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_SPL_11.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_SPL_11.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_SPL_11_NNobj" scale={1.145}>
        <mesh name="Legs009" geometry={nodes.Legs009.geometry} material={nodes.Legs009.material} position={[-0.363, -3.263, 0.038]} />
        <mesh name="M_3YNSD_1_F009" geometry={nodes.M_3YNSD_1_F009.geometry} material={nodes.M_3YNSD_1_F009.material} position={[-3.252, -1.692, 2.855]}>
          <mesh name="M_SPL_1_PNT_H_1003" geometry={nodes.M_SPL_1_PNT_H_1003.geometry} material={nodes.M_SPL_1_PNT_H_1003.material} position={[1.976, 4.872, 0.154]} />
          <mesh name="M_SPL_1_PNT_V_1003" geometry={nodes.M_SPL_1_PNT_V_1003.geometry} material={nodes.M_SPL_1_PNT_V_1003.material} position={[2.629, 4.015, 0.154]} />
        </mesh>
        <mesh name="M_3YNSD_1_F010" geometry={nodes.M_3YNSD_1_F010.geometry} material={nodes.M_3YNSD_1_F010.material} position={[3.255, -1.692, 2.862]}>
          <mesh name="M_SPL_1_PNT_H_2003" geometry={nodes.M_SPL_1_PNT_H_2003.geometry} material={nodes.M_SPL_1_PNT_H_2003.material} position={[-1.994, 4.872, 0.147]} />
          <mesh name="M_SPL_1_PNT_V_2003" geometry={nodes.M_SPL_1_PNT_V_2003.geometry} material={nodes.M_SPL_1_PNT_V_2003.material} position={[-2.65, 4.015, 0.147]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A009" geometry={nodes.M_3YNSD_1_F_A009.geometry} material={nodes.M_3YNSD_1_F_A009.material} position={[-3.256, -0.938, 2.85]} />
        <mesh name="M_3YNSD_1_F_A010" geometry={nodes.M_3YNSD_1_F_A010.geometry} material={nodes.M_3YNSD_1_F_A010.material} position={[3.254, -0.938, 2.853]} />
        <mesh name="M_3YNSD_1_F_B009" geometry={nodes.M_3YNSD_1_F_B009.geometry} material={nodes.M_3YNSD_1_F_B009.material} position={[-3.257, -0.938, 2.85]} />
        <mesh name="M_3YNSD_1_F_B010" geometry={nodes.M_3YNSD_1_F_B010.geometry} material={nodes.M_3YNSD_1_F_B010.material} position={[3.254, -0.938, 2.853]} />
        <mesh name="M_3YNSD_1_F_C009" geometry={nodes.M_3YNSD_1_F_C009.geometry} material={nodes.M_3YNSD_1_F_C009.material} position={[-3.257, -1.479, 2.85]} />
        <mesh name="M_3YNSD_1_F_C010" geometry={nodes.M_3YNSD_1_F_C010.geometry} material={nodes.M_3YNSD_1_F_C010.material} position={[3.254, -1.479, 2.853]} />
        <mesh name="M_SPL_10" geometry={nodes.M_SPL_10.geometry} material={materials['Material #2143921988.021']} position={[1.758, 0.447, 2.936]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_SPL_11.glb')
