/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_SPL_14.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_SPL_14.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_SPL_14_NNobj" position={[-0.506, 0, 0]} scale={1.144}>
        <mesh name="Legs012" geometry={nodes.Legs012.geometry} material={nodes.Legs012.material} position={[-0.364, -3.269, 0.038]} />
        <mesh name="M_3YNSD_1_F015" geometry={nodes.M_3YNSD_1_F015.geometry} material={nodes.M_3YNSD_1_F015.material} position={[-3.516, -1.695, 2.86]}>
          <mesh name="M_SPL_1_PNT_H_1006" geometry={nodes.M_SPL_1_PNT_H_1006.geometry} material={nodes.M_SPL_1_PNT_H_1006.material} position={[2.749, 4.881, 0.154]} />
          <mesh name="M_SPL_1_PNT_V_1006" geometry={nodes.M_SPL_1_PNT_V_1006.geometry} material={nodes.M_SPL_1_PNT_V_1006.material} position={[3.403, 4.022, 0.154]} />
        </mesh>
        <mesh name="M_3YNSD_1_F016" geometry={nodes.M_3YNSD_1_F016.geometry} material={nodes.M_3YNSD_1_F016.material} position={[4.515, -1.695, 2.867]}>
          <mesh name="M_SPL_1_PNT_H_2006" geometry={nodes.M_SPL_1_PNT_H_2006.geometry} material={nodes.M_SPL_1_PNT_H_2006.material} position={[-2.742, 4.881, 0.147]} />
          <mesh name="M_SPL_1_PNT_V_2006" geometry={nodes.M_SPL_1_PNT_V_2006.geometry} material={nodes.M_SPL_1_PNT_V_2006.material} position={[-3.399, 4.022, 0.147]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A015" geometry={nodes.M_3YNSD_1_F_A015.geometry} material={nodes.M_3YNSD_1_F_A015.material} position={[-3.52, -0.939, 2.855]} />
        <mesh name="M_3YNSD_1_F_A016" geometry={nodes.M_3YNSD_1_F_A016.geometry} material={nodes.M_3YNSD_1_F_A016.material} position={[4.514, -0.939, 2.858]} />
        <mesh name="M_3YNSD_1_F_B015" geometry={nodes.M_3YNSD_1_F_B015.geometry} material={nodes.M_3YNSD_1_F_B015.material} position={[-3.522, -0.939, 2.855]} />
        <mesh name="M_3YNSD_1_F_B016" geometry={nodes.M_3YNSD_1_F_B016.geometry} material={nodes.M_3YNSD_1_F_B016.material} position={[4.514, -0.939, 2.858]} />
        <mesh name="M_3YNSD_1_F_C015" geometry={nodes.M_3YNSD_1_F_C015.geometry} material={nodes.M_3YNSD_1_F_C015.material} position={[-3.522, -1.481, 2.855]} />
        <mesh name="M_3YNSD_1_F_C016" geometry={nodes.M_3YNSD_1_F_C016.geometry} material={nodes.M_3YNSD_1_F_C016.material} position={[4.514, -1.481, 2.858]} />
        <mesh name="M_SPL_13" geometry={nodes.M_SPL_13.geometry} material={materials['Material #2143921988.023']} position={[1.509, 0.448, 2.941]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_SPL_14.glb')
