/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_SPL_10.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_SPL_10.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_SPL_10_NNobj" scale={1.144}>
        <mesh name="Legs008" geometry={nodes.Legs008.geometry} material={nodes.Legs008.material} position={[-0.363, -3.267, 0.038]} />
        <mesh name="M_3YNSD_1_F007" geometry={nodes.M_3YNSD_1_F007.geometry} material={nodes.M_3YNSD_1_F007.material} position={[-3.004, -1.694, 2.858]}>
          <mesh name="M_SPL_1_PNT_H_1002" geometry={nodes.M_SPL_1_PNT_H_1002.geometry} material={nodes.M_SPL_1_PNT_H_1002.material} position={[1.727, 4.878, 0.154]} />
          <mesh name="M_SPL_1_PNT_V_1002" geometry={nodes.M_SPL_1_PNT_V_1002.geometry} material={nodes.M_SPL_1_PNT_V_1002.material} position={[2.381, 4.02, 0.154]} />
        </mesh>
        <mesh name="M_3YNSD_1_F008" geometry={nodes.M_3YNSD_1_F008.geometry} material={nodes.M_3YNSD_1_F008.material} position={[3.01, -1.694, 2.866]}>
          <mesh name="M_SPL_1_PNT_H_2002" geometry={nodes.M_SPL_1_PNT_H_2002.geometry} material={nodes.M_SPL_1_PNT_H_2002.material} position={[-1.748, 4.878, 0.147]} />
          <mesh name="M_SPL_1_PNT_V_2002" geometry={nodes.M_SPL_1_PNT_V_2002.geometry} material={nodes.M_SPL_1_PNT_V_2002.material} position={[-2.405, 4.02, 0.147]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A007" geometry={nodes.M_3YNSD_1_F_A007.geometry} material={nodes.M_3YNSD_1_F_A007.material} position={[-3.008, -0.939, 2.853]} />
        <mesh name="M_3YNSD_1_F_A008" geometry={nodes.M_3YNSD_1_F_A008.geometry} material={nodes.M_3YNSD_1_F_A008.material} position={[3.009, -0.939, 2.856]} />
        <mesh name="M_3YNSD_1_F_B007" geometry={nodes.M_3YNSD_1_F_B007.geometry} material={nodes.M_3YNSD_1_F_B007.material} position={[-3.01, -0.939, 2.853]} />
        <mesh name="M_3YNSD_1_F_B008" geometry={nodes.M_3YNSD_1_F_B008.geometry} material={nodes.M_3YNSD_1_F_B008.material} position={[3.009, -0.939, 2.856]} />
        <mesh name="M_3YNSD_1_F_C007" geometry={nodes.M_3YNSD_1_F_C007.geometry} material={nodes.M_3YNSD_1_F_C007.material} position={[-3.01, -1.481, 2.853]} />
        <mesh name="M_3YNSD_1_F_C008" geometry={nodes.M_3YNSD_1_F_C008.geometry} material={nodes.M_3YNSD_1_F_C008.material} position={[3.009, -1.481, 2.856]} />
        <mesh name="M_SPL_9" geometry={nodes.M_SPL_9.geometry} material={materials['Material #2143921988.020']} position={[2.011, 0.447, 2.94]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_SPL_10.glb')
