/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_SPL_13.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_SPL_13.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_SPL_13_NNobj" scale={1.142}>
        <mesh name="Legs011" geometry={nodes.Legs011.geometry} material={nodes.Legs011.material} position={[-0.365, -3.281, 0.038]} />
        <mesh name="M_3YNSD_1_F013" geometry={nodes.M_3YNSD_1_F013.geometry} material={nodes.M_3YNSD_1_F013.material} position={[-3.53, -1.701, 2.871]}>
          <mesh name="M_SPL_1_PNT_H_1005" geometry={nodes.M_SPL_1_PNT_H_1005.geometry} material={nodes.M_SPL_1_PNT_H_1005.material} position={[2.508, 4.9, 0.155]} />
          <mesh name="M_SPL_1_PNT_V_1005" geometry={nodes.M_SPL_1_PNT_V_1005.geometry} material={nodes.M_SPL_1_PNT_V_1005.material} position={[3.165, 4.037, 0.155]} />
        </mesh>
        <mesh name="M_3YNSD_1_F014" geometry={nodes.M_3YNSD_1_F014.geometry} material={nodes.M_3YNSD_1_F014.material} position={[4.029, -1.701, 2.878]}>
          <mesh name="M_SPL_1_PNT_H_2005" geometry={nodes.M_SPL_1_PNT_H_2005.geometry} material={nodes.M_SPL_1_PNT_H_2005.material} position={[-2.5, 4.9, 0.148]} />
          <mesh name="M_SPL_1_PNT_V_2005" geometry={nodes.M_SPL_1_PNT_V_2005.geometry} material={nodes.M_SPL_1_PNT_V_2005.material} position={[-3.16, 4.037, 0.148]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A013" geometry={nodes.M_3YNSD_1_F_A013.geometry} material={nodes.M_3YNSD_1_F_A013.material} position={[-3.534, -0.943, 2.866]} />
        <mesh name="M_3YNSD_1_F_A014" geometry={nodes.M_3YNSD_1_F_A014.geometry} material={nodes.M_3YNSD_1_F_A014.material} position={[4.028, -0.943, 2.869]} />
        <mesh name="M_3YNSD_1_F_B013" geometry={nodes.M_3YNSD_1_F_B013.geometry} material={nodes.M_3YNSD_1_F_B013.material} position={[-3.536, -0.943, 2.866]} />
        <mesh name="M_3YNSD_1_F_B014" geometry={nodes.M_3YNSD_1_F_B014.geometry} material={nodes.M_3YNSD_1_F_B014.material} position={[4.028, -0.943, 2.869]} />
        <mesh name="M_3YNSD_1_F_C013" geometry={nodes.M_3YNSD_1_F_C013.geometry} material={nodes.M_3YNSD_1_F_C013.material} position={[-3.536, -1.487, 2.866]} />
        <mesh name="M_3YNSD_1_F_C014" geometry={nodes.M_3YNSD_1_F_C014.geometry} material={nodes.M_3YNSD_1_F_C014.material} position={[4.028, -1.487, 2.869]} />
        <mesh name="M_SPL_12" geometry={nodes.M_SPL_12.geometry} material={materials['Material #2143921988.008']} position={[1.515, 0.449, 2.953]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_SPL_13.glb')
