/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_SPL_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_SPL_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_SPL_2_NNglb" scale={1.139}>
        <mesh name="Legs015" geometry={nodes.Legs015.geometry} material={nodes.Legs015.material} position={[-0.362, -3.277, 0.038]} />
        <mesh name="M_SPL_1" geometry={nodes.M_SPL_1.geometry} material={materials['Material #2143921986.003']} />
        <mesh name="M_SPL_1002" geometry={nodes.M_SPL_1002.geometry} material={materials['Material #2143921986.003']} />
        <mesh name="M_SPL_1_F004" geometry={nodes.M_SPL_1_F004.geometry} material={nodes.M_SPL_1_F004.material} position={[1.003, -1.685, 2.891]}>
          <mesh name="M_SPL_1_PNT_H" geometry={nodes.M_SPL_1_PNT_H.geometry} material={nodes.M_SPL_1_PNT_H.material} position={[-1.003, 4.889, 0.134]} />
          <mesh name="M_SPL_1_PNT_V" geometry={nodes.M_SPL_1_PNT_V.geometry} material={nodes.M_SPL_1_PNT_V.material} position={[-1.449, 4.063, 0.134]} />
        </mesh>
        <mesh name="M_SPL_1_F_A003" geometry={nodes.M_SPL_1_F_A003.geometry} material={nodes.M_SPL_1_F_A003.material} position={[1.002, -0.934, 2.883]} />
        <mesh name="M_SPL_1_F_B003" geometry={nodes.M_SPL_1_F_B003.geometry} material={nodes.M_SPL_1_F_B003.material} position={[1.002, -0.934, 2.883]} />
        <mesh name="M_SPL_1_F_C003" geometry={nodes.M_SPL_1_F_C003.geometry} material={nodes.M_SPL_1_F_C003.material} position={[1.002, -1.473, 2.883]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_SPL_2.glb')
