/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_SPL_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_SPL_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_SPL_3_NNobj001" position={[0, -0.002, 0]} scale={1.147}>
        <mesh name="Legs002" geometry={nodes.Legs002.geometry} material={nodes.Legs002.material} position={[-0.362, -3.28, 0.038]} />
        <mesh name="M_3YNSD_1_F" geometry={nodes.M_3YNSD_1_F.geometry} material={nodes.M_3YNSD_1_F.material} position={[1.76, -1.686, 2.853]}>
          <mesh name="M_SPL_1_PNT_H003" geometry={nodes.M_SPL_1_PNT_H003.geometry} material={nodes.M_SPL_1_PNT_H003.material} position={[-1.76, 4.857, 0.146]} />
          <mesh name="M_SPL_1_PNT_V003" geometry={nodes.M_SPL_1_PNT_V003.geometry} material={nodes.M_SPL_1_PNT_V003.material} position={[-2.921, 4.002, 0.146]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A" geometry={nodes.M_3YNSD_1_F_A.geometry} material={nodes.M_3YNSD_1_F_A.material} position={[1.759, -0.935, 2.844]} />
        <mesh name="M_3YNSD_1_F_B" geometry={nodes.M_3YNSD_1_F_B.geometry} material={nodes.M_3YNSD_1_F_B.material} position={[1.759, -0.935, 2.844]} />
        <mesh name="M_3YNSD_1_F_C" geometry={nodes.M_3YNSD_1_F_C.geometry} material={nodes.M_3YNSD_1_F_C.material} position={[1.759, -1.474, 2.844]} />
        <mesh name="M_SPL_4" geometry={nodes.M_SPL_4.geometry} material={materials['Material #2143921988.015']} position={[3.253, 0.445, 2.927]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_SPL_4.glb')
