/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_SPL_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_SPL_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_SPL_6_NNobj" position={[0, -0.002, 0]} scale={1.144}>
        <mesh name="Legs003" geometry={nodes.Legs003.geometry} material={nodes.Legs003.material} position={[-0.363, -3.266, 0.038]} />
        <mesh name="M_3YNSD_1_F001" geometry={nodes.M_3YNSD_1_F001.geometry} material={nodes.M_3YNSD_1_F001.material} position={[2.002, -1.694, 2.865]}>
          <mesh name="M_SPL_1_PNT_H004" geometry={nodes.M_SPL_1_PNT_H004.geometry} material={nodes.M_SPL_1_PNT_H004.material} position={[-2.002, 4.877, 0.147]} />
          <mesh name="M_SPL_1_PNT_V004" geometry={nodes.M_SPL_1_PNT_V004.geometry} material={nodes.M_SPL_1_PNT_V004.material} position={[-3.409, 4.019, 0.147]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A001" geometry={nodes.M_3YNSD_1_F_A001.geometry} material={nodes.M_3YNSD_1_F_A001.material} position={[2, -0.939, 2.856]} />
        <mesh name="M_3YNSD_1_F_B001" geometry={nodes.M_3YNSD_1_F_B001.geometry} material={nodes.M_3YNSD_1_F_B001.material} position={[2, -0.939, 2.856]} />
        <mesh name="M_3YNSD_1_F_C001" geometry={nodes.M_3YNSD_1_F_C001.geometry} material={nodes.M_3YNSD_1_F_C001.material} position={[2, -1.48, 2.856]} />
        <mesh name="M_SPL_5" geometry={nodes.M_SPL_5.geometry} material={materials['Material #2143921988.016']} position={[3.016, 0.447, 2.939]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_SPL_6.glb')
