/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_SPL_12.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_SPL_12.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_SPL_12_NNobj" scale={1.142}>
        <mesh name="Legs010" geometry={nodes.Legs010.geometry} material={nodes.Legs010.material} position={[-0.365, -3.277, 0.038]} />
        <mesh name="M_3YNSD_1_F011" geometry={nodes.M_3YNSD_1_F011.geometry} material={nodes.M_3YNSD_1_F011.material} position={[-3.526, -1.699, 2.867]}>
          <mesh name="M_SPL_1_PNT_H_1004" geometry={nodes.M_SPL_1_PNT_H_1004.geometry} material={nodes.M_SPL_1_PNT_H_1004.material} position={[2.244, 4.894, 0.155]} />
          <mesh name="M_SPL_1_PNT_V_1004" geometry={nodes.M_SPL_1_PNT_V_1004.geometry} material={nodes.M_SPL_1_PNT_V_1004.material} position={[2.9, 4.032, 0.155]} />
        </mesh>
        <mesh name="M_3YNSD_1_F012" geometry={nodes.M_3YNSD_1_F012.geometry} material={nodes.M_3YNSD_1_F012.material} position={[3.529, -1.699, 2.875]}>
          <mesh name="M_SPL_1_PNT_H_2004" geometry={nodes.M_SPL_1_PNT_H_2004.geometry} material={nodes.M_SPL_1_PNT_H_2004.material} position={[-2.263, 4.894, 0.147]} />
          <mesh name="M_SPL_1_PNT_V_2004" geometry={nodes.M_SPL_1_PNT_V_2004.geometry} material={nodes.M_SPL_1_PNT_V_2004.material} position={[-2.922, 4.032, 0.147]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A011" geometry={nodes.M_3YNSD_1_F_A011.geometry} material={nodes.M_3YNSD_1_F_A011.material} position={[-3.53, -0.942, 2.862]} />
        <mesh name="M_3YNSD_1_F_A012" geometry={nodes.M_3YNSD_1_F_A012.geometry} material={nodes.M_3YNSD_1_F_A012.material} position={[3.528, -0.942, 2.865]} />
        <mesh name="M_3YNSD_1_F_B011" geometry={nodes.M_3YNSD_1_F_B011.geometry} material={nodes.M_3YNSD_1_F_B011.material} position={[-3.531, -0.942, 2.862]} />
        <mesh name="M_3YNSD_1_F_B012" geometry={nodes.M_3YNSD_1_F_B012.geometry} material={nodes.M_3YNSD_1_F_B012.material} position={[3.528, -0.942, 2.865]} />
        <mesh name="M_3YNSD_1_F_C011" geometry={nodes.M_3YNSD_1_F_C011.geometry} material={nodes.M_3YNSD_1_F_C011.material} position={[-3.531, -1.485, 2.862]} />
        <mesh name="M_3YNSD_1_F_C012" geometry={nodes.M_3YNSD_1_F_C012.geometry} material={nodes.M_3YNSD_1_F_C012.material} position={[3.528, -1.485, 2.865]} />
        <mesh name="M_SPL_11" geometry={nodes.M_SPL_11.geometry} material={materials['Material #2143921988.022']} position={[1.513, 0.449, 2.949]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_SPL_12.glb')
