/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_SPL_8.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_SPL_8.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_SPL_8_NNobj" scale={1.142}>
        <mesh name="Legs006" geometry={nodes.Legs006.geometry} material={nodes.Legs006.material} position={[-0.365, -3.277, 0.038]} />
        <mesh name="M_3YNSD_1_F003" geometry={nodes.M_3YNSD_1_F003.geometry} material={nodes.M_3YNSD_1_F003.material} position={[-2.522, -1.699, 2.867]}>
          <mesh name="M_SPL_1_PNT_H_1" geometry={nodes.M_SPL_1_PNT_H_1.geometry} material={nodes.M_SPL_1_PNT_H_1.material} position={[1.241, 4.893, 0.154]} />
          <mesh name="M_SPL_1_PNT_V_1" geometry={nodes.M_SPL_1_PNT_V_1.geometry} material={nodes.M_SPL_1_PNT_V_1.material} position={[1.897, 4.032, 0.154]} />
        </mesh>
        <mesh name="M_3YNSD_1_F004" geometry={nodes.M_3YNSD_1_F004.geometry} material={nodes.M_3YNSD_1_F004.material} position={[2.505, -1.699, 2.874]}>
          <mesh name="M_SPL_1_PNT_H_2" geometry={nodes.M_SPL_1_PNT_H_2.geometry} material={nodes.M_SPL_1_PNT_H_2.material} position={[-1.239, 4.893, 0.147]} />
          <mesh name="M_SPL_1_PNT_V_2" geometry={nodes.M_SPL_1_PNT_V_2.geometry} material={nodes.M_SPL_1_PNT_V_2.material} position={[-1.898, 4.032, 0.147]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A003" geometry={nodes.M_3YNSD_1_F_A003.geometry} material={nodes.M_3YNSD_1_F_A003.material} position={[-2.526, -0.942, 2.862]} />
        <mesh name="M_3YNSD_1_F_A004" geometry={nodes.M_3YNSD_1_F_A004.geometry} material={nodes.M_3YNSD_1_F_A004.material} position={[2.504, -0.942, 2.865]} />
        <mesh name="M_3YNSD_1_F_B003" geometry={nodes.M_3YNSD_1_F_B003.geometry} material={nodes.M_3YNSD_1_F_B003.material} position={[-2.528, -0.942, 2.862]} />
        <mesh name="M_3YNSD_1_F_B004" geometry={nodes.M_3YNSD_1_F_B004.geometry} material={nodes.M_3YNSD_1_F_B004.material} position={[2.504, -0.942, 2.865]} />
        <mesh name="M_3YNSD_1_F_C003" geometry={nodes.M_3YNSD_1_F_C003.geometry} material={nodes.M_3YNSD_1_F_C003.material} position={[-2.528, -1.485, 2.862]} />
        <mesh name="M_3YNSD_1_F_C004" geometry={nodes.M_3YNSD_1_F_C004.geometry} material={nodes.M_3YNSD_1_F_C004.material} position={[2.504, -1.485, 2.865]} />
        <mesh name="M_SPL_7" geometry={nodes.M_SPL_7.geometry} material={materials['Material #2143921988.018']} position={[2.521, 0.449, 2.949]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_SPL_8.glb')
