/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_SPL_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_SPL_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_SPL_7_NNobj" position={[0, -0.002, 0]} scale={1.144}>
        <mesh name="Legs004" geometry={nodes.Legs004.geometry} material={nodes.Legs004.material} position={[-0.363, -3.266, 0.038]} />
        <mesh name="M_3YNSD_1_F002" geometry={nodes.M_3YNSD_1_F002.geometry} material={nodes.M_3YNSD_1_F002.material} position={[2.258, -1.693, 2.865]}>
          <mesh name="M_SPL_1_PNT_H005" geometry={nodes.M_SPL_1_PNT_H005.geometry} material={nodes.M_SPL_1_PNT_H005.material} position={[-2.258, 4.877, 0.147]} />
          <mesh name="M_SPL_1_PNT_V005" geometry={nodes.M_SPL_1_PNT_V005.geometry} material={nodes.M_SPL_1_PNT_V005.material} position={[-3.916, 4.018, 0.147]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A002" geometry={nodes.M_3YNSD_1_F_A002.geometry} material={nodes.M_3YNSD_1_F_A002.material} position={[2.256, -0.939, 2.855]} />
        <mesh name="M_3YNSD_1_F_B002" geometry={nodes.M_3YNSD_1_F_B002.geometry} material={nodes.M_3YNSD_1_F_B002.material} position={[2.256, -0.939, 2.855]} />
        <mesh name="M_3YNSD_1_F_C002" geometry={nodes.M_3YNSD_1_F_C002.geometry} material={nodes.M_3YNSD_1_F_C002.material} position={[2.256, -1.48, 2.855]} />
        <mesh name="M_SPL_6" geometry={nodes.M_SPL_6.geometry} material={materials['Material #2143921988.017']} position={[2.764, 0.447, 2.939]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_SPL_7.glb')
