/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_SPL_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_SPL_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_SPL_1_NN" scale={1.137}>
        <mesh name="Legs001" geometry={nodes.Legs001.geometry} material={nodes.Legs001.material} position={[0.009, -3.288, -0.209]} />
        <mesh name="M_SPL_1001" geometry={nodes.M_SPL_1001.geometry} material={materials['wire_153228184.004']} />
        <mesh name="M_SPL_1_F001" geometry={nodes.M_SPL_1_F001.geometry} material={nodes.M_SPL_1_F001.material} position={[1.378, -1.69, 2.636]}>
          <mesh name="M_SPL_PNT001" geometry={nodes.M_SPL_PNT001.geometry} material={nodes.M_SPL_PNT001.material} position={[-1.378, 1.45, 0.135]} />
        </mesh>
        <mesh name="M_SPL_1_F002" geometry={nodes.M_SPL_1_F002.geometry} material={nodes.M_SPL_1_F002.material} position={[1.378, 2.454, 2.636]}>
          <mesh name="M_SPL_1_PNT" geometry={nodes.M_SPL_1_PNT.geometry} material={nodes.M_SPL_1_PNT.material} position={[-1.378, 0.86, 0.135]} />
        </mesh>
        <mesh name="M_SPL_1_F003" geometry={nodes.M_SPL_1_F003.geometry} material={nodes.M_SPL_1_F003.material} position={[1.378, 0.759, 2.636]}>
          <mesh name="M_SPL_PNT" geometry={nodes.M_SPL_PNT.geometry} material={nodes.M_SPL_PNT.material} position={[-1.378, 0.851, 0.135]} />
        </mesh>
        <mesh name="M_SPL_1_F_1002" geometry={nodes.M_SPL_1_F_1002.geometry} material={materials['wire_153228184.004']} />
        <mesh name="M_SPL_1_F_A001" geometry={nodes.M_SPL_1_F_A001.geometry} material={nodes.M_SPL_1_F_A001.material} position={[1.376, -0.937, 2.627]} />
        <mesh name="M_SPL_1_F_A002" geometry={nodes.M_SPL_1_F_A002.geometry} material={nodes.M_SPL_1_F_A002.material} position={[1.376, 3.207, 2.627]} />
        <mesh name="M_SPL_1_F_A006" geometry={nodes.M_SPL_1_F_A006.geometry} material={nodes.M_SPL_1_F_A006.material} position={[1.376, 1.511, 2.627]} />
        <mesh name="M_SPL_1_F_B001" geometry={nodes.M_SPL_1_F_B001.geometry} material={nodes.M_SPL_1_F_B001.material} position={[1.376, -0.937, 2.627]} />
        <mesh name="M_SPL_1_F_B002" geometry={nodes.M_SPL_1_F_B002.geometry} material={nodes.M_SPL_1_F_B002.material} position={[1.376, 3.207, 2.627]} />
        <mesh name="M_SPL_1_F_B006" geometry={nodes.M_SPL_1_F_B006.geometry} material={nodes.M_SPL_1_F_B006.material} position={[1.376, 1.511, 2.627]} />
        <mesh name="M_SPL_1_F_C001" geometry={nodes.M_SPL_1_F_C001.geometry} material={nodes.M_SPL_1_F_C001.material} position={[1.376, -1.478, 2.627]} />
        <mesh name="M_SPL_1_F_C002" geometry={nodes.M_SPL_1_F_C002.geometry} material={nodes.M_SPL_1_F_C002.material} position={[1.376, 2.667, 2.627]} />
        <mesh name="M_SPL_1_F_C006" geometry={nodes.M_SPL_1_F_C006.geometry} material={nodes.M_SPL_1_F_C006.material} position={[1.376, 0.97, 2.627]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_SPL_1.glb')
