/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_SPL_9.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_SPL_9.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_SPL_9_NNobj" scale={1.142}>
        <mesh name="Legs007" geometry={nodes.Legs007.geometry} material={nodes.Legs007.material} position={[-0.365, -3.281, 0.038]} />
        <mesh name="M_3YNSD_1_F005" geometry={nodes.M_3YNSD_1_F005.geometry} material={nodes.M_3YNSD_1_F005.material} position={[-2.757, -1.701, 2.871]}>
          <mesh name="M_SPL_1_PNT_H_1001" geometry={nodes.M_SPL_1_PNT_H_1001.geometry} material={nodes.M_SPL_1_PNT_H_1001.material} position={[1.474, 4.9, 0.155]} />
          <mesh name="M_SPL_1_PNT_V_1001" geometry={nodes.M_SPL_1_PNT_V_1001.geometry} material={nodes.M_SPL_1_PNT_V_1001.material} position={[2.13, 4.038, 0.155]} />
        </mesh>
        <mesh name="M_3YNSD_1_F006" geometry={nodes.M_3YNSD_1_F006.geometry} material={nodes.M_3YNSD_1_F006.material} position={[2.774, -1.701, 2.878]}>
          <mesh name="M_SPL_1_PNT_H_2001" geometry={nodes.M_SPL_1_PNT_H_2001.geometry} material={nodes.M_SPL_1_PNT_H_2001.material} position={[-1.507, 4.9, 0.148]} />
          <mesh name="M_SPL_1_PNT_V_2001" geometry={nodes.M_SPL_1_PNT_V_2001.geometry} material={nodes.M_SPL_1_PNT_V_2001.material} position={[-2.166, 4.038, 0.148]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A005" geometry={nodes.M_3YNSD_1_F_A005.geometry} material={nodes.M_3YNSD_1_F_A005.material} position={[-2.76, -0.943, 2.866]} />
        <mesh name="M_3YNSD_1_F_A006" geometry={nodes.M_3YNSD_1_F_A006.geometry} material={nodes.M_3YNSD_1_F_A006.material} position={[2.773, -0.943, 2.869]} />
        <mesh name="M_3YNSD_1_F_B005" geometry={nodes.M_3YNSD_1_F_B005.geometry} material={nodes.M_3YNSD_1_F_B005.material} position={[-2.762, -0.943, 2.866]} />
        <mesh name="M_3YNSD_1_F_B006" geometry={nodes.M_3YNSD_1_F_B006.geometry} material={nodes.M_3YNSD_1_F_B006.material} position={[2.773, -0.943, 2.869]} />
        <mesh name="M_3YNSD_1_F_C005" geometry={nodes.M_3YNSD_1_F_C005.geometry} material={nodes.M_3YNSD_1_F_C005.material} position={[-2.762, -1.487, 2.866]} />
        <mesh name="M_3YNSD_1_F_C006" geometry={nodes.M_3YNSD_1_F_C006.geometry} material={nodes.M_3YNSD_1_F_C006.material} position={[2.773, -1.487, 2.869]} />
        <mesh name="M_SPL_7001" geometry={nodes.M_SPL_7001.geometry} material={materials['Material #2143921988.019']} position={[2.272, 0.449, 2.953]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_SPL_9.glb')
