/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_SPL_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_SPL_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_SPL_3_NNobj" scale={1.147}>
        <mesh name="Legs" geometry={nodes.Legs.geometry} material={nodes.Legs.material} position={[-0.361, -3.277, 0.038]} />
        <mesh name="M_SPL_1_F" geometry={nodes.M_SPL_1_F.geometry} material={nodes.M_SPL_1_F.material} position={[1.259, -1.685, 2.85]}>
          <mesh name="M_SPL_1_PNT_H001" geometry={nodes.M_SPL_1_PNT_H001.geometry} material={nodes.M_SPL_1_PNT_H001.material} position={[-1.259, 4.852, 0.146]} />
          <mesh name="M_SPL_1_PNT_V001" geometry={nodes.M_SPL_1_PNT_V001.geometry} material={nodes.M_SPL_1_PNT_V001.material} position={[-1.912, 3.998, 0.146]} />
        </mesh>
        <mesh name="M_SPL_1_F_A" geometry={nodes.M_SPL_1_F_A.geometry} material={nodes.M_SPL_1_F_A.material} position={[1.257, -0.934, 2.841]} />
        <mesh name="M_SPL_1_F_B" geometry={nodes.M_SPL_1_F_B.geometry} material={nodes.M_SPL_1_F_B.material} position={[1.257, -0.934, 2.841]} />
        <mesh name="M_SPL_1_F_C" geometry={nodes.M_SPL_1_F_C.geometry} material={nodes.M_SPL_1_F_C.material} position={[1.257, -1.473, 2.841]} />
        <mesh name="M_SPL_2" geometry={nodes.M_SPL_2.geometry} material={materials['Material #2143921988.014']} position={[3.75, 0.445, 2.924]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_SPL_3.glb')
