/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMC_8.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMC_8.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMC_8obj" scale={1.052}>
        <mesh name="M_UMA_1_F001" geometry={nodes.M_UMA_1_F001.geometry} material={nodes.M_UMA_1_F001.material} position={[-2.74, 0.648, 1.445]}>
          <mesh name="M_UMC_8_PNT001" geometry={nodes.M_UMC_8_PNT001.geometry} material={nodes.M_UMC_8_PNT001.material} position={[1.723, -3.022, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F002" geometry={nodes.M_UMA_1_F002.geometry} material={nodes.M_UMA_1_F002.material} position={[2.741, 0.648, 1.445]}>
          <mesh name="M_UMC_8_PNT" geometry={nodes.M_UMC_8_PNT.geometry} material={nodes.M_UMC_8_PNT.material} position={[-1.724, -3.022, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMA_1_F_A001" geometry={nodes.M_UMA_1_F_A001.geometry} material={nodes.M_UMA_1_F_A001.material} position={[-2.746, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_A002" geometry={nodes.M_UMA_1_F_A002.geometry} material={nodes.M_UMA_1_F_A002.material} position={[2.746, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B001" geometry={nodes.M_UMA_1_F_B001.geometry} material={nodes.M_UMA_1_F_B001.material} position={[-2.749, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B002" geometry={nodes.M_UMA_1_F_B002.geometry} material={nodes.M_UMA_1_F_B002.material} position={[2.746, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_C001" geometry={nodes.M_UMA_1_F_C001.geometry} material={nodes.M_UMA_1_F_C001.material} position={[-2.75, 1.158, 1.435]} />
        <mesh name="M_UMA_1_F_C002" geometry={nodes.M_UMA_1_F_C002.geometry} material={nodes.M_UMA_1_F_C002.material} position={[2.746, 1.158, 1.435]} />
        <mesh name="M_UMC_8" geometry={nodes.M_UMC_8.geometry} material={nodes.M_UMC_8.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMC_8.glb')
