/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMC_10.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMC_10.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMC_10obj" scale={1.052}>
        <mesh name="M_UMA_1_F005" geometry={nodes.M_UMA_1_F005.geometry} material={nodes.M_UMA_1_F005.material} position={[-3.238, 0.648, 1.445]}>
          <mesh name="M_UMC_10_PNT001" geometry={nodes.M_UMC_10_PNT001.geometry} material={nodes.M_UMC_10_PNT001.material} position={[2.222, -3.022, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F012" geometry={nodes.M_UMA_1_F012.geometry} material={nodes.M_UMA_1_F012.material} position={[3.241, 0.648, 1.445]}>
          <mesh name="M_UMC_10_PNT" geometry={nodes.M_UMC_10_PNT.geometry} material={nodes.M_UMC_10_PNT.material} position={[-2.224, -3.022, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMA_1_F_A005" geometry={nodes.M_UMA_1_F_A005.geometry} material={nodes.M_UMA_1_F_A005.material} position={[-3.244, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_A012" geometry={nodes.M_UMA_1_F_A012.geometry} material={nodes.M_UMA_1_F_A012.material} position={[3.246, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B005" geometry={nodes.M_UMA_1_F_B005.geometry} material={nodes.M_UMA_1_F_B005.material} position={[-3.248, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B012" geometry={nodes.M_UMA_1_F_B012.geometry} material={nodes.M_UMA_1_F_B012.material} position={[3.246, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_C005" geometry={nodes.M_UMA_1_F_C005.geometry} material={nodes.M_UMA_1_F_C005.material} position={[-3.248, 1.158, 1.435]} />
        <mesh name="M_UMA_1_F_C012" geometry={nodes.M_UMA_1_F_C012.geometry} material={nodes.M_UMA_1_F_C012.material} position={[3.246, 1.158, 1.435]} />
        <mesh name="M_UMC_10" geometry={nodes.M_UMC_10.geometry} material={nodes.M_UMC_10.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMC_10.glb')
