/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMC_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMC_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMC_5_F_5obj" scale={1.052}>
        <mesh name="M_UMA_1_F019" geometry={nodes.M_UMA_1_F019.geometry} material={nodes.M_UMA_1_F019.material} position={[1.99, 0.648, 1.445]}>
          <mesh name="M_UMC_5_PNT_H" geometry={nodes.M_UMC_5_PNT_H.geometry} material={nodes.M_UMC_5_PNT_H.material} position={[-1.99, -3.882, 0.17]} />
          <mesh name="M_UMC_5_PNT_V" geometry={nodes.M_UMC_5_PNT_V.geometry} material={nodes.M_UMC_5_PNT_V.material} position={[-2.993, -3.03, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F_A016" geometry={nodes.M_UMA_1_F_A016.geometry} material={nodes.M_UMA_1_F_A016.material} position={[1.995, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B016" geometry={nodes.M_UMA_1_F_B016.geometry} material={nodes.M_UMA_1_F_B016.material} position={[1.995, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_C016" geometry={nodes.M_UMA_1_F_C016.geometry} material={nodes.M_UMA_1_F_C016.material} position={[1.995, 1.158, 1.435]} />
        <mesh name="M_UMC_5" geometry={nodes.M_UMC_5.geometry} material={nodes.M_UMC_5.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMC_5.glb')
