/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMC_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMC_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMC_7obj" scale={1.052}>
        <mesh name="M_UMA_1_F017" geometry={nodes.M_UMA_1_F017.geometry} material={nodes.M_UMA_1_F017.material} position={[-2.491, 0.648, 1.445]}>
          <mesh name="M_UMC_4_PNT001" geometry={nodes.M_UMC_4_PNT001.geometry} material={nodes.M_UMC_4_PNT001.material} position={[1.236, -3.03, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F018" geometry={nodes.M_UMA_1_F018.geometry} material={nodes.M_UMA_1_F018.material} position={[2.49, 0.648, 1.445]}>
          <mesh name="M_UMC_4_PNT" geometry={nodes.M_UMC_4_PNT.geometry} material={nodes.M_UMC_4_PNT.material} position={[-1.236, -3.03, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMA_1_F_A018" geometry={nodes.M_UMA_1_F_A018.geometry} material={nodes.M_UMA_1_F_A018.material} position={[-2.497, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_A019" geometry={nodes.M_UMA_1_F_A019.geometry} material={nodes.M_UMA_1_F_A019.material} position={[2.496, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B018" geometry={nodes.M_UMA_1_F_B018.geometry} material={nodes.M_UMA_1_F_B018.material} position={[-2.5, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B019" geometry={nodes.M_UMA_1_F_B019.geometry} material={nodes.M_UMA_1_F_B019.material} position={[2.496, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_C018" geometry={nodes.M_UMA_1_F_C018.geometry} material={nodes.M_UMA_1_F_C018.material} position={[-2.501, 1.158, 1.435]} />
        <mesh name="M_UMA_1_F_C019" geometry={nodes.M_UMA_1_F_C019.geometry} material={nodes.M_UMA_1_F_C019.material} position={[2.496, 1.158, 1.435]} />
        <mesh name="M_UMC_7" geometry={nodes.M_UMC_7.geometry} material={nodes.M_UMC_7.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMC_7.glb')
