/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMC_11.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMC_11.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMC_11_F_11obj" scale={1.052}>
        <mesh name="M_UMA_1_F006" geometry={nodes.M_UMA_1_F006.geometry} material={nodes.M_UMA_1_F006.material} position={[-3.486, 0.648, 1.445]}>
          <mesh name="M_UMC_11_PNT_H" geometry={nodes.M_UMC_11_PNT_H.geometry} material={nodes.M_UMC_11_PNT_H.material} position={[1.74, -3.88, 0.17]} />
          <mesh name="M_UMC_11_PNT_V_1" geometry={nodes.M_UMC_11_PNT_V_1.geometry} material={nodes.M_UMC_11_PNT_V_1.material} position={[2.47, -3.022, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F007" geometry={nodes.M_UMA_1_F007.geometry} material={nodes.M_UMA_1_F007.material} position={[3.487, 0.648, 1.445]}>
          <mesh name="M_UMC_11_PNT_H_1" geometry={nodes.M_UMC_11_PNT_H_1.geometry} material={nodes.M_UMC_11_PNT_H_1.material} position={[-1.741, -3.88, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UMC_11_PNT_V" geometry={nodes.M_UMC_11_PNT_V.geometry} material={nodes.M_UMC_11_PNT_V.material} position={[-2.471, -3.022, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMA_1_F_A006" geometry={nodes.M_UMA_1_F_A006.geometry} material={nodes.M_UMA_1_F_A006.material} position={[-3.492, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_A007" geometry={nodes.M_UMA_1_F_A007.geometry} material={nodes.M_UMA_1_F_A007.material} position={[3.493, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B006" geometry={nodes.M_UMA_1_F_B006.geometry} material={nodes.M_UMA_1_F_B006.material} position={[-3.496, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B007" geometry={nodes.M_UMA_1_F_B007.geometry} material={nodes.M_UMA_1_F_B007.material} position={[3.493, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_C006" geometry={nodes.M_UMA_1_F_C006.geometry} material={nodes.M_UMA_1_F_C006.material} position={[-3.496, 1.158, 1.435]} />
        <mesh name="M_UMA_1_F_C007" geometry={nodes.M_UMA_1_F_C007.geometry} material={nodes.M_UMA_1_F_C007.material} position={[3.493, 1.158, 1.435]} />
        <mesh name="M_UMC_11" geometry={nodes.M_UMC_11.geometry} material={nodes.M_UMC_11.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMC_11.glb')
