/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMC_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMC_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMC_3obj" scale={1.052}>
        <mesh name="M_UMA_1_F013" geometry={nodes.M_UMA_1_F013.geometry} material={nodes.M_UMA_1_F013.material} position={[1.49, 0.648, 1.445]}>
          <mesh name="M_UMC_3_PNT" geometry={nodes.M_UMC_3_PNT.geometry} material={nodes.M_UMC_3_PNT.material} position={[-1.994, -3.03, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F_A014" geometry={nodes.M_UMA_1_F_A014.geometry} material={nodes.M_UMA_1_F_A014.material} position={[1.495, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B014" geometry={nodes.M_UMA_1_F_B014.geometry} material={nodes.M_UMA_1_F_B014.material} position={[1.495, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_C014" geometry={nodes.M_UMA_1_F_C014.geometry} material={nodes.M_UMA_1_F_C014.material} position={[1.495, 1.158, 1.435]} />
        <mesh name="M_UMC_3" geometry={nodes.M_UMC_3.geometry} material={nodes.M_UMC_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMC_3.glb')
