/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMC_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMC_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMC_6_F_6obj" scale={1.052}>
        <mesh name="M_UMA_1_F016" geometry={nodes.M_UMA_1_F016.geometry} material={nodes.M_UMA_1_F016.material} position={[2.241, 0.648, 1.445]}>
          <mesh name="M_UMC_6_PNT_H" geometry={nodes.M_UMC_6_PNT_H.geometry} material={nodes.M_UMC_6_PNT_H.material} position={[-2.241, -3.882, 0.17]} />
          <mesh name="M_UMC_6_PNT_V" geometry={nodes.M_UMC_6_PNT_V.geometry} material={nodes.M_UMC_6_PNT_V.material} position={[-3.495, -3.03, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F_A017" geometry={nodes.M_UMA_1_F_A017.geometry} material={nodes.M_UMA_1_F_A017.material} position={[2.246, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B017" geometry={nodes.M_UMA_1_F_B017.geometry} material={nodes.M_UMA_1_F_B017.material} position={[2.246, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_C017" geometry={nodes.M_UMA_1_F_C017.geometry} material={nodes.M_UMA_1_F_C017.material} position={[2.246, 1.158, 1.435]} />
        <mesh name="M_UMC_6" geometry={nodes.M_UMC_6.geometry} material={nodes.M_UMC_6.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMC_6.glb')
