/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMC_13.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMC_13.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMC_13_F_13obj" scale={1.052}>
        <mesh name="M_UMA_1_F010" geometry={nodes.M_UMA_1_F010.geometry} material={nodes.M_UMA_1_F010.material} position={[-3.988, 0.648, 1.445]}>
          <mesh name="M_UMC_10_PNT_V_1001" geometry={nodes.M_UMC_10_PNT_V_1001.geometry} material={nodes.M_UMC_10_PNT_V_1001.material} position={[2.971, -3.022, 0.17]} />
          <mesh name="M_UMC_11_PNT_H003" geometry={nodes.M_UMC_11_PNT_H003.geometry} material={nodes.M_UMC_11_PNT_H003.material} position={[1.948, -3.88, 0.165]} />
        </mesh>
        <mesh name="M_UMA_1_F011" geometry={nodes.M_UMA_1_F011.geometry} material={nodes.M_UMA_1_F011.material} position={[3.989, 0.648, 1.445]}>
          <mesh name="M_UMC_10_PNT_V001" geometry={nodes.M_UMC_10_PNT_V001.geometry} material={nodes.M_UMC_10_PNT_V001.material} position={[-2.972, -3.022, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UMC_11_PNT_H001" geometry={nodes.M_UMC_11_PNT_H001.geometry} material={nodes.M_UMC_11_PNT_H001.material} position={[-1.949, -3.88, 0.165]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMA_1_F_A010" geometry={nodes.M_UMA_1_F_A010.geometry} material={nodes.M_UMA_1_F_A010.material} position={[-3.993, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_A011" geometry={nodes.M_UMA_1_F_A011.geometry} material={nodes.M_UMA_1_F_A011.material} position={[3.994, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B010" geometry={nodes.M_UMA_1_F_B010.geometry} material={nodes.M_UMA_1_F_B010.material} position={[-3.997, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B011" geometry={nodes.M_UMA_1_F_B011.geometry} material={nodes.M_UMA_1_F_B011.material} position={[3.994, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_C010" geometry={nodes.M_UMA_1_F_C010.geometry} material={nodes.M_UMA_1_F_C010.material} position={[-3.998, 1.158, 1.435]} />
        <mesh name="M_UMA_1_F_C011" geometry={nodes.M_UMA_1_F_C011.geometry} material={nodes.M_UMA_1_F_C011.material} position={[3.994, 1.158, 1.435]} />
        <mesh name="M_UMC_13" geometry={nodes.M_UMC_13.geometry} material={nodes.M_UMC_13.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMC_13.glb')
