/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMC_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMC_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMC_4_F_4obj" scale={1.052}>
        <mesh name="M_UMA_1_F015" geometry={nodes.M_UMA_1_F015.geometry} material={nodes.M_UMA_1_F015.material} position={[1.739, 0.648, 1.445]}>
          <mesh name="M_UMC_4_PNT_H" geometry={nodes.M_UMC_4_PNT_H.geometry} material={nodes.M_UMC_4_PNT_H.material} position={[-1.739, -3.882, 0.17]} />
          <mesh name="M_UMC_4_PNT_V" geometry={nodes.M_UMC_4_PNT_V.geometry} material={nodes.M_UMC_4_PNT_V.material} position={[-2.493, -3.03, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F_A015" geometry={nodes.M_UMA_1_F_A015.geometry} material={nodes.M_UMA_1_F_A015.material} position={[1.745, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B015" geometry={nodes.M_UMA_1_F_B015.geometry} material={nodes.M_UMA_1_F_B015.material} position={[1.745, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_C015" geometry={nodes.M_UMA_1_F_C015.geometry} material={nodes.M_UMA_1_F_C015.material} position={[1.745, 1.158, 1.435]} />
        <mesh name="M_UMC_4" geometry={nodes.M_UMC_4.geometry} material={nodes.M_UMC_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMC_4.glb')
