/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMC_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMC_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMC_1obj" scale={1.052}>
        <mesh name="M_UMA_1_F014" geometry={nodes.M_UMA_1_F014.geometry} material={nodes.M_UMA_1_F014.material} position={[0.987, 0.648, 1.445]}>
          <mesh name="M_UMC_1_PNT" geometry={nodes.M_UMC_1_PNT.geometry} material={nodes.M_UMC_1_PNT.material} position={[-0.987, -3.03, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F_A013" geometry={nodes.M_UMA_1_F_A013.geometry} material={nodes.M_UMA_1_F_A013.material} position={[0.992, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B013" geometry={nodes.M_UMA_1_F_B013.geometry} material={nodes.M_UMA_1_F_B013.material} position={[0.992, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_C013" geometry={nodes.M_UMA_1_F_C013.geometry} material={nodes.M_UMA_1_F_C013.material} position={[0.992, 1.158, 1.435]} />
        <mesh name="M_UMC_1" geometry={nodes.M_UMC_1.geometry} material={nodes.M_UMC_1.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMC_1.glb')
