/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMC_12.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMC_12.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMC_12_F_12obj" scale={1.052}>
        <mesh name="M_UMA_1_F008" geometry={nodes.M_UMA_1_F008.geometry} material={nodes.M_UMA_1_F008.material} position={[-3.739, 0.648, 1.445]}>
          <mesh name="M_UMC_12_PNT_H" geometry={nodes.M_UMC_12_PNT_H.geometry} material={nodes.M_UMC_12_PNT_H.material} position={[1.839, -3.88, 0.165]} />
          <mesh name="M_UMC_12_PNT_V" geometry={nodes.M_UMC_12_PNT_V.geometry} material={nodes.M_UMC_12_PNT_V.material} position={[2.722, -3.022, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F009" geometry={nodes.M_UMA_1_F009.geometry} material={nodes.M_UMA_1_F009.material} position={[3.738, 0.648, 1.445]}>
          <mesh name="M_UMC_12_PNT_H_1" geometry={nodes.M_UMC_12_PNT_H_1.geometry} material={nodes.M_UMC_12_PNT_H_1.material} position={[-1.839, -3.88, 0.165]} rotation={[-Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UMC_12_PNT_V_1" geometry={nodes.M_UMC_12_PNT_V_1.geometry} material={nodes.M_UMC_12_PNT_V_1.material} position={[-2.721, -3.022, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMA_1_F_A008" geometry={nodes.M_UMA_1_F_A008.geometry} material={nodes.M_UMA_1_F_A008.material} position={[-3.744, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_A009" geometry={nodes.M_UMA_1_F_A009.geometry} material={nodes.M_UMA_1_F_A009.material} position={[3.743, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B008" geometry={nodes.M_UMA_1_F_B008.geometry} material={nodes.M_UMA_1_F_B008.material} position={[-3.748, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B009" geometry={nodes.M_UMA_1_F_B009.geometry} material={nodes.M_UMA_1_F_B009.material} position={[3.743, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_C008" geometry={nodes.M_UMA_1_F_C008.geometry} material={nodes.M_UMA_1_F_C008.material} position={[-3.749, 1.158, 1.435]} />
        <mesh name="M_UMA_1_F_C009" geometry={nodes.M_UMA_1_F_C009.geometry} material={nodes.M_UMA_1_F_C009.material} position={[3.743, 1.158, 1.435]} />
        <mesh name="M_UMC_12" geometry={nodes.M_UMC_12.geometry} material={nodes.M_UMC_12.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMC_12.glb')
