/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMC_9.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMC_9.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMC_9obj" scale={1.052}>
        <mesh name="M_UMA_1_F003" geometry={nodes.M_UMA_1_F003.geometry} material={nodes.M_UMA_1_F003.material} position={[-2.99, 0.648, 1.445]}>
          <mesh name="M_UMC_9_PNT001" geometry={nodes.M_UMC_9_PNT001.geometry} material={nodes.M_UMC_9_PNT001.material} position={[1.973, -3.022, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F004" geometry={nodes.M_UMA_1_F004.geometry} material={nodes.M_UMA_1_F004.material} position={[2.987, 0.648, 1.445]}>
          <mesh name="M_UMC_9_PNT" geometry={nodes.M_UMC_9_PNT.geometry} material={nodes.M_UMC_9_PNT.material} position={[-1.971, -3.022, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMA_1_F_A003" geometry={nodes.M_UMA_1_F_A003.geometry} material={nodes.M_UMA_1_F_A003.material} position={[-2.996, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_A004" geometry={nodes.M_UMA_1_F_A004.geometry} material={nodes.M_UMA_1_F_A004.material} position={[2.993, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B003" geometry={nodes.M_UMA_1_F_B003.geometry} material={nodes.M_UMA_1_F_B003.material} position={[-2.999, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_B004" geometry={nodes.M_UMA_1_F_B004.geometry} material={nodes.M_UMA_1_F_B004.material} position={[2.993, 2.454, 1.435]} />
        <mesh name="M_UMA_1_F_C003" geometry={nodes.M_UMA_1_F_C003.geometry} material={nodes.M_UMA_1_F_C003.material} position={[-3, 1.158, 1.435]} />
        <mesh name="M_UMA_1_F_C004" geometry={nodes.M_UMA_1_F_C004.geometry} material={nodes.M_UMA_1_F_C004.material} position={[2.993, 1.158, 1.435]} />
        <mesh name="M_UMC_9" geometry={nodes.M_UMC_9.geometry} material={nodes.M_UMC_9.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMC_9.glb')
