/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMK_1_F_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMK_1_F_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMK_4_F_4obj" scale={1.052}>
        <mesh name="M_UMK_1_F002" geometry={nodes.M_UMK_1_F002.geometry} material={nodes.M_UMK_1_F002.material} position={[-3.975, -0.362, 1.442]}>
          <mesh name="M_UMK_4_PNT_H001" geometry={nodes.M_UMK_4_PNT_H001.geometry} material={nodes.M_UMK_4_PNT_H001.material} position={[1.933, -1.625, 0.172]} />
          <mesh name="M_UMK_4_PNT_V001" geometry={nodes.M_UMK_4_PNT_V001.geometry} material={nodes.M_UMK_4_PNT_V001.material} position={[2.945, -0.776, 0.172]} />
        </mesh>
        <mesh name="M_UMK_1_F003" geometry={nodes.M_UMK_1_F003.geometry} material={nodes.M_UMK_1_F003.material} position={[3.981, -0.362, 1.445]}>
          <mesh name="M_UMK_4_PNT__V_1001" geometry={nodes.M_UMK_4_PNT__V_1001.geometry} material={nodes.M_UMK_4_PNT__V_1001.material} position={[-2.952, -0.776, 0.168]} rotation={[-Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UMK_4_PNT_H002" geometry={nodes.M_UMK_4_PNT_H002.geometry} material={nodes.M_UMK_4_PNT_H002.material} position={[-1.939, -1.625, 0.168]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMK_1_F_A002" geometry={nodes.M_UMK_1_F_A002.geometry} material={nodes.M_UMK_1_F_A002.material} position={[-3.989, 1.443, 1.431]} />
        <mesh name="M_UMK_1_F_A003" geometry={nodes.M_UMK_1_F_A003.geometry} material={nodes.M_UMK_1_F_A003.material} position={[3.978, 1.443, 1.435]} />
        <mesh name="M_UMK_1_F_B002" geometry={nodes.M_UMK_1_F_B002.geometry} material={nodes.M_UMK_1_F_B002.material} position={[-3.994, 1.443, 1.431]} />
        <mesh name="M_UMK_1_F_B003" geometry={nodes.M_UMK_1_F_B003.geometry} material={nodes.M_UMK_1_F_B003.material} position={[3.978, 1.443, 1.435]} />
        <mesh name="M_UMK_1_F_C002" geometry={nodes.M_UMK_1_F_C002.geometry} material={nodes.M_UMK_1_F_C002.material} position={[-3.994, 0.147, 1.431]} />
        <mesh name="M_UMK_1_F_C003" geometry={nodes.M_UMK_1_F_C003.geometry} material={nodes.M_UMK_1_F_C003.material} position={[3.978, 0.147, 1.435]} />
        <mesh name="M_UMK_4" geometry={nodes.M_UMK_4.geometry} material={nodes.M_UMK_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMK_1_F_4.glb')
