/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMK_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMK_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMK_2obj" scale={1.271}>
        <mesh name="M_UMK_1_F006" geometry={nodes.M_UMK_1_F006.geometry} material={nodes.M_UMK_1_F006.material} position={[-2.466, -0.3, 1.194]}>
          <mesh name="M_UMK_2_PNT" geometry={nodes.M_UMK_2_PNT.geometry} material={nodes.M_UMK_2_PNT.material} position={[1.614, -0.643, 0.142]} />
        </mesh>
        <mesh name="M_UMK_1_F007" geometry={nodes.M_UMK_1_F007.geometry} material={nodes.M_UMK_1_F007.material} position={[2.471, -0.3, 1.196]}>
          <mesh name="M_UMK_2_PNT001" geometry={nodes.M_UMK_2_PNT001.geometry} material={nodes.M_UMK_2_PNT001.material} position={[-1.619, -0.643, 0.139]} />
        </mesh>
        <mesh name="M_UMK_1_F_A006" geometry={nodes.M_UMK_1_F_A006.geometry} material={nodes.M_UMK_1_F_A006.material} position={[-2.478, 1.194, 1.185]} />
        <mesh name="M_UMK_1_F_A007" geometry={nodes.M_UMK_1_F_A007.geometry} material={nodes.M_UMK_1_F_A007.material} position={[2.468, 1.194, 1.187]} />
        <mesh name="M_UMK_1_F_B006" geometry={nodes.M_UMK_1_F_B006.geometry} material={nodes.M_UMK_1_F_B006.material} position={[-2.481, 1.194, 1.185]} />
        <mesh name="M_UMK_1_F_B007" geometry={nodes.M_UMK_1_F_B007.geometry} material={nodes.M_UMK_1_F_B007.material} position={[2.468, 1.194, 1.187]} />
        <mesh name="M_UMK_1_F_C006" geometry={nodes.M_UMK_1_F_C006.geometry} material={nodes.M_UMK_1_F_C006.material} position={[-2.481, 0.122, 1.185]} />
        <mesh name="M_UMK_1_F_C007" geometry={nodes.M_UMK_1_F_C007.geometry} material={nodes.M_UMK_1_F_C007.material} position={[2.468, 0.122, 1.187]} />
        <mesh name="M_UMK_2" geometry={nodes.M_UMK_2.geometry} material={nodes.M_UMK_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMK_2.glb')
