/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMK_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMK_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMK_1obj" scale={1.27}>
        <mesh name="M_UMK_1" geometry={nodes.M_UMK_1.geometry} material={nodes.M_UMK_1.material} />
        <mesh name="M_UMK_1_F004" geometry={nodes.M_UMK_1_F004.geometry} material={nodes.M_UMK_1_F004.material} position={[-2.056, -0.3, 1.195]}>
          <mesh name="M_UMK_1_PNT001" geometry={nodes.M_UMK_1_PNT001.geometry} material={nodes.M_UMK_1_PNT001.material} position={[1.203, -0.643, 0.142]} />
        </mesh>
        <mesh name="M_UMK_1_F005" geometry={nodes.M_UMK_1_F005.geometry} material={nodes.M_UMK_1_F005.material} position={[2.063, -0.3, 1.197]}>
          <mesh name="M_UMK_1_PNT" geometry={nodes.M_UMK_1_PNT.geometry} material={nodes.M_UMK_1_PNT.material} position={[-1.21, -0.643, 0.14]} />
        </mesh>
        <mesh name="M_UMK_1_F_A004" geometry={nodes.M_UMK_1_F_A004.geometry} material={nodes.M_UMK_1_F_A004.material} position={[-2.068, 1.195, 1.186]} />
        <mesh name="M_UMK_1_F_A005" geometry={nodes.M_UMK_1_F_A005.geometry} material={nodes.M_UMK_1_F_A005.material} position={[2.06, 1.195, 1.189]} />
        <mesh name="M_UMK_1_F_B004" geometry={nodes.M_UMK_1_F_B004.geometry} material={nodes.M_UMK_1_F_B004.material} position={[-2.071, 1.196, 1.186]} />
        <mesh name="M_UMK_1_F_B005" geometry={nodes.M_UMK_1_F_B005.geometry} material={nodes.M_UMK_1_F_B005.material} position={[2.06, 1.196, 1.189]} />
        <mesh name="M_UMK_1_F_C004" geometry={nodes.M_UMK_1_F_C004.geometry} material={nodes.M_UMK_1_F_C004.material} position={[-2.071, 0.122, 1.186]} />
        <mesh name="M_UMK_1_F_C005" geometry={nodes.M_UMK_1_F_C005.geometry} material={nodes.M_UMK_1_F_C005.material} position={[2.06, 0.122, 1.189]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMK_1.glb')
