/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMK_1_F_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMK_1_F_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMK_3_F_3obj" scale={1.052}>
        <mesh name="M_UMK_1_F" geometry={nodes.M_UMK_1_F.geometry} material={nodes.M_UMK_1_F.material} position={[-3.479, -0.362, 1.442]}>
          <mesh name="M_UMK_3_PNT_H" geometry={nodes.M_UMK_3_PNT_H.geometry} material={nodes.M_UMK_3_PNT_H.material} position={[1.724, -1.625, 0.172]} />
          <mesh name="M_UMK_3_PNT_V" geometry={nodes.M_UMK_3_PNT_V.geometry} material={nodes.M_UMK_3_PNT_V.material} position={[2.449, -0.776, 0.172]} />
        </mesh>
        <mesh name="M_UMK_1_F001" geometry={nodes.M_UMK_1_F001.geometry} material={nodes.M_UMK_1_F001.material} position={[3.487, -0.362, 1.445]}>
          <mesh name="M_UMK_3_PNT__V_1" geometry={nodes.M_UMK_3_PNT__V_1.geometry} material={nodes.M_UMK_3_PNT__V_1.material} position={[-2.457, -0.776, 0.168]} rotation={[-Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UMK_3_PNT_H_1" geometry={nodes.M_UMK_3_PNT_H_1.geometry} material={nodes.M_UMK_3_PNT_H_1.material} position={[-1.732, -1.625, 0.168]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMK_1_F_A" geometry={nodes.M_UMK_1_F_A.geometry} material={nodes.M_UMK_1_F_A.material} position={[-3.493, 1.443, 1.431]} />
        <mesh name="M_UMK_1_F_A001" geometry={nodes.M_UMK_1_F_A001.geometry} material={nodes.M_UMK_1_F_A001.material} position={[3.483, 1.443, 1.435]} />
        <mesh name="M_UMK_1_F_B" geometry={nodes.M_UMK_1_F_B.geometry} material={nodes.M_UMK_1_F_B.material} position={[-3.497, 1.443, 1.431]} />
        <mesh name="M_UMK_1_F_B001" geometry={nodes.M_UMK_1_F_B001.geometry} material={nodes.M_UMK_1_F_B001.material} position={[3.483, 1.443, 1.435]} />
        <mesh name="M_UMK_1_F_C" geometry={nodes.M_UMK_1_F_C.geometry} material={nodes.M_UMK_1_F_C.material} position={[-3.497, 0.147, 1.431]} />
        <mesh name="M_UMK_1_F_C001" geometry={nodes.M_UMK_1_F_C001.geometry} material={nodes.M_UMK_1_F_C001.material} position={[3.483, 0.147, 1.435]} />
        <mesh name="M_UMK_3" geometry={nodes.M_UMK_3.geometry} material={nodes.M_UMK_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMK_1_F_3.glb')
