/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMP_8.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMP_8.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMP_8obj" scale={1.052}>
        <mesh name="M_UMP_1_F003" geometry={nodes.M_UMP_1_F003.geometry} material={nodes.M_UMP_1_F003.material} position={[3.003, 2.302, 1.436]}>
          <mesh name="M_UMP_3_PNT005" geometry={nodes.M_UMP_3_PNT005.geometry} material={nodes.M_UMP_3_PNT005.material} position={[-3.003, -3.495, 0.19]} />
        </mesh>
        <mesh name="M_UMP_1_F_A003" geometry={nodes.M_UMP_1_F_A003.geometry} material={nodes.M_UMP_1_F_A003.material} position={[3.001, 2.302, 1.427]} />
        <mesh name="M_UMP_1_F_B003" geometry={nodes.M_UMP_1_F_B003.geometry} material={nodes.M_UMP_1_F_B003.material} position={[3.001, 2.3, 1.427]} />
        <mesh name="M_UMP_1_F_C003" geometry={nodes.M_UMP_1_F_C003.geometry} material={nodes.M_UMP_1_F_C003.material} position={[3.001, 2.298, 1.427]} />
        <mesh name="M_UMP_8" geometry={nodes.M_UMP_8.geometry} material={nodes.M_UMP_8.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMP_8.glb')
