/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMP_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMP_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMP_3obj" scale={1.052}>
        <mesh name="M_UMP_1_F006" geometry={nodes.M_UMP_1_F006.geometry} material={nodes.M_UMP_1_F006.material} position={[2.492, 1.787, 1.436]}>
          <mesh name="M_UMP_3_PNT" geometry={nodes.M_UMP_3_PNT.geometry} material={nodes.M_UMP_3_PNT.material} position={[-2.492, -2.98, 0.147]} />
        </mesh>
        <mesh name="M_UMP_1_F_A006" geometry={nodes.M_UMP_1_F_A006.geometry} material={nodes.M_UMP_1_F_A006.material} position={[2.491, 1.787, 1.427]} />
        <mesh name="M_UMP_1_F_B006" geometry={nodes.M_UMP_1_F_B006.geometry} material={nodes.M_UMP_1_F_B006.material} position={[2.491, 1.785, 1.427]} />
        <mesh name="M_UMP_1_F_C006" geometry={nodes.M_UMP_1_F_C006.geometry} material={nodes.M_UMP_1_F_C006.material} position={[2.491, 1.782, 1.427]} />
        <mesh name="M_UMP_3" geometry={nodes.M_UMP_3.geometry} material={nodes.M_UMP_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMP_3.glb')
