/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMP_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMP_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMP_7obj" scale={1.052}>
        <mesh name="M_UMP_1_F002" geometry={nodes.M_UMP_1_F002.geometry} material={nodes.M_UMP_1_F002.material} position={[2.495, 2.302, 1.436]}>
          <mesh name="M_UMP_3_PNT004" geometry={nodes.M_UMP_3_PNT004.geometry} material={nodes.M_UMP_3_PNT004.material} position={[-2.495, -3.495, 0.19]} />
        </mesh>
        <mesh name="M_UMP_1_F_A002" geometry={nodes.M_UMP_1_F_A002.geometry} material={nodes.M_UMP_1_F_A002.material} position={[2.493, 2.302, 1.427]} />
        <mesh name="M_UMP_1_F_B002" geometry={nodes.M_UMP_1_F_B002.geometry} material={nodes.M_UMP_1_F_B002.material} position={[2.493, 2.3, 1.427]} />
        <mesh name="M_UMP_1_F_C002" geometry={nodes.M_UMP_1_F_C002.geometry} material={nodes.M_UMP_1_F_C002.material} position={[2.493, 2.298, 1.427]} />
        <mesh name="M_UMP_7" geometry={nodes.M_UMP_7.geometry} material={nodes.M_UMP_7.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMP_7.glb')
