/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMP_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMP_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMP_5obj" scale={1.052}>
        <mesh name="M_UMP_1_F" geometry={nodes.M_UMP_1_F.geometry} material={nodes.M_UMP_1_F.material} position={[2.497, 2.131, 1.436]}>
          <mesh name="M_UMP_3_PNT002" geometry={nodes.M_UMP_3_PNT002.geometry} material={nodes.M_UMP_3_PNT002.material} position={[-2.497, -3.325, 0.19]} />
        </mesh>
        <mesh name="M_UMP_1_F_A" geometry={nodes.M_UMP_1_F_A.geometry} material={nodes.M_UMP_1_F_A.material} position={[2.496, 2.131, 1.427]} />
        <mesh name="M_UMP_1_F_B" geometry={nodes.M_UMP_1_F_B.geometry} material={nodes.M_UMP_1_F_B.material} position={[2.496, 2.129, 1.427]} />
        <mesh name="M_UMP_1_F_C" geometry={nodes.M_UMP_1_F_C.geometry} material={nodes.M_UMP_1_F_C.material} position={[2.496, 2.127, 1.427]} />
        <mesh name="M_UMP_5" geometry={nodes.M_UMP_5.geometry} material={nodes.M_UMP_5.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMP_5.glb')
