/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMP_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMP_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMP_1obj" scale={1.061}>
        <mesh name="M_UMP_1" geometry={nodes.M_UMP_1.geometry} material={nodes.M_UMP_1.material} />
        <mesh name="M_UMP_1_F004" geometry={nodes.M_UMP_1_F004.geometry} material={nodes.M_UMP_1_F004.material} position={[2.441, 1.47, 1.439]}>
          <mesh name="M_UMP_1_PNT" geometry={nodes.M_UMP_1_PNT.geometry} material={nodes.M_UMP_1_PNT.material} position={[-2.441, -2.352, 0.145]} />
        </mesh>
        <mesh name="M_UMP_1_F_A004" geometry={nodes.M_UMP_1_F_A004.geometry} material={nodes.M_UMP_1_F_A004.material} position={[2.439, 1.47, 1.429]} />
        <mesh name="M_UMP_1_F_B004" geometry={nodes.M_UMP_1_F_B004.geometry} material={nodes.M_UMP_1_F_B004.material} position={[2.439, 1.469, 1.429]} />
        <mesh name="M_UMP_1_F_C004" geometry={nodes.M_UMP_1_F_C004.geometry} material={nodes.M_UMP_1_F_C004.material} position={[2.439, 1.466, 1.429]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMP_1.glb')
