/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMP_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMP_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMP_4obj" scale={1.052}>
        <mesh name="M_UMP_1_F007" geometry={nodes.M_UMP_1_F007.geometry} material={nodes.M_UMP_1_F007.material} position={[2.997, 1.794, 1.436]}>
          <mesh name="M_UMP_3_PNT001" geometry={nodes.M_UMP_3_PNT001.geometry} material={nodes.M_UMP_3_PNT001.material} position={[-2.997, -2.988, 0.147]} />
        </mesh>
        <mesh name="M_UMP_1_F_A007" geometry={nodes.M_UMP_1_F_A007.geometry} material={nodes.M_UMP_1_F_A007.material} position={[2.995, 1.794, 1.427]} />
        <mesh name="M_UMP_1_F_B007" geometry={nodes.M_UMP_1_F_B007.geometry} material={nodes.M_UMP_1_F_B007.material} position={[2.995, 1.792, 1.427]} />
        <mesh name="M_UMP_1_F_C007" geometry={nodes.M_UMP_1_F_C007.geometry} material={nodes.M_UMP_1_F_C007.material} position={[2.995, 1.79, 1.427]} />
        <mesh name="M_UMP_4" geometry={nodes.M_UMP_4.geometry} material={nodes.M_UMP_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMP_4.glb')
