/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMP_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMP_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMP_2obj" scale={1.056}>
        <mesh name="M_UMP_1_F005" geometry={nodes.M_UMP_1_F005.geometry} material={nodes.M_UMP_1_F005.material} position={[2.988, 1.491, 1.43]}>
          <mesh name="M_UMP_1_PNT001" geometry={nodes.M_UMP_1_PNT001.geometry} material={nodes.M_UMP_1_PNT001.material} position={[-2.988, -2.385, 0.147]} />
        </mesh>
        <mesh name="M_UMP_1_F_A005" geometry={nodes.M_UMP_1_F_A005.geometry} material={nodes.M_UMP_1_F_A005.material} position={[2.987, 1.491, 1.42]} />
        <mesh name="M_UMP_1_F_B005" geometry={nodes.M_UMP_1_F_B005.geometry} material={nodes.M_UMP_1_F_B005.material} position={[2.987, 1.489, 1.42]} />
        <mesh name="M_UMP_1_F_C005" geometry={nodes.M_UMP_1_F_C005.geometry} material={nodes.M_UMP_1_F_C005.material} position={[2.987, 1.486, 1.42]} />
        <mesh name="M_UMP_2" geometry={nodes.M_UMP_2.geometry} material={nodes.M_UMP_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMP_2.glb')
