/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMP_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMP_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMP_6obj" scale={1.052}>
        <mesh name="M_UMP_1_F001" geometry={nodes.M_UMP_1_F001.geometry} material={nodes.M_UMP_1_F001.material} position={[3.002, 2.131, 1.436]}>
          <mesh name="M_UMP_3_PNT003" geometry={nodes.M_UMP_3_PNT003.geometry} material={nodes.M_UMP_3_PNT003.material} position={[-3.002, -3.325, 0.155]} />
        </mesh>
        <mesh name="M_UMP_1_F_A001" geometry={nodes.M_UMP_1_F_A001.geometry} material={nodes.M_UMP_1_F_A001.material} position={[3.001, 2.131, 1.427]} />
        <mesh name="M_UMP_1_F_B001" geometry={nodes.M_UMP_1_F_B001.geometry} material={nodes.M_UMP_1_F_B001.material} position={[3.001, 2.129, 1.427]} />
        <mesh name="M_UMP_1_F_C001" geometry={nodes.M_UMP_1_F_C001.geometry} material={nodes.M_UMP_1_F_C001.material} position={[3.001, 2.127, 1.427]} />
        <mesh name="M_UMP_6" geometry={nodes.M_UMP_6.geometry} material={nodes.M_UMP_6.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMP_6.glb')
