/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMM_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMM_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMM_2_F_2obj" scale={1.052}>
        <mesh name="M_UMM_1_F006" geometry={nodes.M_UMM_1_F006.geometry} material={nodes.M_UMM_1_F006.material} position={[-2.988, -0.362, 1.442]}>
          <mesh name="M_UMM_2_PNT001" geometry={nodes.M_UMM_2_PNT001.geometry} material={nodes.M_UMM_2_PNT001.material} position={[1.962, -2.005, 0.172]} />
        </mesh>
        <mesh name="M_UMM_1_F007" geometry={nodes.M_UMM_1_F007.geometry} material={nodes.M_UMM_1_F007.material} position={[2.993, -0.362, 1.445]}>
          <mesh name="M_UMM_2_PNT" geometry={nodes.M_UMM_2_PNT.geometry} material={nodes.M_UMM_2_PNT.material} position={[-1.966, -2.005, 0.169]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMM_1_F_A006" geometry={nodes.M_UMM_1_F_A006.geometry} material={nodes.M_UMM_1_F_A006.material} position={[-3.003, 1.443, 1.431]} />
        <mesh name="M_UMM_1_F_A007" geometry={nodes.M_UMM_1_F_A007.geometry} material={nodes.M_UMM_1_F_A007.material} position={[2.989, 1.443, 1.435]} />
        <mesh name="M_UMM_1_F_B006" geometry={nodes.M_UMM_1_F_B006.geometry} material={nodes.M_UMM_1_F_B006.material} position={[-3.007, 1.443, 1.431]} />
        <mesh name="M_UMM_1_F_B007" geometry={nodes.M_UMM_1_F_B007.geometry} material={nodes.M_UMM_1_F_B007.material} position={[2.989, 1.443, 1.435]} />
        <mesh name="M_UMM_1_F_C006" geometry={nodes.M_UMM_1_F_C006.geometry} material={nodes.M_UMM_1_F_C006.material} position={[-3.007, 0.147, 1.431]} />
        <mesh name="M_UMM_1_F_C007" geometry={nodes.M_UMM_1_F_C007.geometry} material={nodes.M_UMM_1_F_C007.material} position={[2.989, 0.147, 1.435]} />
        <mesh name="M_UMM_2" geometry={nodes.M_UMM_2.geometry} material={nodes.M_UMM_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMM_2.glb')
