/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMM_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMM_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMM_1obj" scale={1.052}>
        <mesh name="M_UMM_1" geometry={nodes.M_UMM_1.geometry} material={nodes.M_UMM_1.material} />
        <mesh name="M_UMM_1_F004" geometry={nodes.M_UMM_1_F004.geometry} material={nodes.M_UMM_1_F004.material} position={[-2.479, -0.362, 1.442]}>
          <mesh name="M_UMM_1_PNT001" geometry={nodes.M_UMM_1_PNT001.geometry} material={nodes.M_UMM_1_PNT001.material} position={[1.21, -2.005, 0.172]} />
        </mesh>
        <mesh name="M_UMM_1_F005" geometry={nodes.M_UMM_1_F005.geometry} material={nodes.M_UMM_1_F005.material} position={[2.484, -0.362, 1.445]}>
          <mesh name="M_UMM_1_PNT" geometry={nodes.M_UMM_1_PNT.geometry} material={nodes.M_UMM_1_PNT.material} position={[-1.214, -2.005, 0.169]} />
        </mesh>
        <mesh name="M_UMM_1_F_A004" geometry={nodes.M_UMM_1_F_A004.geometry} material={nodes.M_UMM_1_F_A004.material} position={[-2.494, 1.443, 1.431]} />
        <mesh name="M_UMM_1_F_A005" geometry={nodes.M_UMM_1_F_A005.geometry} material={nodes.M_UMM_1_F_A005.material} position={[2.481, 1.443, 1.435]} />
        <mesh name="M_UMM_1_F_B004" geometry={nodes.M_UMM_1_F_B004.geometry} material={nodes.M_UMM_1_F_B004.material} position={[-2.498, 1.443, 1.431]} />
        <mesh name="M_UMM_1_F_B005" geometry={nodes.M_UMM_1_F_B005.geometry} material={nodes.M_UMM_1_F_B005.material} position={[2.481, 1.443, 1.435]} />
        <mesh name="M_UMM_1_F_C004" geometry={nodes.M_UMM_1_F_C004.geometry} material={nodes.M_UMM_1_F_C004.material} position={[-2.498, 0.147, 1.431]} />
        <mesh name="M_UMM_1_F_C005" geometry={nodes.M_UMM_1_F_C005.geometry} material={nodes.M_UMM_1_F_C005.material} position={[2.481, 0.147, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMM_1.glb')
