/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMM_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMM_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMM_4_F_4obj" scale={1.052}>
        <mesh name="M_UMM_1_F002" geometry={nodes.M_UMM_1_F002.geometry} material={nodes.M_UMM_1_F002.material} position={[-3.972, -0.362, 1.442]}>
          <mesh name="M_UMM_4_PNT_H" geometry={nodes.M_UMM_4_PNT_H.geometry} material={nodes.M_UMM_4_PNT_H.material} position={[1.94, -2.855, 0.172]} />
          <mesh name="M_UMM_4_PNT_V" geometry={nodes.M_UMM_4_PNT_V.geometry} material={nodes.M_UMM_4_PNT_V.material} position={[2.946, -2.005, 0.172]} />
        </mesh>
        <mesh name="M_UMM_1_F003" geometry={nodes.M_UMM_1_F003.geometry} material={nodes.M_UMM_1_F003.material} position={[3.987, -0.362, 1.445]}>
          <mesh name="M_UMM_4_PNT_H001" geometry={nodes.M_UMM_4_PNT_H001.geometry} material={nodes.M_UMM_4_PNT_H001.material} position={[-1.955, -2.855, 0.169]} rotation={[-Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UMM_4_PNT_V001" geometry={nodes.M_UMM_4_PNT_V001.geometry} material={nodes.M_UMM_4_PNT_V001.material} position={[-2.961, -2.005, 0.169]} rotation={[Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMM_1_F_A002" geometry={nodes.M_UMM_1_F_A002.geometry} material={nodes.M_UMM_1_F_A002.material} position={[-3.986, 1.443, 1.431]} />
        <mesh name="M_UMM_1_F_A003" geometry={nodes.M_UMM_1_F_A003.geometry} material={nodes.M_UMM_1_F_A003.material} position={[3.984, 1.443, 1.435]} />
        <mesh name="M_UMM_1_F_B002" geometry={nodes.M_UMM_1_F_B002.geometry} material={nodes.M_UMM_1_F_B002.material} position={[-3.99, 1.443, 1.431]} />
        <mesh name="M_UMM_1_F_B003" geometry={nodes.M_UMM_1_F_B003.geometry} material={nodes.M_UMM_1_F_B003.material} position={[3.984, 1.443, 1.435]} />
        <mesh name="M_UMM_1_F_C002" geometry={nodes.M_UMM_1_F_C002.geometry} material={nodes.M_UMM_1_F_C002.material} position={[-3.99, 0.147, 1.431]} />
        <mesh name="M_UMM_1_F_C003" geometry={nodes.M_UMM_1_F_C003.geometry} material={nodes.M_UMM_1_F_C003.material} position={[3.984, 0.147, 1.435]} />
        <mesh name="M_UMM_4" geometry={nodes.M_UMM_4.geometry} material={nodes.M_UMM_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMM_4.glb')
