/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT1_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT1_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT_7obj" scale={1.273}>
        <mesh name="M_UMT_1_F005" geometry={nodes.M_UMT_1_F005.geometry} material={nodes.M_UMT_1_F005.material} position={[3.302, 2.975, 1.186]}>
          <mesh name="M_UMT_1_F004" geometry={nodes.M_UMT_1_F004.geometry} material={nodes.M_UMT_1_F004.material} position={[0, -2.97, 0]}>
            <mesh name="M_UMT_7_PNT" geometry={nodes.M_UMT_7_PNT.geometry} material={nodes.M_UMT_7_PNT.material} position={[-3.302, -2.33, 0.147]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT_1_F_A005" geometry={nodes.M_UMT_1_F_A005.geometry} material={nodes.M_UMT_1_F_A005.material} position={[3.3, 2.974, 1.179]}>
          <mesh name="M_UMT_1_F_A004" geometry={nodes.M_UMT_1_F_A004.geometry} material={nodes.M_UMT_1_F_A004.material} position={[0, -2.97, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_B005" geometry={nodes.M_UMT_1_F_B005.geometry} material={nodes.M_UMT_1_F_B005.material} position={[3.3, 2.972, 1.179]}>
          <mesh name="M_UMT_1_F_B004" geometry={nodes.M_UMT_1_F_B004.geometry} material={nodes.M_UMT_1_F_B004.material} position={[0, -2.97, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_C005" geometry={nodes.M_UMT_1_F_C005.geometry} material={nodes.M_UMT_1_F_C005.material} position={[3.3, 2.969, 1.179]}>
          <mesh name="M_UMT_1_F_C004" geometry={nodes.M_UMT_1_F_C004.geometry} material={nodes.M_UMT_1_F_C004.material} position={[0, -2.97, 0]} />
        </mesh>
        <mesh name="M_UMT_7" geometry={nodes.M_UMT_7.geometry} material={nodes.M_UMT_7.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT1_7.glb')
