/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT1_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT1_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT1_2obj" scale={1.506}>
        <mesh name="M_UMT1_1_F011" geometry={nodes.M_UMT1_1_F011.geometry} material={nodes.M_UMT1_1_F011.material} position={[1.916, 2.968, 1.003]}>
          <mesh name="M_UMT1_1_F010" geometry={nodes.M_UMT1_1_F010.geometry} material={nodes.M_UMT1_1_F010.material} position={[0, -2.957, 0]}>
            <mesh name="M_UMT1_2_PNT" geometry={nodes.M_UMT1_2_PNT.geometry} material={nodes.M_UMT1_2_PNT.material} position={[-1.916, -2.412, 0.124]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT1_1_F_A011" geometry={nodes.M_UMT1_1_F_A011.geometry} material={nodes.M_UMT1_1_F_A011.material} position={[1.915, 2.968, 0.997]}>
          <mesh name="M_UMT1_1_F_A010" geometry={nodes.M_UMT1_1_F_A010.geometry} material={nodes.M_UMT1_1_F_A010.material} position={[0, -2.957, 0]} />
        </mesh>
        <mesh name="M_UMT1_1_F_B011" geometry={nodes.M_UMT1_1_F_B011.geometry} material={nodes.M_UMT1_1_F_B011.material} position={[1.915, 2.966, 0.997]}>
          <mesh name="M_UMT1_1_F_B010" geometry={nodes.M_UMT1_1_F_B010.geometry} material={nodes.M_UMT1_1_F_B010.material} position={[0, -2.957, 0]} />
        </mesh>
        <mesh name="M_UMT1_1_F_C011" geometry={nodes.M_UMT1_1_F_C011.geometry} material={nodes.M_UMT1_1_F_C011.material} position={[1.915, 2.963, 0.997]}>
          <mesh name="M_UMT1_1_F_C010" geometry={nodes.M_UMT1_1_F_C010.geometry} material={nodes.M_UMT1_1_F_C010.material} position={[0, -2.957, 0]} />
        </mesh>
        <mesh name="M_UMT1_2" geometry={nodes.M_UMT1_2.geometry} material={nodes.M_UMT1_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT1_2.glb')
