/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT1_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT1_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT1_6obj" scale={1.505}>
        <mesh name="M_UMT1_1_F005" geometry={nodes.M_UMT1_1_F005.geometry} material={nodes.M_UMT1_1_F005.material} position={[2.624, 2.97, 1.004]}>
          <mesh name="M_UMT1_1_F004" geometry={nodes.M_UMT1_1_F004.geometry} material={nodes.M_UMT1_1_F004.material} position={[0, -2.956, 0]}>
            <mesh name="M_UMT1_6_PNT001" geometry={nodes.M_UMT1_6_PNT001.geometry} material={nodes.M_UMT1_6_PNT001.material} position={[-2.624, -2.414, 0.125]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT1_1_F_A005" geometry={nodes.M_UMT1_1_F_A005.geometry} material={nodes.M_UMT1_1_F_A005.material} position={[2.622, 2.97, 0.997]}>
          <mesh name="M_UMT1_1_F_A004" geometry={nodes.M_UMT1_1_F_A004.geometry} material={nodes.M_UMT1_1_F_A004.material} position={[0, -2.956, 0]} />
        </mesh>
        <mesh name="M_UMT1_1_F_B005" geometry={nodes.M_UMT1_1_F_B005.geometry} material={nodes.M_UMT1_1_F_B005.material} position={[2.622, 2.969, 0.997]}>
          <mesh name="M_UMT1_1_F_B004" geometry={nodes.M_UMT1_1_F_B004.geometry} material={nodes.M_UMT1_1_F_B004.material} position={[0, -2.956, 0]} />
        </mesh>
        <mesh name="M_UMT1_1_F_C005" geometry={nodes.M_UMT1_1_F_C005.geometry} material={nodes.M_UMT1_1_F_C005.material} position={[2.622, 2.966, 0.997]}>
          <mesh name="M_UMT1_1_F_C004" geometry={nodes.M_UMT1_1_F_C004.geometry} material={nodes.M_UMT1_1_F_C004.material} position={[0, -2.956, 0]} />
        </mesh>
        <mesh name="M_UMT1_6" geometry={nodes.M_UMT1_6.geometry} material={nodes.M_UMT1_6.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT1_6.glb')
