/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT1_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT1_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT1_3obj" scale={1.506}>
        <mesh name="M_UMT1_1_F013" geometry={nodes.M_UMT1_1_F013.geometry} material={nodes.M_UMT1_1_F013.material} position={[2.091, 2.967, 1.002]}>
          <mesh name="M_UMT1_1_F012" geometry={nodes.M_UMT1_1_F012.geometry} material={nodes.M_UMT1_1_F012.material} position={[0, -2.955, 0]}>
            <mesh name="M_UMT1_3_PNT001" geometry={nodes.M_UMT1_3_PNT001.geometry} material={nodes.M_UMT1_3_PNT001.material} position={[-2.091, -2.411, 0.124]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT1_1_F_A013" geometry={nodes.M_UMT1_1_F_A013.geometry} material={nodes.M_UMT1_1_F_A013.material} position={[2.09, 2.966, 0.996]}>
          <mesh name="M_UMT1_1_F_A012" geometry={nodes.M_UMT1_1_F_A012.geometry} material={nodes.M_UMT1_1_F_A012.material} position={[0, -2.955, 0]} />
        </mesh>
        <mesh name="M_UMT1_1_F_B013" geometry={nodes.M_UMT1_1_F_B013.geometry} material={nodes.M_UMT1_1_F_B013.material} position={[2.09, 2.965, 0.996]}>
          <mesh name="M_UMT1_1_F_B012" geometry={nodes.M_UMT1_1_F_B012.geometry} material={nodes.M_UMT1_1_F_B012.material} position={[0, -2.955, 0]} />
        </mesh>
        <mesh name="M_UMT1_1_F_C013" geometry={nodes.M_UMT1_1_F_C013.geometry} material={nodes.M_UMT1_1_F_C013.material} position={[2.09, 2.962, 0.996]}>
          <mesh name="M_UMT1_1_F_C012" geometry={nodes.M_UMT1_1_F_C012.geometry} material={nodes.M_UMT1_1_F_C012.material} position={[0, -2.955, 0]} />
        </mesh>
        <mesh name="M_UMT1_3" geometry={nodes.M_UMT1_3.geometry} material={nodes.M_UMT1_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT1_3.glb')
