/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT1_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT1_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT1_5obj" scale={1.501}>
        <mesh name="M_UMT1_1_F003" geometry={nodes.M_UMT1_1_F003.geometry} material={nodes.M_UMT1_1_F003.material} position={[2.446, 2.976, 1.006]}>
          <mesh name="M_UMT1_1_F002" geometry={nodes.M_UMT1_1_F002.geometry} material={nodes.M_UMT1_1_F002.material} position={[0, -2.967, 0]}>
            <mesh name="M_UMT1_5_PNT001" geometry={nodes.M_UMT1_5_PNT001.geometry} material={nodes.M_UMT1_5_PNT001.material} position={[-2.446, -2.419, 0.125]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT1_1_F_A003" geometry={nodes.M_UMT1_1_F_A003.geometry} material={nodes.M_UMT1_1_F_A003.material} position={[2.444, 2.976, 0.999]}>
          <mesh name="M_UMT1_1_F_A002" geometry={nodes.M_UMT1_1_F_A002.geometry} material={nodes.M_UMT1_1_F_A002.material} position={[0, -2.967, 0]} />
        </mesh>
        <mesh name="M_UMT1_1_F_B003" geometry={nodes.M_UMT1_1_F_B003.geometry} material={nodes.M_UMT1_1_F_B003.material} position={[2.444, 2.974, 0.999]}>
          <mesh name="M_UMT1_1_F_B002" geometry={nodes.M_UMT1_1_F_B002.geometry} material={nodes.M_UMT1_1_F_B002.material} position={[0, -2.967, 0]} />
        </mesh>
        <mesh name="M_UMT1_1_F_C003" geometry={nodes.M_UMT1_1_F_C003.geometry} material={nodes.M_UMT1_1_F_C003.material} position={[2.444, 2.971, 0.999]}>
          <mesh name="M_UMT1_1_F_C002" geometry={nodes.M_UMT1_1_F_C002.geometry} material={nodes.M_UMT1_1_F_C002.material} position={[0, -2.967, 0]} />
        </mesh>
        <mesh name="M_UMT1_5" geometry={nodes.M_UMT1_5.geometry} material={nodes.M_UMT1_5.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT1_5.glb')
