/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT1_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT1_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT1_1obj" scale={1.507}>
        <mesh name="M_UMT1_1" geometry={nodes.M_UMT1_1.geometry} material={nodes.M_UMT1_1.material} />
        <mesh name="M_UMT1_1_F009" geometry={nodes.M_UMT1_1_F009.geometry} material={nodes.M_UMT1_1_F009.material} position={[1.74, 2.966, 1.002]}>
          <mesh name="M_UMT1_1_F008" geometry={nodes.M_UMT1_1_F008.geometry} material={nodes.M_UMT1_1_F008.material} position={[0, -2.956, 0]}>
            <mesh name="M_UMT1_1_PNT" geometry={nodes.M_UMT1_1_PNT.geometry} material={nodes.M_UMT1_1_PNT.material} position={[-1.74, -2.411, 0.124]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT1_1_F_A009" geometry={nodes.M_UMT1_1_F_A009.geometry} material={nodes.M_UMT1_1_F_A009.material} position={[1.738, 2.966, 0.996]}>
          <mesh name="M_UMT1_1_F_A008" geometry={nodes.M_UMT1_1_F_A008.geometry} material={nodes.M_UMT1_1_F_A008.material} position={[0, -2.956, 0]} />
        </mesh>
        <mesh name="M_UMT1_1_F_B009" geometry={nodes.M_UMT1_1_F_B009.geometry} material={nodes.M_UMT1_1_F_B009.material} position={[1.738, 2.964, 0.996]}>
          <mesh name="M_UMT1_1_F_B008" geometry={nodes.M_UMT1_1_F_B008.geometry} material={nodes.M_UMT1_1_F_B008.material} position={[0, -2.956, 0]} />
        </mesh>
        <mesh name="M_UMT1_1_F_C009" geometry={nodes.M_UMT1_1_F_C009.geometry} material={nodes.M_UMT1_1_F_C009.material} position={[1.738, 2.961, 0.996]}>
          <mesh name="M_UMT1_1_F_C008" geometry={nodes.M_UMT1_1_F_C008.geometry} material={nodes.M_UMT1_1_F_C008.material} position={[0, -2.956, 0]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT1_1.glb')
