/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Door.glb -k -K 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Door.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Door">
          <mesh name="Door_frame" geometry={nodes.Door_frame.geometry} material={materials.WHITE} position={[-0.001, 1.198, 0]} />
          <mesh name="Door_main" geometry={nodes.Door_main.geometry} material={materials.WHITE} position={[0.4, 1, 0.054]}>
            <mesh name="door_handle_1" geometry={nodes.door_handle_1.geometry} material={materials.WHITE} position={[-0.732, -0.001, 0.02]} />
            <mesh name="door_handle_1_cyl" geometry={nodes.door_handle_1_cyl.geometry} material={materials.WHITE} position={[-0.732, -0.001, 0.02]} />
            <mesh name="door_handle_2" geometry={nodes.door_handle_2.geometry} material={materials.WHITE} position={[-0.732, -0.001, -0.06]} />
            <mesh name="door_handle_2_cyl" geometry={nodes.door_handle_2_cyl.geometry} material={materials.WHITE} position={[-0.732, -0.001, -0.06]} />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Door.glb')
