/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Window.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Window.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.window_corner.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.window_frame_main.geometry} material={materials.WHITE}>
        <mesh geometry={nodes.glass_1.geometry} material={materials.BLUE} />
      </mesh>
      <mesh geometry={nodes.window_frame_sub.geometry} material={materials.WHITE} position={[-0.706, 0.665, 0.035]}>
        <mesh geometry={nodes.glass_2.geometry} material={materials.BLUE} position={[0.706, -0.665, -0.035]} />
        <mesh geometry={nodes.handle.geometry} material={materials.WHITE} position={[0.706, -0.665, -0.035]} />
        <mesh geometry={nodes.handle_part.geometry} material={materials.WHITE} position={[0.706, -0.665, -0.035]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Window.glb')
