/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Door.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Door.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Door_frame" geometry={nodes.Door_frame.geometry} material={materials.WHITE} />
      <mesh name="Door_main" geometry={nodes.Door_main.geometry} material={materials.WHITE}>
        <mesh name="door_handle_1" geometry={nodes.door_handle_1.geometry} material={materials.WHITE} />
        <mesh name="door_handle_1_cyl" geometry={nodes.door_handle_1_cyl.geometry} material={materials.WHITE} />
        <mesh name="door_handle_2" geometry={nodes.door_handle_2.geometry} material={materials.WHITE} />
        <mesh name="door_handle_2_cyl" geometry={nodes.door_handle_2_cyl.geometry} material={materials.WHITE} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Door.glb')
