/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Window.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Window.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="window_corner" geometry={nodes.window_corner.geometry} material={materials.WHITE} />
      <mesh name="window_frame_main" geometry={nodes.window_frame_main.geometry} material={materials.WHITE}>
        <mesh name="glass_1" geometry={nodes.glass_1.geometry} material={materials.BLUE} />
      </mesh>
      <mesh name="window_frame_sub" geometry={nodes.window_frame_sub.geometry} material={materials.WHITE}>
        <mesh name="glass_2" geometry={nodes.glass_2.geometry} material={materials.BLUE} />
        <mesh name="handle" geometry={nodes.handle.geometry} material={materials.WHITE} />
        <mesh name="handle_part" geometry={nodes.handle_part.geometry} material={materials.WHITE} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Window.glb')
