/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMF_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMF_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMF_3obj002" scale={1.05}>
        <mesh name="M_UMF_1_F_IC002" geometry={nodes.M_UMF_1_F_IC002.geometry} material={nodes.M_UMF_1_F_IC002.material} position={[2.805, -0.602, 0.032]}>
          <mesh name="M_UMF_3_PNT_H" geometry={nodes.M_UMF_3_PNT_H.geometry} material={nodes.M_UMF_3_PNT_H.material} position={[-1.3, -2.633, 1.539]} />
          <mesh name="M_UMF_3_PNT_V" geometry={nodes.M_UMF_3_PNT_V.geometry} material={nodes.M_UMF_3_PNT_V.material} position={[-1.964, -1.774, 2.203]} />
        </mesh>
        <mesh name="M_UMF_1_F_IC_A002" geometry={nodes.M_UMF_1_F_IC_A002.geometry} material={nodes.M_UMF_1_F_IC_A002.material} position={[2.802, 1.204, 0.021]} />
        <mesh name="M_UMF_1_F_IC_B002" geometry={nodes.M_UMF_1_F_IC_B002.geometry} material={nodes.M_UMF_1_F_IC_B002.material} position={[2.802, 1.204, 0.021]} />
        <mesh name="M_UMF_1_F_IC_C002" geometry={nodes.M_UMF_1_F_IC_C002.geometry} material={nodes.M_UMF_1_F_IC_C002.material} position={[2.802, -0.092, 0.021]} />
        <mesh name="M_UMF_3" geometry={nodes.M_UMF_3.geometry} material={nodes.M_UMF_3.material} position={[0, -1.25, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMF_3.glb')
