/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMF_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMF_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMF_1001" scale={1.051}>
        <mesh name="M_UMF_1" geometry={nodes.M_UMF_1.geometry} material={nodes.M_UMF_1.material} />
        <mesh name="M_UMF_1_F_IC" geometry={nodes.M_UMF_1_F_IC.geometry} material={nodes.M_UMF_1_F_IC.material} position={[2.805, 0.648, 0.032]}>
          <mesh name="M_UMF_1_PNT_H" geometry={nodes.M_UMF_1_PNT_H.geometry} material={nodes.M_UMF_1_PNT_H.material} position={[-1.3, -2.633, 1.539]} />
          <mesh name="M_UMF_1_PNT_V" geometry={nodes.M_UMF_1_PNT_V.geometry} material={nodes.M_UMF_1_PNT_V.material} position={[-1.964, -1.774, 2.203]} />
        </mesh>
        <mesh name="M_UMF_1_F_IC_A" geometry={nodes.M_UMF_1_F_IC_A.geometry} material={nodes.M_UMF_1_F_IC_A.material} position={[2.802, 2.454, 0.021]} />
        <mesh name="M_UMF_1_F_IC_B" geometry={nodes.M_UMF_1_F_IC_B.geometry} material={nodes.M_UMF_1_F_IC_B.material} position={[2.802, 2.454, 0.021]} />
        <mesh name="M_UMF_1_F_IC_C" geometry={nodes.M_UMF_1_F_IC_C.geometry} material={nodes.M_UMF_1_F_IC_C.material} position={[2.802, 1.158, 0.021]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMF_1.glb')
