/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMF_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMF_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMF_4001" scale={1.051}>
        <mesh name="M_UMF_1_F_IC003" geometry={nodes.M_UMF_1_F_IC003.geometry} material={nodes.M_UMF_1_F_IC003.material} position={[2.805, -0.953, 0.032]}>
          <mesh name="M_UMF_4_PNT_H" geometry={nodes.M_UMF_4_PNT_H.geometry} material={nodes.M_UMF_4_PNT_H.material} position={[-1.3, -2.633, 1.539]} />
          <mesh name="M_UMF_4_PNT_V" geometry={nodes.M_UMF_4_PNT_V.geometry} material={nodes.M_UMF_4_PNT_V.material} position={[-1.964, -1.774, 2.203]} />
        </mesh>
        <mesh name="M_UMF_1_F_IC_A003" geometry={nodes.M_UMF_1_F_IC_A003.geometry} material={nodes.M_UMF_1_F_IC_A003.material} position={[2.802, 0.853, 0.021]} />
        <mesh name="M_UMF_1_F_IC_B003" geometry={nodes.M_UMF_1_F_IC_B003.geometry} material={nodes.M_UMF_1_F_IC_B003.material} position={[2.802, 0.853, 0.021]} />
        <mesh name="M_UMF_1_F_IC_C003" geometry={nodes.M_UMF_1_F_IC_C003.geometry} material={nodes.M_UMF_1_F_IC_C003.material} position={[2.802, -0.443, 0.021]} />
        <mesh name="M_UMF_4" geometry={nodes.M_UMF_4.geometry} material={nodes.M_UMF_4.material} position={[0, -1.601, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMF_4.glb')
