/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMG_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMG_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMG_5obj" scale={1.052}>
        <mesh name="M_UMG_1_F008" geometry={nodes.M_UMG_1_F008.geometry} material={nodes.M_UMG_1_F008.material} position={[2.994, 3.497, 1.442]}>
          <mesh name="M_UMG_5_PNT" geometry={nodes.M_UMG_5_PNT.geometry} material={nodes.M_UMG_5_PNT.material} position={[-2.994, -2.451, 0.172]} />
        </mesh>
        <mesh name="M_UMG_1_F009" geometry={nodes.M_UMG_1_F009.geometry} material={nodes.M_UMG_1_F009.material} position={[2.99, -0.022, 1.44]}>
          <mesh name="M_UMG_5_PNT001" geometry={nodes.M_UMG_5_PNT001.geometry} material={nodes.M_UMG_5_PNT001.material} position={[-2.99, -2.483, 0.174]} />
        </mesh>
        <mesh name="M_UMG_1_F_A008" geometry={nodes.M_UMG_1_F_A008.geometry} material={nodes.M_UMG_1_F_A008.material} position={[2.994, 3.497, 1.442]} />
        <mesh name="M_UMG_1_F_A009" geometry={nodes.M_UMG_1_F_A009.geometry} material={nodes.M_UMG_1_F_A009.material} position={[2.99, -0.022, 1.44]} />
        <mesh name="M_UMG_1_F_B008" geometry={nodes.M_UMG_1_F_B008.geometry} material={nodes.M_UMG_1_F_B008.material} position={[2.994, 3.497, 1.442]} />
        <mesh name="M_UMG_1_F_B009" geometry={nodes.M_UMG_1_F_B009.geometry} material={nodes.M_UMG_1_F_B009.material} position={[2.99, -0.022, 1.44]} />
        <mesh name="M_UMG_1_F_C008" geometry={nodes.M_UMG_1_F_C008.geometry} material={nodes.M_UMG_1_F_C008.material} position={[2.994, 3.497, 1.442]} />
        <mesh name="M_UMG_1_F_C009" geometry={nodes.M_UMG_1_F_C009.geometry} material={nodes.M_UMG_1_F_C009.material} position={[2.99, -0.022, 1.44]} />
        <mesh name="M_UMG_5" geometry={nodes.M_UMG_5.geometry} material={nodes.M_UMG_5.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMG_5.glb')
