/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMG_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMG_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMG_3obj" scale={1.052}>
        <mesh name="M_UMG_1_F004" geometry={nodes.M_UMG_1_F004.geometry} material={nodes.M_UMG_1_F004.material} position={[2.993, 2.992, 1.44]}>
          <mesh name="M_UMG_3_PNT001" geometry={nodes.M_UMG_3_PNT001.geometry} material={nodes.M_UMG_3_PNT001.material} position={[-2.993, -1.946, 0.174]} />
        </mesh>
        <mesh name="M_UMG_1_F005" geometry={nodes.M_UMG_1_F005.geometry} material={nodes.M_UMG_1_F005.material} position={[2.993, -0.022, 1.441]}>
          <mesh name="M_UMG_3_PNT" geometry={nodes.M_UMG_3_PNT.geometry} material={nodes.M_UMG_3_PNT.material} position={[-2.993, -1.956, 0.173]} />
        </mesh>
        <mesh name="M_UMG_1_F_A004" geometry={nodes.M_UMG_1_F_A004.geometry} material={nodes.M_UMG_1_F_A004.material} position={[2.993, 2.992, 1.44]} />
        <mesh name="M_UMG_1_F_A005" geometry={nodes.M_UMG_1_F_A005.geometry} material={nodes.M_UMG_1_F_A005.material} position={[2.993, -0.022, 1.441]} />
        <mesh name="M_UMG_1_F_B004" geometry={nodes.M_UMG_1_F_B004.geometry} material={nodes.M_UMG_1_F_B004.material} position={[2.993, 2.992, 1.44]} />
        <mesh name="M_UMG_1_F_B005" geometry={nodes.M_UMG_1_F_B005.geometry} material={nodes.M_UMG_1_F_B005.material} position={[2.993, -0.022, 1.441]} />
        <mesh name="M_UMG_1_F_C004" geometry={nodes.M_UMG_1_F_C004.geometry} material={nodes.M_UMG_1_F_C004.material} position={[2.993, 2.992, 1.44]} />
        <mesh name="M_UMG_1_F_C005" geometry={nodes.M_UMG_1_F_C005.geometry} material={nodes.M_UMG_1_F_C005.material} position={[2.993, -0.022, 1.441]} />
        <mesh name="M_UMG_3" geometry={nodes.M_UMG_3.geometry} material={nodes.M_UMG_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMG_3.glb')
