/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMG_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMG_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMG_1obj" scale={1.052}>
        <mesh name="M_UMG_1" geometry={nodes.M_UMG_1.geometry} material={nodes.M_UMG_1.material} />
        <mesh name="M_UMG_1_F" geometry={nodes.M_UMG_1_F.geometry} material={nodes.M_UMG_1_F.material} position={[2.995, 2.492, 1.442]}>
          <mesh name="M_UMG_1_PNT" geometry={nodes.M_UMG_1_PNT.geometry} material={nodes.M_UMG_1_PNT.material} position={[-2.995, -1.446, 0.171]} />
        </mesh>
        <mesh name="M_UMG_1_F001" geometry={nodes.M_UMG_1_F001.geometry} material={nodes.M_UMG_1_F001.material} position={[2.993, -0.022, 1.441]}>
          <mesh name="M_UMG_1_PNT001" geometry={nodes.M_UMG_1_PNT001.geometry} material={nodes.M_UMG_1_PNT001.material} position={[-2.993, -1.451, 0.173]} />
        </mesh>
        <mesh name="M_UMG_1_F_A" geometry={nodes.M_UMG_1_F_A.geometry} material={nodes.M_UMG_1_F_A.material} position={[2.995, 2.492, 1.442]} />
        <mesh name="M_UMG_1_F_A001" geometry={nodes.M_UMG_1_F_A001.geometry} material={nodes.M_UMG_1_F_A001.material} position={[2.988, -0.061, 1.435]} />
        <mesh name="M_UMG_1_F_B" geometry={nodes.M_UMG_1_F_B.geometry} material={nodes.M_UMG_1_F_B.material} position={[2.995, 2.492, 1.442]} />
        <mesh name="M_UMG_1_F_B001" geometry={nodes.M_UMG_1_F_B001.geometry} material={nodes.M_UMG_1_F_B001.material} position={[2.993, -0.022, 1.441]} />
        <mesh name="M_UMG_1_F_C" geometry={nodes.M_UMG_1_F_C.geometry} material={nodes.M_UMG_1_F_C.material} position={[2.995, 2.492, 1.442]} />
        <mesh name="M_UMG_1_F_C001" geometry={nodes.M_UMG_1_F_C001.geometry} material={nodes.M_UMG_1_F_C001.material} position={[2.993, -0.022, 1.441]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMG_1.glb')
