/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMG_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMG_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMG_6obj" scale={1.052}>
        <mesh name="M_UMG_1_F010" geometry={nodes.M_UMG_1_F010.geometry} material={nodes.M_UMG_1_F010.material} position={[2.992, 3.738, 1.441]}>
          <mesh name="M_UMG_6_PNT" geometry={nodes.M_UMG_6_PNT.geometry} material={nodes.M_UMG_6_PNT.material} position={[-2.992, -2.692, 0.173]} rotation={[Math.PI / 2, 0.001, 0.001]} />
        </mesh>
        <mesh name="M_UMG_1_F011" geometry={nodes.M_UMG_1_F011.geometry} material={nodes.M_UMG_1_F011.material} position={[2.99, -0.022, 1.44]}>
          <mesh name="M_UMG_6_PNT001" geometry={nodes.M_UMG_6_PNT001.geometry} material={nodes.M_UMG_6_PNT001.material} position={[-2.99, -2.709, 0.174]} rotation={[Math.PI / 2, 0.001, 0.001]} />
        </mesh>
        <mesh name="M_UMG_1_F_A010" geometry={nodes.M_UMG_1_F_A010.geometry} material={nodes.M_UMG_1_F_A010.material} position={[2.992, 3.738, 1.441]} />
        <mesh name="M_UMG_1_F_A011" geometry={nodes.M_UMG_1_F_A011.geometry} material={nodes.M_UMG_1_F_A011.material} position={[2.99, -0.022, 1.44]} />
        <mesh name="M_UMG_1_F_B010" geometry={nodes.M_UMG_1_F_B010.geometry} material={nodes.M_UMG_1_F_B010.material} position={[2.992, 3.738, 1.441]} />
        <mesh name="M_UMG_1_F_B011" geometry={nodes.M_UMG_1_F_B011.geometry} material={nodes.M_UMG_1_F_B011.material} position={[2.99, -0.022, 1.44]} />
        <mesh name="M_UMG_1_F_C010" geometry={nodes.M_UMG_1_F_C010.geometry} material={nodes.M_UMG_1_F_C010.material} position={[2.992, 3.738, 1.441]} />
        <mesh name="M_UMG_1_F_C011" geometry={nodes.M_UMG_1_F_C011.geometry} material={nodes.M_UMG_1_F_C011.material} position={[2.99, -0.022, 1.44]} />
        <mesh name="M_UMG_6" geometry={nodes.M_UMG_6.geometry} material={nodes.M_UMG_6.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMG_6.glb')
