/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMG_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMG_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMG_7obj" scale={1.052}>
        <mesh name="M_UMG_1_F012" geometry={nodes.M_UMG_1_F012.geometry} material={nodes.M_UMG_1_F012.material} position={[2.995, 4.005, 1.441]}>
          <mesh name="M_UMG_6_PNT002" geometry={nodes.M_UMG_6_PNT002.geometry} material={nodes.M_UMG_6_PNT002.material} position={[-2.995, -2.959, 0.172]} rotation={[Math.PI / 2, 0.001, 0.001]} />
        </mesh>
        <mesh name="M_UMG_1_F013" geometry={nodes.M_UMG_1_F013.geometry} material={nodes.M_UMG_1_F013.material} position={[2.994, -0.021, 1.442]}>
          <mesh name="M_UMG_6_PNT003" geometry={nodes.M_UMG_6_PNT003.geometry} material={nodes.M_UMG_6_PNT003.material} position={[-2.994, -2.97, 0.172]} rotation={[Math.PI / 2, 0.001, 0.001]} />
        </mesh>
        <mesh name="M_UMG_1_F_A012" geometry={nodes.M_UMG_1_F_A012.geometry} material={nodes.M_UMG_1_F_A012.material} position={[2.995, 4.005, 1.441]} />
        <mesh name="M_UMG_1_F_A013" geometry={nodes.M_UMG_1_F_A013.geometry} material={nodes.M_UMG_1_F_A013.material} position={[2.994, -0.021, 1.442]} />
        <mesh name="M_UMG_1_F_B012" geometry={nodes.M_UMG_1_F_B012.geometry} material={nodes.M_UMG_1_F_B012.material} position={[2.995, 4.005, 1.441]} />
        <mesh name="M_UMG_1_F_B013" geometry={nodes.M_UMG_1_F_B013.geometry} material={nodes.M_UMG_1_F_B013.material} position={[2.994, -0.021, 1.442]} />
        <mesh name="M_UMG_1_F_C012" geometry={nodes.M_UMG_1_F_C012.geometry} material={nodes.M_UMG_1_F_C012.material} position={[2.995, 4.005, 1.441]} />
        <mesh name="M_UMG_1_F_C013" geometry={nodes.M_UMG_1_F_C013.geometry} material={nodes.M_UMG_1_F_C013.material} position={[2.994, -0.021, 1.442]} />
        <mesh name="M_UMG_7" geometry={nodes.M_UMG_7.geometry} material={nodes.M_UMG_7.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMG_7.glb')
