/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMG_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMG_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMG_2obj" scale={1.052}>
        <mesh name="M_UMG_1_F002" geometry={nodes.M_UMG_1_F002.geometry} material={nodes.M_UMG_1_F002.material} position={[2.997, 2.755, 1.442]}>
          <mesh name="M_UMG_2_PNT" geometry={nodes.M_UMG_2_PNT.geometry} material={nodes.M_UMG_2_PNT.material} position={[-2.997, -1.709, 0.172]} />
        </mesh>
        <mesh name="M_UMG_1_F003" geometry={nodes.M_UMG_1_F003.geometry} material={nodes.M_UMG_1_F003.material} position={[2.996, -0.025, 1.44]}>
          <mesh name="M_UMG_2_PNT001" geometry={nodes.M_UMG_2_PNT001.geometry} material={nodes.M_UMG_2_PNT001.material} position={[-2.996, -1.712, 0.173]} />
        </mesh>
        <mesh name="M_UMG_1_F_A002" geometry={nodes.M_UMG_1_F_A002.geometry} material={nodes.M_UMG_1_F_A002.material} position={[2.997, 2.755, 1.442]} />
        <mesh name="M_UMG_1_F_A003" geometry={nodes.M_UMG_1_F_A003.geometry} material={nodes.M_UMG_1_F_A003.material} position={[2.996, -0.025, 1.44]} />
        <mesh name="M_UMG_1_F_B002" geometry={nodes.M_UMG_1_F_B002.geometry} material={nodes.M_UMG_1_F_B002.material} position={[2.997, 2.755, 1.442]} />
        <mesh name="M_UMG_1_F_B003" geometry={nodes.M_UMG_1_F_B003.geometry} material={nodes.M_UMG_1_F_B003.material} position={[2.996, -0.025, 1.44]} />
        <mesh name="M_UMG_1_F_C002" geometry={nodes.M_UMG_1_F_C002.geometry} material={nodes.M_UMG_1_F_C002.material} position={[2.997, 2.755, 1.442]} />
        <mesh name="M_UMG_1_F_C003" geometry={nodes.M_UMG_1_F_C003.geometry} material={nodes.M_UMG_1_F_C003.material} position={[2.996, -0.025, 1.44]} />
        <mesh name="M_UMG_2" geometry={nodes.M_UMG_2.geometry} material={nodes.M_UMG_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMG_2.glb')
