/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMG_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMG_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMG_4obj" scale={1.052}>
        <mesh name="M_UMG_1_F006" geometry={nodes.M_UMG_1_F006.geometry} material={nodes.M_UMG_1_F006.material} position={[2.991, 3.244, 1.442]}>
          <mesh name="M_UMG_4_PNT" geometry={nodes.M_UMG_4_PNT.geometry} material={nodes.M_UMG_4_PNT.material} position={[-2.991, -2.198, 0.172]} />
        </mesh>
        <mesh name="M_UMG_1_F007" geometry={nodes.M_UMG_1_F007.geometry} material={nodes.M_UMG_1_F007.material} position={[2.988, -0.018, 1.438]}>
          <mesh name="M_UMG_4_PNT001" geometry={nodes.M_UMG_4_PNT001.geometry} material={nodes.M_UMG_4_PNT001.material} position={[-2.988, -2.214, 0.175]} />
        </mesh>
        <mesh name="M_UMG_1_F_A006" geometry={nodes.M_UMG_1_F_A006.geometry} material={nodes.M_UMG_1_F_A006.material} position={[2.991, 3.244, 1.442]} />
        <mesh name="M_UMG_1_F_A007" geometry={nodes.M_UMG_1_F_A007.geometry} material={nodes.M_UMG_1_F_A007.material} position={[2.988, -0.018, 1.438]} />
        <mesh name="M_UMG_1_F_B006" geometry={nodes.M_UMG_1_F_B006.geometry} material={nodes.M_UMG_1_F_B006.material} position={[2.991, 3.244, 1.442]} />
        <mesh name="M_UMG_1_F_B007" geometry={nodes.M_UMG_1_F_B007.geometry} material={nodes.M_UMG_1_F_B007.material} position={[2.988, -0.018, 1.438]} />
        <mesh name="M_UMG_1_F_C006" geometry={nodes.M_UMG_1_F_C006.geometry} material={nodes.M_UMG_1_F_C006.material} position={[2.991, 3.244, 1.442]} />
        <mesh name="M_UMG_1_F_C007" geometry={nodes.M_UMG_1_F_C007.geometry} material={nodes.M_UMG_1_F_C007.material} position={[2.988, -0.018, 1.438]} />
        <mesh name="M_UMG_4" geometry={nodes.M_UMG_4.geometry} material={nodes.M_UMG_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMG_4.glb')
