/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMJ_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMJ_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMJ_6obj" scale={1.625}>
        <mesh name="M_UMJ_1_F004" geometry={nodes.M_UMJ_1_F004.geometry} material={nodes.M_UMJ_1_F004.material} position={[2.969, 2.422, 0.933]}>
          <mesh name="M_UMJ_6_PNT_1" geometry={nodes.M_UMJ_6_PNT_1.geometry} material={nodes.M_UMJ_6_PNT_1.material} position={[-2.969, -1.739, 0.111]} />
        </mesh>
        <mesh name="M_UMJ_1_F005" geometry={nodes.M_UMJ_1_F005.geometry} material={nodes.M_UMJ_1_F005.material} position={[2.97, -0.013, 0.933]}>
          <mesh name="M_UMJ_6_PNT" geometry={nodes.M_UMJ_6_PNT.geometry} material={nodes.M_UMJ_6_PNT.material} position={[-2.97, -1.753, 0.111]} />
        </mesh>
        <mesh name="M_UMJ_1_F_A004" geometry={nodes.M_UMJ_1_F_A004.geometry} material={nodes.M_UMJ_1_F_A004.material} position={[2.969, 2.422, 0.933]} />
        <mesh name="M_UMJ_1_F_A005" geometry={nodes.M_UMJ_1_F_A005.geometry} material={nodes.M_UMJ_1_F_A005.material} position={[2.97, -0.013, 0.933]} />
        <mesh name="M_UMJ_1_F_B004" geometry={nodes.M_UMJ_1_F_B004.geometry} material={nodes.M_UMJ_1_F_B004.material} position={[2.969, 2.422, 0.933]} />
        <mesh name="M_UMJ_1_F_B005" geometry={nodes.M_UMJ_1_F_B005.geometry} material={nodes.M_UMJ_1_F_B005.material} position={[2.97, -0.013, 0.933]} />
        <mesh name="M_UMJ_1_F_C004" geometry={nodes.M_UMJ_1_F_C004.geometry} material={nodes.M_UMJ_1_F_C004.material} position={[2.969, 2.422, 0.933]} />
        <mesh name="M_UMJ_1_F_C005" geometry={nodes.M_UMJ_1_F_C005.geometry} material={nodes.M_UMJ_1_F_C005.material} position={[2.97, -0.013, 0.933]} />
        <mesh name="M_UMJ_6" geometry={nodes.M_UMJ_6.geometry} material={nodes.M_UMJ_6.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMJ_6.glb')
