/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMJ_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMJ_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMJ_4obj" scale={1.388}>
        <mesh name="M_UMJ_1_F" geometry={nodes.M_UMJ_1_F.geometry} material={nodes.M_UMJ_1_F.material} position={[3.477, 2.457, 1.09]}>
          <mesh name="M_UMJ_4_PNT_1" geometry={nodes.M_UMJ_4_PNT_1.geometry} material={nodes.M_UMJ_4_PNT_1.material} position={[-3.477, -1.657, 0.133]} />
        </mesh>
        <mesh name="M_UMJ_1_F001" geometry={nodes.M_UMJ_1_F001.geometry} material={nodes.M_UMJ_1_F001.material} position={[3.477, -0.017, 1.091]}>
          <mesh name="M_UMJ_4_PNT" geometry={nodes.M_UMJ_4_PNT.geometry} material={nodes.M_UMJ_4_PNT.material} position={[-3.477, -1.666, 0.132]} />
        </mesh>
        <mesh name="M_UMJ_1_F_A" geometry={nodes.M_UMJ_1_F_A.geometry} material={nodes.M_UMJ_1_F_A.material} position={[3.477, 2.457, 1.09]} />
        <mesh name="M_UMJ_1_F_A001" geometry={nodes.M_UMJ_1_F_A001.geometry} material={nodes.M_UMJ_1_F_A001.material} position={[3.477, -0.017, 1.091]} />
        <mesh name="M_UMJ_1_F_B" geometry={nodes.M_UMJ_1_F_B.geometry} material={nodes.M_UMJ_1_F_B.material} position={[3.477, 2.457, 1.09]} />
        <mesh name="M_UMJ_1_F_B001" geometry={nodes.M_UMJ_1_F_B001.geometry} material={nodes.M_UMJ_1_F_B001.material} position={[3.477, -0.017, 1.091]} />
        <mesh name="M_UMJ_1_F_C" geometry={nodes.M_UMJ_1_F_C.geometry} material={nodes.M_UMJ_1_F_C.material} position={[3.477, 2.457, 1.09]} />
        <mesh name="M_UMJ_1_F_C001" geometry={nodes.M_UMJ_1_F_C001.geometry} material={nodes.M_UMJ_1_F_C001.material} position={[3.477, -0.017, 1.091]} />
        <mesh name="M_UMJ_4" geometry={nodes.M_UMJ_4.geometry} material={nodes.M_UMJ_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMJ_4.glb')
