/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMJ_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMJ_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMJ_3obj" scale={1.274}>
        <mesh name="M_UMJ_1_F012" geometry={nodes.M_UMJ_1_F012.geometry} material={nodes.M_UMJ_1_F012.material} position={[3.789, 2.471, 1.192]}>
          <mesh name="M_UMJ_2_PNT_1001" geometry={nodes.M_UMJ_2_PNT_1001.geometry} material={nodes.M_UMJ_2_PNT_1001.material} position={[-3.79, -1.6, 0.14]} />
        </mesh>
        <mesh name="M_UMJ_1_F013" geometry={nodes.M_UMJ_1_F013.geometry} material={nodes.M_UMJ_1_F013.material} position={[3.788, -0.019, 1.189]}>
          <mesh name="M_UMJ_2_PNT001" geometry={nodes.M_UMJ_2_PNT001.geometry} material={nodes.M_UMJ_2_PNT001.material} position={[-3.789, -1.617, 0.144]} />
        </mesh>
        <mesh name="M_UMJ_1_F_A012" geometry={nodes.M_UMJ_1_F_A012.geometry} material={nodes.M_UMJ_1_F_A012.material} position={[3.789, 2.471, 1.192]} />
        <mesh name="M_UMJ_1_F_A013" geometry={nodes.M_UMJ_1_F_A013.geometry} material={nodes.M_UMJ_1_F_A013.material} position={[3.788, -0.019, 1.189]} />
        <mesh name="M_UMJ_1_F_B012" geometry={nodes.M_UMJ_1_F_B012.geometry} material={nodes.M_UMJ_1_F_B012.material} position={[3.789, 2.471, 1.192]} />
        <mesh name="M_UMJ_1_F_B013" geometry={nodes.M_UMJ_1_F_B013.geometry} material={nodes.M_UMJ_1_F_B013.material} position={[3.788, -0.019, 1.189]} />
        <mesh name="M_UMJ_1_F_C012" geometry={nodes.M_UMJ_1_F_C012.geometry} material={nodes.M_UMJ_1_F_C012.material} position={[3.789, 2.471, 1.192]} />
        <mesh name="M_UMJ_1_F_C013" geometry={nodes.M_UMJ_1_F_C013.geometry} material={nodes.M_UMJ_1_F_C013.material} position={[3.788, -0.019, 1.189]} />
        <mesh name="M_UMJ_3" geometry={nodes.M_UMJ_3.geometry} material={nodes.M_UMJ_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMJ_3.glb')
