/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMJ_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMJ_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMJ_1obj" scale={1.052}>
        <mesh name="M_UMJ_1" geometry={nodes.M_UMJ_1.geometry} material={nodes.M_UMJ_1.material} />
        <mesh name="M_UMJ_1_F008" geometry={nodes.M_UMJ_1_F008.geometry} material={nodes.M_UMJ_1_F008.material} position={[4.591, 2.49, 1.444]}>
          <mesh name="M_UMJ_1_PNT" geometry={nodes.M_UMJ_1_PNT.geometry} material={nodes.M_UMJ_1_PNT.material} position={[-4.591, -1.444, 0.17]} />
        </mesh>
        <mesh name="M_UMJ_1_F009" geometry={nodes.M_UMJ_1_F009.geometry} material={nodes.M_UMJ_1_F009.material} position={[4.589, -0.025, 1.439]}>
          <mesh name="M_UMJ_1_PNT001" geometry={nodes.M_UMJ_1_PNT001.geometry} material={nodes.M_UMJ_1_PNT001.material} position={[-4.589, -1.467, 0.175]} />
        </mesh>
        <mesh name="M_UMJ_1_F_A008" geometry={nodes.M_UMJ_1_F_A008.geometry} material={nodes.M_UMJ_1_F_A008.material} position={[4.591, 2.49, 1.444]} />
        <mesh name="M_UMJ_1_F_A009" geometry={nodes.M_UMJ_1_F_A009.geometry} material={nodes.M_UMJ_1_F_A009.material} position={[4.589, -0.025, 1.439]} />
        <mesh name="M_UMJ_1_F_B008" geometry={nodes.M_UMJ_1_F_B008.geometry} material={nodes.M_UMJ_1_F_B008.material} position={[4.591, 2.49, 1.444]} />
        <mesh name="M_UMJ_1_F_B009" geometry={nodes.M_UMJ_1_F_B009.geometry} material={nodes.M_UMJ_1_F_B009.material} position={[4.589, -0.025, 1.439]} />
        <mesh name="M_UMJ_1_F_C008" geometry={nodes.M_UMJ_1_F_C008.geometry} material={nodes.M_UMJ_1_F_C008.material} position={[4.591, 2.49, 1.444]} />
        <mesh name="M_UMJ_1_F_C009" geometry={nodes.M_UMJ_1_F_C009.geometry} material={nodes.M_UMJ_1_F_C009.material} position={[4.589, -0.025, 1.439]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMJ_1.glb')
