/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMJ_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMJ_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMJ_7obj" scale={1.735}>
        <mesh name="M_UMJ_1_F006" geometry={nodes.M_UMJ_1_F006.geometry} material={nodes.M_UMJ_1_F006.material} position={[2.782, 2.424, 0.871]}>
          <mesh name="M_UMJ_7_PNT_1" geometry={nodes.M_UMJ_7_PNT_1.geometry} material={nodes.M_UMJ_7_PNT_1.material} position={[-2.782, -1.784, 0.107]} />
        </mesh>
        <mesh name="M_UMJ_1_F007" geometry={nodes.M_UMJ_1_F007.geometry} material={nodes.M_UMJ_1_F007.material} position={[2.781, -0.018, 0.871]}>
          <mesh name="M_UMJ_7_PNT" geometry={nodes.M_UMJ_7_PNT.geometry} material={nodes.M_UMJ_7_PNT.material} position={[-2.782, -1.797, 0.107]} />
        </mesh>
        <mesh name="M_UMJ_1_F_A006" geometry={nodes.M_UMJ_1_F_A006.geometry} material={nodes.M_UMJ_1_F_A006.material} position={[2.782, 2.424, 0.871]} />
        <mesh name="M_UMJ_1_F_A007" geometry={nodes.M_UMJ_1_F_A007.geometry} material={nodes.M_UMJ_1_F_A007.material} position={[2.781, -0.018, 0.871]} />
        <mesh name="M_UMJ_1_F_B006" geometry={nodes.M_UMJ_1_F_B006.geometry} material={nodes.M_UMJ_1_F_B006.material} position={[2.782, 2.424, 0.871]} />
        <mesh name="M_UMJ_1_F_B007" geometry={nodes.M_UMJ_1_F_B007.geometry} material={nodes.M_UMJ_1_F_B007.material} position={[2.781, -0.018, 0.871]} />
        <mesh name="M_UMJ_1_F_C006" geometry={nodes.M_UMJ_1_F_C006.geometry} material={nodes.M_UMJ_1_F_C006.material} position={[2.782, 2.424, 0.871]} />
        <mesh name="M_UMJ_1_F_C007" geometry={nodes.M_UMJ_1_F_C007.geometry} material={nodes.M_UMJ_1_F_C007.material} position={[2.781, -0.018, 0.871]} />
        <mesh name="M_UMJ_7" geometry={nodes.M_UMJ_7.geometry} material={nodes.M_UMJ_7.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMJ_7.glb')
