/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMJ_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMJ_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMJ_2obj" scale={1.16}>
        <mesh name="M_UMJ_1_F010" geometry={nodes.M_UMJ_1_F010.geometry} material={nodes.M_UMJ_1_F010.material} position={[4.162, 2.48, 1.306]}>
          <mesh name="M_UMJ_2_PNT_1" geometry={nodes.M_UMJ_2_PNT_1.geometry} material={nodes.M_UMJ_2_PNT_1.material} position={[-4.163, -1.523, 0.157]} />
        </mesh>
        <mesh name="M_UMJ_1_F011" geometry={nodes.M_UMJ_1_F011.geometry} material={nodes.M_UMJ_1_F011.material} position={[4.161, -0.022, 1.305]}>
          <mesh name="M_UMJ_2_PNT" geometry={nodes.M_UMJ_2_PNT.geometry} material={nodes.M_UMJ_2_PNT.material} position={[-4.162, -1.55, 0.158]} />
        </mesh>
        <mesh name="M_UMJ_1_F_A010" geometry={nodes.M_UMJ_1_F_A010.geometry} material={nodes.M_UMJ_1_F_A010.material} position={[4.162, 2.48, 1.306]} />
        <mesh name="M_UMJ_1_F_A011" geometry={nodes.M_UMJ_1_F_A011.geometry} material={nodes.M_UMJ_1_F_A011.material} position={[4.161, -0.022, 1.305]} />
        <mesh name="M_UMJ_1_F_B010" geometry={nodes.M_UMJ_1_F_B010.geometry} material={nodes.M_UMJ_1_F_B010.material} position={[4.162, 2.48, 1.306]} />
        <mesh name="M_UMJ_1_F_B011" geometry={nodes.M_UMJ_1_F_B011.geometry} material={nodes.M_UMJ_1_F_B011.material} position={[4.161, -0.022, 1.305]} />
        <mesh name="M_UMJ_1_F_C010" geometry={nodes.M_UMJ_1_F_C010.geometry} material={nodes.M_UMJ_1_F_C010.material} position={[4.162, 2.48, 1.306]} />
        <mesh name="M_UMJ_1_F_C011" geometry={nodes.M_UMJ_1_F_C011.geometry} material={nodes.M_UMJ_1_F_C011.material} position={[4.161, -0.022, 1.305]} />
        <mesh name="M_UMJ_2" geometry={nodes.M_UMJ_2.geometry} material={nodes.M_UMJ_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMJ_2.glb')
