/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMJ_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMJ_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMJ_5obj" scale={1.508}>
        <mesh name="M_UMJ_1_F002" geometry={nodes.M_UMJ_1_F002.geometry} material={nodes.M_UMJ_1_F002.material} position={[3.196, 2.439, 1.003]}>
          <mesh name="M_UMJ_5_PNT_1" geometry={nodes.M_UMJ_5_PNT_1.geometry} material={nodes.M_UMJ_5_PNT_1.material} position={[-3.197, -1.703, 0.123]} />
        </mesh>
        <mesh name="M_UMJ_1_F003" geometry={nodes.M_UMJ_1_F003.geometry} material={nodes.M_UMJ_1_F003.material} position={[3.199, -0.014, 1.006]}>
          <mesh name="M_UMJ_5_PNT" geometry={nodes.M_UMJ_5_PNT.geometry} material={nodes.M_UMJ_5_PNT.material} position={[-3.2, -1.718, 0.12]} />
        </mesh>
        <mesh name="M_UMJ_1_F_A002" geometry={nodes.M_UMJ_1_F_A002.geometry} material={nodes.M_UMJ_1_F_A002.material} position={[3.196, 2.439, 1.003]} />
        <mesh name="M_UMJ_1_F_A003" geometry={nodes.M_UMJ_1_F_A003.geometry} material={nodes.M_UMJ_1_F_A003.material} position={[3.199, -0.014, 1.006]} />
        <mesh name="M_UMJ_1_F_B002" geometry={nodes.M_UMJ_1_F_B002.geometry} material={nodes.M_UMJ_1_F_B002.material} position={[3.196, 2.439, 1.003]} />
        <mesh name="M_UMJ_1_F_B003" geometry={nodes.M_UMJ_1_F_B003.geometry} material={nodes.M_UMJ_1_F_B003.material} position={[3.199, -0.014, 1.006]} />
        <mesh name="M_UMJ_1_F_C002" geometry={nodes.M_UMJ_1_F_C002.geometry} material={nodes.M_UMJ_1_F_C002.material} position={[3.196, 2.439, 1.003]} />
        <mesh name="M_UMJ_1_F_C003" geometry={nodes.M_UMJ_1_F_C003.geometry} material={nodes.M_UMJ_1_F_C003.material} position={[3.199, -0.014, 1.006]} />
        <mesh name="M_UMJ_5" geometry={nodes.M_UMJ_5.geometry} material={nodes.M_UMJ_5.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMJ_5.glb')
