/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_2YNSD_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_2YNSD_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_2YNSD_7_NNobj" scale={1.142}>
        <mesh name="Legs004" geometry={nodes.Legs004.geometry} material={nodes.Legs004.material} position={[0.2, -2.869, -0.212]} />
        <mesh name="M_2YNSD_1_F010" geometry={nodes.M_2YNSD_1_F010.geometry} material={nodes.M_2YNSD_1_F010.material} position={[2.764, 1.125, 2.625]}>
          <mesh name="M_2YNSD_7_PNT_1" geometry={nodes.M_2YNSD_7_PNT_1.geometry} material={nodes.M_2YNSD_7_PNT_1.material} position={[-2.764, 1.797, 0.156]} />
        </mesh>
        <mesh name="M_2YNSD_1_F011" geometry={nodes.M_2YNSD_1_F011.geometry} material={nodes.M_2YNSD_1_F011.material} position={[2.764, -2.255, 2.625]}>
          <mesh name="M_2YNSD_7_PNT_2" geometry={nodes.M_2YNSD_7_PNT_2.geometry} material={nodes.M_2YNSD_7_PNT_2.material} position={[-2.764, 1.787, 0.156]} />
        </mesh>
        <mesh name="M_2YNSD_1_F_A010" geometry={nodes.M_2YNSD_1_F_A010.geometry} material={nodes.M_2YNSD_1_F_A010.material} position={[2.761, 2.794, 2.615]} />
        <mesh name="M_2YNSD_1_F_A011" geometry={nodes.M_2YNSD_1_F_A011.geometry} material={nodes.M_2YNSD_1_F_A011.material} position={[2.761, -0.586, 2.615]} />
        <mesh name="M_2YNSD_1_F_B010" geometry={nodes.M_2YNSD_1_F_B010.geometry} material={nodes.M_2YNSD_1_F_B010.material} position={[2.761, 2.794, 2.615]} />
        <mesh name="M_2YNSD_1_F_B011" geometry={nodes.M_2YNSD_1_F_B011.geometry} material={nodes.M_2YNSD_1_F_B011.material} position={[2.761, -0.585, 2.615]} />
        <mesh name="M_2YNSD_1_F_C010" geometry={nodes.M_2YNSD_1_F_C010.geometry} material={nodes.M_2YNSD_1_F_C010.material} position={[2.761, 1.596, 2.615]} />
        <mesh name="M_2YNSD_1_F_C011" geometry={nodes.M_2YNSD_1_F_C011.geometry} material={nodes.M_2YNSD_1_F_C011.material} position={[2.761, -1.784, 2.615]} />
        <mesh name="M_2YNSD_7" geometry={nodes.M_2YNSD_7.geometry} material={materials['wire_153228184.021']} />
        <mesh name="M_2YNSD_7_F_7" geometry={nodes.M_2YNSD_7_F_7.geometry} material={materials['wire_153228184.021']} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_2YNSD_7.glb')
