/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_2YNSD_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_2YNSD_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_2YNSD_5_NNobj" scale={1.141}>
        <mesh name="Legs001" geometry={nodes.Legs001.geometry} material={nodes.Legs001.material} position={[0.199, -2.859, -0.211]} />
        <mesh name="M_2YNSD_1_F006" geometry={nodes.M_2YNSD_1_F006.geometry} material={nodes.M_2YNSD_1_F006.material} position={[2.285, 1.121, 2.616]}>
          <mesh name="M_2YNSD_5_PNT_1" geometry={nodes.M_2YNSD_5_PNT_1.geometry} material={nodes.M_2YNSD_5_PNT_1.material} position={[-2.285, 1.791, 0.155]} />
        </mesh>
        <mesh name="M_2YNSD_1_F007" geometry={nodes.M_2YNSD_1_F007.geometry} material={nodes.M_2YNSD_1_F007.material} position={[2.285, -2.247, 2.616]}>
          <mesh name="M_2YNSD_5_PNT_2" geometry={nodes.M_2YNSD_5_PNT_2.geometry} material={nodes.M_2YNSD_5_PNT_2.material} position={[-2.285, 1.78, 0.155]} />
        </mesh>
        <mesh name="M_2YNSD_1_F_A006" geometry={nodes.M_2YNSD_1_F_A006.geometry} material={nodes.M_2YNSD_1_F_A006.material} position={[2.282, 2.784, 2.606]} />
        <mesh name="M_2YNSD_1_F_A007" geometry={nodes.M_2YNSD_1_F_A007.geometry} material={nodes.M_2YNSD_1_F_A007.material} position={[2.282, -0.584, 2.606]} />
        <mesh name="M_2YNSD_1_F_B006" geometry={nodes.M_2YNSD_1_F_B006.geometry} material={nodes.M_2YNSD_1_F_B006.material} position={[2.282, 2.784, 2.606]} />
        <mesh name="M_2YNSD_1_F_B007" geometry={nodes.M_2YNSD_1_F_B007.geometry} material={nodes.M_2YNSD_1_F_B007.material} position={[2.282, -0.583, 2.606]} />
        <mesh name="M_2YNSD_1_F_C006" geometry={nodes.M_2YNSD_1_F_C006.geometry} material={nodes.M_2YNSD_1_F_C006.material} position={[2.282, 1.591, 2.606]} />
        <mesh name="M_2YNSD_1_F_C007" geometry={nodes.M_2YNSD_1_F_C007.geometry} material={nodes.M_2YNSD_1_F_C007.material} position={[2.282, -1.777, 2.606]} />
        <mesh name="M_2YNSD_5" geometry={nodes.M_2YNSD_5.geometry} material={materials['wire_153228184.002']} />
        <mesh name="M_2YNSD_5_F_5" geometry={nodes.M_2YNSD_5_F_5.geometry} material={materials['wire_153228184.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_2YNSD_5.glb')
