/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_2YNSD_9.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_2YNSD_9.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_2YNSD_9_NNobj" scale={1.141}>
        <mesh name="Legs009" geometry={nodes.Legs009.geometry} material={nodes.Legs009.material} position={[0.2, -2.864, -0.211]} />
        <mesh name="M_2YNSD_1_F014" geometry={nodes.M_2YNSD_1_F014.geometry} material={nodes.M_2YNSD_1_F014.material} position={[3.223, 1.123, 2.621]}>
          <mesh name="M_2YNSD_9_PNT_1" geometry={nodes.M_2YNSD_9_PNT_1.geometry} material={nodes.M_2YNSD_9_PNT_1.material} position={[-3.223, 1.794, 0.155]} />
        </mesh>
        <mesh name="M_2YNSD_1_F015" geometry={nodes.M_2YNSD_1_F015.geometry} material={nodes.M_2YNSD_1_F015.material} position={[3.223, -2.251, 2.621]}>
          <mesh name="M_2YNSD_9_PNT_2" geometry={nodes.M_2YNSD_9_PNT_2.geometry} material={nodes.M_2YNSD_9_PNT_2.material} position={[-3.223, 1.783, 0.155]} />
        </mesh>
        <mesh name="M_2YNSD_1_F_A014" geometry={nodes.M_2YNSD_1_F_A014.geometry} material={nodes.M_2YNSD_1_F_A014.material} position={[3.219, 2.789, 2.611]} />
        <mesh name="M_2YNSD_1_F_A015" geometry={nodes.M_2YNSD_1_F_A015.geometry} material={nodes.M_2YNSD_1_F_A015.material} position={[3.219, -0.585, 2.611]} />
        <mesh name="M_2YNSD_1_F_B014" geometry={nodes.M_2YNSD_1_F_B014.geometry} material={nodes.M_2YNSD_1_F_B014.material} position={[3.219, 2.789, 2.611]} />
        <mesh name="M_2YNSD_1_F_B015" geometry={nodes.M_2YNSD_1_F_B015.geometry} material={nodes.M_2YNSD_1_F_B015.material} position={[3.219, -0.584, 2.611]} />
        <mesh name="M_2YNSD_1_F_C014" geometry={nodes.M_2YNSD_1_F_C014.geometry} material={nodes.M_2YNSD_1_F_C014.material} position={[3.219, 1.593, 2.611]} />
        <mesh name="M_2YNSD_1_F_C015" geometry={nodes.M_2YNSD_1_F_C015.geometry} material={nodes.M_2YNSD_1_F_C015.material} position={[3.219, -1.781, 2.611]} />
        <mesh name="M_2YNSD_9" geometry={nodes.M_2YNSD_9.geometry} material={materials['wire_153228184.007']} />
        <mesh name="M_2YNSD_9_F_9" geometry={nodes.M_2YNSD_9_F_9.geometry} material={materials['wire_153228184.007']} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_2YNSD_9.glb')
