/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_2YNSD_11.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_2YNSD_11.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_2YNSD_11_NNobj" scale={1.14}>
        <mesh name="Legs011" geometry={nodes.Legs011.geometry} material={nodes.Legs011.material} position={[0.198, -2.847, -0.188]} />
        <mesh name="M_2YNSD_11" geometry={nodes.M_2YNSD_11.geometry} material={materials['wire_153228184.025']} />
        <mesh name="M_2YNSD_11_F_11" geometry={nodes.M_2YNSD_11_F_11.geometry} material={materials['wire_153228184.025']} />
        <mesh name="M_2YNSD_1_F018" geometry={nodes.M_2YNSD_1_F018.geometry} material={nodes.M_2YNSD_1_F018.material} position={[3.657, 1.116, 2.332]}>
          <mesh name="M_2YNSD_11_PNT_1" geometry={nodes.M_2YNSD_11_PNT_1.geometry} material={nodes.M_2YNSD_11_PNT_1.material} position={[-3.657, 1.783, 0.138]} />
        </mesh>
        <mesh name="M_2YNSD_1_F019" geometry={nodes.M_2YNSD_1_F019.geometry} material={nodes.M_2YNSD_1_F019.material} position={[3.657, -2.238, 2.332]}>
          <mesh name="M_2YNSD_11_PNT_2" geometry={nodes.M_2YNSD_11_PNT_2.geometry} material={nodes.M_2YNSD_11_PNT_2.material} position={[-3.657, 1.773, 0.138]} />
        </mesh>
        <mesh name="M_2YNSD_1_F_A018" geometry={nodes.M_2YNSD_1_F_A018.geometry} material={nodes.M_2YNSD_1_F_A018.material} position={[3.654, 2.773, 2.323]} />
        <mesh name="M_2YNSD_1_F_A019" geometry={nodes.M_2YNSD_1_F_A019.geometry} material={nodes.M_2YNSD_1_F_A019.material} position={[3.654, -0.581, 2.323]} />
        <mesh name="M_2YNSD_1_F_B018" geometry={nodes.M_2YNSD_1_F_B018.geometry} material={nodes.M_2YNSD_1_F_B018.material} position={[3.654, 2.773, 2.323]} />
        <mesh name="M_2YNSD_1_F_B019" geometry={nodes.M_2YNSD_1_F_B019.geometry} material={nodes.M_2YNSD_1_F_B019.material} position={[3.654, -0.581, 2.323]} />
        <mesh name="M_2YNSD_1_F_C018" geometry={nodes.M_2YNSD_1_F_C018.geometry} material={nodes.M_2YNSD_1_F_C018.material} position={[3.654, 1.584, 2.323]} />
        <mesh name="M_2YNSD_1_F_C019" geometry={nodes.M_2YNSD_1_F_C019.geometry} material={nodes.M_2YNSD_1_F_C019.material} position={[3.654, -1.77, 2.323]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_2YNSD_11.glb')
