/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_2YNSD_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_2YNSD_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_2YNSD_1_NNobj" scale={1.049}>
        <mesh name="Legs012" geometry={nodes.Legs012.geometry} material={nodes.Legs012.material} />
        <mesh name="M_2YNSD_1" geometry={nodes.M_2YNSD_1.geometry} material={materials['wire_153228184.026']} />
        <mesh name="M_2YNSD_1_F_1" geometry={nodes.M_2YNSD_1_F_1.geometry} material={materials['wire_153228184.026']} />
        <mesh name="M_UMM_1_F" geometry={nodes.M_UMM_1_F.geometry} material={nodes.M_UMM_1_F.material}>
          <mesh name="M_2YNSD_1_PNT_1" geometry={nodes.M_2YNSD_1_PNT_1.geometry} material={nodes.M_2YNSD_1_PNT_1.material} position={[0, 3.16, 3.007]} />
        </mesh>
        <mesh name="M_UMM_1_F1" geometry={nodes.M_UMM_1_F1.geometry} material={nodes.M_UMM_1_F1.material}>
          <mesh name="M_2YNSD_1_PNT_2" geometry={nodes.M_2YNSD_1_PNT_2.geometry} material={nodes.M_2YNSD_1_PNT_2.material} position={[0, -0.507, 3.007]} />
        </mesh>
        <mesh name="M_UMM_1_F_A" geometry={nodes.M_UMM_1_F_A.geometry} material={nodes.M_UMM_1_F_A.material} />
        <mesh name="M_UMM_1_F_A1" geometry={nodes.M_UMM_1_F_A1.geometry} material={nodes.M_UMM_1_F_A1.material} />
        <mesh name="M_UMM_1_F_B" geometry={nodes.M_UMM_1_F_B.geometry} material={nodes.M_UMM_1_F_B.material} />
        <mesh name="M_UMM_1_F_B1" geometry={nodes.M_UMM_1_F_B1.geometry} material={nodes.M_UMM_1_F_B1.material} />
        <mesh name="M_UMM_1_F_C" geometry={nodes.M_UMM_1_F_C.geometry} material={nodes.M_UMM_1_F_C.material} />
        <mesh name="M_UMM_1_F_C1" geometry={nodes.M_UMM_1_F_C1.geometry} material={nodes.M_UMM_1_F_C1.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_2YNSD_1.glb')
