/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_2YNSD_10.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_2YNSD_10.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_2YNSD_10_NNobj" scale={1.137}>
        <mesh name="Legs010" geometry={nodes.Legs010.geometry} material={nodes.Legs010.material} position={[0.199, -2.862, -0.211]} />
        <mesh name="M_2YNSD_10" geometry={nodes.M_2YNSD_10.geometry} material={materials['wire_153228184.024']} />
        <mesh name="M_2YNSD_10_F_10" geometry={nodes.M_2YNSD_10_F_10.geometry} material={materials['wire_153228184.024']} />
        <mesh name="M_2YNSD_1_F016" geometry={nodes.M_2YNSD_1_F016.geometry} material={nodes.M_2YNSD_1_F016.material} position={[3.448, 1.122, 2.618]}>
          <mesh name="M_2YNSD_10_PNT_1" geometry={nodes.M_2YNSD_10_PNT_1.geometry} material={nodes.M_2YNSD_10_PNT_1.material} position={[-3.448, 1.792, 0.155]} />
        </mesh>
        <mesh name="M_2YNSD_1_F017" geometry={nodes.M_2YNSD_1_F017.geometry} material={nodes.M_2YNSD_1_F017.material} position={[3.448, -2.249, 2.618]}>
          <mesh name="M_2YNSD_10_PNT_2" geometry={nodes.M_2YNSD_10_PNT_2.geometry} material={nodes.M_2YNSD_10_PNT_2.material} position={[-3.448, 1.782, 0.155]} />
        </mesh>
        <mesh name="M_2YNSD_1_F_A016" geometry={nodes.M_2YNSD_1_F_A016.geometry} material={nodes.M_2YNSD_1_F_A016.material} position={[3.445, 2.787, 2.608]} />
        <mesh name="M_2YNSD_1_F_A017" geometry={nodes.M_2YNSD_1_F_A017.geometry} material={nodes.M_2YNSD_1_F_A017.material} position={[3.445, -0.584, 2.608]} />
        <mesh name="M_2YNSD_1_F_B016" geometry={nodes.M_2YNSD_1_F_B016.geometry} material={nodes.M_2YNSD_1_F_B016.material} position={[3.445, 2.787, 2.608]} />
        <mesh name="M_2YNSD_1_F_B017" geometry={nodes.M_2YNSD_1_F_B017.geometry} material={nodes.M_2YNSD_1_F_B017.material} position={[3.445, -0.584, 2.608]} />
        <mesh name="M_2YNSD_1_F_C016" geometry={nodes.M_2YNSD_1_F_C016.geometry} material={nodes.M_2YNSD_1_F_C016.material} position={[3.445, 1.592, 2.608]} />
        <mesh name="M_2YNSD_1_F_C017" geometry={nodes.M_2YNSD_1_F_C017.geometry} material={nodes.M_2YNSD_1_F_C017.material} position={[3.445, -1.779, 2.608]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_2YNSD_10.glb')
