/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_2YNSD_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_2YNSD_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_2YNSD_4_NNobj" scale={1.142}>
        <mesh name="Legs007" geometry={nodes.Legs007.geometry} material={nodes.Legs007.material} position={[0.2, -2.863, -0.211]} />
        <mesh name="M_2YNSD_1_F004" geometry={nodes.M_2YNSD_1_F004.geometry} material={nodes.M_2YNSD_1_F004.material} position={[2.067, 1.122, 2.62]}>
          <mesh name="M_2YNSD_4_PNT_1" geometry={nodes.M_2YNSD_4_PNT_1.geometry} material={nodes.M_2YNSD_4_PNT_1.material} position={[-2.067, 1.793, 0.155]} />
        </mesh>
        <mesh name="M_2YNSD_1_F005" geometry={nodes.M_2YNSD_1_F005.geometry} material={nodes.M_2YNSD_1_F005.material} position={[2.067, -2.25, 2.62]}>
          <mesh name="M_2YNSD_4_PNT_2" geometry={nodes.M_2YNSD_4_PNT_2.geometry} material={nodes.M_2YNSD_4_PNT_2.material} position={[-2.067, 1.783, 0.155]} />
        </mesh>
        <mesh name="M_2YNSD_1_F_A004" geometry={nodes.M_2YNSD_1_F_A004.geometry} material={nodes.M_2YNSD_1_F_A004.material} position={[2.064, 2.788, 2.61]} />
        <mesh name="M_2YNSD_1_F_A005" geometry={nodes.M_2YNSD_1_F_A005.geometry} material={nodes.M_2YNSD_1_F_A005.material} position={[2.064, -0.584, 2.61]} />
        <mesh name="M_2YNSD_1_F_B004" geometry={nodes.M_2YNSD_1_F_B004.geometry} material={nodes.M_2YNSD_1_F_B004.material} position={[2.064, 2.788, 2.61]} />
        <mesh name="M_2YNSD_1_F_B005" geometry={nodes.M_2YNSD_1_F_B005.geometry} material={nodes.M_2YNSD_1_F_B005.material} position={[2.064, -0.584, 2.61]} />
        <mesh name="M_2YNSD_1_F_C004" geometry={nodes.M_2YNSD_1_F_C004.geometry} material={nodes.M_2YNSD_1_F_C004.material} position={[2.064, 1.593, 2.61]} />
        <mesh name="M_2YNSD_1_F_C005" geometry={nodes.M_2YNSD_1_F_C005.geometry} material={nodes.M_2YNSD_1_F_C005.material} position={[2.064, -1.78, 2.61]} />
        <mesh name="M_2YNSD_4" geometry={nodes.M_2YNSD_4.geometry} material={materials['wire_153228184.001']} />
        <mesh name="M_2YNSD_4_F_4" geometry={nodes.M_2YNSD_4_F_4.geometry} material={materials['wire_153228184.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_2YNSD_4.glb')
