/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_2YNSD_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_2YNSD_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_2YNSD_2_NNobj" scale={1.049}>
        <mesh name="Legs" geometry={nodes.Legs.geometry} material={nodes.Legs.material} position={[-0.034, -3.103, -0.278]} />
        <mesh name="M_2YNSD_1_F" geometry={nodes.M_2YNSD_1_F.geometry} material={nodes.M_2YNSD_1_F.material} position={[1.724, 1.216, 2.789]}>
          <mesh name="M_2YNSD_2_PNT_1" geometry={nodes.M_2YNSD_2_PNT_1.geometry} material={nodes.M_2YNSD_2_PNT_1.material} position={[-1.738, 1.94, 0.168]} />
        </mesh>
        <mesh name="M_2YNSD_1_F1" geometry={nodes.M_2YNSD_1_F1.geometry} material={nodes.M_2YNSD_1_F1.material} position={[1.724, -2.439, 2.789]}>
          <mesh name="M_2YNSD_2_PNT_2" geometry={nodes.M_2YNSD_2_PNT_2.geometry} material={nodes.M_2YNSD_2_PNT_2.material} position={[-1.738, 1.918, 0.168]} />
        </mesh>
        <mesh name="M_2YNSD_1_F_A" geometry={nodes.M_2YNSD_1_F_A.geometry} material={nodes.M_2YNSD_1_F_A.material} position={[1.721, 3.021, 2.779]} />
        <mesh name="M_2YNSD_1_F_A1" geometry={nodes.M_2YNSD_1_F_A1.geometry} material={nodes.M_2YNSD_1_F_A1.material} position={[1.721, -0.634, 2.779]} />
        <mesh name="M_2YNSD_1_F_B" geometry={nodes.M_2YNSD_1_F_B.geometry} material={nodes.M_2YNSD_1_F_B.material} position={[1.721, 3.021, 2.779]} />
        <mesh name="M_2YNSD_1_F_B1" geometry={nodes.M_2YNSD_1_F_B1.geometry} material={nodes.M_2YNSD_1_F_B1.material} position={[1.721, -0.634, 2.779]} />
        <mesh name="M_2YNSD_1_F_C" geometry={nodes.M_2YNSD_1_F_C.geometry} material={nodes.M_2YNSD_1_F_C.material} position={[1.721, 1.725, 2.779]} />
        <mesh name="M_2YNSD_1_F_C1" geometry={nodes.M_2YNSD_1_F_C1.geometry} material={nodes.M_2YNSD_1_F_C1.material} position={[1.721, -1.93, 2.779]} />
        <mesh name="M_2YNSD_2" geometry={nodes.M_2YNSD_2.geometry} material={nodes.M_2YNSD_2.material} position={[-0.25, -0.001, -0.049]} />
        <mesh name="M_2YNSD_2_F_2" geometry={nodes.M_2YNSD_2_F_2.geometry} material={nodes.M_2YNSD_2_F_2.material} position={[0, 0.113, -0.048]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_2YNSD_2.glb')
