/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_2YNSD_8.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_2YNSD_8.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_2YNSD_8_NNobj" scale={1.142}>
        <mesh name="Legs008" geometry={nodes.Legs008.geometry} material={nodes.Legs008.material} position={[0.199, -2.857, -0.211]} />
        <mesh name="M_2YNSD_1_F012" geometry={nodes.M_2YNSD_1_F012.geometry} material={nodes.M_2YNSD_1_F012.material} position={[2.979, 1.12, 2.614]}>
          <mesh name="M_2YNSD_8_PNT_1" geometry={nodes.M_2YNSD_8_PNT_1.geometry} material={nodes.M_2YNSD_8_PNT_1.material} position={[-2.979, 1.79, 0.155]} />
        </mesh>
        <mesh name="M_2YNSD_1_F013" geometry={nodes.M_2YNSD_1_F013.geometry} material={nodes.M_2YNSD_1_F013.material} position={[2.979, -2.246, 2.614]}>
          <mesh name="M_2YNSD_8_PNT_2" geometry={nodes.M_2YNSD_8_PNT_2.geometry} material={nodes.M_2YNSD_8_PNT_2.material} position={[-2.979, 1.779, 0.155]} />
        </mesh>
        <mesh name="M_2YNSD_1_F_A012" geometry={nodes.M_2YNSD_1_F_A012.geometry} material={nodes.M_2YNSD_1_F_A012.material} position={[2.975, 2.783, 2.604]} />
        <mesh name="M_2YNSD_1_F_A013" geometry={nodes.M_2YNSD_1_F_A013.geometry} material={nodes.M_2YNSD_1_F_A013.material} position={[2.975, -0.583, 2.604]} />
        <mesh name="M_2YNSD_1_F_B012" geometry={nodes.M_2YNSD_1_F_B012.geometry} material={nodes.M_2YNSD_1_F_B012.material} position={[2.975, 2.783, 2.604]} />
        <mesh name="M_2YNSD_1_F_B013" geometry={nodes.M_2YNSD_1_F_B013.geometry} material={nodes.M_2YNSD_1_F_B013.material} position={[2.975, -0.583, 2.604]} />
        <mesh name="M_2YNSD_1_F_C012" geometry={nodes.M_2YNSD_1_F_C012.geometry} material={nodes.M_2YNSD_1_F_C012.material} position={[2.975, 1.59, 2.604]} />
        <mesh name="M_2YNSD_1_F_C013" geometry={nodes.M_2YNSD_1_F_C013.geometry} material={nodes.M_2YNSD_1_F_C013.material} position={[2.975, -1.776, 2.604]} />
        <mesh name="M_2YNSD_8" geometry={nodes.M_2YNSD_8.geometry} material={materials['wire_153228184.022']} />
        <mesh name="M_2YNSD_8_F_8" geometry={nodes.M_2YNSD_8_F_8.geometry} material={materials['wire_153228184.022']} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_2YNSD_8.glb')
