/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_2YNSD_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_2YNSD_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_2YNSD_3_NNobj" scale={1.141}>
        <mesh name="Legs003" geometry={nodes.Legs003.geometry} material={nodes.Legs003.material} position={[0.2, -2.871, -0.212]} />
        <mesh name="M_2YNSD_1_F002" geometry={nodes.M_2YNSD_1_F002.geometry} material={nodes.M_2YNSD_1_F002.material} position={[1.827, 1.126, 2.627]}>
          <mesh name="M_2YNSD_3_PNT_1" geometry={nodes.M_2YNSD_3_PNT_1.geometry} material={nodes.M_2YNSD_3_PNT_1.material} position={[-1.827, 1.799, 0.156]} />
        </mesh>
        <mesh name="M_2YNSD_1_F003" geometry={nodes.M_2YNSD_1_F003.geometry} material={nodes.M_2YNSD_1_F003.material} position={[1.827, -2.257, 2.627]}>
          <mesh name="M_2YNSD_3_PNT_2" geometry={nodes.M_2YNSD_3_PNT_2.geometry} material={nodes.M_2YNSD_3_PNT_2.material} position={[-1.827, 1.788, 0.156]} />
        </mesh>
        <mesh name="M_2YNSD_1_F_A002" geometry={nodes.M_2YNSD_1_F_A002.geometry} material={nodes.M_2YNSD_1_F_A002.material} position={[1.824, 2.797, 2.617]} />
        <mesh name="M_2YNSD_1_F_A003" geometry={nodes.M_2YNSD_1_F_A003.geometry} material={nodes.M_2YNSD_1_F_A003.material} position={[1.824, -0.586, 2.617]} />
        <mesh name="M_2YNSD_1_F_B002" geometry={nodes.M_2YNSD_1_F_B002.geometry} material={nodes.M_2YNSD_1_F_B002.material} position={[1.824, 2.797, 2.617]} />
        <mesh name="M_2YNSD_1_F_B003" geometry={nodes.M_2YNSD_1_F_B003.geometry} material={nodes.M_2YNSD_1_F_B003.material} position={[1.824, -0.586, 2.617]} />
        <mesh name="M_2YNSD_1_F_C002" geometry={nodes.M_2YNSD_1_F_C002.geometry} material={nodes.M_2YNSD_1_F_C002.material} position={[1.824, 1.597, 2.617]} />
        <mesh name="M_2YNSD_1_F_C003" geometry={nodes.M_2YNSD_1_F_C003.geometry} material={nodes.M_2YNSD_1_F_C003.material} position={[1.824, -1.785, 2.617]} />
        <mesh name="M_2YNSD_3" geometry={nodes.M_2YNSD_3.geometry} material={materials['wire_153228184.029']} />
        <mesh name="M_2YNSD_3_F_3" geometry={nodes.M_2YNSD_3_F_3.geometry} material={materials['wire_153228184.029']} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_2YNSD_3.glb')
