/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_2YNSD_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_2YNSD_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_2YNSD_6_NNobj" scale={1.142}>
        <mesh name="Legs002" geometry={nodes.Legs002.geometry} material={nodes.Legs002.material} position={[0.2, -2.872, -0.212]} />
        <mesh name="M_2YNSD_1_F008" geometry={nodes.M_2YNSD_1_F008.geometry} material={nodes.M_2YNSD_1_F008.material} position={[2.532, 1.126, 2.628]}>
          <mesh name="M_2YNSD_6_PNT_1" geometry={nodes.M_2YNSD_6_PNT_1.geometry} material={nodes.M_2YNSD_6_PNT_1.material} position={[-2.532, 1.799, 0.156]} />
        </mesh>
        <mesh name="M_2YNSD_1_F009" geometry={nodes.M_2YNSD_1_F009.geometry} material={nodes.M_2YNSD_1_F009.material} position={[2.532, -2.258, 2.628]}>
          <mesh name="M_2YNSD_6_PNT_2" geometry={nodes.M_2YNSD_6_PNT_2.geometry} material={nodes.M_2YNSD_6_PNT_2.material} position={[-2.532, 1.789, 0.156]} />
        </mesh>
        <mesh name="M_2YNSD_1_F_A008" geometry={nodes.M_2YNSD_1_F_A008.geometry} material={nodes.M_2YNSD_1_F_A008.material} position={[2.529, 2.798, 2.618]} />
        <mesh name="M_2YNSD_1_F_A009" geometry={nodes.M_2YNSD_1_F_A009.geometry} material={nodes.M_2YNSD_1_F_A009.material} position={[2.529, -0.586, 2.618]} />
        <mesh name="M_2YNSD_1_F_B008" geometry={nodes.M_2YNSD_1_F_B008.geometry} material={nodes.M_2YNSD_1_F_B008.material} position={[2.529, 2.798, 2.618]} />
        <mesh name="M_2YNSD_1_F_B009" geometry={nodes.M_2YNSD_1_F_B009.geometry} material={nodes.M_2YNSD_1_F_B009.material} position={[2.529, -0.586, 2.618]} />
        <mesh name="M_2YNSD_1_F_C008" geometry={nodes.M_2YNSD_1_F_C008.geometry} material={nodes.M_2YNSD_1_F_C008.material} position={[2.529, 1.598, 2.618]} />
        <mesh name="M_2YNSD_1_F_C009" geometry={nodes.M_2YNSD_1_F_C009.geometry} material={nodes.M_2YNSD_1_F_C009.material} position={[2.529, -1.786, 2.618]} />
        <mesh name="M_2YNSD_6" geometry={nodes.M_2YNSD_6.geometry} material={materials['wire_153228184.020']} />
        <mesh name="M_2YNSD_6_F_6" geometry={nodes.M_2YNSD_6_F_6.geometry} material={materials['wire_153228184.020']} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_2YNSD_6.glb')
