/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_CL_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_CL_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_1CL_2_NNobj" scale={1.15}>
        <mesh name="Legs008" geometry={nodes.Legs008.geometry} material={nodes.Legs008.material} position={[0.01, -3.625, -0.23]} />
        <mesh name="M_1CL_1_F012" geometry={nodes.M_1CL_1_F012.geometry} material={nodes.M_1CL_1_F012.material} position={[2.783, 0.447, 2.86]}>
          <mesh name="M_1CL_2_PNT_H" geometry={nodes.M_1CL_2_PNT_H.geometry} material={nodes.M_1CL_2_PNT_H.material} position={[-2.783, -0.447, -2.86]} />
          <mesh name="M_1CL_2_PNT_V" geometry={nodes.M_1CL_2_PNT_V.geometry} material={nodes.M_1CL_2_PNT_V.material} position={[-2.783, -0.447, -2.86]} />
        </mesh>
        <mesh name="M_1CL_1_F_A012" geometry={nodes.M_1CL_1_F_A012.geometry} material={nodes.M_1CL_1_F_A012.material} position={[2.781, 1.553, 2.851]} />
        <mesh name="M_1CL_1_F_B012" geometry={nodes.M_1CL_1_F_B012.geometry} material={nodes.M_1CL_1_F_B012.material} position={[2.781, 1.553, 2.851]} />
        <mesh name="M_1CL_1_F_C012" geometry={nodes.M_1CL_1_F_C012.geometry} material={nodes.M_1CL_1_F_C012.material} position={[2.781, 0.76, 2.851]} />
        <mesh name="M_1CL_2" geometry={nodes.M_1CL_2.geometry} material={materials['wire_153228184.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_CL_2.glb')
