/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_CL_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_CL_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_1CL_5_NNobj" scale={1.142}>
        <mesh name="Legs004" geometry={nodes.Legs004.geometry} material={nodes.Legs004.material} position={[0.01, -3.635, -0.23]} />
        <mesh name="M_1CL_1_F005" geometry={nodes.M_1CL_1_F005.geometry} material={nodes.M_1CL_1_F005.material} position={[-3.564, 0.449, 2.86]}>
          <mesh name="M_1CL_5_PNT_H_1" geometry={nodes.M_1CL_5_PNT_H_1.geometry} material={nodes.M_1CL_5_PNT_H_1.material} position={[2.033, 2.676, 0.141]} />
          <mesh name="M_1CL_5_PNT_V_1" geometry={nodes.M_1CL_5_PNT_V_1.geometry} material={nodes.M_1CL_5_PNT_V_1.material} position={[2.867, 1.79, 0.141]} />
        </mesh>
        <mesh name="M_1CL_1_F006" geometry={nodes.M_1CL_1_F006.geometry} material={nodes.M_1CL_1_F006.material} position={[3.539, 0.449, 2.867]}>
          <mesh name="M_1CL_5_PNT_H_2" geometry={nodes.M_1CL_5_PNT_H_2.geometry} material={nodes.M_1CL_5_PNT_H_2.material} position={[-2.008, 2.676, 0.134]} />
          <mesh name="M_1CL_5_PNT_V_2" geometry={nodes.M_1CL_5_PNT_V_2.geometry} material={nodes.M_1CL_5_PNT_V_2.material} position={[-2.842, 1.79, 0.134]} />
        </mesh>
        <mesh name="M_1CL_1_F_A005" geometry={nodes.M_1CL_1_F_A005.geometry} material={nodes.M_1CL_1_F_A005.material} position={[-3.562, 1.557, 2.856]} />
        <mesh name="M_1CL_1_F_A006" geometry={nodes.M_1CL_1_F_A006.geometry} material={nodes.M_1CL_1_F_A006.material} position={[3.537, 1.557, 2.859]} />
        <mesh name="M_1CL_1_F_B005" geometry={nodes.M_1CL_1_F_B005.geometry} material={nodes.M_1CL_1_F_B005.material} position={[-3.565, 1.557, 2.856]} />
        <mesh name="M_1CL_1_F_B006" geometry={nodes.M_1CL_1_F_B006.geometry} material={nodes.M_1CL_1_F_B006.material} position={[3.537, 1.557, 2.859]} />
        <mesh name="M_1CL_1_F_C005" geometry={nodes.M_1CL_1_F_C005.geometry} material={nodes.M_1CL_1_F_C005.material} position={[-3.565, 0.762, 2.856]} />
        <mesh name="M_1CL_1_F_C006" geometry={nodes.M_1CL_1_F_C006.geometry} material={nodes.M_1CL_1_F_C006.material} position={[3.537, 0.762, 2.859]} />
        <mesh name="M_1CL_5" geometry={nodes.M_1CL_5.geometry} material={materials['wire_153228184.039']} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_CL_5.glb')
