/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_CL_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_CL_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_1CL_1_NN" scale={1.143}>
        <mesh name="Legs002" geometry={nodes.Legs002.geometry} material={nodes.Legs002.material} position={[0.263, -3.638, -0.252]} />
        <mesh name="M_1CL_1" geometry={nodes.M_1CL_1.geometry} material={materials['wire_153228184.006']} position={[0.253, -0.015, -0.022]} />
        <mesh name="M_1CL_1_F002" geometry={nodes.M_1CL_1_F002.geometry} material={nodes.M_1CL_1_F002.material} position={[2.525, 0.432, 2.854]}>
          <mesh name="M_11CL_1_PNT_V" geometry={nodes.M_11CL_1_PNT_V.geometry} material={nodes.M_11CL_1_PNT_V.material} position={[-4.188, 1.747, 0.091]} />
          <mesh name="M_CL_1_PNT_H" geometry={nodes.M_CL_1_PNT_H.geometry} material={nodes.M_CL_1_PNT_H.material} position={[-2.527, 2.634, 0.091]} />
        </mesh>
        <mesh name="M_1CL_1_F_A011" geometry={nodes.M_1CL_1_F_A011.geometry} material={nodes.M_1CL_1_F_A011.material} position={[2.523, 1.537, 2.845]} />
        <mesh name="M_1CL_1_F_B011" geometry={nodes.M_1CL_1_F_B011.geometry} material={nodes.M_1CL_1_F_B011.material} position={[2.523, 1.537, 2.845]} />
        <mesh name="M_1CL_1_F_C011" geometry={nodes.M_1CL_1_F_C011.geometry} material={nodes.M_1CL_1_F_C011.material} position={[2.523, 0.744, 2.845]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_CL_1.glb')
