/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_CL_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_CL_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_1CL_7_NNobj001" scale={1.145}>
        <mesh name="Legs001" geometry={nodes.Legs001.geometry} material={nodes.Legs001.material} position={[-0.244, -3.64, -0.257]} />
        <mesh name="M_1CL_1_F009" geometry={nodes.M_1CL_1_F009.geometry} material={nodes.M_1CL_1_F009.material} position={[-4.06, 0.436, 2.828]}>
          <mesh name="M_1CL_7_PNT_H_1" geometry={nodes.M_1CL_7_PNT_H_1.geometry} material={nodes.M_1CL_7_PNT_H_1.material} position={[2.529, 2.671, 0.141]} />
          <mesh name="M_1CL_7_PNT_V_1" geometry={nodes.M_1CL_7_PNT_V_1.geometry} material={nodes.M_1CL_7_PNT_V_1.material} position={[3.361, 1.787, 0.141]} />
        </mesh>
        <mesh name="M_1CL_1_F010" geometry={nodes.M_1CL_1_F010.geometry} material={nodes.M_1CL_1_F010.material} position={[4.05, 0.436, 2.835]}>
          <mesh name="M_1CL_7_PNT_H_2" geometry={nodes.M_1CL_7_PNT_H_2.geometry} material={nodes.M_1CL_7_PNT_H_2.material} position={[-2.525, 2.671, 0.134]} />
          <mesh name="M_1CL_7_PNT_V_2" geometry={nodes.M_1CL_7_PNT_V_2.geometry} material={nodes.M_1CL_7_PNT_V_2.material} position={[-3.358, 1.787, 0.134]} />
        </mesh>
        <mesh name="M_1CL_1_F_A009" geometry={nodes.M_1CL_1_F_A009.geometry} material={nodes.M_1CL_1_F_A009.material} position={[-4.058, 1.543, 2.824]} />
        <mesh name="M_1CL_1_F_A010" geometry={nodes.M_1CL_1_F_A010.geometry} material={nodes.M_1CL_1_F_A010.material} position={[4.048, 1.543, 2.827]} />
        <mesh name="M_1CL_1_F_B009" geometry={nodes.M_1CL_1_F_B009.geometry} material={nodes.M_1CL_1_F_B009.material} position={[-4.061, 1.543, 2.824]} />
        <mesh name="M_1CL_1_F_B010" geometry={nodes.M_1CL_1_F_B010.geometry} material={nodes.M_1CL_1_F_B010.material} position={[4.048, 1.543, 2.827]} />
        <mesh name="M_1CL_1_F_C009" geometry={nodes.M_1CL_1_F_C009.geometry} material={nodes.M_1CL_1_F_C009.material} position={[-4.061, 0.749, 2.824]} />
        <mesh name="M_1CL_1_F_C010" geometry={nodes.M_1CL_1_F_C010.geometry} material={nodes.M_1CL_1_F_C010.material} position={[4.048, 0.749, 2.827]} />
        <mesh name="M_1CL_7" geometry={nodes.M_1CL_7.geometry} material={materials['wire_153228184.041']} position={[-0.253, -0.012, -0.027]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_CL_7.glb')
