/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_CL_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_CL_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_1CL_3_NNobj001" scale={1.145}>
        <mesh name="Legs" geometry={nodes.Legs.geometry} material={nodes.Legs.material} position={[0.01, -3.629, -0.23]} />
        <mesh name="M_1CL_1_F" geometry={nodes.M_1CL_1_F.geometry} material={nodes.M_1CL_1_F.material} position={[-3.043, 0.448, 2.856]}>
          <mesh name="M_1CL_1_PNT_H_1" geometry={nodes.M_1CL_1_PNT_H_1.geometry} material={nodes.M_1CL_1_PNT_H_1.material} position={[1.515, 2.671, 0.141]} />
          <mesh name="M_1CL_1_PNT_V_1" geometry={nodes.M_1CL_1_PNT_V_1.geometry} material={nodes.M_1CL_1_PNT_V_1.material} position={[2.347, 1.787, 0.141]} />
        </mesh>
        <mesh name="M_1CL_1_F001" geometry={nodes.M_1CL_1_F001.geometry} material={nodes.M_1CL_1_F001.material} position={[3.047, 0.448, 2.862]}>
          <mesh name="M_1CL_1_PNT_H_2" geometry={nodes.M_1CL_1_PNT_H_2.geometry} material={nodes.M_1CL_1_PNT_H_2.material} position={[-1.519, 2.671, 0.134]} />
          <mesh name="M_1CL_1_PNT_V_2" geometry={nodes.M_1CL_1_PNT_V_2.geometry} material={nodes.M_1CL_1_PNT_V_2.material} position={[-2.352, 1.787, 0.134]} />
        </mesh>
        <mesh name="M_1CL_1_F_A" geometry={nodes.M_1CL_1_F_A.geometry} material={nodes.M_1CL_1_F_A.material} position={[-3.041, 1.554, 2.851]} />
        <mesh name="M_1CL_1_F_A001" geometry={nodes.M_1CL_1_F_A001.geometry} material={nodes.M_1CL_1_F_A001.material} position={[3.045, 1.554, 2.854]} />
        <mesh name="M_1CL_1_F_B" geometry={nodes.M_1CL_1_F_B.geometry} material={nodes.M_1CL_1_F_B.material} position={[-3.044, 1.554, 2.851]} />
        <mesh name="M_1CL_1_F_B001" geometry={nodes.M_1CL_1_F_B001.geometry} material={nodes.M_1CL_1_F_B001.material} position={[3.045, 1.554, 2.854]} />
        <mesh name="M_1CL_1_F_C" geometry={nodes.M_1CL_1_F_C.geometry} material={nodes.M_1CL_1_F_C.material} position={[-3.044, 0.76, 2.851]} />
        <mesh name="M_1CL_1_F_C001" geometry={nodes.M_1CL_1_F_C001.geometry} material={nodes.M_1CL_1_F_C001.material} position={[3.045, 0.76, 2.854]} />
        <mesh name="M_1CL_3" geometry={nodes.M_1CL_3.geometry} material={materials['wire_153228184.008']} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_CL_3.glb')
