/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_CL_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_CL_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_1CL_6_NNobj" scale={1.146}>
        <mesh name="Legs005" geometry={nodes.Legs005.geometry} material={nodes.Legs005.material} position={[0.01, -3.618, -0.229]} />
        <mesh name="M_1CL_1_F007" geometry={nodes.M_1CL_1_F007.geometry} material={nodes.M_1CL_1_F007.material} position={[-3.795, 0.446, 2.847]}>
          <mesh name="M_CL_6_PNT_H_1" geometry={nodes.M_CL_6_PNT_H_1.geometry} material={nodes.M_CL_6_PNT_H_1.material} position={[2.271, 2.663, 0.14]} />
          <mesh name="M_CL_6_PNT_V_1" geometry={nodes.M_CL_6_PNT_V_1.geometry} material={nodes.M_CL_6_PNT_V_1.material} position={[3.101, 1.782, 0.14]} />
        </mesh>
        <mesh name="M_1CL_1_F008" geometry={nodes.M_1CL_1_F008.geometry} material={nodes.M_1CL_1_F008.material} position={[3.777, 0.446, 2.854]}>
          <mesh name="M_CL_6_PNT_H_2" geometry={nodes.M_CL_6_PNT_H_2.geometry} material={nodes.M_CL_6_PNT_H_2.material} position={[-2.253, 2.663, 0.134]} />
          <mesh name="M_CL_6_PNT_V_2" geometry={nodes.M_CL_6_PNT_V_2.geometry} material={nodes.M_CL_6_PNT_V_2.material} position={[-3.083, 1.782, 0.134]} />
        </mesh>
        <mesh name="M_1CL_1_F_A007" geometry={nodes.M_1CL_1_F_A007.geometry} material={nodes.M_1CL_1_F_A007.material} position={[-3.793, 1.549, 2.843]} />
        <mesh name="M_1CL_1_F_A008" geometry={nodes.M_1CL_1_F_A008.geometry} material={nodes.M_1CL_1_F_A008.material} position={[3.775, 1.549, 2.845]} />
        <mesh name="M_1CL_1_F_B007" geometry={nodes.M_1CL_1_F_B007.geometry} material={nodes.M_1CL_1_F_B007.material} position={[-3.796, 1.55, 2.843]} />
        <mesh name="M_1CL_1_F_B008" geometry={nodes.M_1CL_1_F_B008.geometry} material={nodes.M_1CL_1_F_B008.material} position={[3.775, 1.55, 2.845]} />
        <mesh name="M_1CL_1_F_C007" geometry={nodes.M_1CL_1_F_C007.geometry} material={nodes.M_1CL_1_F_C007.material} position={[-3.796, 0.758, 2.843]} />
        <mesh name="M_1CL_1_F_C008" geometry={nodes.M_1CL_1_F_C008.geometry} material={nodes.M_1CL_1_F_C008.material} position={[3.775, 0.758, 2.845]} />
        <mesh name="M_1CL_6" geometry={nodes.M_1CL_6.geometry} material={materials['wire_153228184.040']} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_CL_6.glb')
