/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_CL_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_CL_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_1CL_4_NNobj" scale={1.146}>
        <mesh name="Legs003" geometry={nodes.Legs003.geometry} material={nodes.Legs003.material} position={[0.01, -3.624, -0.23]} />
        <mesh name="M_1CL_1_F003" geometry={nodes.M_1CL_1_F003.geometry} material={nodes.M_1CL_1_F003.material} position={[-3.282, 0.447, 2.852]}>
          <mesh name="M_1CL_4_PNT_H_1" geometry={nodes.M_1CL_4_PNT_H_1.geometry} material={nodes.M_1CL_4_PNT_H_1.material} position={[1.755, 2.668, 0.141]} />
          <mesh name="M_1CL_4_PNT_V_1" geometry={nodes.M_1CL_4_PNT_V_1.geometry} material={nodes.M_1CL_4_PNT_V_1.material} position={[2.587, 1.785, 0.141]} />
        </mesh>
        <mesh name="M_1CL_1_F_A003" geometry={nodes.M_1CL_1_F_A003.geometry} material={nodes.M_1CL_1_F_A003.material} position={[-3.28, 1.552, 2.848]} />
        <mesh name="M_1CL_1_F_A004" geometry={nodes.M_1CL_1_F_A004.geometry} material={nodes.M_1CL_1_F_A004.material} position={[3.286, 1.552, 2.851]} />
        <mesh name="M_1CL_1_F_B003" geometry={nodes.M_1CL_1_F_B003.geometry} material={nodes.M_1CL_1_F_B003.material} position={[-3.283, 1.553, 2.848]} />
        <mesh name="M_1CL_1_F_B004" geometry={nodes.M_1CL_1_F_B004.geometry} material={nodes.M_1CL_1_F_B004.material} position={[3.286, 1.553, 2.851]} />
        <mesh name="M_1CL_1_F_C003" geometry={nodes.M_1CL_1_F_C003.geometry} material={nodes.M_1CL_1_F_C003.material} position={[-3.283, 0.759, 2.848]} />
        <mesh name="M_1CL_1_F_C004" geometry={nodes.M_1CL_1_F_C004.geometry} material={nodes.M_1CL_1_F_C004.material} position={[3.286, 0.759, 2.851]} />
        <mesh name="M_1CL_4" geometry={nodes.M_1CL_4.geometry} material={materials['wire_153228184.038']} />
        <mesh name="M_CL_1_F004" geometry={nodes.M_CL_1_F004.geometry} material={nodes.M_CL_1_F004.material} position={[3.288, 0.447, 2.859]}>
          <mesh name="M_1CL_4_PNT_H_2" geometry={nodes.M_1CL_4_PNT_H_2.geometry} material={nodes.M_1CL_4_PNT_H_2.material} position={[-1.761, 2.668, 0.134]} />
          <mesh name="M_1CL_4_PNT_V_2" geometry={nodes.M_1CL_4_PNT_V_2.geometry} material={nodes.M_1CL_4_PNT_V_2.material} position={[-2.593, 1.785, 0.134]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/M_CL_4.glb')
