/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMO_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMO_1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="M_UMO_1" geometry={nodes.M_UMO_1.geometry} material={materials['wire_000000000.002']} scale={1.273} />
    </group>
  )
}

useGLTF.preload('/M_UMO_1.glb')
