/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT_1obj" scale={1.271}>
        <mesh name="M_UMT_1" geometry={nodes.M_UMT_1.geometry} material={nodes.M_UMT_1.material} />
        <mesh name="M_UMT_1_F007" geometry={nodes.M_UMT_1_F007.geometry} material={nodes.M_UMT_1_F007.material} position={[2.062, 2.979, 1.188]}>
          <mesh name="M_UMT_1_F006" geometry={nodes.M_UMT_1_F006.geometry} material={nodes.M_UMT_1_F006.material} position={[0, -2.98, 0]}>
            <mesh name="M_UMT_1_PNT001" geometry={nodes.M_UMT_1_PNT001.geometry} material={nodes.M_UMT_1_PNT001.material} position={[-2.062, -2.333, 0.147]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT_1_F_A007" geometry={nodes.M_UMT_1_F_A007.geometry} material={nodes.M_UMT_1_F_A007.material} position={[2.061, 2.979, 1.181]}>
          <mesh name="M_UMT_1_F_A006" geometry={nodes.M_UMT_1_F_A006.geometry} material={nodes.M_UMT_1_F_A006.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_B007" geometry={nodes.M_UMT_1_F_B007.geometry} material={nodes.M_UMT_1_F_B007.material} position={[2.061, 2.977, 1.181]}>
          <mesh name="M_UMT_1_F_B006" geometry={nodes.M_UMT_1_F_B006.geometry} material={nodes.M_UMT_1_F_B006.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_C007" geometry={nodes.M_UMT_1_F_C007.geometry} material={nodes.M_UMT_1_F_C007.material} position={[2.061, 2.973, 1.181]}>
          <mesh name="M_UMT_1_F_C006" geometry={nodes.M_UMT_1_F_C006.geometry} material={nodes.M_UMT_1_F_C006.material} position={[0, -2.98, 0]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT_1.glb')
