/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT_3obj" scale={1.052}>
        <mesh name="M_UMT_1_F011" geometry={nodes.M_UMT_1_F011.geometry} material={nodes.M_UMT_1_F011.material} position={[2.994, 3.6, 1.436]}>
          <mesh name="M_UMT_1_F010" geometry={nodes.M_UMT_1_F010.geometry} material={nodes.M_UMT_1_F010.material} position={[0, -3.596, 0]}>
            <mesh name="M_UMT_1_PNT003" geometry={nodes.M_UMT_1_PNT003.geometry} material={nodes.M_UMT_1_PNT003.material} position={[-2.994, -2.819, 0.178]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT_1_F_A011" geometry={nodes.M_UMT_1_F_A011.geometry} material={nodes.M_UMT_1_F_A011.material} position={[2.992, 3.6, 1.427]}>
          <mesh name="M_UMT_1_F_A010" geometry={nodes.M_UMT_1_F_A010.geometry} material={nodes.M_UMT_1_F_A010.material} position={[0, -3.596, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_B011" geometry={nodes.M_UMT_1_F_B011.geometry} material={nodes.M_UMT_1_F_B011.material} position={[2.992, 3.598, 1.427]}>
          <mesh name="M_UMT_1_F_B010" geometry={nodes.M_UMT_1_F_B010.geometry} material={nodes.M_UMT_1_F_B010.material} position={[0, -3.596, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_C011" geometry={nodes.M_UMT_1_F_C011.geometry} material={nodes.M_UMT_1_F_C011.material} position={[2.992, 3.593, 1.427]}>
          <mesh name="M_UMT_1_F_C010" geometry={nodes.M_UMT_1_F_C010.geometry} material={nodes.M_UMT_1_F_C010.material} position={[0, -3.596, 0]} />
        </mesh>
        <mesh name="M_UMT_3" geometry={nodes.M_UMT_3.geometry} material={nodes.M_UMT_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT_3.glb')
