/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT_1obj" scale={1.271}>
        <mesh name="M_UMT_1" geometry={nodes.M_UMT_1.geometry} material={nodes.M_UMT_1.material} />
        <mesh name="M_UMT_1_F007" geometry={nodes.M_UMT_1_F007.geometry} material={nodes.M_UMT_1_F007.material} position={[2.062, 2.979, 1.188]}>
          <mesh name="M_UMT_1_F006" geometry={nodes.M_UMT_1_F006.geometry} material={nodes.M_UMT_1_F006.material} position={[0, -2.98, 0]}>
            <mesh name="M_UMT_1_PNT001" geometry={nodes.M_UMT_1_PNT001.geometry} material={nodes.M_UMT_1_PNT001.material} position={[-2.062, -2.333, 0.147]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT_1_F_A007" geometry={nodes.M_UMT_1_F_A007.geometry} material={nodes.M_UMT_1_F_A007.material} position={[2.061, 2.979, 1.181]}>
          <mesh name="M_UMT_1_F_A006" geometry={nodes.M_UMT_1_F_A006.geometry} material={nodes.M_UMT_1_F_A006.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_B007" geometry={nodes.M_UMT_1_F_B007.geometry} material={nodes.M_UMT_1_F_B007.material} position={[2.061, 2.977, 1.181]}>
          <mesh name="M_UMT_1_F_B006" geometry={nodes.M_UMT_1_F_B006.geometry} material={nodes.M_UMT_1_F_B006.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_C007" geometry={nodes.M_UMT_1_F_C007.geometry} material={nodes.M_UMT_1_F_C007.material} position={[2.061, 2.973, 1.181]}>
          <mesh name="M_UMT_1_F_C006" geometry={nodes.M_UMT_1_F_C006.geometry} material={nodes.M_UMT_1_F_C006.material} position={[0, -2.98, 0]} />
        </mesh>
      </group>
      <group name="M_UMT_2obj" scale={1.27}>
        <mesh name="M_UMT_1_F009" geometry={nodes.M_UMT_1_F009.geometry} material={nodes.M_UMT_1_F009.material} position={[2.273, 2.983, 1.19]}>
          <mesh name="M_UMT_1_F008" geometry={nodes.M_UMT_1_F008.geometry} material={nodes.M_UMT_1_F008.material} position={[0, -2.98, 0]}>
            <mesh name="M_UMT_1_PNT002" geometry={nodes.M_UMT_1_PNT002.geometry} material={nodes.M_UMT_1_PNT002.material} position={[-2.273, -2.336, 0.148]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT_1_F_A009" geometry={nodes.M_UMT_1_F_A009.geometry} material={nodes.M_UMT_1_F_A009.material} position={[2.271, 2.982, 1.182]}>
          <mesh name="M_UMT_1_F_A008" geometry={nodes.M_UMT_1_F_A008.geometry} material={nodes.M_UMT_1_F_A008.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_B009" geometry={nodes.M_UMT_1_F_B009.geometry} material={nodes.M_UMT_1_F_B009.material} position={[2.271, 2.98, 1.182]}>
          <mesh name="M_UMT_1_F_B008" geometry={nodes.M_UMT_1_F_B008.geometry} material={nodes.M_UMT_1_F_B008.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_C009" geometry={nodes.M_UMT_1_F_C009.geometry} material={nodes.M_UMT_1_F_C009.material} position={[2.271, 2.977, 1.182]}>
          <mesh name="M_UMT_1_F_C008" geometry={nodes.M_UMT_1_F_C008.geometry} material={nodes.M_UMT_1_F_C008.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_2" geometry={nodes.M_UMT_2.geometry} material={nodes.M_UMT_2.material} />
      </group>
      <group name="M_UMT_3obj" scale={1.052}>
        <mesh name="M_UMT_1_F011" geometry={nodes.M_UMT_1_F011.geometry} material={nodes.M_UMT_1_F011.material} position={[2.994, 3.6, 1.436]}>
          <mesh name="M_UMT_1_F010" geometry={nodes.M_UMT_1_F010.geometry} material={nodes.M_UMT_1_F010.material} position={[0, -3.596, 0]}>
            <mesh name="M_UMT_1_PNT003" geometry={nodes.M_UMT_1_PNT003.geometry} material={nodes.M_UMT_1_PNT003.material} position={[-2.994, -2.819, 0.178]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT_1_F_A011" geometry={nodes.M_UMT_1_F_A011.geometry} material={nodes.M_UMT_1_F_A011.material} position={[2.992, 3.6, 1.427]}>
          <mesh name="M_UMT_1_F_A010" geometry={nodes.M_UMT_1_F_A010.geometry} material={nodes.M_UMT_1_F_A010.material} position={[0, -3.596, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_B011" geometry={nodes.M_UMT_1_F_B011.geometry} material={nodes.M_UMT_1_F_B011.material} position={[2.992, 3.598, 1.427]}>
          <mesh name="M_UMT_1_F_B010" geometry={nodes.M_UMT_1_F_B010.geometry} material={nodes.M_UMT_1_F_B010.material} position={[0, -3.596, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_C011" geometry={nodes.M_UMT_1_F_C011.geometry} material={nodes.M_UMT_1_F_C011.material} position={[2.992, 3.593, 1.427]}>
          <mesh name="M_UMT_1_F_C010" geometry={nodes.M_UMT_1_F_C010.geometry} material={nodes.M_UMT_1_F_C010.material} position={[0, -3.596, 0]} />
        </mesh>
        <mesh name="M_UMT_3" geometry={nodes.M_UMT_3.geometry} material={nodes.M_UMT_3.material} />
      </group>
      <group name="M_UMT_4obj" scale={1.27}>
        <mesh name="M_UMT_1_F013" geometry={nodes.M_UMT_1_F013.geometry} material={nodes.M_UMT_1_F013.material} position={[2.688, 2.982, 1.189]}>
          <mesh name="M_UMT_1_F012" geometry={nodes.M_UMT_1_F012.geometry} material={nodes.M_UMT_1_F012.material} position={[0, -2.98, 0]}>
            <mesh name="M_UMT_1_PNT004" geometry={nodes.M_UMT_1_PNT004.geometry} material={nodes.M_UMT_1_PNT004.material} position={[-2.688, -2.335, 0.148]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT_1_F_A013" geometry={nodes.M_UMT_1_F_A013.geometry} material={nodes.M_UMT_1_F_A013.material} position={[2.686, 2.981, 1.182]}>
          <mesh name="M_UMT_1_F_A012" geometry={nodes.M_UMT_1_F_A012.geometry} material={nodes.M_UMT_1_F_A012.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_B013" geometry={nodes.M_UMT_1_F_B013.geometry} material={nodes.M_UMT_1_F_B013.material} position={[2.686, 2.979, 1.182]}>
          <mesh name="M_UMT_1_F_B012" geometry={nodes.M_UMT_1_F_B012.geometry} material={nodes.M_UMT_1_F_B012.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_C013" geometry={nodes.M_UMT_1_F_C013.geometry} material={nodes.M_UMT_1_F_C013.material} position={[2.686, 2.976, 1.182]}>
          <mesh name="M_UMT_1_F_C012" geometry={nodes.M_UMT_1_F_C012.geometry} material={nodes.M_UMT_1_F_C012.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_4" geometry={nodes.M_UMT_4.geometry} material={nodes.M_UMT_4.material} />
      </group>
      <group name="M_UMT_5obj" scale={1.27}>
        <mesh name="M_UMT_1_F001" geometry={nodes.M_UMT_1_F001.geometry} material={nodes.M_UMT_1_F001.material} position={[2.894, 2.981, 1.189]}>
          <mesh name="M_UMT_1_F" geometry={nodes.M_UMT_1_F.geometry} material={nodes.M_UMT_1_F.material} position={[0, -2.98, 0]}>
            <mesh name="M_UMT_5_PNT001" geometry={nodes.M_UMT_5_PNT001.geometry} material={nodes.M_UMT_5_PNT001.material} position={[-2.894, -2.334, 0.147]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT_1_F_A001" geometry={nodes.M_UMT_1_F_A001.geometry} material={nodes.M_UMT_1_F_A001.material} position={[2.892, 2.98, 1.181]}>
          <mesh name="M_UMT_1_F_A" geometry={nodes.M_UMT_1_F_A.geometry} material={nodes.M_UMT_1_F_A.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_B001" geometry={nodes.M_UMT_1_F_B001.geometry} material={nodes.M_UMT_1_F_B001.material} position={[2.892, 2.978, 1.181]}>
          <mesh name="M_UMT_1_F_B" geometry={nodes.M_UMT_1_F_B.geometry} material={nodes.M_UMT_1_F_B.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_C001" geometry={nodes.M_UMT_1_F_C001.geometry} material={nodes.M_UMT_1_F_C001.material} position={[2.892, 2.975, 1.181]}>
          <mesh name="M_UMT_1_F_C" geometry={nodes.M_UMT_1_F_C.geometry} material={nodes.M_UMT_1_F_C.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_5" geometry={nodes.M_UMT_5.geometry} material={nodes.M_UMT_5.material} />
      </group>
      <group name="M_UMT_6obj" scale={1.268}>
        <mesh name="M_UMT_1_F003" geometry={nodes.M_UMT_1_F003.geometry} material={nodes.M_UMT_1_F003.material} position={[3.105, 2.985, 1.191]}>
          <mesh name="M_UMT_1_F002" geometry={nodes.M_UMT_1_F002.geometry} material={nodes.M_UMT_1_F002.material} position={[0, -2.986, 0]}>
            <mesh name="M_UMT_6_PNT001" geometry={nodes.M_UMT_6_PNT001.geometry} material={nodes.M_UMT_6_PNT001.material} position={[-3.105, -2.338, 0.148]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT_1_F_A003" geometry={nodes.M_UMT_1_F_A003.geometry} material={nodes.M_UMT_1_F_A003.material} position={[3.104, 2.985, 1.183]}>
          <mesh name="M_UMT_1_F_A002_1" geometry={nodes.M_UMT_1_F_A002_1.geometry} material={nodes.M_UMT_1_F_A002_1.material} position={[0, -3, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_B003" geometry={nodes.M_UMT_1_F_B003.geometry} material={nodes.M_UMT_1_F_B003.material} position={[3.104, 2.983, 1.183]}>
          <mesh name="M_UMT_1_F_B002_1" geometry={nodes.M_UMT_1_F_B002_1.geometry} material={nodes.M_UMT_1_F_B002_1.material} position={[0, -3, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_C003" geometry={nodes.M_UMT_1_F_C003.geometry} material={nodes.M_UMT_1_F_C003.material} position={[3.104, 2.98, 1.183]}>
          <mesh name="M_UMT_1_F_C002_1" geometry={nodes.M_UMT_1_F_C002_1.geometry} material={nodes.M_UMT_1_F_C002_1.material} position={[0, -2.986, 0]} />
        </mesh>
        <mesh name="M_UMT_6" geometry={nodes.M_UMT_6.geometry} material={nodes.M_UMT_6.material} />
      </group>
      <group name="M_UMT_7obj" scale={1.273}>
        <mesh name="M_UMT_1_F005" geometry={nodes.M_UMT_1_F005.geometry} material={nodes.M_UMT_1_F005.material} position={[3.302, 2.975, 1.186]}>
          <mesh name="M_UMT_1_F004" geometry={nodes.M_UMT_1_F004.geometry} material={nodes.M_UMT_1_F004.material} position={[0, -2.973, 0]}>
            <mesh name="M_UMT_7_PNT001" geometry={nodes.M_UMT_7_PNT001.geometry} material={nodes.M_UMT_7_PNT001.material} position={[-3.302, -2.33, 0.147]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT_1_F_A005" geometry={nodes.M_UMT_1_F_A005.geometry} material={nodes.M_UMT_1_F_A005.material} position={[3.3, 2.974, 1.179]}>
          <mesh name="M_UMT_1_F_A004_1" geometry={nodes.M_UMT_1_F_A004_1.geometry} material={nodes.M_UMT_1_F_A004_1.material} position={[0, -2.973, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_B005" geometry={nodes.M_UMT_1_F_B005.geometry} material={nodes.M_UMT_1_F_B005.material} position={[3.3, 2.972, 1.179]}>
          <mesh name="M_UMT_1_F_B004_1" geometry={nodes.M_UMT_1_F_B004_1.geometry} material={nodes.M_UMT_1_F_B004_1.material} position={[0, -2.973, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_C005" geometry={nodes.M_UMT_1_F_C005.geometry} material={nodes.M_UMT_1_F_C005.material} position={[3.3, 2.969, 1.179]}>
          <mesh name="M_UMT_1_F_C004_1" geometry={nodes.M_UMT_1_F_C004_1.geometry} material={nodes.M_UMT_1_F_C004_1.material} position={[0, -2.973, 0]} />
        </mesh>
        <mesh name="M_UMT_7" geometry={nodes.M_UMT_7.geometry} material={nodes.M_UMT_7.material} />
      </group>
      <group name="RootNode001" scale={24.786}>
        <group name="Stove" scale={100}>
          <mesh name="Stove001" geometry={nodes.Stove001.geometry} material={materials['Material.004']} />
          <mesh name="Stove001_1" geometry={nodes.Stove001_1.geometry} material={materials['Material.005']} />
          <mesh name="Stove001_2" geometry={nodes.Stove001_2.geometry} material={materials['Material.006']} />
        </group>
      </group>
      <group name="RootNode" rotation={[0, -0.173, 0]} scale={17.208}>
        <mesh name="Refrigirator" geometry={nodes.Refrigirator.geometry} material={materials['Material.003']} scale={100} />
      </group>
      <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} scale={-11.313} />
      <group name="Capsule001" position={[2.567, 5.853, -1.279]} rotation={[0, -0.299, 0]} scale={0.493}>
        <mesh name="Capsule001_1001" geometry={nodes.Capsule001_1001.geometry} material={materials['01___Default.001']} />
        <mesh name="Capsule001_1001_1" geometry={nodes.Capsule001_1001_1.geometry} material={materials['02___Default.001']} />
      </group>
      <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['06___Default.001']} position={[2.567, 5.853, -1.279]} rotation={[0, -0.299, 0]} scale={0.493} />
      <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['06___Default.001']} position={[2.567, 5.853, -1.279]} rotation={[0, -0.299, 0]} scale={0.493} />
      <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['06___Default.001']} position={[2.567, 5.853, -1.279]} rotation={[0, -0.299, 0]} scale={0.493} />
      <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['06___Default.001']} position={[2.567, 5.853, -1.279]} rotation={[0, -0.299, 0]} scale={0.493} />
      <group name="Tube001" position={[2.567, 5.853, -1.279]} rotation={[0, -0.299, 0]} scale={0.493}>
        <mesh name="Tube001_1001" geometry={nodes.Tube001_1001.geometry} material={materials['02___Default.001']} />
        <mesh name="Tube001_1001_1" geometry={nodes.Tube001_1001_1.geometry} material={materials['05___Default.001']} />
        <mesh name="Tube001_1001_2" geometry={nodes.Tube001_1001_2.geometry} material={materials['04___Default.001']} />
      </group>
      <mesh name="hoodLarge_1" geometry={nodes.hoodLarge_1.geometry} material={materials['metalDark.001']} position={[-7.603, 5.053, 5.26]} rotation={[-Math.PI, 0.203, -Math.PI]} scale={37.845} />
      <mesh name="window_corner" geometry={nodes.window_corner.geometry} material={materials['WHITE.006']} />
      <mesh name="window_frame_main" geometry={nodes.window_frame_main.geometry} material={materials['WHITE.006']}>
        <mesh name="glass_1" geometry={nodes.glass_1.geometry} material={materials['BLUE.001']} />
      </mesh>
      <mesh name="window_frame_sub" geometry={nodes.window_frame_sub.geometry} material={materials['WHITE.006']}>
        <mesh name="glass_2" geometry={nodes.glass_2.geometry} material={materials['BLUE.001']} />
        <mesh name="handle" geometry={nodes.handle.geometry} material={materials['WHITE.006']} />
        <mesh name="handle_part" geometry={nodes.handle_part.geometry} material={materials['WHITE.006']} />
      </mesh>
      <mesh name="Door_frame" geometry={nodes.Door_frame.geometry} material={materials['WHITE.005']} />
      <mesh name="Door_main" geometry={nodes.Door_main.geometry} material={materials['WHITE.005']}>
        <mesh name="door_handle_1" geometry={nodes.door_handle_1.geometry} material={materials['Material.002']} />
        <mesh name="door_handle_1_cyl" geometry={nodes.door_handle_1_cyl.geometry} material={materials['Material.002']} />
        <mesh name="door_handle_2" geometry={nodes.door_handle_2.geometry} material={materials['WHITE.005']} />
        <mesh name="door_handle_2_cyl" geometry={nodes.door_handle_2_cyl.geometry} material={materials['WHITE.005']} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/M_UMT_7.glb')
