/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT_4obj" scale={1.27}>
        <mesh name="M_UMT_1_F013" geometry={nodes.M_UMT_1_F013.geometry} material={nodes.M_UMT_1_F013.material} position={[2.688, 2.982, 1.189]}>
          <mesh name="M_UMT_1_F012" geometry={nodes.M_UMT_1_F012.geometry} material={nodes.M_UMT_1_F012.material} position={[0, -2.98, 0]}>
            <mesh name="M_UMT_1_PNT004" geometry={nodes.M_UMT_1_PNT004.geometry} material={nodes.M_UMT_1_PNT004.material} position={[-2.688, -2.335, 0.148]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT_1_F_A013" geometry={nodes.M_UMT_1_F_A013.geometry} material={nodes.M_UMT_1_F_A013.material} position={[2.686, 2.981, 1.182]}>
          <mesh name="M_UMT_1_F_A012" geometry={nodes.M_UMT_1_F_A012.geometry} material={nodes.M_UMT_1_F_A012.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_B013" geometry={nodes.M_UMT_1_F_B013.geometry} material={nodes.M_UMT_1_F_B013.material} position={[2.686, 2.979, 1.182]}>
          <mesh name="M_UMT_1_F_B012" geometry={nodes.M_UMT_1_F_B012.geometry} material={nodes.M_UMT_1_F_B012.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_C013" geometry={nodes.M_UMT_1_F_C013.geometry} material={nodes.M_UMT_1_F_C013.material} position={[2.686, 2.976, 1.182]}>
          <mesh name="M_UMT_1_F_C012" geometry={nodes.M_UMT_1_F_C012.geometry} material={nodes.M_UMT_1_F_C012.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_4" geometry={nodes.M_UMT_4.geometry} material={nodes.M_UMT_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT_4.glb')
