/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT_5obj" scale={1.27}>
        <mesh name="M_UMT_1_F001" geometry={nodes.M_UMT_1_F001.geometry} material={nodes.M_UMT_1_F001.material} position={[2.894, 2.981, 1.189]}>
          <mesh name="M_UMT_1_F" geometry={nodes.M_UMT_1_F.geometry} material={nodes.M_UMT_1_F.material} position={[0, -2.98, 0]}>
            <mesh name="M_UMT_5_PNT001" geometry={nodes.M_UMT_5_PNT001.geometry} material={nodes.M_UMT_5_PNT001.material} position={[-2.894, -2.334, 0.147]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT_1_F_A001" geometry={nodes.M_UMT_1_F_A001.geometry} material={nodes.M_UMT_1_F_A001.material} position={[2.892, 2.98, 1.181]}>
          <mesh name="M_UMT_1_F_A" geometry={nodes.M_UMT_1_F_A.geometry} material={nodes.M_UMT_1_F_A.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_B001" geometry={nodes.M_UMT_1_F_B001.geometry} material={nodes.M_UMT_1_F_B001.material} position={[2.892, 2.978, 1.181]}>
          <mesh name="M_UMT_1_F_B" geometry={nodes.M_UMT_1_F_B.geometry} material={nodes.M_UMT_1_F_B.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_C001" geometry={nodes.M_UMT_1_F_C001.geometry} material={nodes.M_UMT_1_F_C001.material} position={[2.892, 2.975, 1.181]}>
          <mesh name="M_UMT_1_F_C" geometry={nodes.M_UMT_1_F_C.geometry} material={nodes.M_UMT_1_F_C.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_5" geometry={nodes.M_UMT_5.geometry} material={nodes.M_UMT_5.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT_5.glb')
