/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT_2obj" scale={1.27}>
        <mesh name="M_UMT_1_F009" geometry={nodes.M_UMT_1_F009.geometry} material={nodes.M_UMT_1_F009.material} position={[2.273, 2.983, 1.19]}>
          <mesh name="M_UMT_1_F008" geometry={nodes.M_UMT_1_F008.geometry} material={nodes.M_UMT_1_F008.material} position={[0, -2.98, 0]}>
            <mesh name="M_UMT_1_PNT002" geometry={nodes.M_UMT_1_PNT002.geometry} material={nodes.M_UMT_1_PNT002.material} position={[-2.273, -2.336, 0.148]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT_1_F_A009" geometry={nodes.M_UMT_1_F_A009.geometry} material={nodes.M_UMT_1_F_A009.material} position={[2.271, 2.982, 1.182]}>
          <mesh name="M_UMT_1_F_A008" geometry={nodes.M_UMT_1_F_A008.geometry} material={nodes.M_UMT_1_F_A008.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_B009" geometry={nodes.M_UMT_1_F_B009.geometry} material={nodes.M_UMT_1_F_B009.material} position={[2.271, 2.98, 1.182]}>
          <mesh name="M_UMT_1_F_B008" geometry={nodes.M_UMT_1_F_B008.geometry} material={nodes.M_UMT_1_F_B008.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_C009" geometry={nodes.M_UMT_1_F_C009.geometry} material={nodes.M_UMT_1_F_C009.material} position={[2.271, 2.977, 1.182]}>
          <mesh name="M_UMT_1_F_C008" geometry={nodes.M_UMT_1_F_C008.geometry} material={nodes.M_UMT_1_F_C008.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT_2" geometry={nodes.M_UMT_2.geometry} material={nodes.M_UMT_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT_2.glb')
