/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT_6obj" scale={1.268}>
        <mesh name="M_UMT_1_F003" geometry={nodes.M_UMT_1_F003.geometry} material={nodes.M_UMT_1_F003.material} position={[3.105, 2.985, 1.191]}>
          <mesh name="M_UMT_1_F002" geometry={nodes.M_UMT_1_F002.geometry} material={nodes.M_UMT_1_F002.material} position={[0, -2.986, 0]}>
            <mesh name="M_UMT_6_PNT001" geometry={nodes.M_UMT_6_PNT001.geometry} material={nodes.M_UMT_6_PNT001.material} position={[-3.105, -2.338, 0.148]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT_1_F_A003" geometry={nodes.M_UMT_1_F_A003.geometry} material={nodes.M_UMT_1_F_A003.material} position={[3.104, 2.985, 1.183]}>
          <mesh name="M_UMT_1_F_A002" geometry={nodes.M_UMT_1_F_A002.geometry} material={nodes.M_UMT_1_F_A002.material} position={[0, -3, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_B003" geometry={nodes.M_UMT_1_F_B003.geometry} material={nodes.M_UMT_1_F_B003.material} position={[3.104, 2.983, 1.183]}>
          <mesh name="M_UMT_1_F_B002" geometry={nodes.M_UMT_1_F_B002.geometry} material={nodes.M_UMT_1_F_B002.material} position={[0, -3, 0]} />
        </mesh>
        <mesh name="M_UMT_1_F_C003" geometry={nodes.M_UMT_1_F_C003.geometry} material={nodes.M_UMT_1_F_C003.material} position={[3.104, 2.98, 1.183]}>
          <mesh name="M_UMT_1_F_C002" geometry={nodes.M_UMT_1_F_C002.geometry} material={nodes.M_UMT_1_F_C002.material} position={[0, -2.986, 0]} />
        </mesh>
        <mesh name="M_UMT_6" geometry={nodes.M_UMT_6.geometry} material={nodes.M_UMT_6.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT_6.glb')
