/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Blender.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Blender.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="appliance_blender_knob_Cylinder131" geometry={nodes.appliance_blender_knob_Cylinder131.geometry} material={materials['Solid.001']} />
      <mesh name="appliance_blender_001_Cylinder128" geometry={nodes.appliance_blender_001_Cylinder128.geometry} material={materials['Solid.001']} />
      <mesh name="appliance_blender_lid_Cylinder129-Mesh001" geometry={nodes['appliance_blender_lid_Cylinder129-Mesh001'].geometry} material={materials['Solid.001']} />
      <mesh name="appliance_blender_lid_Cylinder129-Mesh001_1" geometry={nodes['appliance_blender_lid_Cylinder129-Mesh001_1'].geometry} material={materials['Solid_-_25%.001']} />
      <mesh name="appliance_blender_container_Cylinder130-Mesh001" geometry={nodes['appliance_blender_container_Cylinder130-Mesh001'].geometry} material={materials['Solid_-_25%.001']} />
      <mesh name="appliance_blender_container_Cylinder130-Mesh001_1" geometry={nodes['appliance_blender_container_Cylinder130-Mesh001_1'].geometry} material={materials['Solid.001']} />
    </group>
  )
}

useGLTF.preload('/Blender.glb')
