/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CoffeeMachine.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CoffeeMachine.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="hoodLarge_2" geometry={nodes.hoodLarge_2.geometry} material={materials.metalDark} />
      <mesh name="hoodLarge_2_1" geometry={nodes.hoodLarge_2_1.geometry} material={materials._defaultMat} />
      <mesh name="hoodLarge_3" geometry={nodes.hoodLarge_3.geometry} material={materials._defaultMat} />
      <mesh name="hoodLarge_3_1" geometry={nodes.hoodLarge_3_1.geometry} material={materials.metalDark} />
    </group>
  )
}

useGLTF.preload('/CoffeeMachine.glb')
