/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 FridgeWithDisplay.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/FridgeWithDisplay.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="fridge" geometry={nodes.fridge.geometry} material={materials['fridge.001']} />
      <mesh name="display" geometry={nodes.display.geometry} material={materials['display.001']} />
      <mesh name="handle" geometry={nodes.handle.geometry} material={materials['handle.001']} />
      <mesh name="sealing" geometry={nodes.sealing.geometry} material={materials['sealing.001']} />
    </group>
  )
}

useGLTF.preload('/FridgeWithDisplay.glb')
