/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Microwave.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Microwave.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
      <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} />
      <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} />
      <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} />
      <mesh name="Capsule001_1" geometry={nodes.Capsule001_1.geometry} material={materials['01___Default']} />
      <mesh name="Capsule001_1_1" geometry={nodes.Capsule001_1_1.geometry} material={materials['02___Default']} />
      <mesh name="Tube001_1" geometry={nodes.Tube001_1.geometry} material={materials['02___Default']} />
      <mesh name="Tube001_1_1" geometry={nodes.Tube001_1_1.geometry} material={materials['05___Default']} />
      <mesh name="Tube001_1_2" geometry={nodes.Tube001_1_2.geometry} material={materials['04___Default']} />
    </group>
  )
}

useGLTF.preload('/Microwave.glb')
