/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Refrigirator.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Refrigirator.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Refrigirator" geometry={nodes.Refrigirator.geometry} material={materials['Material.001']} scale={2.108} />
    </group>
  )
}

useGLTF.preload('/Refrigirator.glb')
