/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Stove.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Stove.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Stove" geometry={nodes.Stove.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/Stove.glb')
