/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU3_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU3_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU3_3_F_3obj" scale={0.593}>
        <mesh name="M_UMU3_1_F006" geometry={nodes.M_UMU3_1_F006.geometry} material={nodes.M_UMU3_1_F006.material} position={[2.978, 1.751, 2.606]}>
          <mesh name="M_UMU3_3_PNT_H" geometry={nodes.M_UMU3_3_PNT_H.geometry} material={nodes.M_UMU3_3_PNT_H.material} position={[-2.978, -2.852, 0.13]} />
        </mesh>
        <mesh name="M_UMU3_3" geometry={nodes.M_UMU3_3.geometry} material={nodes.M_UMU3_3.material} />
        <mesh name="M_UMU3_F_A006" geometry={nodes.M_UMU3_F_A006.geometry} material={nodes.M_UMU3_F_A006.material} position={[2.976, 1.75, 2.599]} />
        <mesh name="M_UMU3_F_B006" geometry={nodes.M_UMU3_F_B006.geometry} material={nodes.M_UMU3_F_B006.material} position={[2.976, 1.749, 2.599]} />
        <mesh name="M_UMU3_F_C006" geometry={nodes.M_UMU3_F_C006.geometry} material={nodes.M_UMU3_F_C006.material} position={[2.976, 1.745, 2.599]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU3_3.glb')
