/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU3_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU3_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU3_4_F_4obj" scale={0.593}>
        <mesh name="M_UMU3_1_F" geometry={nodes.M_UMU3_1_F.geometry} material={nodes.M_UMU3_1_F.material} position={[3.217, 1.751, 2.606]}>
          <mesh name="M_UMU3_4_PNT_H" geometry={nodes.M_UMU3_4_PNT_H.geometry} material={nodes.M_UMU3_4_PNT_H.material} position={[-3.217, -2.852, 0.13]} />
        </mesh>
        <mesh name="M_UMU3_4" geometry={nodes.M_UMU3_4.geometry} material={nodes.M_UMU3_4.material} />
        <mesh name="M_UMU3_F_A" geometry={nodes.M_UMU3_F_A.geometry} material={nodes.M_UMU3_F_A.material} position={[3.215, 1.75, 2.599]} />
        <mesh name="M_UMU3_F_B" geometry={nodes.M_UMU3_F_B.geometry} material={nodes.M_UMU3_F_B.material} position={[3.215, 1.749, 2.599]} />
        <mesh name="M_UMU3_F_C" geometry={nodes.M_UMU3_F_C.geometry} material={nodes.M_UMU3_F_C.material} position={[3.215, 1.745, 2.599]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU3_4.glb')
