/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU3_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU3_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU3_2_F_2obj" scale={0.593}>
        <mesh name="M_UMU3_1_F005" geometry={nodes.M_UMU3_1_F005.geometry} material={nodes.M_UMU3_1_F005.material} position={[2.746, 1.751, 2.606]}>
          <mesh name="M_UMU3_2_PNT_H" geometry={nodes.M_UMU3_2_PNT_H.geometry} material={nodes.M_UMU3_2_PNT_H.material} position={[-2.746, -2.852, 0.13]} />
        </mesh>
        <mesh name="M_UMU3_2" geometry={nodes.M_UMU3_2.geometry} material={nodes.M_UMU3_2.material} />
        <mesh name="M_UMU3_F_A005" geometry={nodes.M_UMU3_F_A005.geometry} material={nodes.M_UMU3_F_A005.material} position={[2.745, 1.75, 2.599]} />
        <mesh name="M_UMU3_F_B005" geometry={nodes.M_UMU3_F_B005.geometry} material={nodes.M_UMU3_F_B005.material} position={[2.745, 1.749, 2.599]} />
        <mesh name="M_UMU3_F_C005" geometry={nodes.M_UMU3_F_C005.geometry} material={nodes.M_UMU3_F_C005.material} position={[2.745, 1.745, 2.599]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU3_2.glb')
