/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU3_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU3_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU3_6_F_6obj" scale={0.593}>
        <mesh name="M_UMU3_1_F002" geometry={nodes.M_UMU3_1_F002.geometry} material={nodes.M_UMU3_1_F002.material} position={[3.739, 1.751, 2.606]}>
          <mesh name="M_UMU3_6_PNT_H" geometry={nodes.M_UMU3_6_PNT_H.geometry} material={nodes.M_UMU3_6_PNT_H.material} position={[-3.739, -2.852, 0.13]} />
        </mesh>
        <mesh name="M_UMU3_6" geometry={nodes.M_UMU3_6.geometry} material={nodes.M_UMU3_6.material} />
        <mesh name="M_UMU3_F_A002" geometry={nodes.M_UMU3_F_A002.geometry} material={nodes.M_UMU3_F_A002.material} position={[3.737, 1.75, 2.599]} />
        <mesh name="M_UMU3_F_B002" geometry={nodes.M_UMU3_F_B002.geometry} material={nodes.M_UMU3_F_B002.material} position={[3.737, 1.749, 2.599]} />
        <mesh name="M_UMU3_F_C002" geometry={nodes.M_UMU3_F_C002.geometry} material={nodes.M_UMU3_F_C002.material} position={[3.737, 1.745, 2.599]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU3_6.glb')
