/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU3_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU3_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU3_1_F_1obj" scale={0.593}>
        <mesh name="M_UMU3_1" geometry={nodes.M_UMU3_1.geometry} material={nodes.M_UMU3_1.material} />
        <mesh name="M_UMU3_1_F004" geometry={nodes.M_UMU3_1_F004.geometry} material={nodes.M_UMU3_1_F004.material} position={[2.497, 1.751, 2.606]}>
          <mesh name="M_UMU3_1_PNT_H" geometry={nodes.M_UMU3_1_PNT_H.geometry} material={nodes.M_UMU3_1_PNT_H.material} position={[-2.497, -2.852, 0.13]} />
        </mesh>
        <mesh name="M_UMU3_F_A004" geometry={nodes.M_UMU3_F_A004.geometry} material={nodes.M_UMU3_F_A004.material} position={[2.495, 1.75, 2.599]} />
        <mesh name="M_UMU3_F_B004" geometry={nodes.M_UMU3_F_B004.geometry} material={nodes.M_UMU3_F_B004.material} position={[2.495, 1.749, 2.599]} />
        <mesh name="M_UMU3_F_C004" geometry={nodes.M_UMU3_F_C004.geometry} material={nodes.M_UMU3_F_C004.material} position={[2.495, 1.745, 2.599]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU3_1.glb')
