/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU3_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU3_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU3_5_F_5obj" scale={0.593}>
        <mesh name="M_UMU3_1_F001" geometry={nodes.M_UMU3_1_F001.geometry} material={nodes.M_UMU3_1_F001.material} position={[3.491, 1.751, 2.606]}>
          <mesh name="M_UMU3_5_PNT_H" geometry={nodes.M_UMU3_5_PNT_H.geometry} material={nodes.M_UMU3_5_PNT_H.material} position={[-3.491, -2.852, 0.13]} />
        </mesh>
        <mesh name="M_UMU3_5" geometry={nodes.M_UMU3_5.geometry} material={nodes.M_UMU3_5.material} />
        <mesh name="M_UMU3_F_A001" geometry={nodes.M_UMU3_F_A001.geometry} material={nodes.M_UMU3_F_A001.material} position={[3.489, 1.75, 2.599]} />
        <mesh name="M_UMU3_F_B001" geometry={nodes.M_UMU3_F_B001.geometry} material={nodes.M_UMU3_F_B001.material} position={[3.489, 1.749, 2.599]} />
        <mesh name="M_UMU3_F_C001" geometry={nodes.M_UMU3_F_C001.geometry} material={nodes.M_UMU3_F_C001.material} position={[3.489, 1.745, 2.599]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU3_5.glb')
