/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMB_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMB_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMB_5obj" scale={1.052}>
        <mesh name="M_UMA_11_F001" geometry={nodes.M_UMA_11_F001.geometry} material={nodes.M_UMA_11_F001.material} position={[1.987, 0, 1.445]}>
          <mesh name="M_UMB_4_PNT_H001" geometry={nodes.M_UMB_4_PNT_H001.geometry} material={nodes.M_UMB_4_PNT_H001.material} position={[-1.987, -2.579, 0.17]} />
          <mesh name="M_UMB_4_PNT_V001" geometry={nodes.M_UMB_4_PNT_V001.geometry} material={nodes.M_UMB_4_PNT_V001.material} position={[-2.986, -1.744, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F_A001" geometry={nodes.M_UMA_1_F_A001.geometry} material={nodes.M_UMA_1_F_A001.material} position={[1.992, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B001" geometry={nodes.M_UMA_1_F_B001.geometry} material={nodes.M_UMA_1_F_B001.material} position={[1.992, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C001" geometry={nodes.M_UMA_1_F_C001.geometry} material={nodes.M_UMA_1_F_C001.material} position={[1.992, 0.51, 1.435]} />
        <mesh name="M_UMB_5" geometry={nodes.M_UMB_5.geometry} material={nodes.M_UMB_5.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMB_5.glb')
