/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMB_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMB_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMB_3obj" scale={1.052}>
        <mesh name="M_UMA_11_F018" geometry={nodes.M_UMA_11_F018.geometry} material={nodes.M_UMA_11_F018.material} position={[1.488, 0, 1.445]}>
          <mesh name="M_UMB_3_PNT" geometry={nodes.M_UMB_3_PNT.geometry} material={nodes.M_UMB_3_PNT.material} position={[-1.491, -1.744, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F_A018" geometry={nodes.M_UMA_1_F_A018.geometry} material={nodes.M_UMA_1_F_A018.material} position={[1.494, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B018" geometry={nodes.M_UMA_1_F_B018.geometry} material={nodes.M_UMA_1_F_B018.material} position={[1.494, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C018" geometry={nodes.M_UMA_1_F_C018.geometry} material={nodes.M_UMA_1_F_C018.material} position={[1.494, 0.51, 1.435]} />
        <mesh name="M_UMB_3" geometry={nodes.M_UMB_3.geometry} material={nodes.M_UMB_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMB_3.glb')
