/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMB_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMB_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMB_7obj" scale={1.052}>
        <mesh name="M_UMA_11_F003" geometry={nodes.M_UMA_11_F003.geometry} material={nodes.M_UMA_11_F003.material} position={[-2.484, 0, 1.445]}>
          <mesh name="M_UMB_7_PNT" geometry={nodes.M_UMB_7_PNT.geometry} material={nodes.M_UMB_7_PNT.material} position={[1.467, -1.725, 0.17]} />
        </mesh>
        <mesh name="M_UMA_11_F004" geometry={nodes.M_UMA_11_F004.geometry} material={nodes.M_UMA_11_F004.material} position={[2.492, 0, 1.445]}>
          <mesh name="M_UMB_7_PNT001" geometry={nodes.M_UMB_7_PNT001.geometry} material={nodes.M_UMB_7_PNT001.material} position={[-1.475, -1.721, 0.17]} rotation={[Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMA_1_F_A003" geometry={nodes.M_UMA_1_F_A003.geometry} material={nodes.M_UMA_1_F_A003.material} position={[-2.489, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_A004" geometry={nodes.M_UMA_1_F_A004.geometry} material={nodes.M_UMA_1_F_A004.material} position={[2.498, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B003" geometry={nodes.M_UMA_1_F_B003.geometry} material={nodes.M_UMA_1_F_B003.material} position={[-2.493, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B004" geometry={nodes.M_UMA_1_F_B004.geometry} material={nodes.M_UMA_1_F_B004.material} position={[2.498, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C003" geometry={nodes.M_UMA_1_F_C003.geometry} material={nodes.M_UMA_1_F_C003.material} position={[-2.494, 0.51, 1.435]} />
        <mesh name="M_UMA_1_F_C004" geometry={nodes.M_UMA_1_F_C004.geometry} material={nodes.M_UMA_1_F_C004.material} position={[2.498, 0.51, 1.435]} />
        <mesh name="M_UMB_7" geometry={nodes.M_UMB_7.geometry} material={nodes.M_UMB_7.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMB_7.glb')
