/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMB_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMB_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMB_1_F_1obj" scale={1.052}>
        <mesh name="M_UMA_11_F" geometry={nodes.M_UMA_11_F.geometry} material={nodes.M_UMA_11_F.material} position={[1.004, 0, 1.441]}>
          <mesh name="M_UMB_2_PNT" geometry={nodes.M_UMB_2_PNT.geometry} material={nodes.M_UMB_2_PNT.material} position={[-1.004, -1.744, 0.174]} />
        </mesh>
        <mesh name="M_UMA_1_F_A" geometry={nodes.M_UMA_1_F_A.geometry} material={nodes.M_UMA_1_F_A.material} position={[0.994, 1.805, 1.436]} />
        <mesh name="M_UMA_1_F_B" geometry={nodes.M_UMA_1_F_B.geometry} material={nodes.M_UMA_1_F_B.material} position={[0.994, 1.805, 1.436]} />
        <mesh name="M_UMA_1_F_C" geometry={nodes.M_UMA_1_F_C.geometry} material={nodes.M_UMA_1_F_C.material} position={[0.994, 0.51, 1.436]} />
        <mesh name="M_UMB_1" geometry={nodes.M_UMB_1.geometry} material={nodes.M_UMB_1.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMB_1.glb')
