/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMB_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMB_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMB_2obj" scale={1.052}>
        <mesh name="M_UMA_11_F017" geometry={nodes.M_UMA_11_F017.geometry} material={nodes.M_UMA_11_F017.material} position={[1.239, 0, 1.445]}>
          <mesh name="M_UMB_2_PNT001" geometry={nodes.M_UMB_2_PNT001.geometry} material={nodes.M_UMB_2_PNT001.material} position={[-1.239, -1.744, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F_A017" geometry={nodes.M_UMA_1_F_A017.geometry} material={nodes.M_UMA_1_F_A017.material} position={[1.244, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B017" geometry={nodes.M_UMA_1_F_B017.geometry} material={nodes.M_UMA_1_F_B017.material} position={[1.244, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C017" geometry={nodes.M_UMA_1_F_C017.geometry} material={nodes.M_UMA_1_F_C017.material} position={[1.244, 0.51, 1.435]} />
        <mesh name="M_UMB_2" geometry={nodes.M_UMB_2.geometry} material={nodes.M_UMB_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMB_2.glb')
