/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMB_10.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMB_10.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMB_10obj" scale={1.052}>
        <mesh name="M_UMA_11_F009" geometry={nodes.M_UMA_11_F009.geometry} material={nodes.M_UMA_11_F009.material} position={[-3.236, 0, 1.445]}>
          <mesh name="M_UMB_10_PNT_H" geometry={nodes.M_UMB_10_PNT_H.geometry} material={nodes.M_UMB_10_PNT_H.material} position={[1.607, -2.572, 0.17]} />
          <mesh name="M_UMB_10_PNT_V" geometry={nodes.M_UMB_10_PNT_V.geometry} material={nodes.M_UMB_10_PNT_V.material} position={[2.219, -1.725, 0.17]} />
        </mesh>
        <mesh name="M_UMA_11_F010" geometry={nodes.M_UMA_11_F010.geometry} material={nodes.M_UMA_11_F010.material} position={[3.242, 0, 1.445]}>
          <mesh name="M_UMB_10_PNT_H_1" geometry={nodes.M_UMB_10_PNT_H_1.geometry} material={nodes.M_UMB_10_PNT_H_1.material} position={[-1.613, -2.572, 0.17]} rotation={[Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UMB_10_PNT_V_1" geometry={nodes.M_UMB_10_PNT_V_1.geometry} material={nodes.M_UMB_10_PNT_V_1.material} position={[-2.225, -1.721, 0.17]} rotation={[Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMA_1_F_A009" geometry={nodes.M_UMA_1_F_A009.geometry} material={nodes.M_UMA_1_F_A009.material} position={[-3.241, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_A010" geometry={nodes.M_UMA_1_F_A010.geometry} material={nodes.M_UMA_1_F_A010.material} position={[3.247, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B009" geometry={nodes.M_UMA_1_F_B009.geometry} material={nodes.M_UMA_1_F_B009.material} position={[-3.245, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B010" geometry={nodes.M_UMA_1_F_B010.geometry} material={nodes.M_UMA_1_F_B010.material} position={[3.247, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C009" geometry={nodes.M_UMA_1_F_C009.geometry} material={nodes.M_UMA_1_F_C009.material} position={[-3.246, 0.51, 1.435]} />
        <mesh name="M_UMA_1_F_C010" geometry={nodes.M_UMA_1_F_C010.geometry} material={nodes.M_UMA_1_F_C010.material} position={[3.247, 0.51, 1.435]} />
        <mesh name="M_UMB_10" geometry={nodes.M_UMB_10.geometry} material={nodes.M_UMB_10.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMB_10.glb')
