/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMB_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMB_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMB_6obj" scale={1.052}>
        <mesh name="M_UMA_11_F002" geometry={nodes.M_UMA_11_F002.geometry} material={nodes.M_UMA_11_F002.material} position={[2.24, 0, 1.445]}>
          <mesh name="M_UMB_6_PNT_H" geometry={nodes.M_UMB_6_PNT_H.geometry} material={nodes.M_UMB_6_PNT_H.material} position={[-2.24, -2.579, 0.17]} />
          <mesh name="M_UMB_6_PNT_V" geometry={nodes.M_UMB_6_PNT_V.geometry} material={nodes.M_UMB_6_PNT_V.material} position={[-3.498, -1.744, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F_A002" geometry={nodes.M_UMA_1_F_A002.geometry} material={nodes.M_UMA_1_F_A002.material} position={[2.246, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B002" geometry={nodes.M_UMA_1_F_B002.geometry} material={nodes.M_UMA_1_F_B002.material} position={[2.246, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C002" geometry={nodes.M_UMA_1_F_C002.geometry} material={nodes.M_UMA_1_F_C002.material} position={[2.246, 0.51, 1.435]} />
        <mesh name="M_UMB_6" geometry={nodes.M_UMB_6.geometry} material={nodes.M_UMB_6.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMB_6.glb')
