/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMB_9.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMB_9.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMB_9obj" scale={1.052}>
        <mesh name="M_UMA_11_F007" geometry={nodes.M_UMA_11_F007.geometry} material={nodes.M_UMA_11_F007.material} position={[-2.984, 0, 1.445]}>
          <mesh name="M_UMB_9_PNT001" geometry={nodes.M_UMB_9_PNT001.geometry} material={nodes.M_UMB_9_PNT001.material} position={[1.967, -1.725, 0.17]} />
        </mesh>
        <mesh name="M_UMA_11_F008" geometry={nodes.M_UMA_11_F008.geometry} material={nodes.M_UMA_11_F008.material} position={[2.987, 0, 1.445]}>
          <mesh name="M_UMB_9_PNT" geometry={nodes.M_UMB_9_PNT.geometry} material={nodes.M_UMB_9_PNT.material} position={[-1.97, -1.721, 0.17]} rotation={[Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMA_1_F_A007" geometry={nodes.M_UMA_1_F_A007.geometry} material={nodes.M_UMA_1_F_A007.material} position={[-2.99, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_A008" geometry={nodes.M_UMA_1_F_A008.geometry} material={nodes.M_UMA_1_F_A008.material} position={[2.993, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B007" geometry={nodes.M_UMA_1_F_B007.geometry} material={nodes.M_UMA_1_F_B007.material} position={[-2.994, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B008" geometry={nodes.M_UMA_1_F_B008.geometry} material={nodes.M_UMA_1_F_B008.material} position={[2.993, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C007" geometry={nodes.M_UMA_1_F_C007.geometry} material={nodes.M_UMA_1_F_C007.material} position={[-2.994, 0.51, 1.435]} />
        <mesh name="M_UMA_1_F_C008" geometry={nodes.M_UMA_1_F_C008.geometry} material={nodes.M_UMA_1_F_C008.material} position={[2.993, 0.51, 1.435]} />
        <mesh name="M_UMB_9" geometry={nodes.M_UMB_9.geometry} material={nodes.M_UMB_9.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMB_9.glb')
