/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMB_13.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMB_13.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMB_13obj" scale={1.052}>
        <mesh name="M_UMA_11_F015" geometry={nodes.M_UMA_11_F015.geometry} material={nodes.M_UMA_11_F015.material} position={[-3.981, 0, 1.445]}>
          <mesh name="M_UMB_13_PNT_H" geometry={nodes.M_UMB_13_PNT_H.geometry} material={nodes.M_UMB_13_PNT_H.material} position={[1.98, -2.572, 0.17]} />
          <mesh name="M_UMB_13_PNT_V" geometry={nodes.M_UMB_13_PNT_V.geometry} material={nodes.M_UMB_13_PNT_V.material} position={[2.964, -1.725, 0.17]} />
        </mesh>
        <mesh name="M_UMA_11_F016" geometry={nodes.M_UMA_11_F016.geometry} material={nodes.M_UMA_11_F016.material} position={[3.988, 0, 1.445]}>
          <mesh name="M_UMB_13_PNT_H_1" geometry={nodes.M_UMB_13_PNT_H_1.geometry} material={nodes.M_UMB_13_PNT_H_1.material} position={[-1.987, -2.572, 0.17]} rotation={[Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UMB_13_PNT_V_1" geometry={nodes.M_UMB_13_PNT_V_1.geometry} material={nodes.M_UMB_13_PNT_V_1.material} position={[-2.971, -1.721, 0.17]} rotation={[Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMA_1_F_A015" geometry={nodes.M_UMA_1_F_A015.geometry} material={nodes.M_UMA_1_F_A015.material} position={[-3.987, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_A016" geometry={nodes.M_UMA_1_F_A016.geometry} material={nodes.M_UMA_1_F_A016.material} position={[3.994, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B015" geometry={nodes.M_UMA_1_F_B015.geometry} material={nodes.M_UMA_1_F_B015.material} position={[-3.991, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B016" geometry={nodes.M_UMA_1_F_B016.geometry} material={nodes.M_UMA_1_F_B016.material} position={[3.994, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C015" geometry={nodes.M_UMA_1_F_C015.geometry} material={nodes.M_UMA_1_F_C015.material} position={[-3.991, 0.51, 1.435]} />
        <mesh name="M_UMA_1_F_C016" geometry={nodes.M_UMA_1_F_C016.geometry} material={nodes.M_UMA_1_F_C016.material} position={[3.994, 0.51, 1.435]} />
        <mesh name="M_UMB_13" geometry={nodes.M_UMB_13.geometry} material={nodes.M_UMB_13.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMB_13.glb')
