/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMB_8.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMB_8.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMB_8obj" scale={1.052}>
        <mesh name="M_UMA_11_F005" geometry={nodes.M_UMA_11_F005.geometry} material={nodes.M_UMA_11_F005.material} position={[-2.732, 0, 1.445]}>
          <mesh name="M_UMB_8_PNT001" geometry={nodes.M_UMB_8_PNT001.geometry} material={nodes.M_UMB_8_PNT001.material} position={[1.715, -1.725, 0.17]} />
        </mesh>
        <mesh name="M_UMA_11_F006" geometry={nodes.M_UMA_11_F006.geometry} material={nodes.M_UMA_11_F006.material} position={[2.737, 0, 1.445]}>
          <mesh name="M_UMB_8_PNT" geometry={nodes.M_UMB_8_PNT.geometry} material={nodes.M_UMB_8_PNT.material} position={[-1.72, -1.721, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMA_1_F_A005" geometry={nodes.M_UMA_1_F_A005.geometry} material={nodes.M_UMA_1_F_A005.material} position={[-2.737, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_A006" geometry={nodes.M_UMA_1_F_A006.geometry} material={nodes.M_UMA_1_F_A006.material} position={[2.743, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B005" geometry={nodes.M_UMA_1_F_B005.geometry} material={nodes.M_UMA_1_F_B005.material} position={[-2.741, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B006" geometry={nodes.M_UMA_1_F_B006.geometry} material={nodes.M_UMA_1_F_B006.material} position={[2.743, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C005" geometry={nodes.M_UMA_1_F_C005.geometry} material={nodes.M_UMA_1_F_C005.material} position={[-2.742, 0.51, 1.435]} />
        <mesh name="M_UMA_1_F_C006" geometry={nodes.M_UMA_1_F_C006.geometry} material={nodes.M_UMA_1_F_C006.material} position={[2.743, 0.51, 1.435]} />
        <mesh name="M_UMB_8" geometry={nodes.M_UMB_8.geometry} material={nodes.M_UMB_8.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMB_8.glb')
