/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMB_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMB_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMB_4obj" scale={1.052}>
        <mesh name="M_UMA_11_F019" geometry={nodes.M_UMA_11_F019.geometry} material={nodes.M_UMA_11_F019.material} position={[1.73, 0, 1.445]}>
          <mesh name="M_UMB_4_PNT_H" geometry={nodes.M_UMB_4_PNT_H.geometry} material={nodes.M_UMB_4_PNT_H.material} position={[-1.73, -2.579, 0.17]} />
          <mesh name="M_UMB_4_PNT_V" geometry={nodes.M_UMB_4_PNT_V.geometry} material={nodes.M_UMB_4_PNT_V.material} position={[-2.476, -1.744, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F_A019" geometry={nodes.M_UMA_1_F_A019.geometry} material={nodes.M_UMA_1_F_A019.material} position={[1.735, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B019" geometry={nodes.M_UMA_1_F_B019.geometry} material={nodes.M_UMA_1_F_B019.material} position={[1.735, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C019" geometry={nodes.M_UMA_1_F_C019.geometry} material={nodes.M_UMA_1_F_C019.material} position={[1.735, 0.51, 1.435]} />
        <mesh name="M_UMB_4" geometry={nodes.M_UMB_4.geometry} material={nodes.M_UMB_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMB_4.glb')
