/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMB_12.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMB_12.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMB_12obj" scale={1.052}>
        <mesh name="M_UMA_11_F013" geometry={nodes.M_UMA_11_F013.geometry} material={nodes.M_UMA_11_F013.material} position={[-3.737, 0, 1.445]}>
          <mesh name="M_UMB_12_PNT_H" geometry={nodes.M_UMB_12_PNT_H.geometry} material={nodes.M_UMB_12_PNT_H.material} position={[1.83, -2.572, 0.17]} />
          <mesh name="M_UMB_12_PNT_V" geometry={nodes.M_UMB_12_PNT_V.geometry} material={nodes.M_UMB_12_PNT_V.material} position={[2.721, -1.725, 0.17]} />
        </mesh>
        <mesh name="M_UMA_11_F014" geometry={nodes.M_UMA_11_F014.geometry} material={nodes.M_UMA_11_F014.material} position={[3.727, 0, 1.445]}>
          <mesh name="M_UMB_12_PNT_H_1" geometry={nodes.M_UMB_12_PNT_H_1.geometry} material={nodes.M_UMB_12_PNT_H_1.material} position={[-1.82, -2.572, 0.17]} rotation={[Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UMB_12_PNT_V_1" geometry={nodes.M_UMB_12_PNT_V_1.geometry} material={nodes.M_UMB_12_PNT_V_1.material} position={[-2.711, -1.721, 0.17]} rotation={[Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMA_1_F_A013" geometry={nodes.M_UMA_1_F_A013.geometry} material={nodes.M_UMA_1_F_A013.material} position={[-3.743, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_A014" geometry={nodes.M_UMA_1_F_A014.geometry} material={nodes.M_UMA_1_F_A014.material} position={[3.733, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B013" geometry={nodes.M_UMA_1_F_B013.geometry} material={nodes.M_UMA_1_F_B013.material} position={[-3.747, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B014" geometry={nodes.M_UMA_1_F_B014.geometry} material={nodes.M_UMA_1_F_B014.material} position={[3.733, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C013" geometry={nodes.M_UMA_1_F_C013.geometry} material={nodes.M_UMA_1_F_C013.material} position={[-3.747, 0.51, 1.435]} />
        <mesh name="M_UMA_1_F_C014" geometry={nodes.M_UMA_1_F_C014.geometry} material={nodes.M_UMA_1_F_C014.material} position={[3.733, 0.51, 1.435]} />
        <mesh name="M_UMB_12" geometry={nodes.M_UMB_12.geometry} material={nodes.M_UMB_12.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMB_12.glb')
