/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMB_11.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMB_11.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMB_11obj" scale={1.052}>
        <mesh name="M_UMA_11_F011" geometry={nodes.M_UMA_11_F011.geometry} material={nodes.M_UMA_11_F011.material} position={[-3.479, 0, 1.445]}>
          <mesh name="M_UMB_11_PNT_H" geometry={nodes.M_UMB_11_PNT_H.geometry} material={nodes.M_UMB_11_PNT_H.material} position={[1.688, -2.572, 0.17]} />
          <mesh name="M_UMB_11_PNT_V" geometry={nodes.M_UMB_11_PNT_V.geometry} material={nodes.M_UMB_11_PNT_V.material} position={[2.462, -1.725, 0.17]} />
        </mesh>
        <mesh name="M_UMA_11_F012" geometry={nodes.M_UMA_11_F012.geometry} material={nodes.M_UMA_11_F012.material} position={[3.487, 0, 1.445]}>
          <mesh name="M_UMB_11_PNT_H_1" geometry={nodes.M_UMB_11_PNT_H_1.geometry} material={nodes.M_UMB_11_PNT_H_1.material} position={[-1.696, -2.572, 0.17]} rotation={[Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UMB_11_PNT_V_1" geometry={nodes.M_UMB_11_PNT_V_1.geometry} material={nodes.M_UMB_11_PNT_V_1.material} position={[-2.47, -1.721, 0.17]} rotation={[Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMA_1_F_A011" geometry={nodes.M_UMA_1_F_A011.geometry} material={nodes.M_UMA_1_F_A011.material} position={[-3.485, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_A012" geometry={nodes.M_UMA_1_F_A012.geometry} material={nodes.M_UMA_1_F_A012.material} position={[3.493, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B011" geometry={nodes.M_UMA_1_F_B011.geometry} material={nodes.M_UMA_1_F_B011.material} position={[-3.488, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B012" geometry={nodes.M_UMA_1_F_B012.geometry} material={nodes.M_UMA_1_F_B012.material} position={[3.493, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C011" geometry={nodes.M_UMA_1_F_C011.geometry} material={nodes.M_UMA_1_F_C011.material} position={[-3.489, 0.51, 1.435]} />
        <mesh name="M_UMA_1_F_C012" geometry={nodes.M_UMA_1_F_C012.geometry} material={nodes.M_UMA_1_F_C012.material} position={[3.493, 0.51, 1.435]} />
        <mesh name="M_UMB_11" geometry={nodes.M_UMB_11.geometry} material={nodes.M_UMB_11.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMB_11.glb')
