/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_MU_1_F_2_NN.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_MU_1_F_2_NN.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_MU_1_F_1_NNobj" scale={1.049}>
        <mesh name="Legs" geometry={nodes.Legs.geometry} material={nodes.Legs.material} position={[0.01, -3.575, -0.226]} />
        <mesh name="M_MJ_1_F_A2" geometry={nodes.M_MJ_1_F_A2.geometry} material={nodes.M_MJ_1_F_A2.material} position={[4.493, 1.531, 2.702]} />
        <mesh name="M_MU_1" geometry={nodes.M_MU_1.geometry} material={materials['wire_153228184.045']} />
        <mesh name="M_MU_1_F2" geometry={nodes.M_MU_1_F2.geometry} material={nodes.M_MU_1_F2.material} position={[4.495, 0.441, 2.71]}>
          <mesh name="M_MU_1_PNT_H" geometry={nodes.M_MU_1_PNT_H.geometry} material={nodes.M_MU_1_PNT_H.material} position={[-2.008, 2.939, 0.089]} />
          <mesh name="M_MU_1_PNT_V" geometry={nodes.M_MU_1_PNT_V.geometry} material={nodes.M_MU_1_PNT_V.material} position={[-3.255, 2.116, 0.089]} />
        </mesh>
        <mesh name="M_MU_1_F_B2" geometry={nodes.M_MU_1_F_B2.geometry} material={nodes.M_MU_1_F_B2.material} position={[4.493, 1.531, 2.702]} />
        <mesh name="M_MU_1_F_C2" geometry={nodes.M_MU_1_F_C2.geometry} material={nodes.M_MU_1_F_C2.material} position={[4.493, 0.749, 2.702]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_MU_1_F_2_NN.glb')
