/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT2_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT2_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT2_2obj" scale={1.638}>
        <mesh name="M_UMT2_1_F013" geometry={nodes.M_UMT2_1_F013.geometry} material={nodes.M_UMT2_1_F013.material} position={[1.758, 2.954, 0.922]}>
          <mesh name="M_UMT2_1_F012" geometry={nodes.M_UMT2_1_F012.geometry} material={nodes.M_UMT2_1_F012.material} position={[0, -2.952, 0]}>
            <mesh name="M_UMT2_2_PNT001" geometry={nodes.M_UMT2_2_PNT001.geometry} material={nodes.M_UMT2_2_PNT001.material} position={[-1.758, -2.437, 0.114]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT2_1_F_A013" geometry={nodes.M_UMT2_1_F_A013.geometry} material={nodes.M_UMT2_1_F_A013.material} position={[1.757, 2.953, 0.916]}>
          <mesh name="M_UMT2_1_F_A012" geometry={nodes.M_UMT2_1_F_A012.geometry} material={nodes.M_UMT2_1_F_A012.material} position={[0, -2.952, 0]} />
        </mesh>
        <mesh name="M_UMT2_1_F_B013" geometry={nodes.M_UMT2_1_F_B013.geometry} material={nodes.M_UMT2_1_F_B013.material} position={[1.757, 2.952, 0.916]}>
          <mesh name="M_UMT2_1_F_B012" geometry={nodes.M_UMT2_1_F_B012.geometry} material={nodes.M_UMT2_1_F_B012.material} position={[0, -2.952, 0]} />
        </mesh>
        <mesh name="M_UMT2_1_F_C013" geometry={nodes.M_UMT2_1_F_C013.geometry} material={nodes.M_UMT2_1_F_C013.material} position={[1.757, 2.949, 0.916]}>
          <mesh name="M_UMT2_1_F_C012" geometry={nodes.M_UMT2_1_F_C012.geometry} material={nodes.M_UMT2_1_F_C012.material} position={[0, -2.952, 0]} />
        </mesh>
        <mesh name="M_UMT2_2" geometry={nodes.M_UMT2_2.geometry} material={nodes.M_UMT2_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT2_2.glb')
