/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT2_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT2_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT2_1obj" scale={1.634}>
        <mesh name="M_UMT2_1" geometry={nodes.M_UMT2_1.geometry} material={nodes.M_UMT2_1.material} />
        <mesh name="M_UMT2_1_F011" geometry={nodes.M_UMT2_1_F011.geometry} material={nodes.M_UMT2_1_F011.material} position={[1.605, 2.96, 0.924]}>
          <mesh name="M_UMT2_1_F010" geometry={nodes.M_UMT2_1_F010.geometry} material={nodes.M_UMT2_1_F010.material} position={[0, -2.958, 0]}>
            <mesh name="M_UMT2_1_PNT001" geometry={nodes.M_UMT2_1_PNT001.geometry} material={nodes.M_UMT2_1_PNT001.material} position={[-1.605, -2.442, 0.115]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT2_1_F_A011" geometry={nodes.M_UMT2_1_F_A011.geometry} material={nodes.M_UMT2_1_F_A011.material} position={[1.603, 2.96, 0.918]}>
          <mesh name="M_UMT2_1_F_A010" geometry={nodes.M_UMT2_1_F_A010.geometry} material={nodes.M_UMT2_1_F_A010.material} position={[0, -2.958, 0]} />
        </mesh>
        <mesh name="M_UMT2_1_F_B011" geometry={nodes.M_UMT2_1_F_B011.geometry} material={nodes.M_UMT2_1_F_B011.material} position={[1.603, 2.958, 0.918]}>
          <mesh name="M_UMT2_1_F_B010" geometry={nodes.M_UMT2_1_F_B010.geometry} material={nodes.M_UMT2_1_F_B010.material} position={[0, -2.958, 0]} />
        </mesh>
        <mesh name="M_UMT2_1_F_C011" geometry={nodes.M_UMT2_1_F_C011.geometry} material={nodes.M_UMT2_1_F_C011.material} position={[1.603, 2.955, 0.918]}>
          <mesh name="M_UMT2_1_F_C010" geometry={nodes.M_UMT2_1_F_C010.geometry} material={nodes.M_UMT2_1_F_C010.material} position={[0, -2.958, 0]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT2_1.glb')
