/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT2_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT2_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT2_7obj" scale={1.621}>
        <mesh name="M_UMT2_1_F009" geometry={nodes.M_UMT2_1_F009.geometry} material={nodes.M_UMT2_1_F009.material} position={[2.586, 2.984, 0.932]}>
          <mesh name="M_UMT2_1_F008" geometry={nodes.M_UMT2_1_F008.geometry} material={nodes.M_UMT2_1_F008.material} position={[0, -2.982, 0]}>
            <mesh name="M_UMT2_7_PNT001" geometry={nodes.M_UMT2_7_PNT001.geometry} material={nodes.M_UMT2_7_PNT001.material} position={[-2.586, -2.462, 0.116]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT2_1_F_A009" geometry={nodes.M_UMT2_1_F_A009.geometry} material={nodes.M_UMT2_1_F_A009.material} position={[2.584, 2.984, 0.926]}>
          <mesh name="M_UMT2_1_F_A008" geometry={nodes.M_UMT2_1_F_A008.geometry} material={nodes.M_UMT2_1_F_A008.material} position={[0, -2.982, 0]} />
        </mesh>
        <mesh name="M_UMT2_1_F_B009" geometry={nodes.M_UMT2_1_F_B009.geometry} material={nodes.M_UMT2_1_F_B009.material} position={[2.584, 2.983, 0.926]}>
          <mesh name="M_UMT2_1_F_B008" geometry={nodes.M_UMT2_1_F_B008.geometry} material={nodes.M_UMT2_1_F_B008.material} position={[0, -2.982, 0]} />
        </mesh>
        <mesh name="M_UMT2_1_F_C009" geometry={nodes.M_UMT2_1_F_C009.geometry} material={nodes.M_UMT2_1_F_C009.material} position={[2.584, 2.98, 0.926]}>
          <mesh name="M_UMT2_1_F_C008" geometry={nodes.M_UMT2_1_F_C008.geometry} material={nodes.M_UMT2_1_F_C008.material} position={[0, -2.982, 0]} />
        </mesh>
        <mesh name="M_UMT2_7" geometry={nodes.M_UMT2_7.geometry} material={nodes.M_UMT2_7.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT2_7.glb')
