/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT2_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT2_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT2_4obj" scale={1.628}>
        <mesh name="M_UMT2_1_F003" geometry={nodes.M_UMT2_1_F003.geometry} material={nodes.M_UMT2_1_F003.material} position={[2.092, 2.971, 0.928]}>
          <mesh name="M_UMT2_1_F002" geometry={nodes.M_UMT2_1_F002.geometry} material={nodes.M_UMT2_1_F002.material} position={[0, -2.969, 0]}>
            <mesh name="M_UMT2_4_PNT001" geometry={nodes.M_UMT2_4_PNT001.geometry} material={nodes.M_UMT2_4_PNT001.material} position={[-2.092, -2.451, 0.115]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT2_1_F_A003" geometry={nodes.M_UMT2_1_F_A003.geometry} material={nodes.M_UMT2_1_F_A003.material} position={[2.09, 2.971, 0.922]}>
          <mesh name="M_UMT2_1_F_A002" geometry={nodes.M_UMT2_1_F_A002.geometry} material={nodes.M_UMT2_1_F_A002.material} position={[0, -2.969, 0]} />
        </mesh>
        <mesh name="M_UMT2_1_F_B003" geometry={nodes.M_UMT2_1_F_B003.geometry} material={nodes.M_UMT2_1_F_B003.material} position={[2.09, 2.969, 0.922]}>
          <mesh name="M_UMT2_1_F_B002" geometry={nodes.M_UMT2_1_F_B002.geometry} material={nodes.M_UMT2_1_F_B002.material} position={[0, -2.969, 0]} />
        </mesh>
        <mesh name="M_UMT2_1_F_C003" geometry={nodes.M_UMT2_1_F_C003.geometry} material={nodes.M_UMT2_1_F_C003.material} position={[2.09, 2.967, 0.922]}>
          <mesh name="M_UMT2_1_F_C002" geometry={nodes.M_UMT2_1_F_C002.geometry} material={nodes.M_UMT2_1_F_C002.material} position={[0, -2.969, 0]} />
        </mesh>
        <mesh name="M_UMT2_4" geometry={nodes.M_UMT2_4.geometry} material={nodes.M_UMT2_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT2_4.glb')
