/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT2_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT2_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT2_3obj" scale={1.629}>
        <mesh name="M_UMT2_1_F001" geometry={nodes.M_UMT2_1_F001.geometry} material={nodes.M_UMT2_1_F001.material} position={[1.929, 2.97, 0.927]}>
          <mesh name="M_UMT2_1_F" geometry={nodes.M_UMT2_1_F.geometry} material={nodes.M_UMT2_1_F.material} position={[0, -2.968, 0]}>
            <mesh name="M_UMT2_3_PNT001" geometry={nodes.M_UMT2_3_PNT001.geometry} material={nodes.M_UMT2_3_PNT001.material} position={[-1.929, -2.451, 0.115]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT2_1_F_A001" geometry={nodes.M_UMT2_1_F_A001.geometry} material={nodes.M_UMT2_1_F_A001.material} position={[1.927, 2.97, 0.921]}>
          <mesh name="M_UMT2_1_F_A" geometry={nodes.M_UMT2_1_F_A.geometry} material={nodes.M_UMT2_1_F_A.material} position={[0, -2.968, 0]} />
        </mesh>
        <mesh name="M_UMT2_1_F_B001" geometry={nodes.M_UMT2_1_F_B001.geometry} material={nodes.M_UMT2_1_F_B001.material} position={[1.927, 2.969, 0.921]}>
          <mesh name="M_UMT2_1_F_B" geometry={nodes.M_UMT2_1_F_B.geometry} material={nodes.M_UMT2_1_F_B.material} position={[0, -2.968, 0]} />
        </mesh>
        <mesh name="M_UMT2_1_F_C001" geometry={nodes.M_UMT2_1_F_C001.geometry} material={nodes.M_UMT2_1_F_C001.material} position={[1.927, 2.966, 0.921]}>
          <mesh name="M_UMT2_1_F_C" geometry={nodes.M_UMT2_1_F_C.geometry} material={nodes.M_UMT2_1_F_C.material} position={[0, -2.968, 0]} />
        </mesh>
        <mesh name="M_UMT2_3" geometry={nodes.M_UMT2_3.geometry} material={nodes.M_UMT2_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT2_3.glb')
