/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT2_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT2_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT2_6obj" scale={1.623}>
        <mesh name="M_UMT2_1_F007" geometry={nodes.M_UMT2_1_F007.geometry} material={nodes.M_UMT2_1_F007.material} position={[2.423, 2.982, 0.931]}>
          <mesh name="M_UMT2_1_F006" geometry={nodes.M_UMT2_1_F006.geometry} material={nodes.M_UMT2_1_F006.material} position={[0, -2.98, 0]}>
            <mesh name="M_UMT2_6_PNT001" geometry={nodes.M_UMT2_6_PNT001.geometry} material={nodes.M_UMT2_6_PNT001.material} position={[-2.423, -2.46, 0.115]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT2_1_F_A007" geometry={nodes.M_UMT2_1_F_A007.geometry} material={nodes.M_UMT2_1_F_A007.material} position={[2.422, 2.981, 0.925]}>
          <mesh name="M_UMT2_1_F_A006" geometry={nodes.M_UMT2_1_F_A006.geometry} material={nodes.M_UMT2_1_F_A006.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT2_1_F_B007" geometry={nodes.M_UMT2_1_F_B007.geometry} material={nodes.M_UMT2_1_F_B007.material} position={[2.422, 2.98, 0.925]}>
          <mesh name="M_UMT2_1_F_B006" geometry={nodes.M_UMT2_1_F_B006.geometry} material={nodes.M_UMT2_1_F_B006.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT2_1_F_C007" geometry={nodes.M_UMT2_1_F_C007.geometry} material={nodes.M_UMT2_1_F_C007.material} position={[2.422, 2.977, 0.925]}>
          <mesh name="M_UMT2_1_F_C006" geometry={nodes.M_UMT2_1_F_C006.geometry} material={nodes.M_UMT2_1_F_C006.material} position={[0, -2.98, 0]} />
        </mesh>
        <mesh name="M_UMT2_6" geometry={nodes.M_UMT2_6.geometry} material={nodes.M_UMT2_6.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT2_6.glb')
