/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMT2_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMT2_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMT2_5obj" scale={1.62}>
        <mesh name="M_UMT2_1_F005" geometry={nodes.M_UMT2_1_F005.geometry} material={nodes.M_UMT2_1_F005.material} position={[-2.266, 2.985, 0.932]}>
          <mesh name="M_UMT2_1_F004" geometry={nodes.M_UMT2_1_F004.geometry} material={nodes.M_UMT2_1_F004.material} position={[0, -2.983, 0]}>
            <mesh name="M_UMT2_5_PNT001" geometry={nodes.M_UMT2_5_PNT001.geometry} material={nodes.M_UMT2_5_PNT001.material} position={[2.266, -2.462, 0.116]} />
          </mesh>
        </mesh>
        <mesh name="M_UMT2_1_F_A005" geometry={nodes.M_UMT2_1_F_A005.geometry} material={nodes.M_UMT2_1_F_A005.material} position={[-2.264, 2.984, 0.926]}>
          <mesh name="M_UMT2_1_F_A004" geometry={nodes.M_UMT2_1_F_A004.geometry} material={nodes.M_UMT2_1_F_A004.material} position={[0, -2.983, 0]} />
        </mesh>
        <mesh name="M_UMT2_1_F_B005" geometry={nodes.M_UMT2_1_F_B005.geometry} material={nodes.M_UMT2_1_F_B005.material} position={[-2.264, 2.983, 0.926]}>
          <mesh name="M_UMT2_1_F_B004" geometry={nodes.M_UMT2_1_F_B004.geometry} material={nodes.M_UMT2_1_F_B004.material} position={[0, -2.983, 0]} />
        </mesh>
        <mesh name="M_UMT2_1_F_C005" geometry={nodes.M_UMT2_1_F_C005.geometry} material={nodes.M_UMT2_1_F_C005.material} position={[-2.264, 2.98, 0.926]}>
          <mesh name="M_UMT2_1_F_C004" geometry={nodes.M_UMT2_1_F_C004.geometry} material={nodes.M_UMT2_1_F_C004.material} position={[0, -2.983, 0]} />
        </mesh>
        <mesh name="M_UMT2_5" geometry={nodes.M_UMT2_5.geometry} material={nodes.M_UMT2_5.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMT2_5.glb')
