/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_DSY_1_F_2_NN.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_DSY_1_F_2_NN.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_DSY_2_F_2_NNobj001" scale={1.049}>
        <mesh name="Legs003" geometry={nodes.Legs003.geometry} material={nodes.Legs003.material} position={[0.01, -3.575, -0.226]} />
        <mesh name="M_DSY_2001" geometry={nodes.M_DSY_2001.geometry} material={materials['M_DSY_1_F_1_NN_wire_153228184.007']} />
        <mesh name="M_DSY_2_F_2001" geometry={nodes.M_DSY_2_F_2001.geometry} material={materials['M_DSY_1_F_1_NN_wire_153228184.007']} />
        <group name="M_DSY_2_OVEN_BODY001" position={[0, -1.897, 2.776]}>
          <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['WHITE.001']} />
          <mesh name="Cube022_1" geometry={nodes.Cube022_1.geometry} material={materials['GREY.001']} />
        </group>
        <group name="M_DSY_2_OVEN_DOOR001" position={[0, -1.86, 2.806]}>
          <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['WHITE.001']} />
          <mesh name="Cube023_1" geometry={nodes.Cube023_1.geometry} material={materials['GREY.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/M_DSY_1_F_2_NN.glb')
