/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_DSY_1_F_1_NN.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_DSY_1_F_1_NN.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_DSY_1_F_1_NNobj001" scale={1.049}>
        <mesh name="Legs004" geometry={nodes.Legs004.geometry} material={nodes.Legs004.material} position={[0.01, -3.575, -0.226]} />
        <mesh name="M_DSY_1001" geometry={nodes.M_DSY_1001.geometry} material={materials['wire_153228184.001']} />
        <mesh name="M_DSY_1_F_1001" geometry={nodes.M_DSY_1_F_1001.geometry} material={materials['wire_153228184.001']} />
        <group name="M_DSY_1_OVEN_BODY001" position={[0, -1.897, 2.776]}>
          <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials.WHITE} />
          <mesh name="Cube020_1" geometry={nodes.Cube020_1.geometry} material={materials.GREY} />
        </group>
        <group name="M_DSY_1_OVEN_DOOR001" position={[0, -1.86, 2.806]}>
          <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials.WHITE} />
          <mesh name="Cube021_1" geometry={nodes.Cube021_1.geometry} material={materials.GREY} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/M_DSY_1_F_1_NN.glb')
