/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMH_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMH_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMH_6obj" scale={1.108}>
        <mesh name="M_UMH_1_F006" geometry={nodes.M_UMH_1_F006.geometry} material={nodes.M_UMH_1_F006.material} position={[3.411, -0.021, 1.368]}>
          <mesh name="M_UMH_6_PNT001" geometry={nodes.M_UMH_6_PNT001.geometry} material={nodes.M_UMH_6_PNT001.material} position={[-3.411, -2.566, 0.163]} />
        </mesh>
        <mesh name="M_UMH_1_F007" geometry={nodes.M_UMH_1_F007.geometry} material={nodes.M_UMH_1_F007.material} position={[3.408, 3.559, 1.367]}>
          <mesh name="M_UMH_6_PNT" geometry={nodes.M_UMH_6_PNT.geometry} material={nodes.M_UMH_6_PNT.material} position={[-3.408, -2.566, 0.164]} />
        </mesh>
        <mesh name="M_UMH_1_F_A006" geometry={nodes.M_UMH_1_F_A006.geometry} material={nodes.M_UMH_1_F_A006.material} position={[3.411, -0.021, 1.368]} />
        <mesh name="M_UMH_1_F_A007" geometry={nodes.M_UMH_1_F_A007.geometry} material={nodes.M_UMH_1_F_A007.material} position={[3.408, 3.559, 1.367]} />
        <mesh name="M_UMH_1_F_B006" geometry={nodes.M_UMH_1_F_B006.geometry} material={nodes.M_UMH_1_F_B006.material} position={[3.411, -0.021, 1.368]} />
        <mesh name="M_UMH_1_F_B007" geometry={nodes.M_UMH_1_F_B007.geometry} material={nodes.M_UMH_1_F_B007.material} position={[3.408, 3.559, 1.367]} />
        <mesh name="M_UMH_1_F_C006" geometry={nodes.M_UMH_1_F_C006.geometry} material={nodes.M_UMH_1_F_C006.material} position={[3.411, -0.021, 1.368]} />
        <mesh name="M_UMH_1_F_C007" geometry={nodes.M_UMH_1_F_C007.geometry} material={nodes.M_UMH_1_F_C007.material} position={[3.408, 3.559, 1.367]} />
        <mesh name="M_UMH_6" geometry={nodes.M_UMH_6.geometry} material={nodes.M_UMH_6.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMH_6.glb')
