/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMH_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMH_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMH_4obj" scale={0.949}>
        <mesh name="M_UMH_1_F" geometry={nodes.M_UMH_1_F.geometry} material={nodes.M_UMH_1_F.material} position={[3.986, 3.603, 1.598]}>
          <mesh name="M_UMH_4_PNT" geometry={nodes.M_UMH_4_PNT.geometry} material={nodes.M_UMH_4_PNT.material} position={[-3.986, -2.443, 0.19]} />
        </mesh>
        <mesh name="M_UMH_1_F002" geometry={nodes.M_UMH_1_F002.geometry} material={nodes.M_UMH_1_F002.material} position={[3.982, -0.024, 1.596]}>
          <mesh name="M_UMH_4_PNT001" geometry={nodes.M_UMH_4_PNT001.geometry} material={nodes.M_UMH_4_PNT001.material} position={[-3.982, -2.447, 0.192]} />
        </mesh>
        <mesh name="M_UMH_1_F_A" geometry={nodes.M_UMH_1_F_A.geometry} material={nodes.M_UMH_1_F_A.material} position={[3.986, 3.603, 1.598]} />
        <mesh name="M_UMH_1_F_A002" geometry={nodes.M_UMH_1_F_A002.geometry} material={nodes.M_UMH_1_F_A002.material} position={[3.982, -0.024, 1.596]} />
        <mesh name="M_UMH_1_F_B" geometry={nodes.M_UMH_1_F_B.geometry} material={nodes.M_UMH_1_F_B.material} position={[3.982, -0.024, 1.596]} />
        <mesh name="M_UMH_1_F_B002" geometry={nodes.M_UMH_1_F_B002.geometry} material={nodes.M_UMH_1_F_B002.material} position={[3.986, 3.603, 1.598]} />
        <mesh name="M_UMH_1_F_C" geometry={nodes.M_UMH_1_F_C.geometry} material={nodes.M_UMH_1_F_C.material} position={[3.982, -0.024, 1.596]} />
        <mesh name="M_UMH_1_F_C002" geometry={nodes.M_UMH_1_F_C002.geometry} material={nodes.M_UMH_1_F_C002.material} position={[3.986, 3.603, 1.598]} />
        <mesh name="M_UMH_4" geometry={nodes.M_UMH_4.geometry} material={nodes.M_UMH_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMH_4.glb')
