/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMH_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMH_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMH_5obj" scale={1.028}>
        <mesh name="M_UMH_1_F003" geometry={nodes.M_UMH_1_F003.geometry} material={nodes.M_UMH_1_F003.material} position={[3.678, -0.024, 1.474]}>
          <mesh name="M_UMH_5_PNT" geometry={nodes.M_UMH_5_PNT.geometry} material={nodes.M_UMH_5_PNT.material} position={[-3.678, -2.525, 0.177]} />
        </mesh>
        <mesh name="M_UMH_1_F005" geometry={nodes.M_UMH_1_F005.geometry} material={nodes.M_UMH_1_F005.material} position={[3.677, 3.581, 1.474]}>
          <mesh name="M_UMH_5_PNT001" geometry={nodes.M_UMH_5_PNT001.geometry} material={nodes.M_UMH_5_PNT001.material} position={[-3.677, -2.511, 0.178]} />
        </mesh>
        <mesh name="M_UMH_1_F_A003" geometry={nodes.M_UMH_1_F_A003.geometry} material={nodes.M_UMH_1_F_A003.material} position={[3.678, -0.024, 1.474]} />
        <mesh name="M_UMH_1_F_A005" geometry={nodes.M_UMH_1_F_A005.geometry} material={nodes.M_UMH_1_F_A005.material} position={[3.677, 3.581, 1.474]} />
        <mesh name="M_UMH_1_F_B003" geometry={nodes.M_UMH_1_F_B003.geometry} material={nodes.M_UMH_1_F_B003.material} position={[3.678, -0.024, 1.474]} />
        <mesh name="M_UMH_1_F_B005" geometry={nodes.M_UMH_1_F_B005.geometry} material={nodes.M_UMH_1_F_B005.material} position={[3.677, 3.581, 1.474]} />
        <mesh name="M_UMH_1_F_C003" geometry={nodes.M_UMH_1_F_C003.geometry} material={nodes.M_UMH_1_F_C003.material} position={[3.678, -0.024, 1.474]} />
        <mesh name="M_UMH_1_F_C005" geometry={nodes.M_UMH_1_F_C005.geometry} material={nodes.M_UMH_1_F_C005.material} position={[3.677, 3.581, 1.474]} />
        <mesh name="M_UMH_5" geometry={nodes.M_UMH_5.geometry} material={nodes.M_UMH_5.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMH_5.glb')
