/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMH_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMH_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMH_3obj" scale={0.874}>
        <mesh name="M_UMH_1_F001" geometry={nodes.M_UMH_1_F001.geometry} material={nodes.M_UMH_1_F001.material} position={[4.323, 3.627, 1.732]}>
          <mesh name="M_UMH_3_PNT" geometry={nodes.M_UMH_3_PNT.geometry} material={nodes.M_UMH_3_PNT.material} position={[-4.323, -2.368, 0.21]} />
        </mesh>
        <mesh name="M_UMH_1_F004" geometry={nodes.M_UMH_1_F004.geometry} material={nodes.M_UMH_1_F004.material} position={[4.324, -0.027, 1.733]}>
          <mesh name="M_UMH_3_PNT001" geometry={nodes.M_UMH_3_PNT001.geometry} material={nodes.M_UMH_3_PNT001.material} position={[-4.324, -2.36, 0.209]} />
        </mesh>
        <mesh name="M_UMH_1_F_A001" geometry={nodes.M_UMH_1_F_A001.geometry} material={nodes.M_UMH_1_F_A001.material} position={[4.323, 3.627, 1.732]} />
        <mesh name="M_UMH_1_F_A004" geometry={nodes.M_UMH_1_F_A004.geometry} material={nodes.M_UMH_1_F_A004.material} position={[4.324, -0.027, 1.733]} />
        <mesh name="M_UMH_1_F_B001" geometry={nodes.M_UMH_1_F_B001.geometry} material={nodes.M_UMH_1_F_B001.material} position={[4.323, 3.627, 1.732]} />
        <mesh name="M_UMH_1_F_B004" geometry={nodes.M_UMH_1_F_B004.geometry} material={nodes.M_UMH_1_F_B004.material} position={[4.324, -0.027, 1.733]} />
        <mesh name="M_UMH_1_F_C001" geometry={nodes.M_UMH_1_F_C001.geometry} material={nodes.M_UMH_1_F_C001.material} position={[4.323, 3.627, 1.732]} />
        <mesh name="M_UMH_1_F_C004" geometry={nodes.M_UMH_1_F_C004.geometry} material={nodes.M_UMH_1_F_C004.material} position={[4.324, -0.027, 1.733]} />
        <mesh name="M_UMH_3" geometry={nodes.M_UMH_3.geometry} material={nodes.M_UMH_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMH_3.glb')
