/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMH_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMH_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMH_7obj" scale={1.177}>
        <mesh name="M_UMH_1_F008" geometry={nodes.M_UMH_1_F008.geometry} material={nodes.M_UMH_1_F008.material} position={[3.211, -0.021, 1.286]}>
          <mesh name="M_UMH_7_PNT" geometry={nodes.M_UMH_7_PNT.geometry} material={nodes.M_UMH_7_PNT.material} position={[-3.211, -2.642, 0.156]} />
        </mesh>
        <mesh name="M_UMH_1_F009" geometry={nodes.M_UMH_1_F009.geometry} material={nodes.M_UMH_1_F009.material} position={[3.212, 3.563, 1.289]}>
          <mesh name="M_UMH_7_PNT001" geometry={nodes.M_UMH_7_PNT001.geometry} material={nodes.M_UMH_7_PNT001.material} position={[-3.212, -2.628, 0.153]} />
        </mesh>
        <mesh name="M_UMH_1_F_A008" geometry={nodes.M_UMH_1_F_A008.geometry} material={nodes.M_UMH_1_F_A008.material} position={[3.211, -0.021, 1.286]} />
        <mesh name="M_UMH_1_F_A009" geometry={nodes.M_UMH_1_F_A009.geometry} material={nodes.M_UMH_1_F_A009.material} position={[3.212, 3.563, 1.289]} />
        <mesh name="M_UMH_1_F_B008" geometry={nodes.M_UMH_1_F_B008.geometry} material={nodes.M_UMH_1_F_B008.material} position={[3.211, -0.021, 1.286]} />
        <mesh name="M_UMH_1_F_B009" geometry={nodes.M_UMH_1_F_B009.geometry} material={nodes.M_UMH_1_F_B009.material} position={[3.212, 3.563, 1.289]} />
        <mesh name="M_UMH_1_F_C008" geometry={nodes.M_UMH_1_F_C008.geometry} material={nodes.M_UMH_1_F_C008.material} position={[3.211, -0.021, 1.286]} />
        <mesh name="M_UMH_1_F_C009" geometry={nodes.M_UMH_1_F_C009.geometry} material={nodes.M_UMH_1_F_C009.material} position={[3.212, 3.563, 1.289]} />
        <mesh name="M_UMH_7" geometry={nodes.M_UMH_7.geometry} material={nodes.M_UMH_7.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMH_7.glb')
