/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMH_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMH_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMH_2obj" scale={0.799}>
        <mesh name="M_UMH_1_F012" geometry={nodes.M_UMH_1_F012.geometry} material={nodes.M_UMH_1_F012.material} position={[4.732, -0.033, 1.896]}>
          <mesh name="M_UMH_2_PNT001" geometry={nodes.M_UMH_2_PNT001.geometry} material={nodes.M_UMH_2_PNT001.material} position={[-4.732, -2.252, 0.228]} />
        </mesh>
        <mesh name="M_UMH_1_F013" geometry={nodes.M_UMH_1_F013.geometry} material={nodes.M_UMH_1_F013.material} position={[4.731, 3.609, 1.895]}>
          <mesh name="M_UMH_2_PNT" geometry={nodes.M_UMH_2_PNT.geometry} material={nodes.M_UMH_2_PNT.material} position={[-4.731, -2.232, 0.229]} />
        </mesh>
        <mesh name="M_UMH_1_F_A012" geometry={nodes.M_UMH_1_F_A012.geometry} material={nodes.M_UMH_1_F_A012.material} position={[4.732, -0.033, 1.896]} />
        <mesh name="M_UMH_1_F_A013" geometry={nodes.M_UMH_1_F_A013.geometry} material={nodes.M_UMH_1_F_A013.material} position={[4.731, 3.609, 1.895]} />
        <mesh name="M_UMH_1_F_B012" geometry={nodes.M_UMH_1_F_B012.geometry} material={nodes.M_UMH_1_F_B012.material} position={[4.732, -0.033, 1.896]} />
        <mesh name="M_UMH_1_F_B013" geometry={nodes.M_UMH_1_F_B013.geometry} material={nodes.M_UMH_1_F_B013.material} position={[4.731, 3.609, 1.895]} />
        <mesh name="M_UMH_1_F_C012" geometry={nodes.M_UMH_1_F_C012.geometry} material={nodes.M_UMH_1_F_C012.material} position={[4.732, -0.033, 1.896]} />
        <mesh name="M_UMH_1_F_C013" geometry={nodes.M_UMH_1_F_C013.geometry} material={nodes.M_UMH_1_F_C013.material} position={[4.731, 3.609, 1.895]} />
        <mesh name="M_UMH_2" geometry={nodes.M_UMH_2.geometry} material={nodes.M_UMH_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMH_2.glb')
