/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMH_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMH_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMH_1obj" scale={0.73}>
        <mesh name="M_UMH_1" geometry={nodes.M_UMH_1.geometry} material={nodes.M_UMH_1.material} />
        <mesh name="M_UMH_1_F010" geometry={nodes.M_UMH_1_F010.geometry} material={nodes.M_UMH_1_F010.material} position={[5.176, -0.032, 2.075]}>
          <mesh name="M_UMH_1_PNT001" geometry={nodes.M_UMH_1_PNT001.geometry} material={nodes.M_UMH_1_PNT001.material} position={[-5.176, -2.111, 0.25]} />
        </mesh>
        <mesh name="M_UMH_1_F011" geometry={nodes.M_UMH_1_F011.geometry} material={nodes.M_UMH_1_F011.material} position={[5.171, 3.593, 2.068]}>
          <mesh name="M_UMH_1_PNT" geometry={nodes.M_UMH_1_PNT.geometry} material={nodes.M_UMH_1_PNT.material} position={[-5.171, -2.086, 0.257]} />
        </mesh>
        <mesh name="M_UMH_1_F_A010" geometry={nodes.M_UMH_1_F_A010.geometry} material={nodes.M_UMH_1_F_A010.material} position={[5.176, -0.032, 2.075]} />
        <mesh name="M_UMH_1_F_A011" geometry={nodes.M_UMH_1_F_A011.geometry} material={nodes.M_UMH_1_F_A011.material} position={[5.171, 3.593, 2.068]} />
        <mesh name="M_UMH_1_F_B010" geometry={nodes.M_UMH_1_F_B010.geometry} material={nodes.M_UMH_1_F_B010.material} position={[5.171, 3.593, 2.068]} />
        <mesh name="M_UMH_1_F_B011" geometry={nodes.M_UMH_1_F_B011.geometry} material={nodes.M_UMH_1_F_B011.material} position={[5.176, -0.032, 2.075]} />
        <mesh name="M_UMH_1_F_C010" geometry={nodes.M_UMH_1_F_C010.geometry} material={nodes.M_UMH_1_F_C010.material} position={[5.176, -0.032, 2.075]} />
        <mesh name="M_UMH_1_F_C011" geometry={nodes.M_UMH_1_F_C011.geometry} material={nodes.M_UMH_1_F_C011.material} position={[5.171, 3.593, 2.068]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMH_1.glb')
