/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMD_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMD_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMD_2obj" scale={1.052}>
        <mesh name="M_UMD_1_F015" geometry={nodes.M_UMD_1_F015.geometry} material={nodes.M_UMD_1_F015.material} position={[1.238, 0.648, 1.445]}>
          <mesh name="M_UMD_2_PNT" geometry={nodes.M_UMD_2_PNT.geometry} material={nodes.M_UMD_2_PNT.material} position={[-1.238, -3.375, 0.17]} />
        </mesh>
        <mesh name="M_UMD_1_F_A015" geometry={nodes.M_UMD_1_F_A015.geometry} material={nodes.M_UMD_1_F_A015.material} position={[1.243, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B015" geometry={nodes.M_UMD_1_F_B015.geometry} material={nodes.M_UMD_1_F_B015.material} position={[1.243, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_C015" geometry={nodes.M_UMD_1_F_C015.geometry} material={nodes.M_UMD_1_F_C015.material} position={[1.243, 1.158, 1.435]} />
        <mesh name="M_UMD_2" geometry={nodes.M_UMD_2.geometry} material={nodes.M_UMD_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMD_2.glb')
