/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMD_1_F_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMD_1_F_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMD_7_F_7obj" scale={1.052}>
        <mesh name="M_UMD_1_F001" geometry={nodes.M_UMD_1_F001.geometry} material={nodes.M_UMD_1_F001.material} position={[2.487, 0.648, 1.445]}>
          <mesh name="M_UMD_7_PNT_H" geometry={nodes.M_UMD_7_PNT_H.geometry} material={nodes.M_UMD_7_PNT_H.material} position={[-2.487, -4.226, 0.17]} />
          <mesh name="M_UMD_7_PNT_V" geometry={nodes.M_UMD_7_PNT_V.geometry} material={nodes.M_UMD_7_PNT_V.material} position={[-3.988, -3.375, 0.17]} />
        </mesh>
        <mesh name="M_UMD_1_F_A001" geometry={nodes.M_UMD_1_F_A001.geometry} material={nodes.M_UMD_1_F_A001.material} position={[2.493, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B001" geometry={nodes.M_UMD_1_F_B001.geometry} material={nodes.M_UMD_1_F_B001.material} position={[2.493, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_C001" geometry={nodes.M_UMD_1_F_C001.geometry} material={nodes.M_UMD_1_F_C001.material} position={[2.493, 1.158, 1.435]} />
        <mesh name="M_UMD_7" geometry={nodes.M_UMD_7.geometry} material={nodes.M_UMD_7.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMD_1_F_7.glb')
