/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMD_1_F_12.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMD_1_F_12.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMD_12_F_12obj" scale={1.052}>
        <mesh name="M_UMD_12" geometry={nodes.M_UMD_12.geometry} material={nodes.M_UMD_12.material} />
        <mesh name="M_UMD_1_F010" geometry={nodes.M_UMD_1_F010.geometry} material={nodes.M_UMD_1_F010.material} position={[-3.735, 0.648, 1.445]}>
          <mesh name="M_UMD_11_PNT_H_1001" geometry={nodes.M_UMD_11_PNT_H_1001.geometry} material={nodes.M_UMD_11_PNT_H_1001.material} position={[1.84, -4.227, 0.17]} />
          <mesh name="M_UMD_11_PNT_V002" geometry={nodes.M_UMD_11_PNT_V002.geometry} material={nodes.M_UMD_11_PNT_V002.material} position={[2.712, -3.375, 0.17]} />
        </mesh>
        <mesh name="M_UMD_1_F011" geometry={nodes.M_UMD_1_F011.geometry} material={nodes.M_UMD_1_F011.material} position={[3.737, 0.648, 1.445]}>
          <mesh name="M_UMD_11_PNT_H001" geometry={nodes.M_UMD_11_PNT_H001.geometry} material={nodes.M_UMD_11_PNT_H001.material} position={[-1.842, -4.227, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UMD_11_PNT_V_1002" geometry={nodes.M_UMD_11_PNT_V_1002.geometry} material={nodes.M_UMD_11_PNT_V_1002.material} position={[-2.715, -3.375, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMD_1_F_A010" geometry={nodes.M_UMD_1_F_A010.geometry} material={nodes.M_UMD_1_F_A010.material} position={[-3.741, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_A011" geometry={nodes.M_UMD_1_F_A011.geometry} material={nodes.M_UMD_1_F_A011.material} position={[3.743, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B010" geometry={nodes.M_UMD_1_F_B010.geometry} material={nodes.M_UMD_1_F_B010.material} position={[-3.744, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B011" geometry={nodes.M_UMD_1_F_B011.geometry} material={nodes.M_UMD_1_F_B011.material} position={[3.743, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_C010" geometry={nodes.M_UMD_1_F_C010.geometry} material={nodes.M_UMD_1_F_C010.material} position={[-3.745, 1.158, 1.435]} />
        <mesh name="M_UMD_1_F_C011" geometry={nodes.M_UMD_1_F_C011.geometry} material={nodes.M_UMD_1_F_C011.material} position={[3.743, 1.158, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMD_1_F_12.glb')
