/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMD_1_F_10.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMD_1_F_10.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMD_10_F_10obj" scale={1.052}>
        <mesh name="M_UMD_10" geometry={nodes.M_UMD_10.geometry} material={nodes.M_UMD_10.material} />
        <mesh name="M_UMD_1_F006" geometry={nodes.M_UMD_1_F006.geometry} material={nodes.M_UMD_1_F006.material} position={[-3.235, 0.648, 1.445]}>
          <mesh name="M_UMD_9_PNT_H" geometry={nodes.M_UMD_9_PNT_H.geometry} material={nodes.M_UMD_9_PNT_H.material} position={[1.641, -4.227, 0.17]} />
          <mesh name="M_UMD_9_PNT_V" geometry={nodes.M_UMD_9_PNT_V.geometry} material={nodes.M_UMD_9_PNT_V.material} position={[2.212, -3.375, 0.17]} />
        </mesh>
        <mesh name="M_UMD_1_F007" geometry={nodes.M_UMD_1_F007.geometry} material={nodes.M_UMD_1_F007.material} position={[3.237, 0.648, 1.445]}>
          <mesh name="M_UMD_9_PNT_H_1" geometry={nodes.M_UMD_9_PNT_H_1.geometry} material={nodes.M_UMD_9_PNT_H_1.material} position={[-1.643, -4.227, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UMD_9_PNT_V_1" geometry={nodes.M_UMD_9_PNT_V_1.geometry} material={nodes.M_UMD_9_PNT_V_1.material} position={[-2.215, -3.375, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMD_1_F_A006" geometry={nodes.M_UMD_1_F_A006.geometry} material={nodes.M_UMD_1_F_A006.material} position={[-3.241, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_A007" geometry={nodes.M_UMD_1_F_A007.geometry} material={nodes.M_UMD_1_F_A007.material} position={[3.243, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B006" geometry={nodes.M_UMD_1_F_B006.geometry} material={nodes.M_UMD_1_F_B006.material} position={[-3.244, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B007" geometry={nodes.M_UMD_1_F_B007.geometry} material={nodes.M_UMD_1_F_B007.material} position={[3.243, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_C006" geometry={nodes.M_UMD_1_F_C006.geometry} material={nodes.M_UMD_1_F_C006.material} position={[-3.245, 1.158, 1.435]} />
        <mesh name="M_UMD_1_F_C007" geometry={nodes.M_UMD_1_F_C007.geometry} material={nodes.M_UMD_1_F_C007.material} position={[3.243, 1.158, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMD_1_F_10.glb')
