/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMD_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMD_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMD_1obj" scale={1.052}>
        <mesh name="M_UMD_1" geometry={nodes.M_UMD_1.geometry} material={nodes.M_UMD_1.material} />
        <mesh name="M_UMD_1_F014" geometry={nodes.M_UMD_1_F014.geometry} material={nodes.M_UMD_1_F014.material} position={[0.99, 0.648, 1.445]}>
          <mesh name="M_UMD_1_PNT" geometry={nodes.M_UMD_1_PNT.geometry} material={nodes.M_UMD_1_PNT.material} position={[-0.99, -3.375, 0.17]} />
        </mesh>
        <mesh name="M_UMD_1_F_A014" geometry={nodes.M_UMD_1_F_A014.geometry} material={nodes.M_UMD_1_F_A014.material} position={[0.995, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B014" geometry={nodes.M_UMD_1_F_B014.geometry} material={nodes.M_UMD_1_F_B014.material} position={[0.995, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_C014" geometry={nodes.M_UMD_1_F_C014.geometry} material={nodes.M_UMD_1_F_C014.material} position={[0.995, 1.158, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMD_1.glb')
