/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMD_1_F_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMD_1_F_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMD_5_F_5obj" scale={1.052}>
        <mesh name="M_UMD_1_F018" geometry={nodes.M_UMD_1_F018.geometry} material={nodes.M_UMD_1_F018.material} position={[1.987, 0.648, 1.445]}>
          <mesh name="M_UMD_5_PNT_H" geometry={nodes.M_UMD_5_PNT_H.geometry} material={nodes.M_UMD_5_PNT_H.material} position={[-1.987, -4.226, 0.17]} />
          <mesh name="M_UMD_5_PNT_V" geometry={nodes.M_UMD_5_PNT_V.geometry} material={nodes.M_UMD_5_PNT_V.material} position={[-2.988, -3.375, 0.17]} />
        </mesh>
        <mesh name="M_UMD_1_F_A018" geometry={nodes.M_UMD_1_F_A018.geometry} material={nodes.M_UMD_1_F_A018.material} position={[1.993, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B018" geometry={nodes.M_UMD_1_F_B018.geometry} material={nodes.M_UMD_1_F_B018.material} position={[1.993, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_C018" geometry={nodes.M_UMD_1_F_C018.geometry} material={nodes.M_UMD_1_F_C018.material} position={[1.993, 1.158, 1.435]} />
        <mesh name="M_UMD_5" geometry={nodes.M_UMD_5.geometry} material={nodes.M_UMD_5.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMD_1_F_5.glb')
