/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMD_1_F_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMD_1_F_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMD_6_F_6obj" scale={1.052}>
        <mesh name="M_UMD_1_F" geometry={nodes.M_UMD_1_F.geometry} material={nodes.M_UMD_1_F.material} position={[2.237, 0.648, 1.445]}>
          <mesh name="M_UMD_4_PNT_H002" geometry={nodes.M_UMD_4_PNT_H002.geometry} material={nodes.M_UMD_4_PNT_H002.material} position={[-2.237, -4.226, 0.17]} />
          <mesh name="M_UMD_4_PNT_V002" geometry={nodes.M_UMD_4_PNT_V002.geometry} material={nodes.M_UMD_4_PNT_V002.material} position={[-3.492, -3.375, 0.17]} />
        </mesh>
        <mesh name="M_UMD_1_F_A" geometry={nodes.M_UMD_1_F_A.geometry} material={nodes.M_UMD_1_F_A.material} position={[2.243, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B" geometry={nodes.M_UMD_1_F_B.geometry} material={nodes.M_UMD_1_F_B.material} position={[2.243, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_C" geometry={nodes.M_UMD_1_F_C.geometry} material={nodes.M_UMD_1_F_C.material} position={[2.243, 1.158, 1.435]} />
        <mesh name="M_UMD_6" geometry={nodes.M_UMD_6.geometry} material={nodes.M_UMD_6.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMD_1_F_6.glb')
