/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMD_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMD_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMD_3obj" scale={1.052}>
        <mesh name="M_UMD_1_F016" geometry={nodes.M_UMD_1_F016.geometry} material={nodes.M_UMD_1_F016.material} position={[1.487, 0.648, 1.445]}>
          <mesh name="M_UMD_3_PNT" geometry={nodes.M_UMD_3_PNT.geometry} material={nodes.M_UMD_3_PNT.material} position={[-1.992, -3.375, 0.17]} />
        </mesh>
        <mesh name="M_UMD_1_F_A016" geometry={nodes.M_UMD_1_F_A016.geometry} material={nodes.M_UMD_1_F_A016.material} position={[1.493, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B016" geometry={nodes.M_UMD_1_F_B016.geometry} material={nodes.M_UMD_1_F_B016.material} position={[1.493, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_C016" geometry={nodes.M_UMD_1_F_C016.geometry} material={nodes.M_UMD_1_F_C016.material} position={[1.493, 1.158, 1.435]} />
        <mesh name="M_UMD_3" geometry={nodes.M_UMD_3.geometry} material={nodes.M_UMD_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMD_3.glb')
