/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMD_1_F_11.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMD_1_F_11.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMD_11_F_11obj" scale={1.052}>
        <mesh name="M_UMD_11" geometry={nodes.M_UMD_11.geometry} material={nodes.M_UMD_11.material} />
        <mesh name="M_UMD_1_F008" geometry={nodes.M_UMD_1_F008.geometry} material={nodes.M_UMD_1_F008.material} position={[-3.485, 0.648, 1.445]}>
          <mesh name="M_UMD_11_PNT_H" geometry={nodes.M_UMD_11_PNT_H.geometry} material={nodes.M_UMD_11_PNT_H.material} position={[1.714, -4.227, 0.17]} />
          <mesh name="M_UMD_11_PNT_V001" geometry={nodes.M_UMD_11_PNT_V001.geometry} material={nodes.M_UMD_11_PNT_V001.material} position={[2.462, -3.375, 0.17]} />
        </mesh>
        <mesh name="M_UMD_1_F009" geometry={nodes.M_UMD_1_F009.geometry} material={nodes.M_UMD_1_F009.material} position={[3.487, 0.648, 1.445]}>
          <mesh name="M_UMD_11_PNT_H_1" geometry={nodes.M_UMD_11_PNT_H_1.geometry} material={nodes.M_UMD_11_PNT_H_1.material} position={[-1.716, -4.227, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UMD_11_PNT_V_1001" geometry={nodes.M_UMD_11_PNT_V_1001.geometry} material={nodes.M_UMD_11_PNT_V_1001.material} position={[-2.465, -3.375, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMD_1_F_A008" geometry={nodes.M_UMD_1_F_A008.geometry} material={nodes.M_UMD_1_F_A008.material} position={[-3.491, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_A009" geometry={nodes.M_UMD_1_F_A009.geometry} material={nodes.M_UMD_1_F_A009.material} position={[3.493, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B008" geometry={nodes.M_UMD_1_F_B008.geometry} material={nodes.M_UMD_1_F_B008.material} position={[-3.494, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B009" geometry={nodes.M_UMD_1_F_B009.geometry} material={nodes.M_UMD_1_F_B009.material} position={[3.493, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_C008" geometry={nodes.M_UMD_1_F_C008.geometry} material={nodes.M_UMD_1_F_C008.material} position={[-3.495, 1.158, 1.435]} />
        <mesh name="M_UMD_1_F_C009" geometry={nodes.M_UMD_1_F_C009.geometry} material={nodes.M_UMD_1_F_C009.material} position={[3.493, 1.158, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMD_1_F_11.glb')
