/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMD_8.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMD_8.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMD_8obj" scale={1.052}>
        <mesh name="M_UMD_1_F002" geometry={nodes.M_UMD_1_F002.geometry} material={nodes.M_UMD_1_F002.material} position={[-2.737, 0.648, 1.445]}>
          <mesh name="M_UMD_4_PNT" geometry={nodes.M_UMD_4_PNT.geometry} material={nodes.M_UMD_4_PNT.material} position={[1.715, -3.375, 0.17]} />
        </mesh>
        <mesh name="M_UMD_1_F003" geometry={nodes.M_UMD_1_F003.geometry} material={nodes.M_UMD_1_F003.material} position={[2.737, 0.648, 1.445]}>
          <mesh name="M_UMD_4_PNT001" geometry={nodes.M_UMD_4_PNT001.geometry} material={nodes.M_UMD_4_PNT001.material} position={[-1.715, -3.375, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMD_1_F_A002" geometry={nodes.M_UMD_1_F_A002.geometry} material={nodes.M_UMD_1_F_A002.material} position={[-2.743, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_A003" geometry={nodes.M_UMD_1_F_A003.geometry} material={nodes.M_UMD_1_F_A003.material} position={[2.743, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B002" geometry={nodes.M_UMD_1_F_B002.geometry} material={nodes.M_UMD_1_F_B002.material} position={[-2.747, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B003" geometry={nodes.M_UMD_1_F_B003.geometry} material={nodes.M_UMD_1_F_B003.material} position={[2.743, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_C002" geometry={nodes.M_UMD_1_F_C002.geometry} material={nodes.M_UMD_1_F_C002.material} position={[-2.747, 1.158, 1.435]} />
        <mesh name="M_UMD_1_F_C003" geometry={nodes.M_UMD_1_F_C003.geometry} material={nodes.M_UMD_1_F_C003.material} position={[2.743, 1.158, 1.435]} />
        <mesh name="M_UMD_8" geometry={nodes.M_UMD_8.geometry} material={nodes.M_UMD_8.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMD_8.glb')
