/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMD_9.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMD_9.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMD_9obj" scale={1.052}>
        <mesh name="M_UMD_1_F004" geometry={nodes.M_UMD_1_F004.geometry} material={nodes.M_UMD_1_F004.material} position={[-2.995, 0.648, 1.445]}>
          <mesh name="M_UMD_9_PNT" geometry={nodes.M_UMD_9_PNT.geometry} material={nodes.M_UMD_9_PNT.material} position={[1.972, -3.375, 0.17]} />
        </mesh>
        <mesh name="M_UMD_1_F005" geometry={nodes.M_UMD_1_F005.geometry} material={nodes.M_UMD_1_F005.material} position={[2.987, 0.648, 1.445]}>
          <mesh name="M_UMD_9_PNT001" geometry={nodes.M_UMD_9_PNT001.geometry} material={nodes.M_UMD_9_PNT001.material} position={[-1.965, -3.375, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMD_1_F_A004" geometry={nodes.M_UMD_1_F_A004.geometry} material={nodes.M_UMD_1_F_A004.material} position={[-3.001, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_A005" geometry={nodes.M_UMD_1_F_A005.geometry} material={nodes.M_UMD_1_F_A005.material} position={[2.993, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B004" geometry={nodes.M_UMD_1_F_B004.geometry} material={nodes.M_UMD_1_F_B004.material} position={[-3.004, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B005" geometry={nodes.M_UMD_1_F_B005.geometry} material={nodes.M_UMD_1_F_B005.material} position={[2.993, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_C004" geometry={nodes.M_UMD_1_F_C004.geometry} material={nodes.M_UMD_1_F_C004.material} position={[-3.005, 1.158, 1.435]} />
        <mesh name="M_UMD_1_F_C005" geometry={nodes.M_UMD_1_F_C005.geometry} material={nodes.M_UMD_1_F_C005.material} position={[2.993, 1.158, 1.435]} />
        <mesh name="M_UMD_9" geometry={nodes.M_UMD_9.geometry} material={nodes.M_UMD_9.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMD_9.glb')
