/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMD_1_F_13.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMD_1_F_13.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMD_13_F_13obj" scale={1.052}>
        <mesh name="M_UMD_13" geometry={nodes.M_UMD_13.geometry} material={nodes.M_UMD_13.material} />
        <mesh name="M_UMD_1_F012" geometry={nodes.M_UMD_1_F012.geometry} material={nodes.M_UMD_1_F012.material} position={[-3.985, 0.648, 1.445]}>
          <mesh name="M_UMD_11_PNT_H002" geometry={nodes.M_UMD_11_PNT_H002.geometry} material={nodes.M_UMD_11_PNT_H002.material} position={[1.943, -4.227, 0.17]} />
          <mesh name="M_UMD_11_PNT_V003" geometry={nodes.M_UMD_11_PNT_V003.geometry} material={nodes.M_UMD_11_PNT_V003.material} position={[2.962, -3.375, 0.17]} />
        </mesh>
        <mesh name="M_UMD_1_F013" geometry={nodes.M_UMD_1_F013.geometry} material={nodes.M_UMD_1_F013.material} position={[3.987, 0.648, 1.445]}>
          <mesh name="M_UMD_11_PNT_H_1002" geometry={nodes.M_UMD_11_PNT_H_1002.geometry} material={nodes.M_UMD_11_PNT_H_1002.material} position={[-1.945, -4.227, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UMD_11_PNT_V_1003" geometry={nodes.M_UMD_11_PNT_V_1003.geometry} material={nodes.M_UMD_11_PNT_V_1003.material} position={[-2.965, -3.375, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UMD_1_F_A012" geometry={nodes.M_UMD_1_F_A012.geometry} material={nodes.M_UMD_1_F_A012.material} position={[-3.991, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_A013" geometry={nodes.M_UMD_1_F_A013.geometry} material={nodes.M_UMD_1_F_A013.material} position={[3.993, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B012" geometry={nodes.M_UMD_1_F_B012.geometry} material={nodes.M_UMD_1_F_B012.material} position={[-3.994, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_B013" geometry={nodes.M_UMD_1_F_B013.geometry} material={nodes.M_UMD_1_F_B013.material} position={[3.993, 2.454, 1.435]} />
        <mesh name="M_UMD_1_F_C012" geometry={nodes.M_UMD_1_F_C012.geometry} material={nodes.M_UMD_1_F_C012.material} position={[-3.995, 1.158, 1.435]} />
        <mesh name="M_UMD_1_F_C013" geometry={nodes.M_UMD_1_F_C013.geometry} material={nodes.M_UMD_1_F_C013.material} position={[3.993, 1.158, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMD_1_F_13.glb')
