/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU1_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU1_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU1_1obj" scale={0.616}>
        <mesh name="M_UMTU_F_A004" geometry={nodes.M_UMTU_F_A004.geometry} material={nodes.M_UMTU_F_A004.material} position={[4.25, 2.987, 2.435]} />
        <mesh name="M_UMTU_F_B004" geometry={nodes.M_UMTU_F_B004.geometry} material={nodes.M_UMTU_F_B004.material} position={[4.25, 2.984, 2.435]} />
        <mesh name="M_UMTU_F_C004" geometry={nodes.M_UMTU_F_C004.geometry} material={nodes.M_UMTU_F_C004.material} position={[4.25, 2.979, 2.435]} />
        <mesh name="M_UMU1_1" geometry={nodes.M_UMU1_1.geometry} material={materials['wire_000000000.012']} />
        <mesh name="M_UMU_1_F004" geometry={nodes.M_UMU_1_F004.geometry} material={nodes.M_UMU_1_F004.material} position={[4.253, 2.988, 2.447]}>
          <mesh name="M_UMU1_1_PNT" geometry={nodes.M_UMU1_1_PNT.geometry} material={nodes.M_UMU1_1_PNT.material} position={[-4.253, -4.866, 0.222]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU1_1.glb')
