/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU1_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU1_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU1_4obj" scale={0.611}>
        <mesh name="M_UMTU_F_A" geometry={nodes.M_UMTU_F_A.geometry} material={nodes.M_UMTU_F_A.material} position={[5.59, 3.013, 2.457]} />
        <mesh name="M_UMTU_F_B" geometry={nodes.M_UMTU_F_B.geometry} material={nodes.M_UMTU_F_B.material} position={[5.59, 3.01, 2.457]} />
        <mesh name="M_UMTU_F_C" geometry={nodes.M_UMTU_F_C.geometry} material={nodes.M_UMTU_F_C.material} position={[5.59, 3.005, 2.457]} />
        <mesh name="M_UMU1_4" geometry={nodes.M_UMU1_4.geometry} material={nodes.M_UMU1_4.material} />
        <mesh name="M_UMU_1_F" geometry={nodes.M_UMU_1_F.geometry} material={nodes.M_UMU_1_F.material} position={[5.593, 3.014, 2.468]}>
          <mesh name="M_UMU1_4_PNT" geometry={nodes.M_UMU1_4_PNT.geometry} material={nodes.M_UMU1_4_PNT.material} position={[-5.593, -4.908, 0.224]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU1_4.glb')
