/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU1_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU1_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU1_5obj" scale={0.612}>
        <mesh name="M_UMTU_F_A001" geometry={nodes.M_UMTU_F_A001.geometry} material={nodes.M_UMTU_F_A001.material} position={[5.995, 3.01, 2.454]} />
        <mesh name="M_UMTU_F_B001" geometry={nodes.M_UMTU_F_B001.geometry} material={nodes.M_UMTU_F_B001.material} position={[5.995, 3.007, 2.454]} />
        <mesh name="M_UMTU_F_C001" geometry={nodes.M_UMTU_F_C001.geometry} material={nodes.M_UMTU_F_C001.material} position={[5.995, 3.001, 2.454]} />
        <mesh name="M_UMU1_5" geometry={nodes.M_UMU1_5.geometry} material={nodes.M_UMU1_5.material} />
        <mesh name="M_UMU_1_F001" geometry={nodes.M_UMU_1_F001.geometry} material={nodes.M_UMU_1_F001.material} position={[5.998, 3.01, 2.465]}>
          <mesh name="M_UMU1_5_PNT" geometry={nodes.M_UMU1_5_PNT.geometry} material={nodes.M_UMU1_5_PNT.material} position={[-5.998, -4.902, 0.224]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU1_5.glb')
