/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU1_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU1_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU1_7obj" scale={0.613}>
        <mesh name="M_UMTU_F_A003" geometry={nodes.M_UMTU_F_A003.geometry} material={nodes.M_UMTU_F_A003.material} position={[6.858, 3.005, 2.449]} />
        <mesh name="M_UMTU_F_B003" geometry={nodes.M_UMTU_F_B003.geometry} material={nodes.M_UMTU_F_B003.material} position={[6.858, 3.002, 2.449]} />
        <mesh name="M_UMTU_F_C003" geometry={nodes.M_UMTU_F_C003.geometry} material={nodes.M_UMTU_F_C003.material} position={[6.858, 2.996, 2.449]} />
        <mesh name="M_UMU1_7" geometry={nodes.M_UMU1_7.geometry} material={nodes.M_UMU1_7.material} />
        <mesh name="M_UMU_1_F003" geometry={nodes.M_UMU_1_F003.geometry} material={nodes.M_UMU_1_F003.material} position={[6.861, 3.005, 2.461]}>
          <mesh name="M_UMU1_7_PNT" geometry={nodes.M_UMU1_7_PNT.geometry} material={nodes.M_UMU1_7_PNT.material} position={[-6.861, -4.894, 0.224]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU1_7.glb')
