/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU1_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU1_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU1_6obj" scale={0.611}>
        <mesh name="M_UMTU_F_A002" geometry={nodes.M_UMTU_F_A002.geometry} material={nodes.M_UMTU_F_A002.material} position={[6.434, 3.01, 2.454]} />
        <mesh name="M_UMTU_F_B002" geometry={nodes.M_UMTU_F_B002.geometry} material={nodes.M_UMTU_F_B002.material} position={[6.434, 3.007, 2.454]} />
        <mesh name="M_UMTU_F_C002" geometry={nodes.M_UMTU_F_C002.geometry} material={nodes.M_UMTU_F_C002.material} position={[6.434, 3.002, 2.454]} />
        <mesh name="M_UMU1_6" geometry={nodes.M_UMU1_6.geometry} material={nodes.M_UMU1_6.material} />
        <mesh name="M_UMU_1_F002" geometry={nodes.M_UMU_1_F002.geometry} material={nodes.M_UMU_1_F002.material} position={[6.436, 3.011, 2.466]}>
          <mesh name="M_UMU1_6_PNT" geometry={nodes.M_UMU1_6_PNT.geometry} material={nodes.M_UMU1_6_PNT.material} position={[-6.436, -4.903, 0.224]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU1_6.glb')
