/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU1_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU1_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU1_2obj" scale={0.609}>
        <mesh name="M_UMTU_F_A005" geometry={nodes.M_UMTU_F_A005.geometry} material={nodes.M_UMTU_F_A005.material} position={[4.743, 3.023, 2.464]} />
        <mesh name="M_UMTU_F_B005" geometry={nodes.M_UMTU_F_B005.geometry} material={nodes.M_UMTU_F_B005.material} position={[4.743, 3.02, 2.464]} />
        <mesh name="M_UMTU_F_C005" geometry={nodes.M_UMTU_F_C005.geometry} material={nodes.M_UMTU_F_C005.material} position={[4.743, 3.014, 2.464]} />
        <mesh name="M_UMU1_2" geometry={nodes.M_UMU1_2.geometry} material={nodes.M_UMU1_2.material} />
        <mesh name="M_UMU_1_F005" geometry={nodes.M_UMU_1_F005.geometry} material={nodes.M_UMU_1_F005.material} position={[4.746, 3.023, 2.476]}>
          <mesh name="M_UMU1_2_PNT" geometry={nodes.M_UMU1_2_PNT.geometry} material={nodes.M_UMU1_2_PNT.material} position={[-4.746, -4.924, 0.225]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU1_2.glb')
