/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UML_1_F_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UML_1_F_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UML_3_F_3obj" scale={1.052}>
        <mesh name="M_UML_1_F" geometry={nodes.M_UML_1_F.geometry} material={nodes.M_UML_1_F.material} position={[-3.469, -0.362, 1.442]}>
          <mesh name="M_UML_1_PNT_H" geometry={nodes.M_UML_1_PNT_H.geometry} material={nodes.M_UML_1_PNT_H.material} position={[1.733, -2.224, 0.172]} />
          <mesh name="M_UML_1_PNT_V" geometry={nodes.M_UML_1_PNT_V.geometry} material={nodes.M_UML_1_PNT_V.material} position={[2.449, -1.382, 0.172]} />
        </mesh>
        <mesh name="M_UML_1_F001" geometry={nodes.M_UML_1_F001.geometry} material={nodes.M_UML_1_F001.material} position={[3.484, -0.362, 1.445]}>
          <mesh name="M_UML_1_PNT_H_1" geometry={nodes.M_UML_1_PNT_H_1.geometry} material={nodes.M_UML_1_PNT_H_1.material} position={[-1.748, -2.224, 0.169]} rotation={[-Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UML_1_PNT_V_1" geometry={nodes.M_UML_1_PNT_V_1.geometry} material={nodes.M_UML_1_PNT_V_1.material} position={[-2.465, -1.382, 0.169]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UML_1_F_A" geometry={nodes.M_UML_1_F_A.geometry} material={nodes.M_UML_1_F_A.material} position={[-3.483, 1.443, 1.431]} />
        <mesh name="M_UML_1_F_A001" geometry={nodes.M_UML_1_F_A001.geometry} material={nodes.M_UML_1_F_A001.material} position={[3.481, 1.443, 1.435]} />
        <mesh name="M_UML_1_F_B" geometry={nodes.M_UML_1_F_B.geometry} material={nodes.M_UML_1_F_B.material} position={[-3.487, 1.443, 1.431]} />
        <mesh name="M_UML_1_F_B001" geometry={nodes.M_UML_1_F_B001.geometry} material={nodes.M_UML_1_F_B001.material} position={[3.481, 1.443, 1.435]} />
        <mesh name="M_UML_1_F_C" geometry={nodes.M_UML_1_F_C.geometry} material={nodes.M_UML_1_F_C.material} position={[-3.487, 0.147, 1.431]} />
        <mesh name="M_UML_1_F_C001" geometry={nodes.M_UML_1_F_C001.geometry} material={nodes.M_UML_1_F_C001.material} position={[3.481, 0.147, 1.435]} />
        <mesh name="M_UML_3" geometry={nodes.M_UML_3.geometry} material={nodes.M_UML_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UML_1_F_3.glb')
