/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UML_1_F_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UML_1_F_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UML_2_F_2obj" scale={1.052}>
        <mesh name="M_UML_1_F006" geometry={nodes.M_UML_1_F006.geometry} material={nodes.M_UML_1_F006.material} position={[-2.978, -0.362, 1.442]}>
          <mesh name="M_UML_1_PNT_H002" geometry={nodes.M_UML_1_PNT_H002.geometry} material={nodes.M_UML_1_PNT_H002.material} position={[1.482, -2.224, 0.172]} />
          <mesh name="M_UML_1_PNT_V002" geometry={nodes.M_UML_1_PNT_V002.geometry} material={nodes.M_UML_1_PNT_V002.material} position={[1.959, -1.382, 0.172]} />
        </mesh>
        <mesh name="M_UML_1_F007" geometry={nodes.M_UML_1_F007.geometry} material={nodes.M_UML_1_F007.material} position={[2.981, -0.362, 1.445]}>
          <mesh name="M_UML_1_PNT_H_1002" geometry={nodes.M_UML_1_PNT_H_1002.geometry} material={nodes.M_UML_1_PNT_H_1002.material} position={[-1.486, -2.224, 0.169]} rotation={[-Math.PI, 0, 0]} scale={-1} />
          <mesh name="M_UML_1_PNT_V_1002" geometry={nodes.M_UML_1_PNT_V_1002.geometry} material={nodes.M_UML_1_PNT_V_1002.material} position={[-1.962, -1.382, 0.169]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UML_1_F_A006" geometry={nodes.M_UML_1_F_A006.geometry} material={nodes.M_UML_1_F_A006.material} position={[-2.992, 1.443, 1.431]} />
        <mesh name="M_UML_1_F_A007" geometry={nodes.M_UML_1_F_A007.geometry} material={nodes.M_UML_1_F_A007.material} position={[2.978, 1.443, 1.435]} />
        <mesh name="M_UML_1_F_B006" geometry={nodes.M_UML_1_F_B006.geometry} material={nodes.M_UML_1_F_B006.material} position={[-2.997, 1.443, 1.431]} />
        <mesh name="M_UML_1_F_B007" geometry={nodes.M_UML_1_F_B007.geometry} material={nodes.M_UML_1_F_B007.material} position={[2.978, 1.443, 1.435]} />
        <mesh name="M_UML_1_F_C006" geometry={nodes.M_UML_1_F_C006.geometry} material={nodes.M_UML_1_F_C006.material} position={[-2.997, 0.147, 1.431]} />
        <mesh name="M_UML_1_F_C007" geometry={nodes.M_UML_1_F_C007.geometry} material={nodes.M_UML_1_F_C007.material} position={[2.978, 0.147, 1.435]} />
        <mesh name="M_UML_2" geometry={nodes.M_UML_2.geometry} material={nodes.M_UML_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UML_1_F_2.glb')
