/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UML_1_F_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UML_1_F_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UML_1obj" scale={1.052}>
        <mesh name="M_UML_1" geometry={nodes.M_UML_1.geometry} material={nodes.M_UML_1.material} />
        <mesh name="M_UML_1_F004" geometry={nodes.M_UML_1_F004.geometry} material={nodes.M_UML_1_F004.material} position={[-2.477, -0.362, 1.442]}>
          <mesh name="M_UML_1_PNT" geometry={nodes.M_UML_1_PNT.geometry} material={nodes.M_UML_1_PNT.material} position={[1.219, -1.382, 0.172]} />
        </mesh>
        <mesh name="M_UML_1_F005" geometry={nodes.M_UML_1_F005.geometry} material={nodes.M_UML_1_F005.material} position={[2.483, -0.362, 1.445]}>
          <mesh name="M_UML_1_PNT001" geometry={nodes.M_UML_1_PNT001.geometry} material={nodes.M_UML_1_PNT001.material} position={[-1.225, -1.382, 0.169]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        </mesh>
        <mesh name="M_UML_1_F_A004" geometry={nodes.M_UML_1_F_A004.geometry} material={nodes.M_UML_1_F_A004.material} position={[-2.491, 1.443, 1.431]} />
        <mesh name="M_UML_1_F_A005" geometry={nodes.M_UML_1_F_A005.geometry} material={nodes.M_UML_1_F_A005.material} position={[2.48, 1.443, 1.435]} />
        <mesh name="M_UML_1_F_B004" geometry={nodes.M_UML_1_F_B004.geometry} material={nodes.M_UML_1_F_B004.material} position={[-2.496, 1.443, 1.431]} />
        <mesh name="M_UML_1_F_B005" geometry={nodes.M_UML_1_F_B005.geometry} material={nodes.M_UML_1_F_B005.material} position={[2.48, 1.443, 1.435]} />
        <mesh name="M_UML_1_F_C004" geometry={nodes.M_UML_1_F_C004.geometry} material={nodes.M_UML_1_F_C004.material} position={[-2.496, 0.147, 1.431]} />
        <mesh name="M_UML_1_F_C005" geometry={nodes.M_UML_1_F_C005.geometry} material={nodes.M_UML_1_F_C005.material} position={[2.48, 0.147, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UML_1_F_1.glb')
