/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMY_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMY_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMY_4obj" scale={1.137}>
        <mesh name="M_UMY_1_F002" geometry={nodes.M_UMY_1_F002.geometry} material={nodes.M_UMY_1_F002.material} position={[3.924, -0.016, 1.334]}>
          <mesh name="M_UMY_4_PNT001" geometry={nodes.M_UMY_4_PNT001.geometry} material={nodes.M_UMY_4_PNT001.material} position={[-3.924, -2.387, 0.146]} />
        </mesh>
        <mesh name="M_UMY_1_F003" geometry={nodes.M_UMY_1_F003.geometry} material={nodes.M_UMY_1_F003.material} position={[3.924, 3.001, 1.334]}>
          <mesh name="M_UMY_4_PNT" geometry={nodes.M_UMY_4_PNT.geometry} material={nodes.M_UMY_4_PNT.material} position={[-3.924, -2.384, 0.146]} />
        </mesh>
        <mesh name="M_UMY_4" geometry={nodes.M_UMY_4.geometry} material={nodes.M_UMY_4.material} />
        <mesh name="M_UMY_F_A002" geometry={nodes.M_UMY_F_A002.geometry} material={nodes.M_UMY_F_A002.material} position={[3.922, -0.017, 1.327]} />
        <mesh name="M_UMY_F_A003" geometry={nodes.M_UMY_F_A003.geometry} material={nodes.M_UMY_F_A003.material} position={[3.922, 3, 1.327]} />
        <mesh name="M_UMY_F_B002" geometry={nodes.M_UMY_F_B002.geometry} material={nodes.M_UMY_F_B002.material} position={[3.922, -0.018, 1.327]} />
        <mesh name="M_UMY_F_B003" geometry={nodes.M_UMY_F_B003.geometry} material={nodes.M_UMY_F_B003.material} position={[3.922, 2.999, 1.327]} />
        <mesh name="M_UMY_F_C002" geometry={nodes.M_UMY_F_C002.geometry} material={nodes.M_UMY_F_C002.material} position={[3.922, -0.021, 1.327]} />
        <mesh name="M_UMY_F_C003" geometry={nodes.M_UMY_F_C003.geometry} material={nodes.M_UMY_F_C003.material} position={[3.922, 2.996, 1.327]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMY_4.glb')
