/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMY_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMY_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMY_3obj" scale={1.046}>
        <mesh name="M_UMY_1_F" geometry={nodes.M_UMY_1_F.geometry} material={nodes.M_UMY_1_F.material} position={[4.262, -0.018, 1.449]}>
          <mesh name="M_UMY_3_PNT" geometry={nodes.M_UMY_3_PNT.geometry} material={nodes.M_UMY_3_PNT.material} position={[-4.262, -2.353, 0.158]} />
        </mesh>
        <mesh name="M_UMY_1_F001" geometry={nodes.M_UMY_1_F001.geometry} material={nodes.M_UMY_1_F001.material} position={[4.262, 3.001, 1.449]}>
          <mesh name="M_UMY_3_PNT001" geometry={nodes.M_UMY_3_PNT001.geometry} material={nodes.M_UMY_3_PNT001.material} position={[-4.262, -2.331, 0.158]} />
        </mesh>
        <mesh name="M_UMY_3" geometry={nodes.M_UMY_3.geometry} material={nodes.M_UMY_3.material} />
        <mesh name="M_UMY_F_A" geometry={nodes.M_UMY_F_A.geometry} material={nodes.M_UMY_F_A.material} position={[4.26, -0.018, 1.441]} />
        <mesh name="M_UMY_F_A001" geometry={nodes.M_UMY_F_A001.geometry} material={nodes.M_UMY_F_A001.material} position={[4.26, 3.001, 1.441]} />
        <mesh name="M_UMY_F_B" geometry={nodes.M_UMY_F_B.geometry} material={nodes.M_UMY_F_B.material} position={[4.26, -0.02, 1.441]} />
        <mesh name="M_UMY_F_B001" geometry={nodes.M_UMY_F_B001.geometry} material={nodes.M_UMY_F_B001.material} position={[4.26, 2.999, 1.441]} />
        <mesh name="M_UMY_F_C" geometry={nodes.M_UMY_F_C.geometry} material={nodes.M_UMY_F_C.material} position={[4.26, -0.023, 1.441]} />
        <mesh name="M_UMY_F_C001" geometry={nodes.M_UMY_F_C001.geometry} material={nodes.M_UMY_F_C001.material} position={[4.26, 2.996, 1.441]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMY_3.glb')
