/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMY_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMY_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMY_7obj" scale={1.402}>
        <mesh name="M_UMY_1_F008" geometry={nodes.M_UMY_1_F008.geometry} material={nodes.M_UMY_1_F008.material} position={[3.18, -0.013, 1.081]}>
          <mesh name="M_UMY_7_PNT001" geometry={nodes.M_UMY_7_PNT001.geometry} material={nodes.M_UMY_7_PNT001.material} position={[-3.18, -2.507, 0.118]} />
        </mesh>
        <mesh name="M_UMY_1_F009" geometry={nodes.M_UMY_1_F009.geometry} material={nodes.M_UMY_1_F009.material} position={[3.18, 2.997, 1.081]}>
          <mesh name="M_UMY_7_PNT" geometry={nodes.M_UMY_7_PNT.geometry} material={nodes.M_UMY_7_PNT.material} position={[-3.18, -2.497, 0.118]} />
        </mesh>
        <mesh name="M_UMY_7" geometry={nodes.M_UMY_7.geometry} material={nodes.M_UMY_7.material} />
        <mesh name="M_UMY_F_A008" geometry={nodes.M_UMY_F_A008.geometry} material={nodes.M_UMY_F_A008.material} position={[3.179, -0.014, 1.075]} />
        <mesh name="M_UMY_F_A009" geometry={nodes.M_UMY_F_A009.geometry} material={nodes.M_UMY_F_A009.material} position={[3.179, 2.997, 1.075]} />
        <mesh name="M_UMY_F_B008" geometry={nodes.M_UMY_F_B008.geometry} material={nodes.M_UMY_F_B008.material} position={[3.179, -0.015, 1.075]} />
        <mesh name="M_UMY_F_B009" geometry={nodes.M_UMY_F_B009.geometry} material={nodes.M_UMY_F_B009.material} position={[3.179, 2.996, 1.075]} />
        <mesh name="M_UMY_F_C008" geometry={nodes.M_UMY_F_C008.geometry} material={nodes.M_UMY_F_C008.material} position={[3.179, -0.017, 1.075]} />
        <mesh name="M_UMY_F_C009" geometry={nodes.M_UMY_F_C009.geometry} material={nodes.M_UMY_F_C009.material} position={[3.179, 2.993, 1.075]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMY_7.glb')
