/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMY_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMY_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMY_6obj" scale={1.311}>
        <mesh name="M_UMY_1_F006" geometry={nodes.M_UMY_1_F006.geometry} material={nodes.M_UMY_1_F006.material} position={[3.402, -0.014, 1.157]}>
          <mesh name="M_UMY_6_PNT001" geometry={nodes.M_UMY_6_PNT001.geometry} material={nodes.M_UMY_6_PNT001.material} position={[-3.402, -2.484, 0.126]} />
        </mesh>
        <mesh name="M_UMY_1_F007" geometry={nodes.M_UMY_1_F007.geometry} material={nodes.M_UMY_1_F007.material} position={[3.402, 3.014, 1.157]}>
          <mesh name="M_UMY_6_PNT" geometry={nodes.M_UMY_6_PNT.geometry} material={nodes.M_UMY_6_PNT.material} position={[-3.402, -2.479, 0.126]} />
        </mesh>
        <mesh name="M_UMY_6" geometry={nodes.M_UMY_6.geometry} material={nodes.M_UMY_6.material} />
        <mesh name="M_UMY_F_A006" geometry={nodes.M_UMY_F_A006.geometry} material={nodes.M_UMY_F_A006.material} position={[3.401, -0.014, 1.15]} />
        <mesh name="M_UMY_F_A007" geometry={nodes.M_UMY_F_A007.geometry} material={nodes.M_UMY_F_A007.material} position={[3.401, 3.013, 1.15]} />
        <mesh name="M_UMY_F_B006" geometry={nodes.M_UMY_F_B006.geometry} material={nodes.M_UMY_F_B006.material} position={[3.401, -0.016, 1.15]} />
        <mesh name="M_UMY_F_B007" geometry={nodes.M_UMY_F_B007.geometry} material={nodes.M_UMY_F_B007.material} position={[3.401, 3.012, 1.15]} />
        <mesh name="M_UMY_F_C006" geometry={nodes.M_UMY_F_C006.geometry} material={nodes.M_UMY_F_C006.material} position={[3.401, -0.018, 1.15]} />
        <mesh name="M_UMY_F_C007" geometry={nodes.M_UMY_F_C007.geometry} material={nodes.M_UMY_F_C007.material} position={[3.401, 3.009, 1.15]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMY_6.glb')
