/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMY_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMY_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMY_1obj" scale={0.877}>
        <mesh name="M_UMY_1" geometry={nodes.M_UMY_1.geometry} material={nodes.M_UMY_1.material} />
        <mesh name="M_UMY_1_F010" geometry={nodes.M_UMY_1_F010.geometry} material={nodes.M_UMY_1_F010.material} position={[5.085, -0.021, 1.729]}>
          <mesh name="M_UMY_1_PNT001" geometry={nodes.M_UMY_1_PNT001.geometry} material={nodes.M_UMY_1_PNT001.material} position={[-5.085, -2.197, 0.189]} />
        </mesh>
        <mesh name="M_UMY_1_F011" geometry={nodes.M_UMY_1_F011.geometry} material={nodes.M_UMY_1_F011.material} position={[5.085, 2.998, 1.729]}>
          <mesh name="M_UMY_1_PNT" geometry={nodes.M_UMY_1_PNT.geometry} material={nodes.M_UMY_1_PNT.material} position={[-5.085, -2.198, 0.189]} />
        </mesh>
        <mesh name="M_UMY_F_A010" geometry={nodes.M_UMY_F_A010.geometry} material={nodes.M_UMY_F_A010.material} position={[5.083, -0.022, 1.719]} />
        <mesh name="M_UMY_F_A011" geometry={nodes.M_UMY_F_A011.geometry} material={nodes.M_UMY_F_A011.material} position={[5.083, 2.997, 1.719]} />
        <mesh name="M_UMY_F_B010" geometry={nodes.M_UMY_F_B010.geometry} material={nodes.M_UMY_F_B010.material} position={[5.083, -0.024, 1.719]} />
        <mesh name="M_UMY_F_B011" geometry={nodes.M_UMY_F_B011.geometry} material={nodes.M_UMY_F_B011.material} position={[5.083, 2.995, 1.719]} />
        <mesh name="M_UMY_F_C010" geometry={nodes.M_UMY_F_C010.geometry} material={nodes.M_UMY_F_C010.material} position={[5.083, -0.027, 1.719]} />
        <mesh name="M_UMY_F_C011" geometry={nodes.M_UMY_F_C011.geometry} material={nodes.M_UMY_F_C011.material} position={[5.083, 2.991, 1.719]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMY_1.glb')
