/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMY_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMY_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMY_2obj" scale={0.956}>
        <mesh name="M_UMY_1_F012" geometry={nodes.M_UMY_1_F012.geometry} material={nodes.M_UMY_1_F012.material} position={[4.665, -0.02, 1.586]}>
          <mesh name="M_UMY_1_PNT002" geometry={nodes.M_UMY_1_PNT002.geometry} material={nodes.M_UMY_1_PNT002.material} position={[-4.665, -2.296, 0.173]} />
        </mesh>
        <mesh name="M_UMY_1_F013" geometry={nodes.M_UMY_1_F013.geometry} material={nodes.M_UMY_1_F013.material} position={[4.665, 3.009, 1.586]}>
          <mesh name="M_UMY_1_PNT003" geometry={nodes.M_UMY_1_PNT003.geometry} material={nodes.M_UMY_1_PNT003.material} position={[-4.665, -2.275, 0.173]} />
        </mesh>
        <mesh name="M_UMY_2" geometry={nodes.M_UMY_2.geometry} material={nodes.M_UMY_2.material} />
        <mesh name="M_UMY_F_A012" geometry={nodes.M_UMY_F_A012.geometry} material={nodes.M_UMY_F_A012.material} position={[4.663, -0.02, 1.577]} />
        <mesh name="M_UMY_F_A013" geometry={nodes.M_UMY_F_A013.geometry} material={nodes.M_UMY_F_A013.material} position={[4.663, 3.009, 1.577]} />
        <mesh name="M_UMY_F_B012" geometry={nodes.M_UMY_F_B012.geometry} material={nodes.M_UMY_F_B012.material} position={[4.663, -0.022, 1.577]} />
        <mesh name="M_UMY_F_B013" geometry={nodes.M_UMY_F_B013.geometry} material={nodes.M_UMY_F_B013.material} position={[4.663, 3.007, 1.577]} />
        <mesh name="M_UMY_F_C012" geometry={nodes.M_UMY_F_C012.geometry} material={nodes.M_UMY_F_C012.material} position={[4.663, -0.025, 1.577]} />
        <mesh name="M_UMY_F_C013" geometry={nodes.M_UMY_F_C013.geometry} material={nodes.M_UMY_F_C013.material} position={[4.663, 3.004, 1.577]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMY_2.glb')
