/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMY_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMY_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMY_5obj" scale={1.223}>
        <mesh name="M_UMY_1_F004" geometry={nodes.M_UMY_1_F004.geometry} material={nodes.M_UMY_1_F004.material} position={[3.649, -0.015, 1.24]}>
          <mesh name="M_UMY_5_PNT001" geometry={nodes.M_UMY_5_PNT001.geometry} material={nodes.M_UMY_5_PNT001.material} position={[-3.649, -2.434, 0.135]} />
        </mesh>
        <mesh name="M_UMY_1_F005" geometry={nodes.M_UMY_1_F005.geometry} material={nodes.M_UMY_1_F005.material} position={[3.649, 3.005, 1.24]}>
          <mesh name="M_UMY_5_PNT" geometry={nodes.M_UMY_5_PNT.geometry} material={nodes.M_UMY_5_PNT.material} position={[-3.649, -2.431, 0.135]} />
        </mesh>
        <mesh name="M_UMY_5" geometry={nodes.M_UMY_5.geometry} material={nodes.M_UMY_5.material} />
        <mesh name="M_UMY_F_A004" geometry={nodes.M_UMY_F_A004.geometry} material={nodes.M_UMY_F_A004.material} position={[3.647, -0.016, 1.233]} />
        <mesh name="M_UMY_F_A005" geometry={nodes.M_UMY_F_A005.geometry} material={nodes.M_UMY_F_A005.material} position={[3.647, 3.005, 1.233]} />
        <mesh name="M_UMY_F_B004" geometry={nodes.M_UMY_F_B004.geometry} material={nodes.M_UMY_F_B004.material} position={[3.647, -0.017, 1.233]} />
        <mesh name="M_UMY_F_B005" geometry={nodes.M_UMY_F_B005.geometry} material={nodes.M_UMY_F_B005.material} position={[3.647, 3.004, 1.233]} />
        <mesh name="M_UMY_F_C004" geometry={nodes.M_UMY_F_C004.geometry} material={nodes.M_UMY_F_C004.material} position={[3.647, -0.02, 1.233]} />
        <mesh name="M_UMY_F_C005" geometry={nodes.M_UMY_F_C005.geometry} material={nodes.M_UMY_F_C005.material} position={[3.647, 3.001, 1.233]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMY_5.glb')
