/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU2_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU2_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU2_2obj" scale={1.052}>
        <mesh name="M_UMU2_1_F008" geometry={nodes.M_UMU2_1_F008.geometry} material={nodes.M_UMU2_1_F008.material} position={[1.247, 1.751, 1.442]}>
          <mesh name="M_UMU2_2_PNT" geometry={nodes.M_UMU2_2_PNT.geometry} material={nodes.M_UMU2_2_PNT.material} position={[-1.247, -2.851, 0.13]} />
        </mesh>
        <mesh name="M_UMU2_2" geometry={nodes.M_UMU2_2.geometry} material={nodes.M_UMU2_2.material} />
        <mesh name="M_UMU2_F_A008" geometry={nodes.M_UMU2_F_A008.geometry} material={nodes.M_UMU2_F_A008.material} position={[1.246, 1.75, 1.435]} />
        <mesh name="M_UMU2_F_B008" geometry={nodes.M_UMU2_F_B008.geometry} material={nodes.M_UMU2_F_B008.material} position={[1.246, 1.749, 1.435]} />
        <mesh name="M_UMU2_F_C008" geometry={nodes.M_UMU2_F_C008.geometry} material={nodes.M_UMU2_F_C008.material} position={[1.246, 1.745, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU2_2.glb')
