/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU2_11.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU2_11.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU2_11obj" scale={1.052}>
        <mesh name="M_UMU2_11" geometry={nodes.M_UMU2_11.geometry} material={nodes.M_UMU2_11.material} />
        <mesh name="M_UMU2_1_F004" geometry={nodes.M_UMU2_1_F004.geometry} material={nodes.M_UMU2_1_F004.material} position={[3.484, 1.751, 1.442]}>
          <mesh name="M_UMU2_11_PNT" geometry={nodes.M_UMU2_11_PNT.geometry} material={nodes.M_UMU2_11_PNT.material} position={[-3.484, -2.851, 0.13]} />
        </mesh>
        <mesh name="M_UMU2_F_A004" geometry={nodes.M_UMU2_F_A004.geometry} material={nodes.M_UMU2_F_A004.material} position={[3.482, 1.75, 1.435]} />
        <mesh name="M_UMU2_F_B004" geometry={nodes.M_UMU2_F_B004.geometry} material={nodes.M_UMU2_F_B004.material} position={[3.482, 1.749, 1.435]} />
        <mesh name="M_UMU2_F_C004" geometry={nodes.M_UMU2_F_C004.geometry} material={nodes.M_UMU2_F_C004.material} position={[3.482, 1.745, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU2_11.glb')
