/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU2_13.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU2_13.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU2_13obj" scale={1.052}>
        <mesh name="M_UMU2_13" geometry={nodes.M_UMU2_13.geometry} material={nodes.M_UMU2_13.material} />
        <mesh name="M_UMU2_1_F006" geometry={nodes.M_UMU2_1_F006.geometry} material={nodes.M_UMU2_1_F006.material} position={[3.99, 1.751, 1.442]}>
          <mesh name="M_UMU2_13_PNT" geometry={nodes.M_UMU2_13_PNT.geometry} material={nodes.M_UMU2_13_PNT.material} position={[-3.99, -2.851, 0.13]} />
        </mesh>
        <mesh name="M_UMU2_F_A006" geometry={nodes.M_UMU2_F_A006.geometry} material={nodes.M_UMU2_F_A006.material} position={[3.988, 1.75, 1.435]} />
        <mesh name="M_UMU2_F_B006" geometry={nodes.M_UMU2_F_B006.geometry} material={nodes.M_UMU2_F_B006.material} position={[3.988, 1.749, 1.435]} />
        <mesh name="M_UMU2_F_C006" geometry={nodes.M_UMU2_F_C006.geometry} material={nodes.M_UMU2_F_C006.material} position={[3.988, 1.745, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU2_13.glb')
