/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU2_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU2_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU2_5obj" scale={1.052}>
        <mesh name="M_UMU2_1_F011" geometry={nodes.M_UMU2_1_F011.geometry} material={nodes.M_UMU2_1_F011.material} position={[1.993, 1.751, 1.442]}>
          <mesh name="M_UMU2_5_PNT" geometry={nodes.M_UMU2_5_PNT.geometry} material={nodes.M_UMU2_5_PNT.material} position={[-1.993, -2.851, 0.13]} />
        </mesh>
        <mesh name="M_UMU2_5" geometry={nodes.M_UMU2_5.geometry} material={nodes.M_UMU2_5.material} />
        <mesh name="M_UMU2_F_A011" geometry={nodes.M_UMU2_F_A011.geometry} material={nodes.M_UMU2_F_A011.material} position={[1.992, 1.75, 1.435]} />
        <mesh name="M_UMU2_F_B011" geometry={nodes.M_UMU2_F_B011.geometry} material={nodes.M_UMU2_F_B011.material} position={[1.992, 1.749, 1.435]} />
        <mesh name="M_UMU2_F_C011" geometry={nodes.M_UMU2_F_C011.geometry} material={nodes.M_UMU2_F_C011.material} position={[1.992, 1.745, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU2_5.glb')
