/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU2_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU2_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU2_4obj" scale={1.052}>
        <mesh name="M_UMU2_1_F010" geometry={nodes.M_UMU2_1_F010.geometry} material={nodes.M_UMU2_1_F010.material} position={[1.748, 1.751, 1.442]}>
          <mesh name="M_UMU2_4_PNT" geometry={nodes.M_UMU2_4_PNT.geometry} material={nodes.M_UMU2_4_PNT.material} position={[-1.748, -2.851, 0.13]} />
        </mesh>
        <mesh name="M_UMU2_4_" geometry={nodes.M_UMU2_4_.geometry} material={nodes.M_UMU2_4_.material} />
        <mesh name="M_UMU2_F_A010" geometry={nodes.M_UMU2_F_A010.geometry} material={nodes.M_UMU2_F_A010.material} position={[1.747, 1.75, 1.435]} />
        <mesh name="M_UMU2_F_B010" geometry={nodes.M_UMU2_F_B010.geometry} material={nodes.M_UMU2_F_B010.material} position={[1.747, 1.749, 1.435]} />
        <mesh name="M_UMU2_F_C010" geometry={nodes.M_UMU2_F_C010.geometry} material={nodes.M_UMU2_F_C010.material} position={[1.747, 1.745, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU2_4.glb')
