/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU2_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU2_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU2_7obj" scale={1.052}>
        <mesh name="M_UMU2_1_F" geometry={nodes.M_UMU2_1_F.geometry} material={nodes.M_UMU2_1_F.material} position={[2.489, 1.751, 1.442]}>
          <mesh name="M_UMU2_7_PNT" geometry={nodes.M_UMU2_7_PNT.geometry} material={nodes.M_UMU2_7_PNT.material} position={[-2.489, -2.851, 0.13]} />
        </mesh>
        <mesh name="M_UMU2_7" geometry={nodes.M_UMU2_7.geometry} material={nodes.M_UMU2_7.material} />
        <mesh name="M_UMU2_F_A" geometry={nodes.M_UMU2_F_A.geometry} material={nodes.M_UMU2_F_A.material} position={[2.488, 1.75, 1.435]} />
        <mesh name="M_UMU2_F_B" geometry={nodes.M_UMU2_F_B.geometry} material={nodes.M_UMU2_F_B.material} position={[2.488, 1.749, 1.435]} />
        <mesh name="M_UMU2_F_C" geometry={nodes.M_UMU2_F_C.geometry} material={nodes.M_UMU2_F_C.material} position={[2.488, 1.745, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU2_7.glb')
