/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU2_10.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU2_10.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU2_10obj" scale={1.052}>
        <mesh name="M_UMU2_10" geometry={nodes.M_UMU2_10.geometry} material={nodes.M_UMU2_10.material} />
        <mesh name="M_UMU2_1_F003" geometry={nodes.M_UMU2_1_F003.geometry} material={nodes.M_UMU2_1_F003.material} position={[3.236, 1.751, 1.442]}>
          <mesh name="M_UMU2_10_PNT" geometry={nodes.M_UMU2_10_PNT.geometry} material={nodes.M_UMU2_10_PNT.material} position={[-3.236, -2.851, 0.13]} />
        </mesh>
        <mesh name="M_UMU2_F_A003" geometry={nodes.M_UMU2_F_A003.geometry} material={nodes.M_UMU2_F_A003.material} position={[3.234, 1.75, 1.435]} />
        <mesh name="M_UMU2_F_B003" geometry={nodes.M_UMU2_F_B003.geometry} material={nodes.M_UMU2_F_B003.material} position={[3.234, 1.749, 1.435]} />
        <mesh name="M_UMU2_F_C003" geometry={nodes.M_UMU2_F_C003.geometry} material={nodes.M_UMU2_F_C003.material} position={[3.234, 1.745, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU2_10.glb')
