/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU2_12.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU2_12.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU2_12obj" scale={1.052}>
        <mesh name="M_UMU2_12" geometry={nodes.M_UMU2_12.geometry} material={nodes.M_UMU2_12.material} />
        <mesh name="M_UMU2_1_F005" geometry={nodes.M_UMU2_1_F005.geometry} material={nodes.M_UMU2_1_F005.material} position={[3.741, 1.751, 1.442]}>
          <mesh name="M_UMU2_12_PNT" geometry={nodes.M_UMU2_12_PNT.geometry} material={nodes.M_UMU2_12_PNT.material} position={[-3.741, -2.851, 0.13]} />
        </mesh>
        <mesh name="M_UMU2_F_A005" geometry={nodes.M_UMU2_F_A005.geometry} material={nodes.M_UMU2_F_A005.material} position={[3.739, 1.75, 1.435]} />
        <mesh name="M_UMU2_F_B005" geometry={nodes.M_UMU2_F_B005.geometry} material={nodes.M_UMU2_F_B005.material} position={[3.739, 1.749, 1.435]} />
        <mesh name="M_UMU2_F_C005" geometry={nodes.M_UMU2_F_C005.geometry} material={nodes.M_UMU2_F_C005.material} position={[3.739, 1.745, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU2_12.glb')
