/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU2_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU2_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU2_3obj" scale={1.052}>
        <mesh name="M_UMU2_1_F009" geometry={nodes.M_UMU2_1_F009.geometry} material={nodes.M_UMU2_1_F009.material} position={[1.489, 1.751, 1.442]}>
          <mesh name="M_UMU2_3_PNT_H" geometry={nodes.M_UMU2_3_PNT_H.geometry} material={nodes.M_UMU2_3_PNT_H.material} position={[-1.489, -2.851, 0.13]} />
        </mesh>
        <mesh name="M_UMU2_3" geometry={nodes.M_UMU2_3.geometry} material={nodes.M_UMU2_3.material} />
        <mesh name="M_UMU2_F_A009" geometry={nodes.M_UMU2_F_A009.geometry} material={nodes.M_UMU2_F_A009.material} position={[1.487, 1.75, 1.435]} />
        <mesh name="M_UMU2_F_B009" geometry={nodes.M_UMU2_F_B009.geometry} material={nodes.M_UMU2_F_B009.material} position={[1.487, 1.749, 1.435]} />
        <mesh name="M_UMU2_F_C009" geometry={nodes.M_UMU2_F_C009.geometry} material={nodes.M_UMU2_F_C009.material} position={[1.487, 1.745, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU2_3.glb')
