/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU2_8.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU2_8.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU2_8obj" scale={1.052}>
        <mesh name="M_UMU2_1_F001" geometry={nodes.M_UMU2_1_F001.geometry} material={nodes.M_UMU2_1_F001.material} position={[2.739, 1.751, 1.442]}>
          <mesh name="M_UMU2_8_PNT" geometry={nodes.M_UMU2_8_PNT.geometry} material={nodes.M_UMU2_8_PNT.material} position={[-2.739, -2.851, 0.13]} />
        </mesh>
        <mesh name="M_UMU2_8" geometry={nodes.M_UMU2_8.geometry} material={materials['wire_000000000.014']} />
        <mesh name="M_UMU2_F_A001" geometry={nodes.M_UMU2_F_A001.geometry} material={nodes.M_UMU2_F_A001.material} position={[2.737, 1.75, 1.435]} />
        <mesh name="M_UMU2_F_B001" geometry={nodes.M_UMU2_F_B001.geometry} material={nodes.M_UMU2_F_B001.material} position={[2.737, 1.749, 1.435]} />
        <mesh name="M_UMU2_F_C001" geometry={nodes.M_UMU2_F_C001.geometry} material={nodes.M_UMU2_F_C001.material} position={[2.737, 1.745, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU2_8.glb')
