/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU2_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU2_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU2_6obj" scale={1.052}>
        <mesh name="M_UMU2_1_F012" geometry={nodes.M_UMU2_1_F012.geometry} material={nodes.M_UMU2_1_F012.material} position={[2.246, 1.751, 1.442]}>
          <mesh name="M_UMU2_6_PNT" geometry={nodes.M_UMU2_6_PNT.geometry} material={nodes.M_UMU2_6_PNT.material} position={[-2.246, -2.851, 0.13]} />
        </mesh>
        <mesh name="M_UMU2_6" geometry={nodes.M_UMU2_6.geometry} material={nodes.M_UMU2_6.material} />
        <mesh name="M_UMU2_F_A012" geometry={nodes.M_UMU2_F_A012.geometry} material={nodes.M_UMU2_F_A012.material} position={[2.244, 1.75, 1.435]} />
        <mesh name="M_UMU2_F_B012" geometry={nodes.M_UMU2_F_B012.geometry} material={nodes.M_UMU2_F_B012.material} position={[2.244, 1.749, 1.435]} />
        <mesh name="M_UMU2_F_C012" geometry={nodes.M_UMU2_F_C012.geometry} material={nodes.M_UMU2_F_C012.material} position={[2.244, 1.745, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU2_6.glb')
