/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU2_9.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU2_9.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU2_9obj" scale={1.052}>
        <mesh name="M_UMU2_1_F002" geometry={nodes.M_UMU2_1_F002.geometry} material={nodes.M_UMU2_1_F002.material} position={[2.99, 1.751, 1.442]}>
          <mesh name="M_UMU2_9_PNT" geometry={nodes.M_UMU2_9_PNT.geometry} material={nodes.M_UMU2_9_PNT.material} position={[-2.99, -2.851, 0.13]} />
        </mesh>
        <mesh name="M_UMU2_9" geometry={nodes.M_UMU2_9.geometry} material={nodes.M_UMU2_9.material} />
        <mesh name="M_UMU2_F_A002" geometry={nodes.M_UMU2_F_A002.geometry} material={nodes.M_UMU2_F_A002.material} position={[2.988, 1.75, 1.435]} />
        <mesh name="M_UMU2_F_B002" geometry={nodes.M_UMU2_F_B002.geometry} material={nodes.M_UMU2_F_B002.material} position={[2.988, 1.749, 1.435]} />
        <mesh name="M_UMU2_F_C002" geometry={nodes.M_UMU2_F_C002.geometry} material={nodes.M_UMU2_F_C002.material} position={[2.988, 1.745, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU2_9.glb')
