/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMU2_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMU2_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMU2_1obj" scale={1.052}>
        <mesh name="M_UMU2_1" geometry={nodes.M_UMU2_1.geometry} material={materials['wire_000000000.013']} />
        <mesh name="M_UMU2_1_F007" geometry={nodes.M_UMU2_1_F007.geometry} material={nodes.M_UMU2_1_F007.material} position={[0.995, 1.751, 1.442]}>
          <mesh name="M_UMU2_1_PNT" geometry={nodes.M_UMU2_1_PNT.geometry} material={nodes.M_UMU2_1_PNT.material} position={[-0.995, -2.851, 0.13]} />
        </mesh>
        <mesh name="M_UMU2_F_A007" geometry={nodes.M_UMU2_F_A007.geometry} material={nodes.M_UMU2_F_A007.material} position={[0.994, 1.75, 1.435]} />
        <mesh name="M_UMU2_F_B007" geometry={nodes.M_UMU2_F_B007.geometry} material={nodes.M_UMU2_F_B007.material} position={[0.994, 1.749, 1.435]} />
        <mesh name="M_UMU2_F_C007" geometry={nodes.M_UMU2_F_C007.geometry} material={nodes.M_UMU2_F_C007.material} position={[0.994, 1.745, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMU2_1.glb')
