/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./Handle2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('Handle2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Handle_02" geometry={nodes.Handle_02.geometry} material={nodes.Handle_02.material} rotation={[Math.PI / 2, 0, 0]} scale={0.012} />
    </group>
  )
}

useGLTF.preload('Handle2.glb')
