/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./Handle5.glb -k 
*/

import React from 'react'

export function Model(props) {
  return (
    <group {...props} dispose={null}>
      <group name="Scene" />
    </group>
  )
}

