/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./Handle4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('Handle4.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Handle_04" geometry={nodes.Handle_04.geometry} material={nodes.Handle_04.material} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
    </group>
  )
}

useGLTF.preload('Handle4.glb')
