/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./Handle1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes } = useGLTF('Handle1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="handle_01" geometry={nodes.handle_01.geometry} material={nodes.handle_01.material} rotation={[Math.PI / 2, 0, 0]} scale={0.005} />
    </group>
  )
}

useGLTF.preload('Handle1.glb')
