/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMN_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMN_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMN_2obj" scale={1.613}>
        <mesh name="M_UMM_1_F" geometry={nodes.M_UMM_1_F.geometry} material={nodes.M_UMM_1_F.material} position={[-1.945, -0.236, 0.941]}>
          <mesh name="M_UMN_1_PNT_H" geometry={nodes.M_UMN_1_PNT_H.geometry} material={nodes.M_UMN_1_PNT_H.material} position={[0.973, -2.098, 0.113]} />
          <mesh name="M_UMN_1_PNT_V002" geometry={nodes.M_UMN_1_PNT_V002.geometry} material={nodes.M_UMN_1_PNT_V002.material} position={[1.272, -1.544, 0.113]} />
        </mesh>
        <mesh name="M_UMM_1_F001" geometry={nodes.M_UMM_1_F001.geometry} material={nodes.M_UMM_1_F001.material} position={[1.948, -0.236, 0.943]}>
          <mesh name="M_UMN_1_PNT_H_1" geometry={nodes.M_UMN_1_PNT_H_1.geometry} material={nodes.M_UMN_1_PNT_H_1.material} position={[-0.976, -2.098, 0.111]} />
          <mesh name="M_UMN_1_PNT_V_1002" geometry={nodes.M_UMN_1_PNT_V_1002.geometry} material={nodes.M_UMN_1_PNT_V_1002.material} position={[-1.275, -1.544, 0.111]} />
        </mesh>
        <mesh name="M_UMM_1_F_A" geometry={nodes.M_UMM_1_F_A.geometry} material={nodes.M_UMM_1_F_A.material} position={[-1.954, 0.941, 0.934]} />
        <mesh name="M_UMM_1_F_A001" geometry={nodes.M_UMM_1_F_A001.geometry} material={nodes.M_UMM_1_F_A001.material} position={[1.946, 0.941, 0.936]} />
        <mesh name="M_UMM_1_F_B" geometry={nodes.M_UMM_1_F_B.geometry} material={nodes.M_UMM_1_F_B.material} position={[-1.957, 0.941, 0.934]} />
        <mesh name="M_UMM_1_F_B001" geometry={nodes.M_UMM_1_F_B001.geometry} material={nodes.M_UMM_1_F_B001.material} position={[1.946, 0.941, 0.936]} />
        <mesh name="M_UMM_1_F_C" geometry={nodes.M_UMM_1_F_C.geometry} material={nodes.M_UMM_1_F_C.material} position={[-1.957, 0.096, 0.934]} />
        <mesh name="M_UMM_1_F_C001" geometry={nodes.M_UMM_1_F_C001.geometry} material={nodes.M_UMM_1_F_C001.material} position={[1.946, 0.096, 0.936]} />
        <mesh name="M_UMN_2" geometry={nodes.M_UMN_2.geometry} material={nodes.M_UMN_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMN_2.glb')
