/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMN_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMN_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMN_3obj" scale={1.609}>
        <mesh name="M_UMM_1_F002" geometry={nodes.M_UMM_1_F002.geometry} material={nodes.M_UMM_1_F002.material} position={[-2.273, -0.237, 0.942]}>
          <mesh name="M_UMN_1_PNT_H001" geometry={nodes.M_UMN_1_PNT_H001.geometry} material={nodes.M_UMN_1_PNT_H001.material} position={[1.119, -2.102, 0.113]} />
          <mesh name="M_UMN_1_PNT_V003" geometry={nodes.M_UMN_1_PNT_V003.geometry} material={nodes.M_UMN_1_PNT_V003.material} position={[1.599, -1.547, 0.113]} />
        </mesh>
        <mesh name="M_UMM_1_F003" geometry={nodes.M_UMM_1_F003.geometry} material={nodes.M_UMM_1_F003.material} position={[2.278, -0.237, 0.944]}>
          <mesh name="M_UMN_1_PNT_H_1001" geometry={nodes.M_UMN_1_PNT_H_1001.geometry} material={nodes.M_UMN_1_PNT_H_1001.material} position={[-1.124, -2.102, 0.111]} />
          <mesh name="M_UMN_1_PNT_V_1003" geometry={nodes.M_UMN_1_PNT_V_1003.geometry} material={nodes.M_UMN_1_PNT_V_1003.material} position={[-1.604, -1.547, 0.111]} />
        </mesh>
        <mesh name="M_UMM_1_F_A002" geometry={nodes.M_UMM_1_F_A002.geometry} material={nodes.M_UMM_1_F_A002.material} position={[-2.283, 0.943, 0.935]} />
        <mesh name="M_UMM_1_F_A003" geometry={nodes.M_UMM_1_F_A003.geometry} material={nodes.M_UMM_1_F_A003.material} position={[2.276, 0.943, 0.937]} />
        <mesh name="M_UMM_1_F_B002" geometry={nodes.M_UMM_1_F_B002.geometry} material={nodes.M_UMM_1_F_B002.material} position={[-2.285, 0.943, 0.935]} />
        <mesh name="M_UMM_1_F_B003" geometry={nodes.M_UMM_1_F_B003.geometry} material={nodes.M_UMM_1_F_B003.material} position={[2.276, 0.943, 0.937]} />
        <mesh name="M_UMM_1_F_C002" geometry={nodes.M_UMM_1_F_C002.geometry} material={nodes.M_UMM_1_F_C002.material} position={[-2.285, 0.096, 0.935]} />
        <mesh name="M_UMM_1_F_C003" geometry={nodes.M_UMM_1_F_C003.geometry} material={nodes.M_UMM_1_F_C003.material} position={[2.276, 0.096, 0.937]} />
        <mesh name="M_UMN_3" geometry={nodes.M_UMN_3.geometry} material={nodes.M_UMN_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMN_3.glb')
