/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMN_1_F_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMN_1_F_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMN_1_F_1obj" scale={1.052}>
        <mesh name="M_UMM_1_F006" geometry={nodes.M_UMM_1_F006.geometry} material={nodes.M_UMM_1_F006.material} position={[-2.491, -0.362, 1.442]} />
        <mesh name="M_UMM_1_F007" geometry={nodes.M_UMM_1_F007.geometry} material={nodes.M_UMM_1_F007.material} position={[2.481, -0.362, 1.445]} />
        <mesh name="M_UMM_1_F_A006" geometry={nodes.M_UMM_1_F_A006.geometry} material={nodes.M_UMM_1_F_A006.material} position={[-2.505, 1.443, 1.431]} />
        <mesh name="M_UMM_1_F_A007" geometry={nodes.M_UMM_1_F_A007.geometry} material={nodes.M_UMM_1_F_A007.material} position={[2.477, 1.443, 1.435]} />
        <mesh name="M_UMM_1_F_B006" geometry={nodes.M_UMM_1_F_B006.geometry} material={nodes.M_UMM_1_F_B006.material} position={[-2.509, 1.443, 1.431]} />
        <mesh name="M_UMM_1_F_B007" geometry={nodes.M_UMM_1_F_B007.geometry} material={nodes.M_UMM_1_F_B007.material} position={[2.477, 1.443, 1.435]} />
        <mesh name="M_UMM_1_F_C006" geometry={nodes.M_UMM_1_F_C006.geometry} material={nodes.M_UMM_1_F_C006.material} position={[-2.509, 0.147, 1.431]} />
        <mesh name="M_UMM_1_F_C007" geometry={nodes.M_UMM_1_F_C007.geometry} material={nodes.M_UMM_1_F_C007.material} position={[2.477, 0.147, 1.435]} />
        <mesh name="M_UMN_1" geometry={nodes.M_UMN_1.geometry} material={nodes.M_UMN_1.material} />
        <mesh name="M_UMN_1_PNT_V" geometry={nodes.M_UMN_1_PNT_V.geometry} material={nodes.M_UMN_1_PNT_V.material} position={[-1.031, -2.73, 1.615]} />
        <mesh name="M_UMN_1_PNT_V001" geometry={nodes.M_UMN_1_PNT_V001.geometry} material={nodes.M_UMN_1_PNT_V001.material} position={[-1.031, -2.73, 1.615]} />
        <mesh name="M_UMN_1_PNT_V_1" geometry={nodes.M_UMN_1_PNT_V_1.geometry} material={nodes.M_UMN_1_PNT_V_1.material} position={[1.031, -2.73, 1.615]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh name="M_UMN_1_PNT_V_1001" geometry={nodes.M_UMN_1_PNT_V_1001.geometry} material={nodes.M_UMN_1_PNT_V_1001.material} position={[1.031, -2.73, 1.615]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMN_1_F_1.glb')
