/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMN_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMN_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMN_4obj" scale={1.613}>
        <mesh name="M_UMM_1_F004" geometry={nodes.M_UMM_1_F004.geometry} material={nodes.M_UMM_1_F004.material} position={[-2.59, -0.236, 0.941]}>
          <mesh name="M_UMN_1_PNT_H002" geometry={nodes.M_UMN_1_PNT_H002.geometry} material={nodes.M_UMN_1_PNT_H002.material} position={[1.267, -2.098, 0.113]} />
          <mesh name="M_UMN_1_PNT_V004" geometry={nodes.M_UMN_1_PNT_V004.geometry} material={nodes.M_UMN_1_PNT_V004.material} position={[1.918, -1.544, 0.113]} />
        </mesh>
        <mesh name="M_UMM_1_F005" geometry={nodes.M_UMM_1_F005.geometry} material={nodes.M_UMM_1_F005.material} position={[2.598, -0.236, 0.943]}>
          <mesh name="M_UMN_1_PNT_H_1002" geometry={nodes.M_UMN_1_PNT_H_1002.geometry} material={nodes.M_UMN_1_PNT_H_1002.material} position={[-1.275, -2.098, 0.111]} />
          <mesh name="M_UMN_1_PNT_V_1004" geometry={nodes.M_UMN_1_PNT_V_1004.geometry} material={nodes.M_UMN_1_PNT_V_1004.material} position={[-1.925, -1.544, 0.111]} />
        </mesh>
        <mesh name="M_UMM_1_F_A004" geometry={nodes.M_UMM_1_F_A004.geometry} material={nodes.M_UMM_1_F_A004.material} position={[-2.6, 0.941, 0.933]} />
        <mesh name="M_UMM_1_F_A005" geometry={nodes.M_UMM_1_F_A005.geometry} material={nodes.M_UMM_1_F_A005.material} position={[2.596, 0.941, 0.935]} />
        <mesh name="M_UMM_1_F_B004" geometry={nodes.M_UMM_1_F_B004.geometry} material={nodes.M_UMM_1_F_B004.material} position={[-2.603, 0.941, 0.933]} />
        <mesh name="M_UMM_1_F_B005" geometry={nodes.M_UMM_1_F_B005.geometry} material={nodes.M_UMM_1_F_B005.material} position={[2.596, 0.941, 0.935]} />
        <mesh name="M_UMM_1_F_C004" geometry={nodes.M_UMM_1_F_C004.geometry} material={nodes.M_UMM_1_F_C004.material} position={[-2.603, 0.096, 0.933]} />
        <mesh name="M_UMM_1_F_C005" geometry={nodes.M_UMM_1_F_C005.geometry} material={nodes.M_UMM_1_F_C005.material} position={[2.596, 0.096, 0.935]} />
        <mesh name="M_UMN_4" geometry={nodes.M_UMN_4.geometry} material={nodes.M_UMN_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMN_4.glb')
