/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMS_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMS_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMS_4obj" scale={1.052}>
        <mesh name="M_UMS_1_F001" geometry={nodes.M_UMS_1_F001.geometry} material={nodes.M_UMS_1_F001.material} position={[3.246, 2.998, 1.436]}>
          <mesh name="M_UMS_1_F" geometry={nodes.M_UMS_1_F.geometry} material={nodes.M_UMS_1_F.material} position={[0, -2.964, 0]}>
            <mesh name="M_UMS_4_PNT" geometry={nodes.M_UMS_4_PNT.geometry} material={nodes.M_UMS_4_PNT.material} position={[-3.246, -2.188, 0.178]} />
          </mesh>
        </mesh>
        <mesh name="M_UMS_1_F_A001" geometry={nodes.M_UMS_1_F_A001.geometry} material={nodes.M_UMS_1_F_A001.material} position={[3.244, 2.998, 1.427]}>
          <mesh name="M_UMS_1_F_A" geometry={nodes.M_UMS_1_F_A.geometry} material={nodes.M_UMS_1_F_A.material} position={[0, -3.015, 0]} />
        </mesh>
        <mesh name="M_UMS_1_F_B001" geometry={nodes.M_UMS_1_F_B001.geometry} material={nodes.M_UMS_1_F_B001.material} position={[3.244, 2.996, 1.427]}>
          <mesh name="M_UMS_1_F_B" geometry={nodes.M_UMS_1_F_B.geometry} material={nodes.M_UMS_1_F_B.material} position={[0, -2.964, 0]} />
        </mesh>
        <mesh name="M_UMS_1_F_C001" geometry={nodes.M_UMS_1_F_C001.geometry} material={nodes.M_UMS_1_F_C001.material} position={[3.244, 2.991, 1.427]}>
          <mesh name="M_UMS_1_F_C" geometry={nodes.M_UMS_1_F_C.geometry} material={nodes.M_UMS_1_F_C.material} position={[0, -2.964, 0]} />
        </mesh>
        <mesh name="M_UMS_4" geometry={nodes.M_UMS_4.geometry} material={nodes.M_UMS_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMS_4.glb')
