/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMS_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMS_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMS_2obj" scale={1.052}>
        <mesh name="M_UMS_1_F011" geometry={nodes.M_UMS_1_F011.geometry} material={nodes.M_UMS_1_F011.material} position={[2.741, 2.998, 1.436]}>
          <mesh name="M_UMS_1_F010" geometry={nodes.M_UMS_1_F010.geometry} material={nodes.M_UMS_1_F010.material} position={[0, -2.964, 0]}>
            <mesh name="M_UMS_2_PNT" geometry={nodes.M_UMS_2_PNT.geometry} material={nodes.M_UMS_2_PNT.material} position={[-2.741, -2.188, 0.178]} />
          </mesh>
        </mesh>
        <mesh name="M_UMS_1_F_A011" geometry={nodes.M_UMS_1_F_A011.geometry} material={nodes.M_UMS_1_F_A011.material} position={[2.739, 2.998, 1.427]}>
          <mesh name="M_UMS_1_F_A010" geometry={nodes.M_UMS_1_F_A010.geometry} material={nodes.M_UMS_1_F_A010.material} position={[0, -2.964, 0]} />
        </mesh>
        <mesh name="M_UMS_1_F_B011" geometry={nodes.M_UMS_1_F_B011.geometry} material={nodes.M_UMS_1_F_B011.material} position={[2.739, 2.996, 1.427]}>
          <mesh name="M_UMS_1_F_B010" geometry={nodes.M_UMS_1_F_B010.geometry} material={nodes.M_UMS_1_F_B010.material} position={[0, -2.964, 0]} />
        </mesh>
        <mesh name="M_UMS_1_F_C011" geometry={nodes.M_UMS_1_F_C011.geometry} material={nodes.M_UMS_1_F_C011.material} position={[2.739, 2.991, 1.427]}>
          <mesh name="M_UMS_1_F_C010" geometry={nodes.M_UMS_1_F_C010.geometry} material={nodes.M_UMS_1_F_C010.material} position={[0, -2.964, 0]} />
        </mesh>
        <mesh name="M_UMS_2" geometry={nodes.M_UMS_2.geometry} material={nodes.M_UMS_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMS_2.glb')
