/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMS_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMS_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMS_5obj" scale={1.052}>
        <mesh name="M_UMS_1_F003" geometry={nodes.M_UMS_1_F003.geometry} material={nodes.M_UMS_1_F003.material} position={[3.487, 2.998, 1.436]}>
          <mesh name="M_UMS_1_F002" geometry={nodes.M_UMS_1_F002.geometry} material={nodes.M_UMS_1_F002.material} position={[0, -2.962, 0]}>
            <mesh name="M_UMS_4_PNT001" geometry={nodes.M_UMS_4_PNT001.geometry} material={nodes.M_UMS_4_PNT001.material} position={[-3.481, -2.188, 0.173]} />
          </mesh>
        </mesh>
        <mesh name="M_UMS_1_F_A003" geometry={nodes.M_UMS_1_F_A003.geometry} material={nodes.M_UMS_1_F_A003.material} position={[3.485, 2.998, 1.427]}>
          <mesh name="M_UMS_1_F_A002" geometry={nodes.M_UMS_1_F_A002.geometry} material={nodes.M_UMS_1_F_A002.material} position={[0, -2.962, 0]} />
        </mesh>
        <mesh name="M_UMS_1_F_B003" geometry={nodes.M_UMS_1_F_B003.geometry} material={nodes.M_UMS_1_F_B003.material} position={[3.485, 2.996, 1.427]}>
          <mesh name="M_UMS_1_F_B002" geometry={nodes.M_UMS_1_F_B002.geometry} material={nodes.M_UMS_1_F_B002.material} position={[0, -2.962, 0]} />
        </mesh>
        <mesh name="M_UMS_1_F_C003" geometry={nodes.M_UMS_1_F_C003.geometry} material={nodes.M_UMS_1_F_C003.material} position={[3.485, 2.991, 1.427]}>
          <mesh name="M_UMS_1_F_C002" geometry={nodes.M_UMS_1_F_C002.geometry} material={nodes.M_UMS_1_F_C002.material} position={[0, -2.962, 0]} />
        </mesh>
        <mesh name="M_UMS_5" geometry={nodes.M_UMS_5.geometry} material={nodes.M_UMS_5.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMS_5.glb')
