/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMS_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMS_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMS_7obj" scale={1.052}>
        <mesh name="M_UMS_1_F007" geometry={nodes.M_UMS_1_F007.geometry} material={nodes.M_UMS_1_F007.material} position={[3.992, 2.998, 1.436]}>
          <mesh name="M_UMS_1_F006" geometry={nodes.M_UMS_1_F006.geometry} material={nodes.M_UMS_1_F006.material} position={[0, -2.964, 0]}>
            <mesh name="M_UMS_7_PNT" geometry={nodes.M_UMS_7_PNT.geometry} material={nodes.M_UMS_7_PNT.material} position={[-3.987, -2.188, 0.173]} />
          </mesh>
        </mesh>
        <mesh name="M_UMS_1_F_A007" geometry={nodes.M_UMS_1_F_A007.geometry} material={nodes.M_UMS_1_F_A007.material} position={[3.99, 2.998, 1.427]}>
          <mesh name="M_UMS_1_F_A006" geometry={nodes.M_UMS_1_F_A006.geometry} material={nodes.M_UMS_1_F_A006.material} position={[0, -2.964, 0]} />
        </mesh>
        <mesh name="M_UMS_1_F_B007" geometry={nodes.M_UMS_1_F_B007.geometry} material={nodes.M_UMS_1_F_B007.material} position={[3.99, 2.996, 1.427]}>
          <mesh name="M_UMS_1_F_B006" geometry={nodes.M_UMS_1_F_B006.geometry} material={nodes.M_UMS_1_F_B006.material} position={[0, -2.964, 0]} />
        </mesh>
        <mesh name="M_UMS_1_F_C007" geometry={nodes.M_UMS_1_F_C007.geometry} material={nodes.M_UMS_1_F_C007.material} position={[3.99, 2.991, 1.427]}>
          <mesh name="M_UMS_1_F_C006" geometry={nodes.M_UMS_1_F_C006.geometry} material={nodes.M_UMS_1_F_C006.material} position={[0, -2.964, 0]} />
        </mesh>
        <mesh name="M_UMS_7" geometry={nodes.M_UMS_7.geometry} material={nodes.M_UMS_7.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMS_7.glb')
