/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMS_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMS_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMS_6obj" scale={1.052}>
        <mesh name="M_UMS_1_F005" geometry={nodes.M_UMS_1_F005.geometry} material={nodes.M_UMS_1_F005.material} position={[3.735, 2.998, 1.436]}>
          <mesh name="M_UMS_1_F004" geometry={nodes.M_UMS_1_F004.geometry} material={nodes.M_UMS_1_F004.material} position={[0, -2.964, 0]}>
            <mesh name="M_UMS_6_PNT" geometry={nodes.M_UMS_6_PNT.geometry} material={nodes.M_UMS_6_PNT.material} position={[-3.73, -2.188, 0.173]} />
          </mesh>
        </mesh>
        <mesh name="M_UMS_1_F_A005" geometry={nodes.M_UMS_1_F_A005.geometry} material={nodes.M_UMS_1_F_A005.material} position={[3.733, 2.998, 1.427]}>
          <mesh name="M_UMS_1_F_A004" geometry={nodes.M_UMS_1_F_A004.geometry} material={nodes.M_UMS_1_F_A004.material} position={[0, -2.964, 0]} />
        </mesh>
        <mesh name="M_UMS_1_F_B005" geometry={nodes.M_UMS_1_F_B005.geometry} material={nodes.M_UMS_1_F_B005.material} position={[3.733, 2.996, 1.427]}>
          <mesh name="M_UMS_1_F_B004" geometry={nodes.M_UMS_1_F_B004.geometry} material={nodes.M_UMS_1_F_B004.material} position={[0, -2.964, 0]} />
        </mesh>
        <mesh name="M_UMS_1_F_C005" geometry={nodes.M_UMS_1_F_C005.geometry} material={nodes.M_UMS_1_F_C005.material} position={[3.733, 2.991, 1.427]}>
          <mesh name="M_UMS_1_F_C004" geometry={nodes.M_UMS_1_F_C004.geometry} material={nodes.M_UMS_1_F_C004.material} position={[0, -2.964, 0]} />
        </mesh>
        <mesh name="M_UMS_6" geometry={nodes.M_UMS_6.geometry} material={nodes.M_UMS_6.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMS_6.glb')
