/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMS_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMS_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMS_3obj" scale={1.052}>
        <mesh name="M_UMS_1_F013" geometry={nodes.M_UMS_1_F013.geometry} material={nodes.M_UMS_1_F013.material} position={[2.977, 2.998, 1.436]}>
          <mesh name="M_UMS_1_F012" geometry={nodes.M_UMS_1_F012.geometry} material={nodes.M_UMS_1_F012.material} position={[0, -2.963, 0]}>
            <mesh name="M_UMS_3_PNT" geometry={nodes.M_UMS_3_PNT.geometry} material={nodes.M_UMS_3_PNT.material} position={[-2.977, -2.188, 0.178]} />
          </mesh>
        </mesh>
        <mesh name="M_UMS_1_F_A013" geometry={nodes.M_UMS_1_F_A013.geometry} material={nodes.M_UMS_1_F_A013.material} position={[2.974, 2.998, 1.427]}>
          <mesh name="M_UMS_1_F_A012" geometry={nodes.M_UMS_1_F_A012.geometry} material={nodes.M_UMS_1_F_A012.material} position={[0, -2.963, 0]} />
        </mesh>
        <mesh name="M_UMS_1_F_B013" geometry={nodes.M_UMS_1_F_B013.geometry} material={nodes.M_UMS_1_F_B013.material} position={[2.974, 2.996, 1.427]}>
          <mesh name="M_UMS_1_F_B012" geometry={nodes.M_UMS_1_F_B012.geometry} material={nodes.M_UMS_1_F_B012.material} position={[0, -2.963, 0]} />
        </mesh>
        <mesh name="M_UMS_1_F_C013" geometry={nodes.M_UMS_1_F_C013.geometry} material={nodes.M_UMS_1_F_C013.material} position={[2.974, 2.991, 1.427]}>
          <mesh name="M_UMS_1_F_C012" geometry={nodes.M_UMS_1_F_C012.geometry} material={nodes.M_UMS_1_F_C012.material} position={[0, -2.963, 0]} />
        </mesh>
        <mesh name="M_UMS_3" geometry={nodes.M_UMS_3.geometry} material={nodes.M_UMS_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMS_3.glb')
