/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMS_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMS_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMS_1obj" scale={1.052}>
        <mesh name="M_UMS_1" geometry={nodes.M_UMS_1.geometry} material={nodes.M_UMS_1.material} />
        <mesh name="M_UMS_1_F009" geometry={nodes.M_UMS_1_F009.geometry} material={nodes.M_UMS_1_F009.material} position={[2.492, 2.998, 1.436]}>
          <mesh name="M_UMS_1_F008" geometry={nodes.M_UMS_1_F008.geometry} material={nodes.M_UMS_1_F008.material} position={[0, -2.965, 0]}>
            <mesh name="M_UMS_1_PNT001" geometry={nodes.M_UMS_1_PNT001.geometry} material={nodes.M_UMS_1_PNT001.material} position={[-2.492, -2.188, 0.178]} />
          </mesh>
        </mesh>
        <mesh name="M_UMS_1_F_A009" geometry={nodes.M_UMS_1_F_A009.geometry} material={nodes.M_UMS_1_F_A009.material} position={[2.49, 2.998, 1.427]}>
          <mesh name="M_UMS_1_F_A008" geometry={nodes.M_UMS_1_F_A008.geometry} material={nodes.M_UMS_1_F_A008.material} position={[0, -2.965, 0]} />
        </mesh>
        <mesh name="M_UMS_1_F_B009" geometry={nodes.M_UMS_1_F_B009.geometry} material={nodes.M_UMS_1_F_B009.material} position={[2.49, 2.996, 1.427]}>
          <mesh name="M_UMS_1_F_B008" geometry={nodes.M_UMS_1_F_B008.geometry} material={nodes.M_UMS_1_F_B008.material} position={[0, -2.965, 0]} />
        </mesh>
        <mesh name="M_UMS_1_F_C009" geometry={nodes.M_UMS_1_F_C009.geometry} material={nodes.M_UMS_1_F_C009.material} position={[2.49, 2.991, 1.427]}>
          <mesh name="M_UMS_1_F_C008" geometry={nodes.M_UMS_1_F_C008.geometry} material={nodes.M_UMS_1_F_C008.material} position={[0, -2.965, 0]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMS_1.glb')
