/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMA_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMA_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMA_6obj" scale={1.052}>
        <mesh name="M_UMA_11_F001" geometry={nodes.M_UMA_11_F001.geometry} material={nodes.M_UMA_11_F001.material} position={[2.235, 0, 1.445]}>
          <mesh name="M_UMA_6_PNT_H" geometry={nodes.M_UMA_6_PNT_H.geometry} material={nodes.M_UMA_6_PNT_H.material} position={[-2.235, -1.988, 0.17]} scale={10} />
          <mesh name="M_UMA_6_PNT_V" geometry={nodes.M_UMA_6_PNT_V.geometry} material={nodes.M_UMA_6_PNT_V.material} position={[-2.235, -1.121, 0.17]} scale={10} />
        </mesh>
        <mesh name="M_UMA_1_F_A004" geometry={nodes.M_UMA_1_F_A004.geometry} material={nodes.M_UMA_1_F_A004.material} position={[2.24, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B004" geometry={nodes.M_UMA_1_F_B004.geometry} material={nodes.M_UMA_1_F_B004.material} position={[2.24, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C004" geometry={nodes.M_UMA_1_F_C004.geometry} material={nodes.M_UMA_1_F_C004.material} position={[2.24, 0.51, 1.435]} />
        <mesh name="M_UMA_6" geometry={nodes.M_UMA_6.geometry} material={nodes.M_UMA_6.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMA_6.glb')
