/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMA_8.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMA_8.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMA_8obj" scale={1.052}>
        <mesh name="M_UMA_11_F003" geometry={nodes.M_UMA_11_F003.geometry} material={nodes.M_UMA_11_F003.material} position={[-2.738, 0, 1.445]}>
          <mesh name="M_UMA_7_PNT002" geometry={nodes.M_UMA_7_PNT002.geometry} material={nodes.M_UMA_7_PNT002.material} position={[1.34, -1.121, 0.17]} scale={10} />
        </mesh>
        <mesh name="M_UMA_11_F004" geometry={nodes.M_UMA_11_F004.geometry} material={nodes.M_UMA_11_F004.material} position={[2.737, 0, 1.445]}>
          <mesh name="M_UMA_7_PNT003" geometry={nodes.M_UMA_7_PNT003.geometry} material={nodes.M_UMA_7_PNT003.material} position={[-1.339, -1.121, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-10} />
        </mesh>
        <mesh name="M_UMA_1_F_A006" geometry={nodes.M_UMA_1_F_A006.geometry} material={nodes.M_UMA_1_F_A006.material} position={[-2.744, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_A007" geometry={nodes.M_UMA_1_F_A007.geometry} material={nodes.M_UMA_1_F_A007.material} position={[2.742, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B006" geometry={nodes.M_UMA_1_F_B006.geometry} material={nodes.M_UMA_1_F_B006.material} position={[-2.747, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B007" geometry={nodes.M_UMA_1_F_B007.geometry} material={nodes.M_UMA_1_F_B007.material} position={[2.742, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C006" geometry={nodes.M_UMA_1_F_C006.geometry} material={nodes.M_UMA_1_F_C006.material} position={[-2.748, 0.51, 1.435]} />
        <mesh name="M_UMA_1_F_C007" geometry={nodes.M_UMA_1_F_C007.geometry} material={nodes.M_UMA_1_F_C007.material} position={[2.742, 0.51, 1.435]} />
        <mesh name="M_UMA_8" geometry={nodes.M_UMA_8.geometry} material={nodes.M_UMA_8.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMA_8.glb')
