/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMA_11.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMA_11.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMA_11obj" scale={1.052}>
        <mesh name="M_UMA_11" geometry={nodes.M_UMA_11.geometry} material={nodes.M_UMA_11.material} />
        <mesh name="M_UMA_11_F_11" geometry={nodes.M_UMA_11_F_11.geometry} material={nodes.M_UMA_11_F_11.material} position={[-3.49, 0, 1.445]}>
          <mesh name="M_UMA_7_PNT_H_2" geometry={nodes.M_UMA_7_PNT_H_2.geometry} material={nodes.M_UMA_7_PNT_H_2.material} position={[1.721, -1.993, 0.17]} />
          <mesh name="M_UMA_7_PNT_V_2" geometry={nodes.M_UMA_7_PNT_V_2.geometry} material={nodes.M_UMA_7_PNT_V_2.material} position={[2.255, -1.121, 0.17]} />
        </mesh>
        <mesh name="M_UMA_11_F_11001" geometry={nodes.M_UMA_11_F_11001.geometry} material={nodes.M_UMA_11_F_11001.material} position={[3.49, 0, 1.445]}>
          <mesh name="M_UMA_7_PNT_H_1" geometry={nodes.M_UMA_7_PNT_H_1.geometry} material={nodes.M_UMA_7_PNT_H_1.material} position={[-1.721, -1.993, 0.17]} />
          <mesh name="M_UMA_7_PNT_V_1" geometry={nodes.M_UMA_7_PNT_V_1.geometry} material={nodes.M_UMA_7_PNT_V_1.material} position={[-2.255, -1.121, 0.17]} />
        </mesh>
        <mesh name="M_UMA_1_F_A010" geometry={nodes.M_UMA_1_F_A010.geometry} material={nodes.M_UMA_1_F_A010.material} position={[-3.483, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_A011" geometry={nodes.M_UMA_1_F_A011.geometry} material={nodes.M_UMA_1_F_A011.material} position={[3.495, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B010" geometry={nodes.M_UMA_1_F_B010.geometry} material={nodes.M_UMA_1_F_B010.material} position={[-3.486, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B011" geometry={nodes.M_UMA_1_F_B011.geometry} material={nodes.M_UMA_1_F_B011.material} position={[3.495, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C010" geometry={nodes.M_UMA_1_F_C010.geometry} material={nodes.M_UMA_1_F_C010.material} position={[-3.487, 0.51, 1.435]} />
        <mesh name="M_UMA_1_F_C011" geometry={nodes.M_UMA_1_F_C011.geometry} material={nodes.M_UMA_1_F_C011.material} position={[3.495, 0.51, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMA_11.glb')
