/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMA_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMA_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMA_7_7obj" scale={1.052}>
        <mesh name="M_UMA_11_F002" geometry={nodes.M_UMA_11_F002.geometry} material={nodes.M_UMA_11_F002.material} position={[2.485, 0, 1.445]}>
          <mesh name="M_UMA_7_PNT" geometry={nodes.M_UMA_7_PNT.geometry} material={nodes.M_UMA_7_PNT.material} position={[-1.25, -1.121, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-10} />
        </mesh>
        <mesh name="M_UMA_11_F1" geometry={nodes.M_UMA_11_F1.geometry} material={nodes.M_UMA_11_F1.material} position={[-2.49, 0, 1.445]}>
          <mesh name="M_UMA_7_PNT001" geometry={nodes.M_UMA_7_PNT001.geometry} material={nodes.M_UMA_7_PNT001.material} position={[1.255, -1.121, 0.17]} scale={10} />
        </mesh>
        <mesh name="M_UMA_1_F_A001" geometry={nodes.M_UMA_1_F_A001.geometry} material={nodes.M_UMA_1_F_A001.material} position={[-2.495, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_A002" geometry={nodes.M_UMA_1_F_A002.geometry} material={nodes.M_UMA_1_F_A002.material} position={[2.491, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B001" geometry={nodes.M_UMA_1_F_B001.geometry} material={nodes.M_UMA_1_F_B001.material} position={[-2.499, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B002" geometry={nodes.M_UMA_1_F_B002.geometry} material={nodes.M_UMA_1_F_B002.material} position={[2.491, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C001" geometry={nodes.M_UMA_1_F_C001.geometry} material={nodes.M_UMA_1_F_C001.material} position={[-2.5, 0.51, 1.435]} />
        <mesh name="M_UMA_1_F_C002" geometry={nodes.M_UMA_1_F_C002.geometry} material={nodes.M_UMA_1_F_C002.material} position={[2.491, 0.51, 1.435]} />
        <mesh name="M_UMA_7" geometry={nodes.M_UMA_7.geometry} material={nodes.M_UMA_7.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMA_7.glb')
