/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMA_10.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMA_10.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMA_10obj" scale={1.052}>
        <mesh name="M_UMA_10" geometry={nodes.M_UMA_10.geometry} material={nodes.M_UMA_10.material} />
        <mesh name="M_UMA_10_F_10" geometry={nodes.M_UMA_10_F_10.geometry} material={nodes.M_UMA_10_F_10.material} position={[-3.24, 0, 1.445]}>
          <mesh name="M_UMA_7_PNT006" geometry={nodes.M_UMA_7_PNT006.geometry} material={nodes.M_UMA_7_PNT006.material} position={[2.005, -1.121, 0.17]} scale={10} />
        </mesh>
        <mesh name="M_UMA_10_F_10001" geometry={nodes.M_UMA_10_F_10001.geometry} material={nodes.M_UMA_10_F_10001.material} position={[3.241, 0, 1.445]}>
          <mesh name="M_UMA_7_PNT007" geometry={nodes.M_UMA_7_PNT007.geometry} material={nodes.M_UMA_7_PNT007.material} position={[-2.006, -1.121, 0.17]} rotation={[Math.PI, 0, 0]} scale={-10} />
        </mesh>
        <mesh name="M_UMA_1_F_A008" geometry={nodes.M_UMA_1_F_A008.geometry} material={nodes.M_UMA_1_F_A008.material} position={[-3.242, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_A009" geometry={nodes.M_UMA_1_F_A009.geometry} material={nodes.M_UMA_1_F_A009.material} position={[3.241, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B008" geometry={nodes.M_UMA_1_F_B008.geometry} material={nodes.M_UMA_1_F_B008.material} position={[-3.245, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B009" geometry={nodes.M_UMA_1_F_B009.geometry} material={nodes.M_UMA_1_F_B009.material} position={[3.241, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C008" geometry={nodes.M_UMA_1_F_C008.geometry} material={nodes.M_UMA_1_F_C008.material} position={[-3.246, 0.51, 1.435]} />
        <mesh name="M_UMA_1_F_C009" geometry={nodes.M_UMA_1_F_C009.geometry} material={nodes.M_UMA_1_F_C009.material} position={[3.241, 0.51, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMA_10.glb')
