/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMA_13.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMA_13.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMA_13_F_13obj" scale={1.052}>
        <mesh name="M_UMA_11_F_11004" geometry={nodes.M_UMA_11_F_11004.geometry} material={nodes.M_UMA_11_F_11004.material} position={[-3.983, 0, 1.445]}>
          <mesh name="M_UMA_7_PNT_H_1004" geometry={nodes.M_UMA_7_PNT_H_1004.geometry} material={nodes.M_UMA_7_PNT_H_1004.material} position={[1.951, -1.981, 0.17]} scale={10} />
          <mesh name="M_UMA_7_PNT_V_2002" geometry={nodes.M_UMA_7_PNT_V_2002.geometry} material={nodes.M_UMA_7_PNT_V_2002.material} position={[2.748, -1.109, 0.17]} scale={10} />
        </mesh>
        <mesh name="M_UMA_11_F_11005" geometry={nodes.M_UMA_11_F_11005.geometry} material={nodes.M_UMA_11_F_11005.material} position={[3.986, 0, 1.445]}>
          <mesh name="M_UMA_7_PNT_H_1003" geometry={nodes.M_UMA_7_PNT_H_1003.geometry} material={nodes.M_UMA_7_PNT_H_1003.material} position={[-1.954, -1.981, 0.17]} rotation={[Math.PI, 0, 0]} scale={-10} />
          <mesh name="M_UMA_7_PNT_V_1002" geometry={nodes.M_UMA_7_PNT_V_1002.geometry} material={nodes.M_UMA_7_PNT_V_1002.material} position={[-2.752, -1.109, 0.17]} rotation={[Math.PI, 0, 0]} scale={-10} />
        </mesh>
        <mesh name="M_UMA_13" geometry={nodes.M_UMA_13.geometry} material={nodes.M_UMA_13.material} />
        <mesh name="M_UMA_1_F_A014" geometry={nodes.M_UMA_1_F_A014.geometry} material={nodes.M_UMA_1_F_A014.material} position={[-3.976, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_A015" geometry={nodes.M_UMA_1_F_A015.geometry} material={nodes.M_UMA_1_F_A015.material} position={[3.992, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B014" geometry={nodes.M_UMA_1_F_B014.geometry} material={nodes.M_UMA_1_F_B014.material} position={[-3.98, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B015" geometry={nodes.M_UMA_1_F_B015.geometry} material={nodes.M_UMA_1_F_B015.material} position={[3.992, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C014" geometry={nodes.M_UMA_1_F_C014.geometry} material={nodes.M_UMA_1_F_C014.material} position={[-3.98, 0.51, 1.435]} />
        <mesh name="M_UMA_1_F_C015" geometry={nodes.M_UMA_1_F_C015.geometry} material={nodes.M_UMA_1_F_C015.material} position={[3.992, 0.51, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMA_13.glb')
