/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMA_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMA_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMA_5obj" scale={1.052}>
        <mesh name="M_UMA_11_F" geometry={nodes.M_UMA_11_F.geometry} material={nodes.M_UMA_11_F.material} position={[1.992, 0, 1.445]}>
          <mesh name="M_UMA_5_PNT" geometry={nodes.M_UMA_5_PNT.geometry} material={nodes.M_UMA_5_PNT.material} position={[-1.992, -1.121, 0.17]} scale={10} />
        </mesh>
        <mesh name="M_UMA_1_F_A" geometry={nodes.M_UMA_1_F_A.geometry} material={nodes.M_UMA_1_F_A.material} position={[1.998, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B" geometry={nodes.M_UMA_1_F_B.geometry} material={nodes.M_UMA_1_F_B.material} position={[1.998, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C" geometry={nodes.M_UMA_1_F_C.geometry} material={nodes.M_UMA_1_F_C.material} position={[1.998, 0.51, 1.435]} />
        <mesh name="M_UMA_5" geometry={nodes.M_UMA_5.geometry} material={nodes.M_UMA_5.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMA_5.glb')
