/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMA_12.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMA_12.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMA_12obj" scale={1.052}>
        <mesh name="M_UMA_11_F_11002" geometry={nodes.M_UMA_11_F_11002.geometry} material={nodes.M_UMA_11_F_11002.material} position={[-3.743, 0, 1.445]}>
          <mesh name="M_UMA_7_PNT_H_1002" geometry={nodes.M_UMA_7_PNT_H_1002.geometry} material={nodes.M_UMA_7_PNT_H_1002.material} position={[1.858, -1.993, 0.17]} scale={10} />
          <mesh name="M_UMA_7_PNT_V_2001" geometry={nodes.M_UMA_7_PNT_V_2001.geometry} material={nodes.M_UMA_7_PNT_V_2001.material} position={[2.508, -1.121, 0.17]} scale={10} />
        </mesh>
        <mesh name="M_UMA_11_F_11003" geometry={nodes.M_UMA_11_F_11003.geometry} material={nodes.M_UMA_11_F_11003.material} position={[3.737, 0, 1.445]}>
          <mesh name="M_UMA_7_PNT_H_1001" geometry={nodes.M_UMA_7_PNT_H_1001.geometry} material={nodes.M_UMA_7_PNT_H_1001.material} position={[-1.852, -1.993, 0.17]} rotation={[Math.PI, 0, 0]} scale={-10} />
          <mesh name="M_UMA_7_PNT_V_1001" geometry={nodes.M_UMA_7_PNT_V_1001.geometry} material={nodes.M_UMA_7_PNT_V_1001.material} position={[-2.502, -1.121, 0.17]} rotation={[Math.PI, 0, 0]} scale={-10} />
        </mesh>
        <mesh name="M_UMA_12" geometry={nodes.M_UMA_12.geometry} material={nodes.M_UMA_12.material} />
        <mesh name="M_UMA_1_F_A012" geometry={nodes.M_UMA_1_F_A012.geometry} material={nodes.M_UMA_1_F_A012.material} position={[-3.736, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_A013" geometry={nodes.M_UMA_1_F_A013.geometry} material={nodes.M_UMA_1_F_A013.material} position={[3.742, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B012" geometry={nodes.M_UMA_1_F_B012.geometry} material={nodes.M_UMA_1_F_B012.material} position={[-3.74, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B013" geometry={nodes.M_UMA_1_F_B013.geometry} material={nodes.M_UMA_1_F_B013.material} position={[3.742, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C012" geometry={nodes.M_UMA_1_F_C012.geometry} material={nodes.M_UMA_1_F_C012.material} position={[-3.74, 0.51, 1.435]} />
        <mesh name="M_UMA_1_F_C013" geometry={nodes.M_UMA_1_F_C013.geometry} material={nodes.M_UMA_1_F_C013.material} position={[3.742, 0.51, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMA_12.glb')
