/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMA_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMA_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMA_1obj" scale={1.052}>
        <mesh name="M_UMA_1" geometry={nodes.M_UMA_1.geometry} material={nodes.M_UMA_1.material} />
        <mesh name="M_UMA_11_F005" geometry={nodes.M_UMA_11_F005.geometry} material={nodes.M_UMA_11_F005.material} position={[0.989, 0, 1.445]}>
          <mesh name="M_UMA_1_PNT" geometry={nodes.M_UMA_1_PNT.geometry} material={nodes.M_UMA_1_PNT.material} position={[-0.989, -1.121, 0.17]} scale={10} />
        </mesh>
        <mesh name="M_UMA_1_F_A016" geometry={nodes.M_UMA_1_F_A016.geometry} material={nodes.M_UMA_1_F_A016.material} position={[0.994, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B016" geometry={nodes.M_UMA_1_F_B016.geometry} material={nodes.M_UMA_1_F_B016.material} position={[0.994, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C016" geometry={nodes.M_UMA_1_F_C016.geometry} material={nodes.M_UMA_1_F_C016.material} position={[0.994, 0.51, 1.435]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMA_1.glb')
