/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMA_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMA_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMA_4obj" scale={1.052}>
        <mesh name="M_UMA_1_F" geometry={nodes.M_UMA_1_F.geometry} material={nodes.M_UMA_1_F.material} position={[1.738, 0, 1.445]}>
          <mesh name="M_UMA_4_PNT" geometry={nodes.M_UMA_4_PNT.geometry} material={nodes.M_UMA_4_PNT.material} position={[-1.738, -1.121, 0.17]} scale={10} />
        </mesh>
        <mesh name="M_UMA_1_F_A018" geometry={nodes.M_UMA_1_F_A018.geometry} material={nodes.M_UMA_1_F_A018.material} position={[1.743, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B018" geometry={nodes.M_UMA_1_F_B018.geometry} material={nodes.M_UMA_1_F_B018.material} position={[1.743, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C018" geometry={nodes.M_UMA_1_F_C018.geometry} material={nodes.M_UMA_1_F_C018.material} position={[1.743, 0.51, 1.435]} />
        <mesh name="M_UMA_4" geometry={nodes.M_UMA_4.geometry} material={nodes.M_UMA_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMA_4.glb')
