/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMA_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMA_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMA_3_NN" scale={1.052}>
        <mesh name="M_UMA_11_F_3" geometry={nodes.M_UMA_11_F_3.geometry} material={nodes.M_UMA_11_F_3.material} position={[1.479, 0, 1.445]}>
          <mesh name="M_UMA_3_PNT" geometry={nodes.M_UMA_3_PNT.geometry} material={nodes.M_UMA_3_PNT.material} position={[-1.479, -1.121, 0.17]} scale={10} />
        </mesh>
        <mesh name="M_UMA_1_F_A017" geometry={nodes.M_UMA_1_F_A017.geometry} material={nodes.M_UMA_1_F_A017.material} position={[1.484, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B017" geometry={nodes.M_UMA_1_F_B017.geometry} material={nodes.M_UMA_1_F_B017.material} position={[1.484, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C017" geometry={nodes.M_UMA_1_F_C017.geometry} material={nodes.M_UMA_1_F_C017.material} position={[1.484, 0.51, 1.435]} />
        <mesh name="M_UMA_3" geometry={nodes.M_UMA_3.geometry} material={nodes.M_UMA_3.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMA_3.glb')
