/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMA_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMA_2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="M_UMA_2" geometry={nodes.M_UMA_2.geometry} material={nodes.M_UMA_2.material} />
      <mesh name="M_UMA_2_F_1" geometry={nodes.M_UMA_2_F_1.geometry} material={nodes.M_UMA_2_F_1.material}>
        <mesh name="M_UMA_2_PNT" geometry={nodes.M_UMA_2_PNT.geometry} material={nodes.M_UMA_2_PNT.material} position={[0, -1.179, 1.699]} scale={10.517} />
      </mesh>
      <mesh name="M_UMA_2_F_A" geometry={nodes.M_UMA_2_F_A.geometry} material={nodes.M_UMA_2_F_A.material} />
      <mesh name="M_UMA_2_F_B" geometry={nodes.M_UMA_2_F_B.geometry} material={nodes.M_UMA_2_F_B.material} />
      <mesh name="M_UMA_2_F_C" geometry={nodes.M_UMA_2_F_C.geometry} material={nodes.M_UMA_2_F_C.material} />
    </group>
  )
}

useGLTF.preload('/M_UMA_2.glb')
