/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_UMA_9.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_UMA_9.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_UMA_9obj" scale={1.052}>
        <mesh name="M_UMA_1_F_A003" geometry={nodes.M_UMA_1_F_A003.geometry} material={nodes.M_UMA_1_F_A003.material} position={[-2.987, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_A005" geometry={nodes.M_UMA_1_F_A005.geometry} material={nodes.M_UMA_1_F_A005.material} position={[2.999, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B003" geometry={nodes.M_UMA_1_F_B003.geometry} material={nodes.M_UMA_1_F_B003.material} position={[-2.991, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_B005" geometry={nodes.M_UMA_1_F_B005.geometry} material={nodes.M_UMA_1_F_B005.material} position={[2.999, 1.805, 1.435]} />
        <mesh name="M_UMA_1_F_C003" geometry={nodes.M_UMA_1_F_C003.geometry} material={nodes.M_UMA_1_F_C003.material} position={[-2.991, 0.51, 1.435]} />
        <mesh name="M_UMA_1_F_C005" geometry={nodes.M_UMA_1_F_C005.geometry} material={nodes.M_UMA_1_F_C005.material} position={[2.999, 0.51, 1.435]} />
        <mesh name="M_UMA_9" geometry={nodes.M_UMA_9.geometry} material={nodes.M_UMA_9.material} />
        <mesh name="M_UMA_9_F_9" geometry={nodes.M_UMA_9_F_9.geometry} material={nodes.M_UMA_9_F_9.material} position={[-2.995, 2.991, 1.44]}>
          <mesh name="M_UMA_7_PNT004" geometry={nodes.M_UMA_7_PNT004.geometry} material={nodes.M_UMA_7_PNT004.material} position={[1.76, -4.111, 0.175]} scale={10} />
        </mesh>
        <mesh name="M_UMA_9_F_9001" geometry={nodes.M_UMA_9_F_9001.geometry} material={nodes.M_UMA_9_F_9001.material} position={[2.99, 2.999, 1.435]}>
          <mesh name="M_UMA_7_PNT005" geometry={nodes.M_UMA_7_PNT005.geometry} material={nodes.M_UMA_7_PNT005.material} position={[-1.755, -4.12, 0.18]} rotation={[Math.PI, 0, 0]} scale={-10} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/M_UMA_9.glb')
