/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_BTL_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_BTL_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_1BTL_1_NNobj" scale={1.142}>
        <mesh name="Legs003" geometry={nodes.Legs003.geometry} material={nodes.Legs003.material} position={[0.002, -3.299, -0.209]} />
        <mesh name="M_1BTL_1" geometry={nodes.M_1BTL_1.geometry} material={nodes.M_1BTL_1.material} />
        <mesh name="M_1BTL_1001" geometry={nodes.M_1BTL_1001.geometry} material={nodes.M_1BTL_1001.material} />
        <mesh name="M_1BTL_1_F001" geometry={nodes.M_1BTL_1_F001.geometry} material={nodes.M_1BTL_1_F001.material} position={[0.692, 0.407, 2.647]}>
          <mesh name="M_1BTL_1_PNT_1" geometry={nodes.M_1BTL_1_PNT_1.geometry} material={nodes.M_1BTL_1_PNT_1.material} position={[-0.692, 1.879, 0.122]} />
        </mesh>
        <mesh name="M_1BTL_1_F_A001" geometry={nodes.M_1BTL_1_F_A001.geometry} material={nodes.M_1BTL_1_F_A001.material} position={[0.69, 1.413, 2.639]} />
        <mesh name="M_1BTL_1_F_B001" geometry={nodes.M_1BTL_1_F_B001.geometry} material={nodes.M_1BTL_1_F_B001.material} position={[0.69, 1.413, 2.639]} />
        <mesh name="M_1BTL_1_F_C001" geometry={nodes.M_1BTL_1_F_C001.geometry} material={nodes.M_1BTL_1_F_C001.material} position={[0.69, 0.691, 2.639]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_BTL_1.glb')
