/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_BTL_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_BTL_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_1BTL_4_NNobj" scale={1.142}>
        <mesh name="Legs" geometry={nodes.Legs.geometry} material={nodes.Legs.material} position={[0.009, -3.293, -0.209]} />
        <mesh name="M_1BTL_1_F" geometry={nodes.M_1BTL_1_F.geometry} material={nodes.M_1BTL_1_F.material} position={[1.364, 0.406, 2.614]}>
          <mesh name="M_1BTL_4_PNT" geometry={nodes.M_1BTL_4_PNT.geometry} material={nodes.M_1BTL_4_PNT.material} position={[-1.364, 1.875, 0.15]} />
        </mesh>
        <mesh name="M_1BTL_1_F_A2" geometry={nodes.M_1BTL_1_F_A2.geometry} material={nodes.M_1BTL_1_F_A2.material} position={[1.363, 1.41, 2.606]} />
        <mesh name="M_1BTL_1_F_B2" geometry={nodes.M_1BTL_1_F_B2.geometry} material={nodes.M_1BTL_1_F_B2.material} position={[1.363, 1.41, 2.606]} />
        <mesh name="M_1BTL_1_F_C2" geometry={nodes.M_1BTL_1_F_C2.geometry} material={nodes.M_1BTL_1_F_C2.material} position={[1.363, 0.69, 2.606]} />
        <mesh name="M_1BTL_4" geometry={nodes.M_1BTL_4.geometry} material={nodes.M_1BTL_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_BTL_4.glb')
