/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_BTL_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_BTL_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_1BTL_2_NNobj" scale={1.142}>
        <mesh name="Legs004" geometry={nodes.Legs004.geometry} material={nodes.Legs004.material} position={[0.002, -3.29, -0.208]} />
        <mesh name="M_1BTL_1_F003" geometry={nodes.M_1BTL_1_F003.geometry} material={nodes.M_1BTL_1_F003.material} position={[0.912, 0.406, 2.611]}>
          <mesh name="M_1BTL_1_PNT" geometry={nodes.M_1BTL_1_PNT.geometry} material={nodes.M_1BTL_1_PNT.material} position={[-0.912, 1.873, 0.149]} />
        </mesh>
        <mesh name="M_1BTL_1_F_A003" geometry={nodes.M_1BTL_1_F_A003.geometry} material={nodes.M_1BTL_1_F_A003.material} position={[0.91, 1.409, 2.603]} />
        <mesh name="M_1BTL_1_F_B003" geometry={nodes.M_1BTL_1_F_B003.geometry} material={nodes.M_1BTL_1_F_B003.material} position={[0.91, 1.409, 2.603]} />
        <mesh name="M_1BTL_1_F_C003" geometry={nodes.M_1BTL_1_F_C003.geometry} material={nodes.M_1BTL_1_F_C003.material} position={[0.91, 0.689, 2.603]} />
        <mesh name="M_1BTL_2" geometry={nodes.M_1BTL_2.geometry} material={nodes.M_1BTL_2.material} />
        <mesh name="M_1BTL_2001" geometry={nodes.M_1BTL_2001.geometry} material={nodes.M_1BTL_2001.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_BTL_2.glb')
