/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_BTL_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_BTL_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_1BTL_3_NNobj" scale={1.142}>
        <mesh name="Legs005" geometry={nodes.Legs005.geometry} material={nodes.Legs005.material} position={[0.009, -3.289, -0.208]} />
        <mesh name="M_1BTL_1_F004" geometry={nodes.M_1BTL_1_F004.geometry} material={nodes.M_1BTL_1_F004.material} position={[1.147, 0.406, 2.611]}>
          <mesh name="M_1BTL_1_PNT001" geometry={nodes.M_1BTL_1_PNT001.geometry} material={nodes.M_1BTL_1_PNT001.material} position={[-1.147, 1.873, 0.149]} />
        </mesh>
        <mesh name="M_1BTL_1_F_A004" geometry={nodes.M_1BTL_1_F_A004.geometry} material={nodes.M_1BTL_1_F_A004.material} position={[1.145, 1.409, 2.603]} />
        <mesh name="M_1BTL_1_F_B004" geometry={nodes.M_1BTL_1_F_B004.geometry} material={nodes.M_1BTL_1_F_B004.material} position={[1.145, 1.409, 2.603]} />
        <mesh name="M_1BTL_1_F_C004" geometry={nodes.M_1BTL_1_F_C004.geometry} material={nodes.M_1BTL_1_F_C004.material} position={[1.145, 0.689, 2.603]} />
        <mesh name="M_1BTL_3" geometry={nodes.M_1BTL_3.geometry} material={nodes.M_1BTL_3.material} />
        <mesh name="M_1BTL_3001" geometry={nodes.M_1BTL_3001.geometry} material={nodes.M_1BTL_3001.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_BTL_3.glb')
