/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_3YNSD_5.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_3YNSD_5.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_3YNSD_5_NN" scale={1.142}>
        <mesh name="Legs004" geometry={nodes.Legs004.geometry} material={nodes.Legs004.material} position={[0.849, -2.961, -0.365]} />
        <mesh name="M_3YNSD_1_F012" geometry={nodes.M_3YNSD_1_F012.geometry} material={nodes.M_3YNSD_1_F012.material} position={[2.29, 1.961, 2.509]}>
          <mesh name="M_3YNSD_1_PNT_1002" geometry={nodes.M_3YNSD_1_PNT_1002.geometry} material={nodes.M_3YNSD_1_PNT_1002.material} position={[-2.331, 0.961, 0.158]} />
        </mesh>
        <mesh name="M_3YNSD_1_F013" geometry={nodes.M_3YNSD_1_F013.geometry} material={nodes.M_3YNSD_1_F013.material} position={[2.29, 0.282, 2.509]}>
          <mesh name="M_3YNSD_1_PNT_2002" geometry={nodes.M_3YNSD_1_PNT_2002.geometry} material={nodes.M_3YNSD_1_PNT_2002.material} position={[-2.331, 0.971, 0.158]} />
        </mesh>
        <mesh name="M_3YNSD_1_F014" geometry={nodes.M_3YNSD_1_F014.geometry} material={nodes.M_3YNSD_1_F014.material} position={[2.29, -1.41, 2.509]}>
          <mesh name="M_3YNSD_1_PNT_3002" geometry={nodes.M_3YNSD_1_PNT_3002.geometry} material={nodes.M_3YNSD_1_PNT_3002.material} position={[-2.331, 0.966, 0.158]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A012" geometry={nodes.M_3YNSD_1_F_A012.geometry} material={nodes.M_3YNSD_1_F_A012.material} position={[2.287, 3.652, 2.499]} />
        <mesh name="M_3YNSD_1_F_A013" geometry={nodes.M_3YNSD_1_F_A013.geometry} material={nodes.M_3YNSD_1_F_A013.material} position={[2.287, 1.973, 2.499]} />
        <mesh name="M_3YNSD_1_F_A014" geometry={nodes.M_3YNSD_1_F_A014.geometry} material={nodes.M_3YNSD_1_F_A014.material} position={[2.287, 0.282, 2.499]} />
        <mesh name="M_3YNSD_1_F_B012" geometry={nodes.M_3YNSD_1_F_B012.geometry} material={nodes.M_3YNSD_1_F_B012.material} position={[2.287, 3.652, 2.499]} />
        <mesh name="M_3YNSD_1_F_B013" geometry={nodes.M_3YNSD_1_F_B013.geometry} material={nodes.M_3YNSD_1_F_B013.material} position={[2.287, 1.973, 2.499]} />
        <mesh name="M_3YNSD_1_F_B014" geometry={nodes.M_3YNSD_1_F_B014.geometry} material={nodes.M_3YNSD_1_F_B014.material} position={[2.287, 0.282, 2.499]} />
        <mesh name="M_3YNSD_1_F_C012" geometry={nodes.M_3YNSD_1_F_C012.geometry} material={nodes.M_3YNSD_1_F_C012.material} position={[2.287, 2.438, 2.499]} />
        <mesh name="M_3YNSD_1_F_C013" geometry={nodes.M_3YNSD_1_F_C013.geometry} material={nodes.M_3YNSD_1_F_C013.material} position={[2.287, 0.759, 2.499]} />
        <mesh name="M_3YNSD_1_F_C014" geometry={nodes.M_3YNSD_1_F_C014.geometry} material={nodes.M_3YNSD_1_F_C014.material} position={[2.287, -0.932, 2.499]} />
        <mesh name="M_3YNSD_5" geometry={nodes.M_3YNSD_5.geometry} material={materials['Material #2143921989.005']} position={[0, 0.302, 0]} />
        <mesh name="M_3YNSD_5_F_5" geometry={nodes.M_3YNSD_5_F_5.geometry} material={materials['Material #2143921989.005']} position={[2.302, -0.001, 2.594]} />
        <mesh name="M_3YNSD_5_F_5001" geometry={nodes.M_3YNSD_5_F_5001.geometry} material={materials['Material #2143921989.005']} position={[2.302, -0.001, 2.594]} />
        <mesh name="M_3YNSD_5_F_5002" geometry={nodes.M_3YNSD_5_F_5002.geometry} material={materials['Material #2143921989.005']} position={[2.302, -0.001, 2.594]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_3YNSD_5.glb')
