/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_3YNSD_2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_3YNSD_2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_3YNSD_2_NN" scale={1.142}>
        <mesh name="Legs001" geometry={nodes.Legs001.geometry} material={nodes.Legs001.material} position={[0.834, -2.877, -0.359]} />
        <mesh name="M_3YNSD_1_F003" geometry={nodes.M_3YNSD_1_F003.geometry} material={nodes.M_3YNSD_1_F003.material} position={[1.553, 0.322, 2.476]}>
          <mesh name="M_3YNSD_PNT_2001" geometry={nodes.M_3YNSD_PNT_2001.geometry} material={nodes.M_3YNSD_PNT_2001.material} position={[-1.618, 0.957, 0.156]} />
        </mesh>
        <mesh name="M_3YNSD_1_F004" geometry={nodes.M_3YNSD_1_F004.geometry} material={nodes.M_3YNSD_1_F004.material} position={[1.553, 1.978, 2.476]}>
          <mesh name="M_3YNSD_PNT_1001" geometry={nodes.M_3YNSD_PNT_1001.geometry} material={nodes.M_3YNSD_PNT_1001.material} position={[-1.618, 0.947, 0.156]} />
        </mesh>
        <mesh name="M_3YNSD_1_F005" geometry={nodes.M_3YNSD_1_F005.geometry} material={nodes.M_3YNSD_1_F005.material} position={[1.553, -1.347, 2.476]}>
          <mesh name="M_3YNSD_PNT_3001" geometry={nodes.M_3YNSD_PNT_3001.geometry} material={nodes.M_3YNSD_PNT_3001.material} position={[-1.618, 0.931, 0.156]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A003" geometry={nodes.M_3YNSD_1_F_A003.geometry} material={nodes.M_3YNSD_1_F_A003.material} position={[1.55, 1.99, 2.466]} />
        <mesh name="M_3YNSD_1_F_A004" geometry={nodes.M_3YNSD_1_F_A004.geometry} material={nodes.M_3YNSD_1_F_A004.material} position={[1.55, 3.647, 2.466]} />
        <mesh name="M_3YNSD_1_F_A005" geometry={nodes.M_3YNSD_1_F_A005.geometry} material={nodes.M_3YNSD_1_F_A005.material} position={[1.55, 0.322, 2.466]} />
        <mesh name="M_3YNSD_1_F_B003" geometry={nodes.M_3YNSD_1_F_B003.geometry} material={nodes.M_3YNSD_1_F_B003.material} position={[1.55, 1.99, 2.466]} />
        <mesh name="M_3YNSD_1_F_B004" geometry={nodes.M_3YNSD_1_F_B004.geometry} material={nodes.M_3YNSD_1_F_B004.material} position={[1.55, 3.647, 2.466]} />
        <mesh name="M_3YNSD_1_F_B005" geometry={nodes.M_3YNSD_1_F_B005.geometry} material={nodes.M_3YNSD_1_F_B005.material} position={[1.55, 0.322, 2.466]} />
        <mesh name="M_3YNSD_1_F_C003" geometry={nodes.M_3YNSD_1_F_C003.geometry} material={nodes.M_3YNSD_1_F_C003.material} position={[1.55, -0.875, 2.466]} />
        <mesh name="M_3YNSD_1_F_C004" geometry={nodes.M_3YNSD_1_F_C004.geometry} material={nodes.M_3YNSD_1_F_C004.material} position={[1.55, 0.793, 2.466]} />
        <mesh name="M_3YNSD_1_F_C005" geometry={nodes.M_3YNSD_1_F_C005.geometry} material={nodes.M_3YNSD_1_F_C005.material} position={[1.55, 2.45, 2.466]} />
        <mesh name="M_3YNSD_2" geometry={nodes.M_3YNSD_2.geometry} material={materials['Material #2143921989']} position={[0, 0.293, 0]} />
        <mesh name="M_3YNSD_2_F_2" geometry={nodes.M_3YNSD_2_F_2.geometry} material={materials['Material #2143921989']} position={[2.961, 0.043, 2.56]} />
        <mesh name="M_3YNSD_2_F_2001" geometry={nodes.M_3YNSD_2_F_2001.geometry} material={materials['Material #2143921989']} position={[2.961, 0.043, 2.56]} />
        <mesh name="M_3YNSD_2_F_2002" geometry={nodes.M_3YNSD_2_F_2002.geometry} material={materials['Material #2143921989']} position={[2.961, 0.043, 2.56]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_3YNSD_2.glb')
