/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_3YNSD_11.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_3YNSD_11.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_3YNSD_11_NN" scale={1.14}>
        <mesh name="Legs010" geometry={nodes.Legs010.geometry} material={nodes.Legs010.material} position={[0.891, -2.958, -0.259]} />
        <mesh name="M_3YNSD_11" geometry={nodes.M_3YNSD_11.geometry} material={materials['Material #2143921989.016']} position={[0.105, 0.3, 0.121]} />
        <mesh name="M_3YNSD_11_F_11" geometry={nodes.M_3YNSD_11_F_11.geometry} material={materials['Material #2143921989.016']} position={[0.938, -0.009, 2.689]} />
        <mesh name="M_3YNSD_11_F_11001" geometry={nodes.M_3YNSD_11_F_11001.geometry} material={materials['Material #2143921989.016']} position={[0.938, -0.009, 2.689]} />
        <mesh name="M_3YNSD_11_F_11002" geometry={nodes.M_3YNSD_11_F_11002.geometry} material={materials['Material #2143921989.016']} position={[0.938, -0.009, 2.689]} />
        <mesh name="M_3YNSD_1_F030" geometry={nodes.M_3YNSD_1_F030.geometry} material={nodes.M_3YNSD_1_F030.material} position={[3.731, 0.272, 2.604]}>
          <mesh name="M_3YNSD_1_PNT_2008" geometry={nodes.M_3YNSD_1_PNT_2008.geometry} material={nodes.M_3YNSD_1_PNT_2008.material} position={[-3.726, 0.968, 0.157]} />
        </mesh>
        <mesh name="M_3YNSD_1_F031" geometry={nodes.M_3YNSD_1_F031.geometry} material={nodes.M_3YNSD_1_F031.material} position={[3.731, 1.945, 2.604]}>
          <mesh name="M_3YNSD_1_PNT_1008" geometry={nodes.M_3YNSD_1_PNT_1008.geometry} material={nodes.M_3YNSD_1_PNT_1008.material} position={[-3.726, 0.957, 0.157]} />
        </mesh>
        <mesh name="M_3YNSD_1_F032" geometry={nodes.M_3YNSD_1_F032.geometry} material={nodes.M_3YNSD_1_F032.material} position={[3.731, -1.413, 2.604]}>
          <mesh name="M_3YNSD_1_PNT_3008" geometry={nodes.M_3YNSD_1_PNT_3008.geometry} material={nodes.M_3YNSD_1_PNT_3008.material} position={[-3.726, 0.962, 0.157]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A030" geometry={nodes.M_3YNSD_1_F_A030.geometry} material={nodes.M_3YNSD_1_F_A030.material} position={[3.728, 1.957, 2.594]} />
        <mesh name="M_3YNSD_1_F_A031" geometry={nodes.M_3YNSD_1_F_A031.geometry} material={nodes.M_3YNSD_1_F_A031.material} position={[3.728, 3.63, 2.594]} />
        <mesh name="M_3YNSD_1_F_A032" geometry={nodes.M_3YNSD_1_F_A032.geometry} material={nodes.M_3YNSD_1_F_A032.material} position={[3.728, 0.272, 2.594]} />
        <mesh name="M_3YNSD_1_F_B030" geometry={nodes.M_3YNSD_1_F_B030.geometry} material={nodes.M_3YNSD_1_F_B030.material} position={[3.728, 1.957, 2.594]} />
        <mesh name="M_3YNSD_1_F_B031" geometry={nodes.M_3YNSD_1_F_B031.geometry} material={nodes.M_3YNSD_1_F_B031.material} position={[3.728, 3.631, 2.594]} />
        <mesh name="M_3YNSD_1_F_B032" geometry={nodes.M_3YNSD_1_F_B032.geometry} material={nodes.M_3YNSD_1_F_B032.material} position={[3.728, 0.272, 2.594]} />
        <mesh name="M_3YNSD_1_F_C030" geometry={nodes.M_3YNSD_1_F_C030.geometry} material={nodes.M_3YNSD_1_F_C030.material} position={[3.728, -0.937, 2.594]} />
        <mesh name="M_3YNSD_1_F_C031" geometry={nodes.M_3YNSD_1_F_C031.geometry} material={nodes.M_3YNSD_1_F_C031.material} position={[3.728, 0.748, 2.594]} />
        <mesh name="M_3YNSD_1_F_C032" geometry={nodes.M_3YNSD_1_F_C032.geometry} material={nodes.M_3YNSD_1_F_C032.material} position={[3.728, 2.421, 2.594]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_3YNSD_11.glb')
