/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_3YNSD_10.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_3YNSD_10.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_3YNSD_10_NN" scale={1.14}>
        <mesh name="Legs009" geometry={nodes.Legs009.geometry} material={nodes.Legs009.material} position={[0.874, -2.868, -0.256]} scale={1.283} />
        <mesh name="M_3YNSD_1_F027" geometry={nodes.M_3YNSD_1_F027.geometry} material={nodes.M_3YNSD_1_F027.material} position={[3.196, 1.97, 2.569]} scale={1.283}>
          <mesh name="M_3YNSD_1_PNT_1007" geometry={nodes.M_3YNSD_1_PNT_1007.geometry} material={nodes.M_3YNSD_1_PNT_1007.material} position={[-2.492, 0.736, 0.121]} scale={0.78} />
        </mesh>
        <mesh name="M_3YNSD_1_F028" geometry={nodes.M_3YNSD_1_F028.geometry} material={nodes.M_3YNSD_1_F028.material} position={[3.196, 0.32, 2.569]} scale={1.283}>
          <mesh name="M_3YNSD_1_PNT_2007" geometry={nodes.M_3YNSD_1_PNT_2007.geometry} material={nodes.M_3YNSD_1_PNT_2007.material} position={[-2.492, 0.745, 0.121]} scale={0.78} />
        </mesh>
        <mesh name="M_3YNSD_1_F029" geometry={nodes.M_3YNSD_1_F029.geometry} material={nodes.M_3YNSD_1_F029.material} position={[3.196, -1.343, 2.569]} scale={1.283}>
          <mesh name="M_3YNSD_1_PNT_3007" geometry={nodes.M_3YNSD_1_PNT_3007.geometry} material={nodes.M_3YNSD_1_PNT_3007.material} position={[-2.492, 0.74, 0.121]} scale={0.78} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A027" geometry={nodes.M_3YNSD_1_F_A027.geometry} material={nodes.M_3YNSD_1_F_A027.material} position={[3.193, 3.633, 2.559]} scale={1.283} />
        <mesh name="M_3YNSD_1_F_A028" geometry={nodes.M_3YNSD_1_F_A028.geometry} material={nodes.M_3YNSD_1_F_A028.material} position={[3.193, 1.982, 2.559]} scale={1.283} />
        <mesh name="M_3YNSD_1_F_A029" geometry={nodes.M_3YNSD_1_F_A029.geometry} material={nodes.M_3YNSD_1_F_A029.material} position={[3.193, 0.32, 2.559]} scale={1.283} />
        <mesh name="M_3YNSD_1_F_B027" geometry={nodes.M_3YNSD_1_F_B027.geometry} material={nodes.M_3YNSD_1_F_B027.material} position={[3.193, 3.633, 2.559]} scale={1.283} />
        <mesh name="M_3YNSD_1_F_B028" geometry={nodes.M_3YNSD_1_F_B028.geometry} material={nodes.M_3YNSD_1_F_B028.material} position={[3.193, 1.982, 2.559]} scale={1.283} />
        <mesh name="M_3YNSD_1_F_B029" geometry={nodes.M_3YNSD_1_F_B029.geometry} material={nodes.M_3YNSD_1_F_B029.material} position={[3.193, 0.32, 2.559]} scale={1.283} />
        <mesh name="M_3YNSD_1_F_C027" geometry={nodes.M_3YNSD_1_F_C027.geometry} material={nodes.M_3YNSD_1_F_C027.material} position={[3.193, 2.44, 2.559]} scale={1.283} />
        <mesh name="M_3YNSD_1_F_C028" geometry={nodes.M_3YNSD_1_F_C028.geometry} material={nodes.M_3YNSD_1_F_C028.material} position={[3.193, 0.789, 2.559]} scale={1.283} />
        <mesh name="M_3YNSD_1_F_C029" geometry={nodes.M_3YNSD_1_F_C029.geometry} material={nodes.M_3YNSD_1_F_C029.material} position={[3.193, -0.873, 2.559]} scale={1.283} />
        <mesh name="M_3YNSD_9001" geometry={nodes.M_3YNSD_9001.geometry} material={materials['Material #2143921989.002']} position={[0.085, 0.361, 0.095]} scale={1.283} />
        <mesh name="M_3YNSD_9_F_9003" geometry={nodes.M_3YNSD_9_F_9003.geometry} material={materials['Material #2143921989.002']} position={[1.382, 0.042, 2.653]} scale={1.283} />
        <mesh name="M_3YNSD_9_F_9004" geometry={nodes.M_3YNSD_9_F_9004.geometry} material={materials['Material #2143921989.002']} position={[1.382, 0.042, 2.653]} scale={1.283} />
        <mesh name="M_3YNSD_9_F_9005" geometry={nodes.M_3YNSD_9_F_9005.geometry} material={materials['Material #2143921989.002']} position={[1.382, 0.042, 2.653]} scale={1.283} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_3YNSD_10.glb')
