/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_3YNSD_4.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_3YNSD_4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_3YNSD_4_NN" scale={1.142}>
        <mesh name="Legs003" geometry={nodes.Legs003.geometry} material={nodes.Legs003.material} position={[0.846, -2.863, -0.363]} />
        <mesh name="M_3YNSD_1_F009" geometry={nodes.M_3YNSD_1_F009.geometry} material={nodes.M_3YNSD_1_F009.material} position={[2.032, 0.324, 2.461]}>
          <mesh name="M_3YNSD_1_PNT_2001" geometry={nodes.M_3YNSD_1_PNT_2001.geometry} material={nodes.M_3YNSD_1_PNT_2001.material} position={[-2.061, 0.955, 0.155]} />
        </mesh>
        <mesh name="M_3YNSD_1_F010" geometry={nodes.M_3YNSD_1_F010.geometry} material={nodes.M_3YNSD_1_F010.material} position={[2.032, 1.975, 2.461]}>
          <mesh name="M_3YNSD_1_PNT_1001" geometry={nodes.M_3YNSD_1_PNT_1001.geometry} material={nodes.M_3YNSD_1_PNT_1001.material} position={[-2.061, 0.944, 0.155]} />
        </mesh>
        <mesh name="M_3YNSD_1_F011" geometry={nodes.M_3YNSD_1_F011.geometry} material={nodes.M_3YNSD_1_F011.material} position={[2.032, -1.338, 2.461]}>
          <mesh name="M_3YNSD_1_PNT_3001" geometry={nodes.M_3YNSD_1_PNT_3001.geometry} material={nodes.M_3YNSD_1_PNT_3001.material} position={[-2.061, 0.95, 0.155]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A009" geometry={nodes.M_3YNSD_1_F_A009.geometry} material={nodes.M_3YNSD_1_F_A009.material} position={[2.029, 1.987, 2.452]} />
        <mesh name="M_3YNSD_1_F_A010" geometry={nodes.M_3YNSD_1_F_A010.geometry} material={nodes.M_3YNSD_1_F_A010.material} position={[2.029, 3.638, 2.452]} />
        <mesh name="M_3YNSD_1_F_A011" geometry={nodes.M_3YNSD_1_F_A011.geometry} material={nodes.M_3YNSD_1_F_A011.material} position={[2.029, 0.324, 2.452]} />
        <mesh name="M_3YNSD_1_F_B009" geometry={nodes.M_3YNSD_1_F_B009.geometry} material={nodes.M_3YNSD_1_F_B009.material} position={[2.029, 1.987, 2.452]} />
        <mesh name="M_3YNSD_1_F_B010" geometry={nodes.M_3YNSD_1_F_B010.geometry} material={nodes.M_3YNSD_1_F_B010.material} position={[2.029, 3.638, 2.452]} />
        <mesh name="M_3YNSD_1_F_B011" geometry={nodes.M_3YNSD_1_F_B011.geometry} material={nodes.M_3YNSD_1_F_B011.material} position={[2.029, 0.324, 2.452]} />
        <mesh name="M_3YNSD_1_F_C009" geometry={nodes.M_3YNSD_1_F_C009.geometry} material={nodes.M_3YNSD_1_F_C009.material} position={[2.029, -0.869, 2.452]} />
        <mesh name="M_3YNSD_1_F_C010" geometry={nodes.M_3YNSD_1_F_C010.geometry} material={nodes.M_3YNSD_1_F_C010.material} position={[2.029, 0.794, 2.452]} />
        <mesh name="M_3YNSD_1_F_C011" geometry={nodes.M_3YNSD_1_F_C011.geometry} material={nodes.M_3YNSD_1_F_C011.material} position={[2.029, 2.445, 2.452]} />
        <mesh name="M_3YNSD_4" geometry={nodes.M_3YNSD_4.geometry} material={materials['Material #2143921991.004']} position={[0, 0.397, 0]} />
        <mesh name="M_3YNSD_4_F_4" geometry={nodes.M_3YNSD_4_F_4.geometry} material={materials['Material #2143921991.004']} position={[2.504, 0.046, 2.545]} />
        <mesh name="M_3YNSD_4_F_4001" geometry={nodes.M_3YNSD_4_F_4001.geometry} material={materials['Material #2143921991.004']} position={[2.504, 0.046, 2.545]} />
        <mesh name="M_3YNSD_4_F_4002" geometry={nodes.M_3YNSD_4_F_4002.geometry} material={materials['Material #2143921991.004']} position={[2.504, 0.046, 2.545]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_3YNSD_4.glb')
