/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_3YNSD_3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_3YNSD_3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_3YNSD_3_NN" scale={1.142}>
        <mesh name="Legs002" geometry={nodes.Legs002.geometry} material={nodes.Legs002.material} position={[0.847, -2.955, -0.365]} />
        <mesh name="M_3YNSD_1_F006" geometry={nodes.M_3YNSD_1_F006.geometry} material={nodes.M_3YNSD_1_F006.material} position={[1.806, 1.959, 2.504]}>
          <mesh name="M_3YNSD_1_PNT_1" geometry={nodes.M_3YNSD_1_PNT_1.geometry} material={nodes.M_3YNSD_1_PNT_1.material} position={[-1.847, 0.959, 0.157]} />
        </mesh>
        <mesh name="M_3YNSD_1_F007" geometry={nodes.M_3YNSD_1_F007.geometry} material={nodes.M_3YNSD_1_F007.material} position={[1.806, 0.282, 2.504]}>
          <mesh name="M_3YNSD_1_PNT_2" geometry={nodes.M_3YNSD_1_PNT_2.geometry} material={nodes.M_3YNSD_1_PNT_2.material} position={[-1.847, 0.97, 0.157]} />
        </mesh>
        <mesh name="M_3YNSD_1_F008" geometry={nodes.M_3YNSD_1_F008.geometry} material={nodes.M_3YNSD_1_F008.material} position={[1.806, -1.406, 2.504]}>
          <mesh name="M_3YNSD_1_PNT_3" geometry={nodes.M_3YNSD_1_PNT_3.geometry} material={nodes.M_3YNSD_1_PNT_3.material} position={[-1.847, 0.964, 0.157]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A006" geometry={nodes.M_3YNSD_1_F_A006.geometry} material={nodes.M_3YNSD_1_F_A006.material} position={[1.803, 3.647, 2.494]} />
        <mesh name="M_3YNSD_1_F_A007" geometry={nodes.M_3YNSD_1_F_A007.geometry} material={nodes.M_3YNSD_1_F_A007.material} position={[1.803, 1.971, 2.494]} />
        <mesh name="M_3YNSD_1_F_A008" geometry={nodes.M_3YNSD_1_F_A008.geometry} material={nodes.M_3YNSD_1_F_A008.material} position={[1.803, 0.282, 2.494]} />
        <mesh name="M_3YNSD_1_F_B006" geometry={nodes.M_3YNSD_1_F_B006.geometry} material={nodes.M_3YNSD_1_F_B006.material} position={[1.803, 3.647, 2.494]} />
        <mesh name="M_3YNSD_1_F_B007" geometry={nodes.M_3YNSD_1_F_B007.geometry} material={nodes.M_3YNSD_1_F_B007.material} position={[1.803, 1.971, 2.494]} />
        <mesh name="M_3YNSD_1_F_B008" geometry={nodes.M_3YNSD_1_F_B008.geometry} material={nodes.M_3YNSD_1_F_B008.material} position={[1.803, 0.282, 2.494]} />
        <mesh name="M_3YNSD_1_F_C006" geometry={nodes.M_3YNSD_1_F_C006.geometry} material={nodes.M_3YNSD_1_F_C006.material} position={[1.803, 2.435, 2.494]} />
        <mesh name="M_3YNSD_1_F_C007" geometry={nodes.M_3YNSD_1_F_C007.geometry} material={nodes.M_3YNSD_1_F_C007.material} position={[1.803, 0.759, 2.494]} />
        <mesh name="M_3YNSD_1_F_C008" geometry={nodes.M_3YNSD_1_F_C008.geometry} material={nodes.M_3YNSD_1_F_C008.material} position={[1.803, -0.929, 2.494]} />
        <mesh name="M_3YNSD_3" geometry={nodes.M_3YNSD_3.geometry} material={materials['Material #2143921989.004']} position={[0, 0.233, 0]} />
        <mesh name="M_3YNSD_3_F_3" geometry={nodes.M_3YNSD_3_F_3.geometry} material={materials['Material #2143921989.004']} position={[2.766, 0, 2.589]} />
        <mesh name="M_3YNSD_3_F_3001" geometry={nodes.M_3YNSD_3_F_3001.geometry} material={materials['Material #2143921989.004']} position={[2.766, 0, 2.589]} />
        <mesh name="M_3YNSD_3_F_3002" geometry={nodes.M_3YNSD_3_F_3002.geometry} material={materials['Material #2143921989.004']} position={[2.766, 0, 2.589]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_3YNSD_3.glb')
