/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_3YNSD_9.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_3YNSD_9.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_3YNSD_9_NN" scale={1.14}>
        <mesh name="Legs008" geometry={nodes.Legs008.geometry} material={nodes.Legs008.material} position={[0.888, -2.957, -0.259]} />
        <mesh name="M_3YNSD_1_F024" geometry={nodes.M_3YNSD_1_F024.geometry} material={nodes.M_3YNSD_1_F024.material} position={[3.244, 1.954, 2.608]}>
          <mesh name="M_3YNSD_1_PNT_1006" geometry={nodes.M_3YNSD_1_PNT_1006.geometry} material={nodes.M_3YNSD_1_PNT_1006.material} position={[-3.244, 0.959, 0.157]} />
        </mesh>
        <mesh name="M_3YNSD_1_F025" geometry={nodes.M_3YNSD_1_F025.geometry} material={nodes.M_3YNSD_1_F025.material} position={[3.244, 0.278, 2.608]}>
          <mesh name="M_3YNSD_1_PNT_2006" geometry={nodes.M_3YNSD_1_PNT_2006.geometry} material={nodes.M_3YNSD_1_PNT_2006.material} position={[-3.244, 0.969, 0.157]} />
        </mesh>
        <mesh name="M_3YNSD_1_F026" geometry={nodes.M_3YNSD_1_F026.geometry} material={nodes.M_3YNSD_1_F026.material} position={[3.244, -1.41, 2.608]}>
          <mesh name="M_3YNSD_1_PNT_3006" geometry={nodes.M_3YNSD_1_PNT_3006.geometry} material={nodes.M_3YNSD_1_PNT_3006.material} position={[-3.244, 0.964, 0.157]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A024" geometry={nodes.M_3YNSD_1_F_A024.geometry} material={nodes.M_3YNSD_1_F_A024.material} position={[3.241, 3.641, 2.598]} />
        <mesh name="M_3YNSD_1_F_A025" geometry={nodes.M_3YNSD_1_F_A025.geometry} material={nodes.M_3YNSD_1_F_A025.material} position={[3.241, 1.965, 2.598]} />
        <mesh name="M_3YNSD_1_F_A026" geometry={nodes.M_3YNSD_1_F_A026.geometry} material={nodes.M_3YNSD_1_F_A026.material} position={[3.241, 0.278, 2.598]} />
        <mesh name="M_3YNSD_1_F_B024" geometry={nodes.M_3YNSD_1_F_B024.geometry} material={nodes.M_3YNSD_1_F_B024.material} position={[3.241, 3.641, 2.598]} />
        <mesh name="M_3YNSD_1_F_B025" geometry={nodes.M_3YNSD_1_F_B025.geometry} material={nodes.M_3YNSD_1_F_B025.material} position={[3.241, 1.966, 2.598]} />
        <mesh name="M_3YNSD_1_F_B026" geometry={nodes.M_3YNSD_1_F_B026.geometry} material={nodes.M_3YNSD_1_F_B026.material} position={[3.241, 0.278, 2.598]} />
        <mesh name="M_3YNSD_1_F_C024" geometry={nodes.M_3YNSD_1_F_C024.geometry} material={nodes.M_3YNSD_1_F_C024.material} position={[3.241, 2.43, 2.598]} />
        <mesh name="M_3YNSD_1_F_C025" geometry={nodes.M_3YNSD_1_F_C025.geometry} material={nodes.M_3YNSD_1_F_C025.material} position={[3.241, 0.754, 2.598]} />
        <mesh name="M_3YNSD_1_F_C026" geometry={nodes.M_3YNSD_1_F_C026.geometry} material={nodes.M_3YNSD_1_F_C026.material} position={[3.241, -0.933, 2.598]} />
        <mesh name="M_3YNSD_9" geometry={nodes.M_3YNSD_9.geometry} material={materials['Material #2143921989.011']} position={[0.087, 0.32, 0.096]} />
        <mesh name="M_3YNSD_9_F_9" geometry={nodes.M_3YNSD_9_F_9.geometry} material={materials['Material #2143921989.011']} position={[1.403, -0.004, 2.693]} />
        <mesh name="M_3YNSD_9_F_9001" geometry={nodes.M_3YNSD_9_F_9001.geometry} material={materials['Material #2143921989.011']} position={[1.403, -0.004, 2.693]} />
        <mesh name="M_3YNSD_9_F_9002" geometry={nodes.M_3YNSD_9_F_9002.geometry} material={materials['Material #2143921989.011']} position={[1.403, -0.004, 2.693]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_3YNSD_9.glb')
