/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_3YNSD_6.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_3YNSD_6.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_3YNSD_6_NN" scale={1.14}>
        <mesh name="Legs005" geometry={nodes.Legs005.geometry} material={nodes.Legs005.material} position={[0.881, -2.911, -0.21]} />
        <mesh name="M_3YNSD_1_F015" geometry={nodes.M_3YNSD_1_F015.geometry} material={nodes.M_3YNSD_1_F015.material} position={[2.545, 0.295, 2.632]}>
          <mesh name="M_3YNSD_1_PNT_2003" geometry={nodes.M_3YNSD_1_PNT_2003.geometry} material={nodes.M_3YNSD_1_PNT_2003.material} position={[-2.543, 0.961, 0.156]} />
        </mesh>
        <mesh name="M_3YNSD_1_F016" geometry={nodes.M_3YNSD_1_F016.geometry} material={nodes.M_3YNSD_1_F016.material} position={[2.545, 1.956, 2.632]}>
          <mesh name="M_3YNSD_1_PNT_1003" geometry={nodes.M_3YNSD_1_PNT_1003.geometry} material={nodes.M_3YNSD_1_PNT_1003.material} position={[-2.543, 0.95, 0.156]} />
        </mesh>
        <mesh name="M_3YNSD_1_F017" geometry={nodes.M_3YNSD_1_F017.geometry} material={nodes.M_3YNSD_1_F017.material} position={[2.545, -1.377, 2.632]}>
          <mesh name="M_3YNSD_1_PNT_3003" geometry={nodes.M_3YNSD_1_PNT_3003.geometry} material={nodes.M_3YNSD_1_PNT_3003.material} position={[-2.543, 0.955, 0.156]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A015" geometry={nodes.M_3YNSD_1_F_A015.geometry} material={nodes.M_3YNSD_1_F_A015.material} position={[2.542, 1.968, 2.621]} />
        <mesh name="M_3YNSD_1_F_A016" geometry={nodes.M_3YNSD_1_F_A016.geometry} material={nodes.M_3YNSD_1_F_A016.material} position={[2.542, 3.628, 2.621]} />
        <mesh name="M_3YNSD_1_F_A017" geometry={nodes.M_3YNSD_1_F_A017.geometry} material={nodes.M_3YNSD_1_F_A017.material} position={[2.542, 0.295, 2.621]} />
        <mesh name="M_3YNSD_1_F_B015" geometry={nodes.M_3YNSD_1_F_B015.geometry} material={nodes.M_3YNSD_1_F_B015.material} position={[2.542, 1.968, 2.621]} />
        <mesh name="M_3YNSD_1_F_B016" geometry={nodes.M_3YNSD_1_F_B016.geometry} material={nodes.M_3YNSD_1_F_B016.material} position={[2.542, 3.628, 2.621]} />
        <mesh name="M_3YNSD_1_F_B017" geometry={nodes.M_3YNSD_1_F_B017.geometry} material={nodes.M_3YNSD_1_F_B017.material} position={[2.542, 0.295, 2.621]} />
        <mesh name="M_3YNSD_1_F_C015" geometry={nodes.M_3YNSD_1_F_C015.geometry} material={nodes.M_3YNSD_1_F_C015.material} position={[2.542, -0.905, 2.621]} />
        <mesh name="M_3YNSD_1_F_C016" geometry={nodes.M_3YNSD_1_F_C016.geometry} material={nodes.M_3YNSD_1_F_C016.material} position={[2.542, 0.767, 2.621]} />
        <mesh name="M_3YNSD_1_F_C017" geometry={nodes.M_3YNSD_1_F_C017.geometry} material={nodes.M_3YNSD_1_F_C017.material} position={[2.542, 2.428, 2.621]} />
        <mesh name="M_3YNSD_6" geometry={nodes.M_3YNSD_6.geometry} material={materials['Material #2143921989.001']} position={[0.061, 0.316, 0.145]} />
        <mesh name="M_3YNSD_6_F_6" geometry={nodes.M_3YNSD_6_F_6.geometry} material={materials['Material #2143921989.001']} position={[2.087, 0.016, 2.716]} />
        <mesh name="M_3YNSD_6_F_6001" geometry={nodes.M_3YNSD_6_F_6001.geometry} material={materials['Material #2143921989.001']} position={[2.087, 0.016, 2.716]} />
        <mesh name="M_3YNSD_6_F_6002" geometry={nodes.M_3YNSD_6_F_6002.geometry} material={materials['Material #2143921989.001']} position={[2.087, 0.016, 2.716]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_3YNSD_6.glb')
