/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_3YNSD_8.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_3YNSD_8.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_3YNSD_8_NN" scale={1.14}>
        <mesh name="Legs007" geometry={nodes.Legs007.geometry} material={nodes.Legs007.material} position={[0.841, -2.937, -0.397]} />
        <mesh name="M_3YNSD_1_F021" geometry={nodes.M_3YNSD_1_F021.geometry} material={nodes.M_3YNSD_1_F021.material} position={[2.995, 0.293, 2.466]}>
          <mesh name="M_3YNSD_1_PNT_2005" geometry={nodes.M_3YNSD_1_PNT_2005.geometry} material={nodes.M_3YNSD_1_PNT_2005.material} position={[-3.04, 0.968, 0.157]} />
        </mesh>
        <mesh name="M_3YNSD_1_F022" geometry={nodes.M_3YNSD_1_F022.geometry} material={nodes.M_3YNSD_1_F022.material} position={[2.995, 1.966, 2.466]}>
          <mesh name="M_3YNSD_1_PNT_1005" geometry={nodes.M_3YNSD_1_PNT_1005.geometry} material={nodes.M_3YNSD_1_PNT_1005.material} position={[-3.04, 0.957, 0.157]} />
        </mesh>
        <mesh name="M_3YNSD_1_F023" geometry={nodes.M_3YNSD_1_F023.geometry} material={nodes.M_3YNSD_1_F023.material} position={[2.995, -1.392, 2.466]}>
          <mesh name="M_3YNSD_1_PNT_3005" geometry={nodes.M_3YNSD_1_PNT_3005.geometry} material={nodes.M_3YNSD_1_PNT_3005.material} position={[-3.04, 0.962, 0.157]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A021" geometry={nodes.M_3YNSD_1_F_A021.geometry} material={nodes.M_3YNSD_1_F_A021.material} position={[2.992, 1.978, 2.456]} />
        <mesh name="M_3YNSD_1_F_A022" geometry={nodes.M_3YNSD_1_F_A022.geometry} material={nodes.M_3YNSD_1_F_A022.material} position={[2.992, 3.651, 2.456]} />
        <mesh name="M_3YNSD_1_F_A023" geometry={nodes.M_3YNSD_1_F_A023.geometry} material={nodes.M_3YNSD_1_F_A023.material} position={[2.992, 0.293, 2.456]} />
        <mesh name="M_3YNSD_1_F_B021" geometry={nodes.M_3YNSD_1_F_B021.geometry} material={nodes.M_3YNSD_1_F_B021.material} position={[2.992, 1.978, 2.456]} />
        <mesh name="M_3YNSD_1_F_B022" geometry={nodes.M_3YNSD_1_F_B022.geometry} material={nodes.M_3YNSD_1_F_B022.material} position={[2.992, 3.652, 2.456]} />
        <mesh name="M_3YNSD_1_F_B023" geometry={nodes.M_3YNSD_1_F_B023.geometry} material={nodes.M_3YNSD_1_F_B023.material} position={[2.992, 0.293, 2.456]} />
        <mesh name="M_3YNSD_1_F_C021" geometry={nodes.M_3YNSD_1_F_C021.geometry} material={nodes.M_3YNSD_1_F_C021.material} position={[2.992, -0.916, 2.456]} />
        <mesh name="M_3YNSD_1_F_C022" geometry={nodes.M_3YNSD_1_F_C022.geometry} material={nodes.M_3YNSD_1_F_C022.material} position={[2.992, 0.769, 2.456]} />
        <mesh name="M_3YNSD_1_F_C023" geometry={nodes.M_3YNSD_1_F_C023.geometry} material={nodes.M_3YNSD_1_F_C023.material} position={[2.992, 2.442, 2.456]} />
        <mesh name="M_3YNSD_8" geometry={nodes.M_3YNSD_8.geometry} material={materials['Material #2143921989.007']} position={[0, 0.293, 0]} />
        <mesh name="M_3YNSD_8_F_8" geometry={nodes.M_3YNSD_8_F_8.geometry} material={materials['Material #2143921989.007']} position={[1.589, 0.012, 2.551]} />
        <mesh name="M_3YNSD_8_F_8001" geometry={nodes.M_3YNSD_8_F_8001.geometry} material={materials['Material #2143921989.007']} position={[1.589, 0.012, 2.551]} />
        <mesh name="M_3YNSD_8_F_8002" geometry={nodes.M_3YNSD_8_F_8002.geometry} material={materials['Material #2143921989.007']} position={[1.589, 0.012, 2.551]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_3YNSD_8.glb')
