/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_3YNSD_7.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_3YNSD_7.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_3YNSD_7_NN" scale={1.14}>
        <mesh name="Legs006" geometry={nodes.Legs006.geometry} material={nodes.Legs006.material} position={[0.8, -2.711, -0.377]} />
        <mesh name="M_3YNSD_1_F018" geometry={nodes.M_3YNSD_1_F018.geometry} material={nodes.M_3YNSD_1_F018.material} position={[2.642, 2.022, 2.387]}>
          <mesh name="M_3YNSD_1_PNT_1004" geometry={nodes.M_3YNSD_1_PNT_1004.geometry} material={nodes.M_3YNSD_1_PNT_1004.material} position={[-2.698, 0.924, 0.152]} />
        </mesh>
        <mesh name="M_3YNSD_1_F019" geometry={nodes.M_3YNSD_1_F019.geometry} material={nodes.M_3YNSD_1_F019.material} position={[2.642, 0.407, 2.387]}>
          <mesh name="M_3YNSD_1_PNT_2004" geometry={nodes.M_3YNSD_1_PNT_2004.geometry} material={nodes.M_3YNSD_1_PNT_2004.material} position={[-2.698, 0.934, 0.152]} />
        </mesh>
        <mesh name="M_3YNSD_1_F020" geometry={nodes.M_3YNSD_1_F020.geometry} material={nodes.M_3YNSD_1_F020.material} position={[2.642, -1.219, 2.387]}>
          <mesh name="M_3YNSD_1_PNT_3004" geometry={nodes.M_3YNSD_1_PNT_3004.geometry} material={nodes.M_3YNSD_1_PNT_3004.material} position={[-2.698, 0.929, 0.152]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_A018" geometry={nodes.M_3YNSD_1_F_A018.geometry} material={nodes.M_3YNSD_1_F_A018.material} position={[2.639, 3.648, 2.377]} />
        <mesh name="M_3YNSD_1_F_A019" geometry={nodes.M_3YNSD_1_F_A019.geometry} material={nodes.M_3YNSD_1_F_A019.material} position={[2.639, 2.034, 2.377]} />
        <mesh name="M_3YNSD_1_F_A020" geometry={nodes.M_3YNSD_1_F_A020.geometry} material={nodes.M_3YNSD_1_F_A020.material} position={[2.639, 0.407, 2.377]} />
        <mesh name="M_3YNSD_1_F_B018" geometry={nodes.M_3YNSD_1_F_B018.geometry} material={nodes.M_3YNSD_1_F_B018.material} position={[2.639, 3.649, 2.377]} />
        <mesh name="M_3YNSD_1_F_B019" geometry={nodes.M_3YNSD_1_F_B019.geometry} material={nodes.M_3YNSD_1_F_B019.material} position={[2.639, 2.034, 2.377]} />
        <mesh name="M_3YNSD_1_F_B020" geometry={nodes.M_3YNSD_1_F_B020.geometry} material={nodes.M_3YNSD_1_F_B020.material} position={[2.639, 0.407, 2.377]} />
        <mesh name="M_3YNSD_1_F_C018" geometry={nodes.M_3YNSD_1_F_C018.geometry} material={nodes.M_3YNSD_1_F_C018.material} position={[2.639, 2.481, 2.377]} />
        <mesh name="M_3YNSD_1_F_C019" geometry={nodes.M_3YNSD_1_F_C019.geometry} material={nodes.M_3YNSD_1_F_C019.material} position={[2.639, 0.866, 2.377]} />
        <mesh name="M_3YNSD_1_F_C020" geometry={nodes.M_3YNSD_1_F_C020.geometry} material={nodes.M_3YNSD_1_F_C020.material} position={[2.639, -0.76, 2.377]} />
        <mesh name="M_3YNSD_7" geometry={nodes.M_3YNSD_7.geometry} material={materials['Material #2143921989.006']} position={[0, 0.427, 0]} />
        <mesh name="M_3YNSD_7_F_7" geometry={nodes.M_3YNSD_7_F_7.geometry} material={materials['Material #2143921989.006']} position={[1.747, 0.135, 2.469]} />
        <mesh name="M_3YNSD_7_F_7001" geometry={nodes.M_3YNSD_7_F_7001.geometry} material={materials['Material #2143921989.006']} position={[1.747, 0.135, 2.469]} />
        <mesh name="M_3YNSD_7_F_7002" geometry={nodes.M_3YNSD_7_F_7002.geometry} material={materials['Material #2143921989.006']} position={[1.747, 0.135, 2.469]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_3YNSD_7.glb')
