/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 M_3YNSD_1.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/M_3YNSD_1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="M_3YNSD_1_NN" scale={1.142}>
        <mesh name="Legs" geometry={nodes.Legs.geometry} material={nodes.Legs.material} position={[0.888, -2.985, -0.379]} />
        <mesh name="M_3YNSD_1" geometry={nodes.M_3YNSD_1.geometry} material={materials['Material #2143921991.002']} />
        <mesh name="M_3YNSD_1_F" geometry={nodes.M_3YNSD_1_F.geometry} material={nodes.M_3YNSD_1_F.material} position={[1.382, 1.949, 2.502]}>
          <mesh name="M_3YNSD_PNT_1" geometry={nodes.M_3YNSD_PNT_1.geometry} material={nodes.M_3YNSD_PNT_1.material} position={[-1.407, 0.929, 0.158]} />
        </mesh>
        <mesh name="M_3YNSD_1_F1" geometry={nodes.M_3YNSD_1_F1.geometry} material={nodes.M_3YNSD_1_F1.material} position={[1.382, 0.266, 2.502]}>
          <mesh name="M_3YNSD_PNT_2" geometry={nodes.M_3YNSD_PNT_2.geometry} material={nodes.M_3YNSD_PNT_2.material} position={[-1.407, 0.94, 0.158]} />
        </mesh>
        <mesh name="M_3YNSD_1_F2" geometry={nodes.M_3YNSD_1_F2.geometry} material={nodes.M_3YNSD_1_F2.material} position={[1.382, -1.43, 2.502]}>
          <mesh name="M_3YNSD_PNT_3" geometry={nodes.M_3YNSD_PNT_3.geometry} material={nodes.M_3YNSD_PNT_3.material} position={[-1.407, 0.934, 0.158]} />
        </mesh>
        <mesh name="M_3YNSD_1_F_1" geometry={nodes.M_3YNSD_1_F_1.geometry} material={materials['Material #2143921991.002']} position={[3.269, -0.018, 2.587]} />
        <mesh name="M_3YNSD_1_F_1001" geometry={nodes.M_3YNSD_1_F_1001.geometry} material={materials['Material #2143921991.002']} position={[3.269, -0.018, 2.587]} />
        <mesh name="M_3YNSD_1_F_1002" geometry={nodes.M_3YNSD_1_F_1002.geometry} material={materials['Material #2143921991.002']} position={[3.269, -0.018, 2.587]} />
        <mesh name="M_3YNSD_1_F_A" geometry={nodes.M_3YNSD_1_F_A.geometry} material={nodes.M_3YNSD_1_F_A.material} position={[1.379, 3.645, 2.492]} />
        <mesh name="M_3YNSD_1_F_A1" geometry={nodes.M_3YNSD_1_F_A1.geometry} material={nodes.M_3YNSD_1_F_A1.material} position={[1.379, 1.961, 2.492]} />
        <mesh name="M_3YNSD_1_F_A2" geometry={nodes.M_3YNSD_1_F_A2.geometry} material={nodes.M_3YNSD_1_F_A2.material} position={[1.379, 0.266, 2.492]} />
        <mesh name="M_3YNSD_1_F_B" geometry={nodes.M_3YNSD_1_F_B.geometry} material={nodes.M_3YNSD_1_F_B.material} position={[1.379, 3.645, 2.492]} />
        <mesh name="M_3YNSD_1_F_B1" geometry={nodes.M_3YNSD_1_F_B1.geometry} material={nodes.M_3YNSD_1_F_B1.material} position={[1.379, 1.961, 2.492]} />
        <mesh name="M_3YNSD_1_F_B2" geometry={nodes.M_3YNSD_1_F_B2.geometry} material={nodes.M_3YNSD_1_F_B2.material} position={[1.379, 0.266, 2.492]} />
        <mesh name="M_3YNSD_1_F_C" geometry={nodes.M_3YNSD_1_F_C.geometry} material={nodes.M_3YNSD_1_F_C.material} position={[1.379, 2.428, 2.492]} />
        <mesh name="M_3YNSD_1_F_C1" geometry={nodes.M_3YNSD_1_F_C1.geometry} material={nodes.M_3YNSD_1_F_C1.material} position={[1.379, 0.744, 2.492]} />
        <mesh name="M_3YNSD_1_F_C2" geometry={nodes.M_3YNSD_1_F_C2.geometry} material={nodes.M_3YNSD_1_F_C2.material} position={[1.379, -0.951, 2.492]} />
      </group>
    </group>
  )
}

useGLTF.preload('/M_3YNSD_1.glb')
